### ISSUE TITLE
Add GitLab auth provider

### ISSUE THREAD

**Issue by benjamin-schilling** [baptisteArno/typebot.io#10]
When I run typebot using the provided docker-compose file, the only login method available is GitHub OAuth, does typebot support a "username + password" login option or allows to configure a custom OAuth provider?

I want to host typebot in an company internal environment.

One additional question:
Is it possible to prevent user registration in the builder? Something like setting up a small defined set of user accounts for it only?

**Comment by baptisteArno** [comment]
Check out https://app.typebot.io

By default, I allow signing up with GitHub, Google, Facebook, or Magic Link.
I prefer to avoid storing passwords. You can enable those providers by adding [dedicated environment variables](https://docs.typebot.io/self-hosting/configuration)

You can also fork the repo and add your own providers / logic. It uses [NextAuth](https://next-auth.js.org/) under the hood :)

**Comment by benjamin-schilling** [comment]
I completely agree on avoiding password where possible, what is your opinion on adding support for a "generic" OAuth2/OpenID Connect provider, like a self-hosted Keycloak or similar?

**Comment by baptisteArno** [comment]
Yeah, any provider would be a great thing to add! So that anyone could enable a provider by just providing the corresponding environment variable.

Any PR related to this would be greatly appreciated 🥰

Here are the instructions for Keycloak: https://next-auth.js.org/providers/keycloak

**Comment by baptisteArno** [comment]
Hey,

Thank you for your work on this!

1. Then it's probably an issue on [next-auth](https://github.com/nextauthjs/next-auth) since their official Prisma adapter looks pretty much the same: https://github.com/nextauthjs/adapters/blob/main/packages/prisma/src/index.ts. It might be great to also create a pull request there! 👍 
2. Sure, sounds awesome. The goal is to be able to configure this with environment variables.

Let me know if you need any help!

**Comment by benjamin-schilling** [comment]
For now we have only tested this on our side with a dev build, which works fine.

What do we have to do to run our changes in a production environment?

When I run `docker-compose up` I only get the original state deployed, our changes are missing.

Am I missing something?

**Comment by baptisteArno** [comment]
If it works on dev, it should work fine in the production environment.

Feel free to create the Pull request and I'll review it 😃

**Comment by baptisteArno** [comment]
Any updates on this @benjamin-schilling? 🙂

**Comment by benjamin-schilling** [comment]
We are currently struggeling a little with our environment, but we will definitely create the pull request once we are convinced it's done.
