### ISSUE TITLE
Build failed to compile due to type error

### ISSUE THREAD

**Issue by drafteqlp** [baptisteArno/typebot.io#1002]
viewer:build:    Creating an optimized production build ...
builder:build:    Linting and checking validity of types ...
viewer:build:  ✓ Compiled successfully
viewer:build:    Linting and checking validity of types ...
viewer:build: Failed to compile.
viewer:build: 
viewer:build: ../../packages/bot-engine/parseBubbleBlock.ts:198:44
viewer:build: Type error: Type 'PlatePlugin<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>>[]' is not assignable to type 'PlatePlugin<AnyObject, Value>[]'.
viewer:build:   Type 'PlatePlugin<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>>' is not assignable to type 'PlatePlugin<AnyObject, Value>'.
viewer:build:     Type 'PlatePlugin<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>>' is not assignable to type '{ editor?: Nullable<{ insertData?: PlatePluginInsertData<Value> | undefined; }> | undefined; handlers?: Nullable<DOMHandlers<AnyObject, Value, PlateEditor<...>> & { ...; }> | undefined; ... 6 more ...; type?: string | undefined; }'.
viewer:build:       Types of property 'handlers' are incompatible.
viewer:build:         Type 'Nullable<DOMHandlers<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>> & { onChange?: OnChange<DeserializeMdPlugin<Value>, Value, PlateEditor<...>> | undefined; }> | undefined' is not assignable to type 'Nullable<DOMHandlers<AnyObject, Value, PlateEditor<Value>> & { onChange?: OnChange<AnyObject, Value, PlateEditor<Value>> | undefined; }> | undefined'.
viewer:build:           Type 'Nullable<DOMHandlers<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>> & { onChange?: OnChange<DeserializeMdPlugin<Value>, Value, PlateEditor<...>> | undefined; }>' is not assignable to type 'Nullable<DOMHandlers<AnyObject, Value, PlateEditor<Value>> & { onChange?: OnChange<AnyObject, Value, PlateEditor<Value>> | undefined; }>'.
viewer:build:             Types of property 'onCopy' are incompatible.
viewer:build:               Type 'DOMHandler<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>, ClipboardEvent<Element>> | null | undefined' is not assignable to type 'DOMHandler<AnyObject, Value, PlateEditor<Value>, ClipboardEvent<Element>> | null | undefined'.
viewer:build:                 Type 'DOMHandler<DeserializeMdPlugin<Value>, Value, PlateEditor<Value>, ClipboardEvent<Element>>' is not assignable to type 'DOMHandler<AnyObject, Value, PlateEditor<Value>, ClipboardEvent<Element>>'.
viewer:build:                   Types of parameters 'editor' and 'editor' are incompatible.
viewer:build:                     Type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.5.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0__6bd7cp3xm4nvsn7bsauylrv4fa/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_mo...' is not assignable to type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.1.5_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0_slate-history@0.93._gjgzfudipgnjxawgqcll7jnaie/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_mo...'.
viewer:build:                       Type 'PlateEditor<Value>' is not assignable to type '{ key: any; plugins: WithPlatePlugin<{}, Value>[]; pluginsByKey: Record<string, WithPlatePlugin<{}, Value>>; prevSelection: BaseRange | null; blockFactory: (node?: Partial<...> | undefined, path?: Path | undefined) => TElement; childrenFactory: () => Value; currentKeyboardEvent: KeyboardEvent<...> | null; }'.
viewer:build:                         Types of property 'plugins' are incompatible.
viewer:build:                           Type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.5.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0__6bd7cp3xm4nvsn7bsauylrv4fa/node_modules/@udecode/plate-core/dist/types/plugin/PlatePlugin").WithPlatePlugin<{}, import("/Users/a/Desktop/Ionic/WeddingApp/...' is not assignable to type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.1.5_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0_slate-history@0.93._gjgzfudipgnjxawgqcll7jnaie/node_modules/@udecode/plate-core/dist/types/plugin/PlatePlugin").WithPlatePlugin<{}, import("/Users/a/Desktop/Ionic/WeddingApp/...'.
viewer:build:                             Type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.5.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0__6bd7cp3xm4nvsn7bsauylrv4fa/node_modules/@udecode/plate-core/dist/types/plugin/PlatePlugin").WithPlatePlugin<{}, import("/Users/a/Desktop/Ionic/WeddingApp/...' is not assignable to type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.1.5_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0_slate-history@0.93._gjgzfudipgnjxawgqcll7jnaie/node_modules/@udecode/plate-core/dist/types/plugin/PlatePlugin").WithPlatePlugin<{}, import("/Users/a/Desktop/Ionic/WeddingApp/...'.
viewer:build:                               Type 'WithPlatePlugin<{}, Value>' is not assignable to type 'Omit<PlatePlugin<{}, Value, PlateEditor<Value>>, "options" | "type" | "editor" | "inject">'.
viewer:build:                                 Types of property 'then' are incompatible.
viewer:build:                                   Type '((editor: import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.5.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0__6bd7cp3xm4nvsn7bsauylrv4fa/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeB...' is not assignable to type '((editor: import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.1.5_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0_slate-history@0.93._gjgzfudipgnjxawgqcll7jnaie/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeB...'.
viewer:build:                                     Type '(editor: import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.5.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0__6bd7cp3xm4nvsn7bsauylrv4fa/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeBo...' is not assignable to type '(editor: import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.1.5_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0_slate-history@0.93._gjgzfudipgnjxawgqcll7jnaie/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeBo...'.
viewer:build:                                       Types of parameters 'editor' and 'editor' are incompatible.
viewer:build:                                         Type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.1.5_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0_slate-history@0.93._gjgzfudipgnjxawgqcll7jnaie/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_mo...' is not assignable to type 'import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_modules/.pnpm/@udecode+plate-core@21.5.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0_scheduler@0.23.0__6bd7cp3xm4nvsn7bsauylrv4fa/node_modules/@udecode/plate-core/dist/types/PlateEditor").PlateEditor<import("/Users/a/Desktop/Ionic/WeddingApp/TypeBot/node_mo...'.
viewer:build:                                           Type 'PlateEditor<Value>' is missing the following properties from type 'PlateEditorMethods<Value>': reset, redecorate, plate

**Comment by baptisteArno** [comment]
Can you pull the latest commit (0c22d858b749c0f39eb595ad6e8f74a497abc198)

Run `pnpm install` and try again?

**Comment by baptisteArno** [comment]
Closing it. Feel free to re-open if you have more info 🙏
