### ISSUE TITLE
Whole page overflowing on the x axis and displaying a horizontal scrollbar

### ISSUE THREAD

**Issue by elwinjyot** [baptisteArno/typebot.io#1008]
On the landing page load the whole page is overflowing on the x axis and the horizontal scroll is triggered to display
![image](https://github.com/baptisteArno/typebot.io/assets/84516959/416e9a8b-0acc-4d66-bd46-3c754934c1d5)
![image](https://github.com/baptisteArno/typebot.io/assets/84516959/1c606a33-49a1-456d-a1ce-c78059b778d7)
The scrollbar goes away once it passes some vertical scroll distance as well. The below image shows the point at which the scrollbar disappears
![image](https://github.com/baptisteArno/typebot.io/assets/84516959/5710cb13-bfec-42c2-8db2-19f82a3b0d30)

**Comment by AbhiShake1** [comment]
hey @baptisteArno, can i work on this?

**Comment by baptisteArno** [comment]
Sure! Let me know if you need any help

**Comment by AbhiShake1** [comment]
> Sure! Let me know if you need any help

thanks alot for the opportunity man! https://github.com/baptisteArno/typebot.io/pull/1011
sorry for the stupid question, but why is the issue not being linked after mentioning it in PR description?

**Comment by baptisteArno** [comment]
It needs to say "Closes #<Issue number>". It needs to have a "close" keyword.

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
