### ISSUE TITLE
Dynamic proactive messages in bubble widget

### ISSUE THREAD

**Issue by mariosant** [baptisteArno/typebot.io#101]
Hi there and thank you for all the effort put in typebot!

I've been thinking that in order to engage higher conversion rates using typebot in websites, sometimes proactive messages have to be set dynamically after typebot initializes.

Is there a way to do this? If not, do you think it would make a good feature?

**Comment by baptisteArno** [comment]
Hey @mariosant, thank you for this.

> have to be set dynamically

What do you mean by that? Do you mean changing the text content of the proactive message? Can you explain the potential scenario a bit more?

**Comment by mariosant** [comment]
Hey @baptisteArno, exactly what you said. Change the text content of the proactive message.

Think of a scenario like that:
We would like to capture users who intent to exit the website and help users facing issues with traditional forms. The proactive message should be different in those cases and need a way to change them dynamically.

**Comment by baptisteArno** [comment]
It's implemented in the new embed library.

That will be live once #211 is completed.
