### ISSUE TITLE
Select between multiple font provider: `Bunny`, `custom`...

### ISSUE THREAD

**Issue by lazmo88** [baptisteArno/typebot.io#1019]
Is it possible to use local fonts instead of loading all fonts from bunny?

For some special edge cases using 3rd party assets/scripts is not possible and it would be great to have an option to server all assets from the local server instead.

**Comment by baptisteArno** [comment]
You should be able to actually type your custom font in the Typebot settings as far as I know, have you tried it?

**Comment by lazmo88** [comment]
> You should be able to actually type your custom font in the Typebot settings as far as I know, have you tried it?

I tried, it still sent a request to bunny fonts? Even if the font is a standard Arial or Helvetica etc.

**Comment by lazmo88** [comment]
@baptisteArno https://github.com/baptisteArno/typebot.io/commit/cccf905d38204c466e3ae6476152a2f266ca4e06

Above seems to be the only reference to Bunny fonts, so it seems to be always used as default, no way to bypass it.

Env variable to specify font source would be great. local, bunny, google, custom.

**Comment by baptisteArno** [comment]
Will be possible with https://github.com/baptisteArno/typebot.io/issues/1249
