### ISSUE TITLE
Json suggestion model with a "," invalidating the reading in the api

### ISSUE THREAD

**Issue by marcio-andrade** [baptisteArno/typebot.io#1022]
In > with the following JSON body:

{
  "startParams": {
    "typebot": "typebot-name",
  }
}

This "," at the end invalidates the json return.

![image](https://github.com/baptisteArno/typebot.io/assets/59773648/6b82b251-016a-48f2-8b2d-0e07ecd8cd1b)

**Comment by baptisteArno** [comment]
Thank you for the report!
