### ISSUE TITLE
OpenAI Assistant API support

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1024]

**Comment by baptisteArno** [comment]
The Assistant-related APIs are really complexe, to chat with an assistant, you need to:

1. Create thread
2. Add message to thread
3. Send a run request
4. Poll the run to check when it's completed
5. List the threads messages to be able to extract the assistant latest messages

I'm thinking of just providing a "Chat with assistant" convenient task where you give it a Thread ID variable and messages and it automatically trigger all the mentioned steps.

**Comment by baptisteArno** [comment]
We should probably wait for response streaming support (https://platform.openai.com/docs/assistants/how-it-works/limitations).

**Comment by jmlmvi** [comment]
It would be great, how can we help you to do that? I have GPT assistants and hopped that Typebot can work with. Many thanks in advance.

**Comment by jmlmvi** [comment]
Let me come back to the subject, but the ChatGP assistant is the ultimate goal of a ChatBot, how can we help, is it a financial problem?
Unless you have information from Open AI that there's going to be a new way of doing things?

We need two things:
- to be able to use another user's API key to perform a chat on their behalf.
-Access to the assistant.

TypeBot is an extraordinary product, and an OpenSource one at that, 1000 Bravos, for that, but access to chatGPT assistants is the "Grail"!  
!

**Comment by baptisteArno** [comment]
Will soon work on this! Any financial support is indeed appreciated ❤️

https://github.com/sponsors/baptisteArno
