### ISSUE TITLE
ERROR IMPORTING TYPE

### ISSUE THREAD

**Issue by jonsf2** [baptisteArno/typebot.io#1028]
hello, I can't import my structure into a new type bot, I'm on version 2.19.0

this error happens in my easypanel structure, i tested other types too and it doesn't open, always the same error!

 I've already tested it on another type.io structure and it worked, only this one isn't working.

<img width="443" alt="Captura de Tela 2023-11-11 às 22 46 44" src="https://github.com/baptisteArno/typebot.io/assets/68832949/f90c3972-3b63-4b98-8156-a2b3f6166034">

{
  "issues": [
    {
      "code": "invalid_literal",
      "expected": 3,
      "path": [
        "groups",
        0,
        "blocks",
        5,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 3"
    },
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "groups",
        0,
        "blocks",
        5,
        "options",
        "buttonLabel"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "groups",
        0,
        "blocks",
        5,
        "options",
        "searchInputPlaceholder"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        1,
        "blocks",
        13,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_type",
      "expected": "boolean",
      "received": "undefined",
      "path": [
        "groups",
        2,
        "blocks",
        1,
        "options",
        "isLong"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "boolean",
      "received": "undefined",
      "path": [
        "groups",
        2,
        "blocks",
        6,
        "options",
        "isLong"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_type",
      "expected": "boolean",
      "received": "undefined",
      "path": [
        "groups",
        2,
        "blocks",
        9,
        "options",
        "isLong"
      ],
      "message": "Required"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        2,
        "blocks",
        12,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        3,
        "blocks",
        9,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_union",
      "unionErrors": [
        {
          "issues": [
            {
              "code": "invalid_type",
              "expected": "number",
              "received": "undefined",
              "path": [
                "groups",
                4,
                "blocks",
                4,
                "content",
                "height"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "code": "custom",
              "fatal": true,
              "path": [
                "groups",
                4,
                "blocks",
                4,
                "content",
                "height"
              ],
              "message": "Invalid input"
            }
          ],
          "name": "ZodError"
        }
      ],
      "path": [
        "groups",
        4,
        "blocks",
        4,
        "content",
        "height"
      ],
      "message": "Invalid input"
    },
    {
      "code": "invalid_union",
      "unionErrors": [
        {
          "issues": [
            {
              "code": "invalid_type",
              "expected": "number",
              "received": "undefined",
              "path": [
                "groups",
                4,
                "blocks",
                8,
                "content",
                "height"
              ],
              "message": "Required"
            }
          ],
          "name": "ZodError"
        },
        {
          "issues": [
            {
              "code": "custom",
              "fatal": true,
              "path": [
                "groups",
                4,
                "blocks",
                8,
                "content",
                "height"
              ],
              "message": "Invalid input"
            }
          ],
          "name": "ZodError"
        }
      ],
      "path": [
        "groups",
        4,
        "blocks",
        8,
        "content",
        "height"
      ],
      "message": "Invalid input"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        4,
        "blocks",
        13,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        5,
        "blocks",
        13,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        6,
        "blocks",
        9,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_literal",
      "expected": 0,
      "path": [
        "groups",
        7,
        "blocks",
        14,
        "items",
        0,
        "type"
      ],
      "message": "Invalid literal value, expected 0"
    },
    {
      "code": "invalid_type",
      "expected": "boolean",
      "received": "undefined",
      "path": [
        "groups",
        7,
        "blocks",
        17,
        "options",
        "isNewTab"
      ],
      "message": "Required"
    }
  ],
  "name": "ZodError"
}

**Comment by jonsf2** [comment]
I've already tested it on another type.io structure and it worked, only this one isn't working

**Comment by baptisteArno** [comment]
Can you provide the bot you're trying to import?

**Comment by rcamilo** [comment]
Hi @baptisteArno 
In my case this error its happen. I'm sending bot json as an example:

[example-bot.json](https://github.com/baptisteArno/typebot.io/files/13478321/example-bot.json)

**Comment by baptisteArno** [comment]
Your typebot instance version is probably out of date. Can you upgrade and try again?

**Comment by rcamilo** [comment]
@baptisteArno I did update to latest version and import typebot file with successful

Tks for support

best regards
