### ISSUE TITLE
Weird text in ChatGPT response when user input is in arabic 

### ISSUE THREAD

**Issue by kaminske** [baptisteArno/typebot.io#1029]
I added the open ai block and set up everything correctly , when asked in french / english the bot answers correctly however when I ask in arabic the answer contains some weird text. 
I asked the same question in chatgpt and it replied correctly so it must be from typebot 
![image](https://github.com/baptisteArno/typebot.io/assets/85418657/c353095e-d5d5-41a5-b1cb-e279da62d548)
![image](https://github.com/baptisteArno/typebot.io/assets/85418657/adfcafec-ce38-43db-b5aa-1d59fa60ba98)

**Comment by baptisteArno** [comment]
Can you provide the prompt so that I can try to reproduce and see what's wrong?

**Comment by kaminske** [comment]
the prompt was : 
"أريد أن أعرف أكثر عن التأمين في تونس "
it translates to " I want to know more about insurance in Tunisia" 
**However** , I have noticed that this was happening only in one of the chatbots and upon further inspection found out  that the text in the system message in the openAi block were different , the bot that was showing the weird text had less "context" and fewer "details" , by adding more to it the problem no longer occurs .

**Comment by baptisteArno** [comment]
Ok, I guess we don't really have the hand on this, then 🙏
