### ISSUE TITLE
OpenAI Image API support

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1032]

**Comment by rishi-raj-jain** [comment]
Do you mean https://platform.openai.com/docs/guides/images?context=node?

Are you looking to reward via Algora?

**Comment by baptisteArno** [comment]
https://docs.typebot.io/editor/blocks/integrations/openai#vision-support

**Comment by baptisteArno** [comment]
https://docs.typebot.io/editor/blocks/integrations/openai#vision-support
