### ISSUE TITLE
can't find `/api/v1/typebots/bot-id/startChat`

### ISSUE THREAD

**Issue by ivopr** [baptisteArno/typebot.io#1034]
Well as the title implies, this URL gives me a 404. I'm using the Wordpress initBubble, I'm also able to open the viewer on the same bot-id and it works.

I don't know exactly what I should provide more, as I'm actually lost in this one...

**Comment by ivopr** [comment]
Well, I think I've found it, the CDN used on the plugin is pointing to `@typebot.io/js@0.2`, in my perception, it is pointing effectively to 0.2.17. Forcing to use 0.2.13 solved it, it seems.

**Comment by baptisteArno** [comment]
Indeed, how did you force it to use 0.2.13?

**Comment by ivopr** [comment]
we did a "fork" of the wordpress plugin and changed it manually on `public/class-typebot-public.php`, where is 0.2 to 0.2.13

**Comment by baptisteArno** [comment]
Wow, OK. Sorry for that. Indeed that was a breaking change and I didn't think about the WP plugin.

This will make sure it won't happen again: #1035
