### ISSUE TITLE
I can't create a new Docker Image v2.19.0

### ISSUE THREAD

**Issue by clikalogo** [baptisteArno/typebot.io#1037]
I'm trying to create my own image v2.19.0 (builder) with the DockerFile that is in the project and it's giving this error:
![image](https://github.com/baptisteArno/typebot.io/assets/107278009/4ba86b95-daa2-438c-9212-5735d4261910)

I was unable to join discussion #888 or #889, which have the same problem.
In versions v2.18.0 and earlier I was able to generate the ARM image normally. Any suggestions on how to solve the problem when trying to generate the image locally?

**Comment by baptisteArno** [comment]
What command are you running?

**Comment by clikalogo** [comment]
> What command are you running? Did you change anything in the code base? If not, why do you want to build the docker image yourself? An image is already available https://hub.docker.com/r/baptistearno/typebot-builder

@baptisteArno 
I can generate the "viewer" image successfully, but the "builder" image is showing the error above when trying to generate it.

used to generate local images on docker (ARM):
docker build -t typebot-typebot-viewer:localv2.19.0 . --build-arg="SCOPE=viewer"
docker build -t typebot-typebot-builder:localv2.19.0 . --build-arg="SCOPE=builder"

Nothing was changed or added to the original code. Just necessary to perform some additional translations (text to pt-BR) that are not achieved by the existing translation. (Example: "404 The bot you're looking for doesn't exist.")

**Comment by baptisteArno** [comment]
You don't have to build the docker images for this

See this guide on how to run the project locally: https://github.com/baptisteArno/typebot.io/blob/main/CONTRIBUTING.md#running-the-project-locally

**Comment by clikalogo** [comment]
@baptisteArno
