### ISSUE TITLE
Issue with WordPress plugin

### ISSUE THREAD

**Issue by mrworldling** [baptisteArno/typebot.io#1038]
Seems like there is a new issue with the WordPress plugin - now displaying a "bot was not found" message. All other sharing ways (iframe/script/etc) work fine

**Comment by mrworldling** [comment]
Latest version - 3.4.1 
Link: https://uniglobalcareers.com/berlin-war-simulation/

**Comment by mrworldling** [comment]
Awesome, thanks, just checked and it's running fine

**Comment by mrworldling** [comment]
This issues has resurfaced I'm afraid. Same details as above still valid.

**Comment by baptisteArno** [comment]
You are talking about v3.5.0? eeac4933870216017806586b9032e8af86ce75dc

You now can specify `lib_version` param in the shortcode.  Try to put it to "0.2.13"
