### ISSUE TITLE
TRPCError - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by montenegromatheus** [baptisteArno/typebot.io#1040]
Hello, evryone.

For the second time, I had an error really weird.

I'm using a flow that conect by webhook in N8N and another API. To test, I've executed many time using the Preview button.
When i was testing again, the mesage showed and I can't use the flow anymore.

![image](https://github.com/baptisteArno/typebot.io/assets/15305366/4b659e3c-4d24-48ac-88f3-353809bf6ff4)
[tx89cnaowlwiq06vyyp0yqrz7_logs.txt](https://github.com/baptisteArno/typebot.io/files/13385437/tx89cnaowlwiq06vyyp0yqrz7_logs.txt)

**Comment by baptisteArno** [comment]
There must be an issue with your "Save in variables" section in the Webhook configuration. Can you send a screenshot of that section?

**Comment by montenegromatheus** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/15305366/91d7a2e9-c1bc-4cfb-a89e-695667d26af8)

**Comment by montenegromatheus** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/15305366/30d8cffd-8c52-45f0-a9c7-14e0af4967f4)

**Comment by baptisteArno** [comment]
Can't guess what's wrong. Can send a reproduction?
