### ISSUE TITLE
Variable is not showing in bubbles text.

### ISSUE THREAD

**Issue by felipeab10** [baptisteArno/typebot.io#1041]
I have a variable with a return in the form of an object, and I'm trying to use just one property of the object to show it in the flow, but it's not showing up.

variable return:
return {
		mensagemCurta: tipoPlano.mensagemCurta,
		descricao: tipoPlano.descricao,
  		gb: gb,
		descricaoBase: ''.concat(baseGB, 'GB Plano TIM Controle'),
		descricaoFlashSales: comFlashSale,
  		descricaoPortabilidade: tipoPlano.descricaoPortabilidade,
		descricaoC6: comC6,
		plano_id: planoParsed.tim_id,
		fidelidade_id: fidelidade.tim_id,
		ddd: ddd,
		preco: preco,
		nome: planoParsed.nome
	};

Bubbles text:
{{={{smart}}.nome=}}

result:
![image](https://github.com/baptisteArno/typebot.io/assets/46427955/381fbbb3-6fc1-4708-98b6-4bcdefae196e)

**Comment by baptisteArno** [comment]
In your screenshot, there is a typo, instead of `{{={{smart}}.nome=}}`, it's `{{={{smart}}{{.nome=}}`

**Comment by felipeab10** [comment]
I tested it and it gave the same result, it didn't work.
![image](https://github.com/baptisteArno/typebot.io/assets/46427955/c62fbbcd-7eed-41bc-a76c-36ef1981ed19)
![image](https://github.com/baptisteArno/typebot.io/assets/46427955/8f3137c0-0327-47fa-a8da-2b9f1cb1cd64)

**Comment by felipeab10** [comment]
I did a simple test and it still didn't work.

![image](https://github.com/baptisteArno/typebot.io/assets/46427955/53afa275-e2fc-4079-aa5a-ff876b1f1b22)
![image](https://github.com/baptisteArno/typebot.io/assets/46427955/27379b34-15d6-47ba-8e26-a65a7e61ca31)
![image](https://github.com/baptisteArno/typebot.io/assets/46427955/88e3fefa-9e0f-4342-a4c6-5cf662a08ada)

**Comment by baptisteArno** [comment]
Hi, your screenshot still show a typo...

**instead of** {{={{smart}}.nome=}}, **it should be** {{={{smart}}{{.nome=}}

**Comment by baptisteArno** [comment]
And still, in fact it won't work because you can only save strings or list of strings in a Typebot variable. So you can't access to objects property like you are doing here

**Comment by baptisteArno** [comment]
Check this clear example on how to properly save your variables from a webhook block: https://docs.typebot.io/editor/blocks/integrations/webhook#example-with-a-dummy-api-create-and-get
