### ISSUE TITLE
Upload in AWS S3

### ISSUE THREAD

**Issue by souzadeveloper** [baptisteArno/typebot.io#1042]
I'm running Typebot version 2.16 via docker on self-hosting and trying to use AWS S3. I'm using the settings below in both Builder and Viewer:

- S3_ACCESS_KEY=my_access_key
- S3_SECRET_KEY=my_secret
- S3_BUCKET=my_bucket
- S3_ENDPOINT=s3.us-east-1.amazonaws.com
- S3_SSL=true

However, I cannot upload files to Flows. I have already checked CORS policy and Access policy and they are as required by the Typebot documentation. What could I be doing wrong? Is there any way to know what error is occurring during Upload?

Thanks in advance for your help.

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!
