### ISSUE TITLE
Plug'n play blocks/integrations proposal

### ISSUE THREAD

**Issue by caioreis** [baptisteArno/typebot.io#1044]
Hey @baptisteArno! First, great job :)

I'm checking some old PRs to see how you handled new blocks/integrations and it seems that there's a relative good amount of code that needs to change in order to "just add" a new block/integration. I'm thinking if a package manager way of doing things shouldn't be the way here. Does this makes sense?

**Comment by baptisteArno** [comment]
Yes! Currently working on it (#380)
