### ISSUE TITLE
conditions bug?

### ISSUE THREAD

**Issue by RazielKanos** [baptisteArno/typebot.io#1045]
I had a bunch of buttons, and wanted to move on in the group once all buttons (and their answers) had be checks/read.
So i created a condition field with het settings:
IF var1 is set
AND ver2 is set
AND var3 is set

else

Every time i just clicked the first button, and only var1 was set, it triggered the else field. I than created a text block to check the variables, they have all been empty, only the first was set.

**Comment by RazielKanos** [comment]
but that isn't what i need I need them combines with AND

**Comment by baptisteArno** [comment]
If only var 1 is set, then this:

IF var1 is set
OR ver2 is set
OR var3 is set

Will always trigger the Else
