### ISSUE TITLE
When starting a typebot via the api, I can't give the bot a value from a variable

### ISSUE THREAD

**Issue by fhonline** [baptisteArno/typebot.io#1051]
When starting a typebot via the api, I can't give the bot a value from a variable, for example telephone, I want to start the bot with a contact number via the api... it won't... does anyone know how this works, see the what I tried:

![image](https://github.com/baptisteArno/typebot.io/assets/95591514/1979823d-3c9f-4711-bc4a-f98c8d50a18e)

Another thing that's confusing:

When testing the api when creating the bot, it is a way of communicating, but in the documentation, it is another address, which does not work due to the html error... why is this crazy?

![image](https://github.com/baptisteArno/typebot.io/assets/95591514/ec209391-bedb-49ed-af7e-541bb9b37ec6)

**Comment by luizeof** [comment]
You are also not getting the first message at the start of the bot.

**Comment by alexmsaraiva1** [comment]
going through the same thing here too

**Comment by baptisteArno** [comment]
What's the request response? I can see the error on your screenshot

**Comment by baptisteArno** [comment]
Indeed there are new endpoints now that still need to be documented in the Preview drawer. But the old endpoint should still work!

**Comment by fhonline** [comment]
I found out what it is:
Only in API V1 does the prefilledVAriables array work, in V2, as available when creating the flow, it is not available or does not work...
So everyone, use V1 which captures the variable when starting the flow, filling in the prefilledVariables key.

![image](https://github.com/baptisteArno/typebot.io/assets/95591514/4bb9a406-e2c8-4802-a7db-92a964559a7e)

**Comment by fhonline** [comment]
It was confusing because in the documentation there is a way, and when executing the flow there where we select web or api, V2 is displayed and another way to execute the api

**Comment by baptisteArno** [comment]
Rewrote documentation: 993bc7900ede9fa44189f88724e35852bf5fe032

Thanks for the heads up!
