### ISSUE TITLE
 Message losing formatting on WhatsApp

### ISSUE THREAD

**Issue by felipeab10** [baptisteArno/typebot.io#1056]
Hello, I'm having problems receiving messages on WhatsApp, they're losing their formatting, the preview is ok.

![image](https://github.com/baptisteArno/typebot.io/assets/46427955/eb088015-84eb-44db-b806-081a90368abc)
const ddds = [ "71", "73", "74", "75", "77", "67", "86", "89" ].includes( String({{telefone}}).substring(0, 2) );
const smart = JSON.parse({{smart}});
const redesSociais = JSON.parse({{redesSociais}});

return `
Vamos lá, seguem o *planos* disponíveis para contratação.
\n

✅ ${smart.nome} 🏆
\n
${smart.descricao}
\n
${smart.descricaoBase}
\n
${smart.descricaoFlashSales}
\n
${smart.descricaoPortabilidade}
\n
${smart.descricaoC6}
\n
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
\n
✅  ${redesSociais.nome} 📱
\n
${redesSociais.descricao}
\n
${redesSociais.descricaoBase}
\n
${redesSociais.descricaoFlashSales}
\n
${redesSociais.descricaoPortabilidade}
\n
${redesSociais.descricaoC6}
\n
Qual plano deseja escolher?
`;

![image](https://github.com/baptisteArno/typebot.io/assets/46427955/69c7a1c5-cb22-441f-90cd-7d2bd39bf11f)

to show I'm using this variable "conteudoPlanos"

![Captura de tela 2023-11-23 152220](https://github.com/baptisteArno/typebot.io/assets/46427955/ba76747a-07e6-464f-aee7-6ddd62c21d86)

**Comment by ruben18salazar3** [comment]
I have the same problem...line breaks are not being generated when generating texts with the variable functionality:

![image](https://github.com/baptisteArno/typebot.io/assets/86245508/e1448514-ea02-4f01-85d3-d6ee5712b6d3)

**The variable is set with this code:**

```
let ids = {{Cerveza_ID_Catalogo}};
let nombres = {{Cerveza_Catalogo}};
let precios = {{Cerveza_Precio_Catalogo}};

let salida = ids.map((id, index) => `${ids[index]} | $${precios[index]} | 🍺 ${nombres[index]}`).join('\n\n');

return salida;
```

**La salida esperada es:**

![image](https://github.com/baptisteArno/typebot.io/assets/86245508/c9f7a93d-93df-442b-b5dd-a964be67117c)
