### ISSUE TITLE
process.env.NEXT_PUBLIC_VIEWER_URL is missing in env

### ISSUE THREAD

**Issue by traderpedroso** [baptisteArno/typebot.io#106]
Even when I set it and rebuild on vercel it's returning process.env.NEXT_PUBLIC_VIEWER_URL is missing in env

I have both env set on both side 

https://viewer.mydomain.com
https://typebot.mydomain.com

**Comment by murmrs** [comment]
I'm getting the same issue - what was the solve here? Feel like I'm missing something obvious.

**Comment by traderpedroso** [comment]
Hardcode changing VIEWER_URL to process.env.NEXT_PUBLIC_VIEWER_URL on my fork

**Comment by traderpedroso** [comment]
> I'm getting the same issue - what was the solve here? Feel like I'm missing something obvious.

`env('VIEWER_URL') to process.env.NEXT_PUBLIC_VIEWER_URL`

**Comment by baptisteArno** [comment]
> > I'm getting the same issue - what was the solve here? Feel like I'm missing something obvious.
> 
> `env('VIEWER_URL') to process.env.NEXT_PUBLIC_VIEWER_URL`

This should not be a solution. `env` function is here for a reason. I need more info to investigate what's the issue
