### ISSUE TITLE
The `details` column of the Log table is always empty rendering debug impossible

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#1063]
Whenever a webhook returns an error, I'd like to be able to access it's error logs. Though, the `Log` table doesn't have any details/logs in it's `details` column.

![image](https://github.com/baptisteArno/typebot.io/assets/73610779/4c0dda45-401f-48de-8e18-16b44bfc543b)

**Comment by baptisteArno** [comment]
In theory, it should!

I'm not sure what you are showing in the screenshot

**Comment by Lanhild** [comment]
@baptisteArno The screenshot shows a row of the `Log` table in my self-hosted instance. The last column in the screenshot is the `details` column of that same table. It only contains `{}`, i.e. an empty object.

**Comment by Lanhild** [comment]
@baptisteArno Yeah, the only content is the body of my webhook, and a partial response
