### ISSUE TITLE
Too many requests. try again later.

### ISSUE THREAD

**Issue by EduardoJC77** [baptisteArno/typebot.io#1066]
I installed Typebot via doc composer on a VPS server and I am managing the stakes and proxy through Portainer and Traefik. After configuration and installation on the VPS server, when I enter the domain to access with the configured email, the following error message appears :

Too many requests. try again later.

What could be causing the error?

![image](https://github.com/baptisteArno/typebot.io/assets/97754681/fd804138-4d69-46ef-8b4b-fa0bd0c4c544)

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by bee360** [comment]
Same around here. I not even have logged in before and it is not working at all.
