### ISSUE TITLE
I can´t get connected with Google Sheets

### ISSUE THREAD

**Issue by FabiolaBaani** [baptisteArno/typebot.io#1067]
I have a self-hosting typebot running, but when I need connect to Sheets, I always receive the message (in the fourth image):
![image](https://github.com/baptisteArno/typebot.io/assets/33585451/8636f7b9-868f-4038-b3ba-1f1849afd120)
![image](https://github.com/baptisteArno/typebot.io/assets/33585451/7912ca53-8f64-47e1-9186-2c71d83b6eaa)
![image](https://github.com/baptisteArno/typebot.io/assets/33585451/993bf9c8-62a4-42d6-acb0-faf82007d231)
![image](https://github.com/baptisteArno/typebot.io/assets/33585451/ff9ab145-01a9-4d43-a630-d7023b6942a3)

_Originally posted by @FabiolaBaani in https://github.com/baptisteArno/typebot.io/issues/1055#issuecomment-1828959743_

**Comment by FabiolaBaani** [comment]
> Did you correctly set your `GOOGLE_CLIENT_ID` environment variable? https://docs.typebot.io/self-hosting/configuration#google-auth-sheets-fonts

Yes. At the photo I change some characters by "x" for safety

**Comment by baptisteArno** [comment]
Mmmh not sure what's going on! Are you sure you restarted the docker compose after adding your env variable?

**Comment by FabiolaBaani** [comment]
Yes, but I'll do that again

Em ter, 12 de dez de 2023 10:07, Baptiste Arnaud ***@***.***>
escreveu:
