### ISSUE TITLE
Unable to sign in with sign up disabled?

### ISSUE THREAD

**Issue by abdullahbaa5** [baptisteArno/typebot.io#1081]
Fresh install on docker with latest version.
Only have SMTP Enabled.

When I set DISABLE_SIGNUP to true, I am not even able to sign in (i get error sign up not allowed) error even tho i am trying to log in...

with DISABLE_SIGNUP set to false I can sign in and i do get the email for login just fine...

**Comment by baptisteArno** [comment]
That's odd, I can't reproduce. Are you sure that the user is already created when you try to sign in with `DISABLE_SIGNUP` enabled?

**Comment by abdullahbaa5** [comment]
> That's odd, I can't reproduce. Are you sure that the user is already created when you try to sign in with `DISABLE_SIGNUP` enabled?

just to confirm, is the admin email we define in env created by default.. if no then that is probably why...
