### ISSUE TITLE
create variables dynamically ?

### ISSUE THREAD

**Issue by waelchamkhi** [baptisteArno/typebot.io#1085]
I'm not sure if this counts as an issue or not but I need help with this problem
is it possible to create variables dynamically ? 
I have a section in my bot that allows the user to input a title and description , I don't know how many titles and descriptions the user will be adding so I thought of making a loop 
2 blocks one containing a text input to add the title then takes the user to the other block , they can add the description and choose to move on or add another title which will take them back to the title block restarting the process again.
is it possible to change the variables I store the title and description in everytime the user enters the block ? something like 
title1 desc1 , title2 desc2 , ... 
if there's an alternative solution I'd really appreciate the help thank you !

**Comment by baptisteArno** [comment]
Sure, you could keep track of a variable called "Aggregate" or something then you'd add a Set variable block below the user input and put:

{{Aggregate}} + {{Title answer}}

**Comment by baptisteArno** [comment]
Definitely not an issue though! Feel free to join the Discord to talk about it! https://typebot.io/discord
