### ISSUE TITLE
The bot you're looking for doesn't exist 

### ISSUE THREAD

**Issue by cherrycharan** [baptisteArno/typebot.io#1086]
I have two deployements which has been done one using docker-compose and another in K8's . The underlying DB is hosted in AWS RDS service and i am connecting to the same db in both deployments . 

When i tried to open bot with url which is pointing to k8's is getting 404 error but when i open with url which is pointed to docker deployment in Ec2 its working . 

Any idea how to resolve this ?

**Comment by cherrycharan** [comment]
There was a config issue , we  configured viewer url wrongly .
There was a trailing forward slash(/) in viewer url

**Comment by bpawel-bclub** [comment]
I have the same error, and the url seems correct. I am running it in Docker, behind nginx.
``` 
typebot-typebot-viewer-1   | 2023-12-12T00:49:58.772869347Z TypeError: Cannot read properties of undefined (reading 'split') 
```
