### ISSUE TITLE
typebot json not sending openai response

### ISSUE THREAD

**Issue by laroccathebrux** [baptisteArno/typebot.io#1090]
I setup the typebot on the Izing.io platform like this:
![image](https://github.com/baptisteArno/typebot.io/assets/7272614/1bb9e163-7bf6-4530-abc4-edf1b4a2246f)

My typebot flow is this:
![image](https://github.com/baptisteArno/typebot.io/assets/7272614/a5fda026-a249-4427-ad2f-21575df76a8a)

The result in webhook site is:
![image](https://github.com/baptisteArno/typebot.io/assets/7272614/37f9c913-c7b1-48b3-a562-f62450497e42)

It happens only for OpenAi.
Example:

![image](https://github.com/baptisteArno/typebot.io/assets/7272614/1eb104fa-db0a-44e4-b211-c1a26730edfc)

**Comment by baptisteArno** [comment]
Hi,

This sounds like an issue with the service you're using (Izing). Please reach out to them.

On another note, I suggest you use the official WhatsApp integration

**Comment by joweste** [comment]
> I setup the typebot on the Izing.io platform like this: ![image](https://private-user-images.githubusercontent.com/7272614/289086609-1bb9e163-7bf6-4530-abc4-edf1b4a2246f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzE3OTksIm5iZiI6MTcwMjczMTQ5OSwicGF0aCI6Ii83MjcyNjE0LzI4OTA4NjYwOS0xYmI5ZTE2My03YmY2LTQ1MzAtYWJjNC1lZGYxYjRhMjI0NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTI1ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTZhMzUwMjkwOTAwMThhYWU5MTcyYmE2MDVkMjA2ZmUxM2Q4YzQxZTczNzUwNDVjNGE3YTIyY2I0NDkzYzQ4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JhwUR9XhrKBjaAFhNboZv5uZ0V5doJ4OFTucEd5XR4Q)
> 
> My typebot flow is this: ![image](https://private-user-images.githubusercontent.com/7272614/289086893-a5fda026-a249-4427-ad2f-21575df76a8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzE3OTksIm5iZiI6MTcwMjczMTQ5OSwicGF0aCI6Ii83MjcyNjE0LzI4OTA4Njg5My1hNWZkYTAyNi1hMjQ5LTQ0MjctYWQyZi0yMTU3NWRmNzZhOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTI1ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM4MmI3YWEwMzAwOTNiZTc4ZWY0OWMwOTE0ZjAwYTU5NzJlNGU3YzVhMjVjNmI1MjNmN2I3NWVmNTQ2MDkyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9cczB8v3VMaT6UhCrjNr8WK0yYpMVySMpf2XGoBeZxA)
> 
> The result in webhook site is: ![image](https://private-user-images.githubusercontent.com/7272614/289087079-37f9c913-c7b1-48b3-a562-f62450497e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzE3OTksIm5iZiI6MTcwMjczMTQ5OSwicGF0aCI6Ii83MjcyNjE0LzI4OTA4NzA3OS0zN2Y5YzkxMy1jN2IxLTQ4YjMtYTU2Mi1mNjI0NTA0OTdlNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTI1ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ5Mzc5MTc4N2U0NWRhYjM5NzhhYTk5ODMyMTE4MTI4YzgyNzU2ZjRiZTE5MzNlOGUwMWY1ZGVhYzkwMzQxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._nEc8i09MJlM5pWyxjyaP21gli9kEHAr78eurz638vI)
> 
> It happens only for OpenAi. Example:
> 
> ![image](https://private-user-images.githubusercontent.com/7272614/289087455-1eb104fa-db0a-44e4-b211-c1a26730edfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzE3OTksIm5iZiI6MTcwMjczMTQ5OSwicGF0aCI6Ii83MjcyNjE0LzI4OTA4NzQ1NS0xZWIxMDRmYS1kYjBhLTQ0ZTQtYjIxMS1jMWEyNjczMGVkZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTZUMTI1ODE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTZjZDE3OWQ4YzgzODczNWExZTU1NmE2ZTQzZDNmZjBlMTY1MGExZjRkYmQwZWI5ZGUwMzYwNzM4MzEwNmQyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f5lFEzBK54zM91BtnMmDDeALlNozufXEU7lx9eI6lew)

Your izing version has a bug.  I have a izing modified version that I did. I implemented typebot integration on it and it´s working  very well

**Comment by laroccathebrux** [comment]
it was indeed a izing issue. I solved working with another solution called Evolution-API.
