### ISSUE TITLE
Move the canvas with shift and ctrl + mousewheel (just like figma) [improvement]

### ISSUE THREAD

**Issue by lerenos** [baptisteArno/typebot.io#1092]
Hello!
Congrats for this great software.

## Feature Request/Improvement:
Move the canvas using:
- the mousewheel to move up and down (default web behaviour)
- shift + mousewheel to move left and right
- ctrl + mousewheel to zoom in and out

## Why?
1. Nowadays, some little bugs happen when draggind the canvas around. Sometimes I grab the empty screen, but accidentally move a block (even if I clicked far from the block). If I do a single click once on the canvas, and then click again to grab the screen, then everything works fine.
2. The above mentioned way can make us more faster to move around
3. It is a usual way to move around canvas, used in some great softares, such as Figma and Manychat.

A little improvement that would make the work way more pleasant :)
Thanks in advance!

**Comment by baptisteArno** [comment]
Can you tell me what's the current behavior with a mouse?

**Comment by lerenos** [comment]
Current behaviour:
- Scroll for zoom
- Ctrl and Shift have no effect
- To move on the screen, you have to grab the empty area of the canvas (actually you have to make a single click to 'activate' the empty area, and then grab the screen).
