### ISSUE TITLE
"Error! Couldn't initiate the chat." - I have searched for this among the issues, but no other case is similar to this

### ISSUE THREAD

**Issue by Anonym69** [baptisteArno/typebot.io#1093]
I have searched for this issue ("Error! Couldn't initiate the chat.") in the github issues, but I can't find anything that is similar to my case.

The server is a 40 vCPU server, 512 GB RAM, super fast NVMe disks running Proxmox and this server is running in a VM running Debian 12. Several other web sites run on this server and they run smoothly. I really have no clue what is wrong. I would appreciate some help. Port 8080 and 8081 are both open in the firewall. So far I am running Typebot without https.

This is what happens:

https://screencast-o-matic.com/watch/c0l6fpVmG14

--

// Please note! I am running Debian 12, docker compose is called just that, not docker-compose.

docker compose logs

https://pastebin.com/S014Ppst

// content of .env file

https://pastebin.com/b9hM3C8y

// docker compose.yml

https://pastebin.com/TfjHqATS

=====================

I am out of ideas and I would really appreciate some help.

Thank you!

**Comment by Anonym69** [comment]
What does this mean?

![image](https://github.com/baptisteArno/typebot.io/assets/4282174/0ca00b93-8ff0-43c8-9e26-a30c9c7ef81c)

**Comment by Anonym69** [comment]
Hmmm... So it could potentially be a reverse proxy thingy.

**Comment by Anonym69** [comment]
Hmmm... I am not using https, so I should not have to add a reverse proxy.
I am clueless.

Any ideas, @baptisteArno ?

**Comment by baptisteArno** [comment]
So this is an issue while previewing the bot?

Is there the same issue when starting a published bot?

You really don't have more server logs than the one you provided?

**Comment by Anonym69** [comment]
I run the Test on it, so I guess it's previewing it. When publishing it it, I get an HTTP error 404. 
Building it is not a problem at all. 

Nope that is what is mentioned in the logs. I have the same for every attempt, but I guess that won't help...?

**Comment by Anonym69** [comment]
Latest logs:

https://pastebin.com/eNTHSW4K

**Comment by Anonym69** [comment]
This is what I got. Why would Stripe variables be necessary?

https://pastebin.com/mXAqtFUT

**Comment by baptisteArno** [comment]
The Stripe error is unrelated to your issue, you most likely opened a Upgrade popup that generate the error.

In your logs I can't see any `[DEBUG]` log. So it seems you either did not restart the app after adding the variable or didn't launched the published bot.

A video recording would help make sure you are doing things right

**Comment by Anonym69** [comment]
You are right, but I stopped and removed the docker container several times and I realize now that debug was never activated at all. I found the error now. It was a port issue.

Thank you for your help.!

**Comment by Anonym69** [comment]
How do I access the latest addition, Chatnode integration?

**Comment by baptisteArno** [comment]
Next release :)
