### ISSUE TITLE
Error when using typebot Bubble in vite.js

### ISSUE THREAD

**Issue by LucasAlexsander** [baptisteArno/typebot.io#1097]
When I try to use Standard mode, everything works fine, where I can see the perfect conversation with the bot, however, if I want to use Bubble it ends up giving an error in the typebot.io repository. The following error appears:
![Screenshot_1](https://github.com/baptisteArno/typebot.io/assets/90354669/db4f9cb7-ebb1-48bf-8ef1-4a2e74fef08e)
![Screenshot_2](https://github.com/baptisteArno/typebot.io/assets/90354669/a4146ec8-6f38-4884-a051-2ff604f6730b)

**Comment by baptisteArno** [comment]
Can you provide a reproduction? How can I reproduce this from scratch?
