### ISSUE TITLE
The bot you're looking for doesn't exist (docker, nginx)

### ISSUE THREAD

**Issue by bpawel-bclub** [baptisteArno/typebot.io#1098]
I have the same error as #1086, and my url seems correct. I am running it in Docker, behind nginx.

``` 
typebot-typebot-viewer-1   | 2023-12-12T00:49:58.772869347Z TypeError: Cannot read properties of undefined (reading 'split') 
``` 

typebot works fine
bot (viewer) shows this error: The bot you're looking for doesn't exist

**Comment by baptisteArno** [comment]
try to add the DEBUG=true variable and provide the logs 👍

**Comment by baptisteArno** [comment]
So here I can see that your `NEXT_PUBLIC_VIEWER_URL` is set to `https://bot.example.com` or did you edit this intentionnally?

**Comment by bpawel-bclub** [comment]
> So here I can see that your `NEXT_PUBLIC_VIEWER_URL` is set to `https://bot.example.com` or did you edit this intentionnally?

I didn't want to post my real address here, but of course I have my own domain specified.

**Comment by baptisteArno** [comment]
Ok so it seems the host is not properly forwarded with your NGINX config: https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

**Comment by baptisteArno** [comment]
Also related: https://github.com/baptisteArno/typebot.io/issues/840#issuecomment-1859829583
