### ISSUE TITLE
Integration webhook Custom body not working  with variables 

### ISSUE THREAD

**Issue by traderpedroso** [baptisteArno/typebot.io#110]
Example 

Variable block

```javascript
JSON.stringify({
  "amount": parseFloat({{amount}}),
  "email": {{Email}}
})
```

Variable name body

inside the custom Body 

`{{body}}`

its not reading the variable

**Comment by baptisteArno** [comment]
That's not clear enough. Can you tell me how I can reproduce?

**Comment by traderpedroso** [comment]
> That's not clear enough. Can you tell me how I can reproduce?


For dynamic custom body when it changes according to bot interaction, I save these entries in different variables then I have to pass them in json format for set body webhook integration

let's say I got the input email and name I sent them to two variables one `"Email"` another `"Name"` I need to convert them in the block of variables to json I do the following

Logic 
i use set variable for code "variables block"

inside the editor 

```javascript
JSON.stringify({
  "name": {{Name}},
  "email": {{Email}}
})
```

and select to save the output in other variable  `data-from-variable`

 if i set the variable `{{data-from-variable}} `in Buddles Text the output will be 

```json
{"Name":"Name Example","email":"myemail@example.com"}
```


as I have the output exactly the right way in json I would like to use it in **integration webhooks** I configure everything `url` `header` and when I get to body `select custom body` and in the` code editor `inset the variable `{{data-from-variable}} ` usually a malformatted json error appears, in the code is set to lang="json" I tried changing the code to lang="js" the error stopped appearing,  even in both attempts they didn't work, then I put a console.log debug inside the code to find out and the variable doesn't arrive in body.

But when I put it in JSON format directly inside the custom body, it works normally
```json
{"Name":"Name Example","email":"myemail@example.com"}
```

**Comment by baptisteArno** [comment]
Thank you for this use case 👍
