### ISSUE TITLE
File name and extension in s3 url

### ISSUE THREAD

**Issue by DavidsonGomes** [baptisteArno/typebot.io#1100]
How do I make the url of the uploaded file come with the file name and extension?

In other previous versions there was still a way to change this in the code, but in this new one I no longer see it. Is there any option in the env that can be done?

<img width="622" alt="Screenshot 2023-12-13 at 06 31 03" src="https://github.com/baptisteArno/typebot.io/assets/24706726/e512ec67-4063-4eba-abf8-e98dba8ba287">

**Comment by DavidsonGomes** [comment]
created PR to solve this problem #1101

**Comment by baptisteArno** [comment]
Why would you want that?

We omit the name so that it overwrites previously uploaded image on the same asset.

**Comment by DavidsonGomes** [comment]
> Why would you want that?
> 
> We omit the name so that it overwrites previously uploaded image on the same asset.

I'm the developer of the Evolution API, when we pull the files with axios, it gets a little lost in relation to the mimetype to send on WhatsApp, when we send it with the file name in the url the system can pick it up much easier

https://github.com/EvolutionAPI/evolution-api

**Comment by baptisteArno** [comment]
You should be able to get the Mime-type with the `content-type` header returned though 🤔

I'm sorry but Typebot would have no use of this kind of feature 🙏

**Comment by DavidsonGomes** [comment]
The problem is the following, I receive the feedback from the api, and the content.url comes to me, would it be possible to send the mimetype as well?

Because when axios tries to retrieve the file by doing get no content.url I can't know the mimetype, can you show how you would solve this?

**Comment by DavidsonGomes** [comment]
> You should be able to get the Mime-type with the `content-type` header returned though 🤔
> 
> I'm sorry but Typebot would have no use of this kind of feature 🙏

How could we resolve this detail in the way it is today? People who use the API with typebot are unable to send the media when they are in s3/minio, would it be possible to retrieve the mimetype somehow?

**Comment by baptisteArno** [comment]
What do you mean you can't get the mime/type? I think axios should return the content-type header with the mimtype.

**Comment by baptisteArno** [comment]
A simple GET request should return the `content-type` header:

<img width="1394" alt="CleanShot 2023-12-14 at 13 53 55@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/cd86a9ca-b74b-433f-a6c7-40a610d26f3a">

**Comment by DavidsonGomes** [comment]
> Uma simples solicitação GET deve retornar o `content-type`cabeçalho:
> 
> <img alt="CleanShot 14/12/2023 às 13 53 55@2x" width="1394" src="https://private-user-images.githubusercontent.com/16015833/290523805-cd86a9ca-b74b-433f-a6c7-40a610d26f3a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NjUxNTMsIm5iZiI6MTcwMjU2NDg1MywicGF0aCI6Ii8xNjAxNTgzMy8yOTA1MjM4MDUtY2Q4NmE5Y2EtYjc0Yi00MzNmLWE2YzctNDBhNjEwZDI2ZjNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDE0NDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlODNkMDM3YTRiMmJhZWRmZTUyOWU5MmViZjMyY2I4NzY4OTAzODU2MTI1Y2IxYmMyOTU2YWJkYjljZDYzMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XpQ--2XJAQoNIx3pmjgEEHNd-qVFxYO9pXmwu6NDCSE">

Thank you, problem solved then!
