### ISSUE TITLE
Typebot v.2.20 - Problem with googlesheet - Resolvido

### ISSUE THREAD

**Issue by adonisluiz** [baptisteArno/typebot.io#1103]
I installed version 2.20 of typebot on the server and I'm having problems with Googlesheets. Follow the prints below

![image](https://github.com/baptisteArno/typebot.io/assets/70245225/1389169c-2cf5-40c5-ad11-9cfbb9e13f1d)

![image](https://github.com/baptisteArno/typebot.io/assets/70245225/1a328008-8f3f-4faa-890d-6b5187a357ad)

As you can see, there is no duplicate item and it is reporting that it does not exist.

How could I resolve this issue?

Because even version 2.18.2 didn't have this problem.

**Comment by adonisluiz** [comment]
Foi equivoco meu ficou faltando adicionar dentro do sistema do app liberar api e colocar dentro dele o acesso

**Comment by adonisluiz** [comment]
> I installed version 2.20 of typebot on the server and I'm having problems with Googlesheets. Follow the prints below
> 
> ![image](https://private-user-images.githubusercontent.com/70245225/290221020-1389169c-2cf5-40c5-ad11-9cfbb9e13f1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Nzg5ODcsIm5iZiI6MTcwMjQ3ODY4NywicGF0aCI6Ii83MDI0NTIyNS8yOTAyMjEwMjAtMTM4OTE2OWMtMmNmNS00MGM1LWFkMTEtOWNmYmI5ZTEzZjFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE0NDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmN2M4YjllZmFhMDNiN2U5Y2RlY2RjOTk0MDVkN2I0ZjBlMWFkNThlZDkyNTRhOTkxMjIwODdhOTMyZmEwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BVWXvaWmcaDwzMGbgvzZ0U-VKx0hOLDNKMQdsNSdW1U)
> 
> ![image](https://private-user-images.githubusercontent.com/70245225/290221107-1a328008-8f3f-4faa-890d-6b5187a357ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0Nzg5ODcsIm5iZiI6MTcwMjQ3ODY4NywicGF0aCI6Ii83MDI0NTIyNS8yOTAyMjExMDctMWEzMjgwMDgtOGYzZi00ZmFhLTg5MGQtNmI1MTg3YTM1N2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDE0NDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3OGUyNTM4ODZjZDFkMjA1MzRmMDNiZTljZWY2ZTgyZGRiMDU3YmMzY2I5ODYxOTkzMzIxNzllM2M5NTU5YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nRi9rhWBCfMzCSP7AiDmNi7r32ZTznLy5Nb7gX8VU88)
> 
> As you can see, there is no duplicate item and it is reporting that it does not exist.
> 
> How could I resolve this issue?
> 
> Because even version 2.18.2 didn't have this problem.

**Comment by bizkast** [comment]
@adonisluiz : Can you please share the steps you took to address this? I am facing similar issue
