### ISSUE TITLE
I CANNOT SEND PREFILLED VARIABLES USING THE N8N HTTP REQUEST

### ISSUE THREAD

**Issue by fortisbr** [baptisteArno/typebot.io#1108]
[HELP] [START TYPEBOT] [PREFILLED VARIABLES] [HTTP REQUEST N8N]

How do I send the data I collected through an n8n webhook, to start a typebot flow, using http request or another node that starts typebot and for typebot to receive this data to use in the flow.

I saw in the typebot documentation that it is necessary to use "Prefilled variables", but I am not getting these variables received in typebot. The same variables that I am sending in prefilled variables, I am also defining within typebot, but typebot does not recognize the data.

I published the typebot, and got the API link (https://chat.embaixadorton.com.br/api/v1/typebots/cupom-whatsapp-t3-smart-promo/startChat) and added an http request on n8n, as POST method.

![http-request01](https://github.com/baptisteArno/typebot.io/assets/66486056/2afe7390-8590-4f51-8adc-0f5ec26a6c0f)

![http-request02](https://github.com/baptisteArno/typebot.io/assets/66486056/46e96629-23d4-4147-bf73-547d1a208e03)

![json-n8n-variables](https://github.com/baptisteArno/typebot.io/assets/66486056/435c0050-bb20-431f-a7fe-8b1e6c3e54c7)

![typebot-api](https://github.com/baptisteArno/typebot.io/assets/66486056/79db2603-63e3-4838-9291-263cd62739ed)

![typebot](https://github.com/baptisteArno/typebot.io/assets/66486056/19923d59-98e4-463c-94b7-ba90b98f1833)

**Comment by baptisteArno** [comment]
You are reinitiliazing the variables with the `Group #2`. Delete this group and it will work like a charm :)

**Comment by cleitondm** [comment]
I have the same problem. sending request via n8n to typebot.

follows as images,

![image](https://github.com/baptisteArno/typebot.io/assets/49585614/57eb7e28-aff6-4716-babc-d110c7ca1213)


n8n
![image](https://github.com/baptisteArno/typebot.io/assets/49585614/c1602ffa-a7e4-4f8d-81fa-e51a94132355)

**Comment by baptisteArno** [comment]
@cleitondm What problem are you showing here?

**Comment by drksbr** [comment]
I believe I managed to reproduce the problem reported in this thread.

It turns out that the predefined variables at the time of initialization of the flow are only being received when passed via TypeBotViewer, if passed via API the flow does not receive the value of the variable.

It's an issue related to the topic: https://docs.typebot.io/editor/variables#prefilled-variables

ex:
-- https://typebotviewer.domain.com/bot1?Name=JohnDoe (This is ok)

-- https://typebotapi.domain.com/api/v1/typebots/bot1/startChat?Name=JohnDoe (This is not working)

**Comment by baptisteArno** [comment]
https://typebotapi.domain.com/api/v1/typebots/bot1/startChat?Name=JohnDoe

That does not work like that. See the `prefilledVariables` in the body configuration: https://docs.typebot.io/api-reference/chat/start-chat
