### ISSUE TITLE
Docker - DISABLE_SIGNUP Ignored

### ISSUE THREAD

**Issue by bionemesis** [baptisteArno/typebot.io#111]
I have setup - DISABLE-SIGNUP=true under both viewer and builder environment variables within my docker-compose.yml. However, new signups are still permitted. I've even completely wiped my containers and volumes and started from scratch and there is no change. Is it possible that variable isn't supported via docker?

**Comment by baptisteArno** [comment]
That's odd 🤔

I just tried it out and it works as expected. Are you sure new signups are still permitted? You managed to create new accounts?

**Comment by bionemesis** [comment]
Ah I see now, so it still generates the sign up email, but clicking on it just results in an error. I was expecting it to either disable the UI ability to create a new account or just not send an email. Should probably do one of those things, otherwise it's just generating email needlessly.

**Comment by baptisteArno** [comment]
Yeah I can add a check before sending the email, thank you for the suggestion 👍
