### ISSUE TITLE
Option to tell the API to return markdown instead of rich text

### ISSUE THREAD

**Issue by fortisbr** [baptisteArno/typebot.io#1111]
Hello @baptisteArno!

I'm facing an issue with prefilled variables sent from n8n via an HTTP request not being displayed correctly in my Typebot chat flow.

I've set up an HTTP request node in n8n with the Typebot API endpoint and included the necessary headers and body. While the Typebot seems to recognize the variables (as shown in the attached screenshots/output examples), these variables are not being displayed as expected in the chat flow.

Despite trying to manipulate the variables within Typebot and ensuring that the variable group is not connected (to avoid reinitialization), the issue persists. I've also tested without the variable group inside Typebot but to no avail.

Could you please advise if there's a specific setup or syntax required in Typebot to handle these prefilled variables correctly? Any guidance or suggestions would be greatly appreciated.

Thank you for your support, and greetings from Brazil!
Junior Mota

![http-request01](https://github.com/baptisteArno/typebot.io/assets/66486056/91990789-2ba3-4dd1-a984-a7a927a85f18)
![body-json-n8n](https://github.com/baptisteArno/typebot.io/assets/66486056/3438ebc1-57de-4e07-93fd-2307383f8cc7)
![output01](https://github.com/baptisteArno/typebot.io/assets/66486056/893e39b8-8863-400e-9a20-8dc703a612dc)
![output02](https://github.com/baptisteArno/typebot.io/assets/66486056/afda7ab7-02e3-4606-9218-7570f6e851f4)
![typebot-start](https://github.com/baptisteArno/typebot.io/assets/66486056/a44b52ad-d817-46f6-a0c2-cd9eeea86284)
![typebot-start2](https://github.com/baptisteArno/typebot.io/assets/66486056/9987dea5-7087-4d1f-9ea7-8f8f76f74522)
![typebot-start03](https://github.com/baptisteArno/typebot.io/assets/66486056/c4e49d69-9e02-487c-ab63-29bca304258f)

**Comment by baptisteArno** [comment]
> these variables are not being displayed as expected in the chat flow.

What are you expecting? What you show in the screenshot looks right to me!
