### ISSUE TITLE
GPT chat completion duplicating messages

### ISSUE THREAD

**Issue by drauber** [baptisteArno/typebot.io#1112]
I have few GPT chat completions in typebot, before the version 2.20 it work like a charm, but, after uptade to 2.20, the response of chat completion is generating an array of values, incrementing it at every new phrase.
Like this, in TypeBot 2.19
![2 19 GPT_Example](https://github.com/baptisteArno/typebot.io/assets/4416953/50c8c465-997d-4814-838b-281d36cc3bd0)
and, in 2.20
![2 20_GPT_Example](https://github.com/baptisteArno/typebot.io/assets/4416953/4668dbb8-957b-4437-abd9-1edbaae691e2)

this is the flow 
[Flow.json](https://github.com/baptisteArno/typebot.io/files/13725814/Flow.json)

How i can i send to screen only the last message from GPT?

**Comment by baptisteArno** [comment]
Yes that's part of the Typebot schema breaking changes (https://docs.typebot.io/breaking-changes).
