### ISSUE TITLE
Googlesheets integration issue: Could not fetch Typebot during configuration step

### ISSUE THREAD

**Issue by bizkast** [baptisteArno/typebot.io#1113]
Hi team, 
I have a self hosted typebot that I am building out. 
I am trying to connect to google sheets. I've gone through the process of creating the app enabling APIs, credentials, settign environment variables (Client ID, and Secret).

On the flow screen, when I go through the 'Connect' step (i've tried with multiple google accounts), the integration fails.
First I see "Saving" on the screen (one of the images below), and after a 1 minute, I see "Failed to fetch" (the other two images  below).

Any clue what could be the culprit here? Cheers

![Sheets conection](https://github.com/baptisteArno/typebot.io/assets/154477759/c3446dad-d407-41e3-8d05-bf5a06b956d0)
![Sheets conection1](https://github.com/baptisteArno/typebot.io/assets/154477759/f6f4ed3f-d7c2-45a2-b3ab-f74a501da044)
![Sheets conection2](https://github.com/baptisteArno/typebot.io/assets/154477759/693e07d5-375b-4020-9184-ed169d5f372a)

**Comment by baptisteArno** [comment]
Oh right, the documentation was updated for the new Typebot version that will be available the 1st of Jan. So for now, you need to add the `drive.readonly` scope in your OAuth config

**Comment by bizkast** [comment]
@baptisteArno : Thanks for the response. I just added that scope as well. Unfortunately, I am still facing the same issue.
Does it take a while for the changes to propagate?
And do we need to change anything on the environment variables at all ( I assume not)

**Comment by baptisteArno** [comment]
Delete your credentials and create it again!

**Comment by bizkast** [comment]
That isn't the root cause I am afraid. I've tried that. The connection was established with the sheet so it isn't the credentials. I am investigating and will report back, but I feel the typebot code/configuration parameteres doesn't integrate with the latest version of the google app. Will share more details shortly.

**Comment by Bipund** [comment]
I have same problem while doing this any solution on this

**Comment by Bipund** [comment]
<img width="1248" alt="Screenshot 2023-12-27 at 11 17 59 PM" src="https://github.com/baptisteArno/typebot.io/assets/41412272/d95fa93d-f3b6-433f-a65f-a964ab374876">
this is what my permission looks like @baptisteArno

**Comment by bizkast** [comment]
@baptisteArno : Looks like others have the same issue. I can confirm that I've tried it on the cloud version of typebot and it is working ok. On the self hosted version, it looks like there are issues in the read/edit/view settings of the scope. Can you please reopen this issue and advise.

**Comment by baptisteArno** [comment]
A video recording would help a lot understanding what's up here 🙏

**Comment by bizkast** [comment]
@baptisteArno : As you requested, please see link to the video recording explaining the issue being faced: https://drive.google.com/file/d/16Tp7XWqrN7DXVVaBCyPd3OvhAAwPr7zG/view?usp=sharing

I'd appreciate your review.

**Comment by baptisteArno** [comment]
<img width="446" alt="CleanShot 2024-01-02 at 10 30 38@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/3a233acf-1cdc-4e39-9073-944631253a18">

This looks strange, it should show "Google Drive API" instead of "Google Sheets API"

I just released 2.21.0 that should with the requirements from https://docs.typebot.io/self-hosting/configuration#google-auth-sheets-fonts

**Comment by bizkast** [comment]
It works! updated the code and reconfigured the app. Feel free to close the ticket!
