### ISSUE TITLE
Import typebot flow at installation time

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#1122]
I want to install it, and when I access it for the first time there will already be a typebot flow inside, how can I do this?
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/3d6b626b-ae30-4ba0-8321-1e52a1f25575)

**Comment by baptisteArno** [comment]
There is no such feature! You could use the API under the hood to automatically create a typebot but I'm not sure why you need this.

I'll close this for now as it's not relevant for Typebot Cloud.
