### ISSUE TITLE
Can I set the time zone in a variable in the .env file?

### ISSUE THREAD

**Issue by willph** [baptisteArno/typebot.io#1126]
Would it be possible to configure a variable in the .env file to get the local time?

Because System.Now is picking up UTC and as I live in Brazil it is -3

Even configuring the server as America/Sao_Paulo, Typebot continues to pick up Universal Time

**Comment by baptisteArno** [comment]
I could add options with the `System.now` to format to a specific timezone

**Comment by eliasmainetti** [comment]
Hi Guys, 
I'm also from Brazil and timezone would be a great improvement.

**Comment by baptisteArno** [comment]
Feature introduced recently!
