### ISSUE TITLE
Dynamic values for buttons not working properly 

### ISSUE THREAD

**Issue by kaminske** [baptisteArno/typebot.io#1129]
in my chatbot I'm adding the options for a buttons block dynamically , I noticed that ( in this case ) there are 3 options and one of them is always not getting selected.

As you can see in these 2 screenshots , I have selected all 3 options and when I click send only 2 are shown to be selected : 
![modifgaranties1](https://github.com/baptisteArno/typebot.io/assets/85418657/a64ccb80-096f-4dee-aa47-9df064be8b9a)
![modifgaranties2](https://github.com/baptisteArno/typebot.io/assets/85418657/848cfa8e-82b6-4c5e-99ee-9f1df12cc86e)

**Comment by baptisteArno** [comment]
I could not reproduce. What version of Typebot is it?
