### ISSUE TITLE
SMTP Config Issue

### ISSUE THREAD

**Issue by bionemesis** [baptisteArno/typebot.io#113]
We use an Amazon SES account for sending transactional emails like what's used by Typebot. We have this configured in the docker-compose.yml and it works fine for sign-up emails. When we attempt to use the same configuration (copy/paste from docker-compose.yml) in the Create SMTP config screen from an email integration, it fails with the message:

Unexpected token I in JSON at position 0

But the test email is actually sent. It doesn't let us save, however, due to the error.

**Comment by baptisteArno** [comment]
Can you check the logs after you tried to add your email config? There should be an error in the builder logs can you paste it here?

**Comment by bionemesis** [comment]
This is what docker compose logs shows, not sure if it's helpful though (sanitized).

`typebot-caddy-gen-1        | caddy.1    | {"level":"error","ts":1657984387.310109,"logger":"http.log.access.log1","msg":"handled request","request":{"remote_addr":"xx.xx.xx.xx:44755","proto":"HTTP/2.0","method":"POST","host":"mydomain.tld","uri":"/api/credentials?workspaceId=nopenottotdayhackers","headers":{"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7"],"Sec-Ch-Ua-Mobile":["?0"],"Content-Type":["application/json"],"Origin":["https://mydomain.tld"],"Sec-Ch-Ua-Platform":["\"macOS\""],"Cookie":["_MINDYOURBUSINESS"],"Referer":["https://mydomain.tld/typebots/nopenottodayhackers/edit"],"Content-Length":["300"],"Accept":["*/*"],"Sec-Fetch-Dest":["empty"],"Sec-Fetch-Mode":["cors"],"Sec-Ch-Ua":["\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\""],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"],"Sec-Fetch-Site":["same-origin"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"mydomain.tld"}},"common_log":"xx.xx.xx.xx - - [16/Jul/2022:15:13:07 +0000] \"POST /api/credentials?workspaceId=nopenottotdayhackers HTTP/2.0\" 500 21","duration":0.061987335,"size":21,"status":500,"resp_headers":{"Date":["Sat, 16 Jul 2022 15:13:07 GMT"],"Server":["Caddy"]}}`

**Comment by baptisteArno** [comment]
Have you checked the logs from your result?

See: https://docs.typebot.io/editor/results#logs

**Comment by bionemesis** [comment]
Sorry, either I'm missing something or you are misunderstanding the issue. Unless I'm mistaken, result logs only exist after the form has been submitted by a user. The issue I'm having is when I try and create an account for the email integration in the builder.

**Comment by baptisteArno** [comment]
Ok, I wasn't sure.

I need more info on the error then. Either inspect the "Network tab" of the browser and check the error message. Or try to look for an error log from the builder container.

**Comment by bionemesis** [comment]
Network tab shows a 500 error posting against /api/credentials?workspaceId=xxx (removed actual workspace ID). This is what shows up in the builder container logs:
```
RangeError: Invalid key length
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:138:10)
    at encrypt (/app/.next/server/chunks/1269.js:4146:25)
    at handler (/app/.next/server/pages/api/credentials.js:106:97)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_CRYPTO_INVALID_KEYLEN'
}
```

**Comment by baptisteArno** [comment]
Ok, so it means your `ENCRYPTION_SECRET` doesn't have the correct format. How did you generate it?

**Comment by bionemesis** [comment]
Following the documentation, but I just took a look and I believe it's missing the = at the end of what was originally generated. Not sure how that happened, but it did. What happens if I change it and restart the container?

**Comment by baptisteArno** [comment]
Indeed I just figured that the openssl command to generate the secret isn't valid.

It should be:

```sh
openssl rand -base64 24 | tr -d '\n' ; echo
```

To have a 32-char length secret.

You should be able to update your compose file, restart the app and it should fix the issue

**Comment by bionemesis** [comment]
Yup that fixed the issue. Cheers.
