### ISSUE TITLE
Display multiple rows from Google Sheets as caraousel

### ISSUE THREAD

**Issue by bizkast** [baptisteArno/typebot.io#1130]
Hi @baptisteArno,

Let's say we have an inventory of products in the database with a number of data points (Name, description, price, pictures).
What is the best way to to show these to a user who wants to browse the inventory in the chatbot?

I was thinking a caraousel within the bot that can read the data from the Google Sheets (which can be used as a Database for the products).

Your thoughts on how/whether this can be done? 'Thank you!

**Comment by baptisteArno** [comment]
Have you checked the Picture choice input with dynamic items option?

https://docs.typebot.io/editor/blocks/inputs/picture-choice

To discuss, it's preferable to do it on the Discord server :) https://typebot.io/discord
