### ISSUE TITLE
pnpm build:apps fails?

### ISSUE THREAD

**Issue by stevexm** [baptisteArno/typebot.io#1132]
Hi, I love typebot!

Hope someone might advise as to building it for self-hosting, to experiment with.  I successfully installed a clone of the repo and then ran the build command with pnpm 8.14:
`pnpm run build:apps`

Got back this error message:
`
 ERROR  run failed: Package tasks (<package>#<task>) are not allowed in single-package repositories: found docs#build
Turbo error: Package tasks (<package>#<task>) are not allowed in single-package repositories: found docs#build
 ELIFECYCLE  Command failed with exit code 1.
`

Any idea where I went wrong? Is it better to simply build each app separately, and leave out the docs#build task?

TIA,
Steve

**Comment by baptisteArno** [comment]
It looks like you forgot to run pnpm install you most likely did it with npm. You should remove the package-lock.json

**Comment by leonardocxavier** [comment]
Solved to me:  pnpm install
