### ISSUE TITLE
Bug quand on crée un nouveau typebot à partir d'un modèle

### ISSUE THREAD

**Issue by KazeroG** [baptisteArno/typebot.io#1133]
**Quand on choisit l'option : Commencer à partir d'un modèle.**
![image](https://github.com/baptisteArno/typebot.io/assets/17680194/43d06224-af57-4b86-9ed2-0d8aef07234a)

**et puis on choisit une de ces options :**
![image](https://github.com/baptisteArno/typebot.io/assets/17680194/f123cdc1-d0c8-44b3-a9c4-d980855a19df)

**ça nous crée à la place ce type de bot peu importe le modèle choisi:** 
![image](https://github.com/baptisteArno/typebot.io/assets/17680194/3a8dd03a-8f22-4989-b723-b4bfb72d0e21)

**Comment by baptisteArno** [comment]
I don't understand the situation. Can you maybe record a video?

**Comment by KazeroG** [comment]
With pleasure, :) check this out : 
https://github.com/baptisteArno/typebot.io/assets/17680194/57f23239-60c9-448d-9864-a83893c4ff6f

**Comment by baptisteArno** [comment]
Does this constantly happen on your instance? I can't reproduce on Typebot (https://app.typebot.io)

Any chance I can have access to your instance (you can share the URL to support@typebot.io)

**Comment by KazeroG** [comment]
First time happening for me, I'm using it since several months

invitation sent to the Railway.app project check your email :) [support@typebot.io](mailto:support@typebot.io)

**Comment by baptisteArno** [comment]
I meant access to your Typebot builder URL 🙏

**Comment by KazeroG** [comment]
@baptisteArno email sent :) from support@allowebs.com
