### ISSUE TITLE
Error inside workspaces

### ISSUE THREAD

**Issue by shashicpontentwriter** [baptisteArno/typebot.io#1138]
Hi bro, I'm encountering an error when I create a new Typebot inside workspaces. The steps are as follows: I just created a new workspace, and after that, I tried to create a new bot from scratch. This error appears. After some time, it disappears.

![tyoebot error](https://github.com/baptisteArno/typebot.io/assets/123541173/bab6f292-ff65-44bf-948f-9eb684cdb1c2)

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by shashicpontentwriter** [comment]
> Can you provide the server logs? There should be a clear error there.
> 
> If you are self-hosting it with docker. Type this command in your terminal:
> 
> ```shell
> docker-compose logs
> ```
> 
> Paste all the logs here so that we can help you properly!

Working now, and log shows nothing. I will monitor this. Thanks bro.
