### ISSUE TITLE
Error while running locally : 'sleep' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by shubh675** [baptisteArno/typebot.io#1139]
steps to reproduce:
run pnpm i 
run pnpm dev 
operating system Windows 11 
node version 20.9.0

PS C:\Users\shubh\OneDrive\Desktop\OpenSource\type-bot\typebot.io> pnpm i
Scope: all 30 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 384ms
Done in 3.9s
PS C:\Users\shubh\OneDrive\Desktop\OpenSource\type-bot\typebot.io> pnpm dev

> typebot-os@2.21.3 dev C:\Users\shubh\OneDrive\Desktop\OpenSource\type-bot\typebot.io
> pnpm docker:up && turbo build --filter=@typebot.io/nextjs... && turbo run dev --filter=builder... --filter=viewer... --parallel --no-cache

> typebot-os@2.21.3 docker:up C:\Users\shubh\OneDrive\Desktop\OpenSource\type-bot\typebot.io
> docker compose -f docker-compose.dev.yml up -d && sleep 5

[+] Building 0.0s (0/0)                                                                                                                             docker:default
[+] Running 3/3
 ✔ Container typebotio-minio-1          Running                                                                                                               0.0s 
 ✔ Container typebotio-typebot-db-1     Running                                                                                                               0.0s 
 ✔ Container typebotio-createbuckets-1  Started
                                                                                                                0.0s 
'sleep' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
 
 Getting this error while running locally 'sleep' is not recognized as an internal or external command,

**Comment by baptisteArno** [comment]
Thanks for the report :)

It should work after pulling the changes from main
