### ISSUE TITLE
GOOGLE SHEETS DON'T WORKING 

### ISSUE THREAD

**Issue by williamzzz1** [baptisteArno/typebot.io#1140]
After updating to the latest version, the integration with Google sheets is not working.

![Imagem do WhatsApp de 2024-01-07 à(s) 12 09 16_023a5bef](https://github.com/baptisteArno/typebot.io/assets/52936830/7a3155b2-8fd5-4b15-a222-9d87cbee8d0c)

![image](https://github.com/baptisteArno/typebot.io/assets/52936830/4e9af092-c42a-4f9a-b2e8-6eca91f1f843)

**Comment by abdullahbaa5** [comment]
> [v2.21.0](https://github.com/baptisteArno/typebot.io/releases/tag/v2.21.0)
Breaking changes
The Google Sheets block config was updated and its configuration changed.

>The Google Picker API needs to be enabled in the Google Cloud console. You also need to enable it in your NEXT_PUBLIC_GOOGLE_API_KEY.
Add the drive.file OAuth scope.
For more info, see the new requirements: https://docs.typebot.io/self-hosting/configuration#google-auth-sheets-fonts
