### ISSUE TITLE
Webhook triggered as the flow starts

### ISSUE THREAD

**Issue by pedrofnts** [baptisteArno/typebot.io#1144]
I'm using Typebot integrated with Evolution API. After bot starts, I have a text bubble that says "Hello", and next there's a webhook that makes a POST call. Basically, it sends a lists on WhatsApp. The problem is that the webhook is being triggered BEFORE the "Hello" is sent. 

You can see that's not a problem with the integration, because it happens even in web interface (note in the screenshot that webhook is called even before the remoteJid (necessary on the request) is set (resulting in an error).

I've tried many approaches, like putting a wait, redirecting to group, but the problem remains with all of them.

I've tried it with:

- another bot
- another installation
- other versions (latest, 2, main, etc)
- other webhook requests

In all cases, the problem remains.

Any way of adjusting this?

![Captura de Tela 2024-01-10 às 17 42 39](https://github.com/baptisteArno/typebot.io/assets/63073772/a7bd5d1e-e846-4d27-bdee-fa3a1b08253c)

**Comment by pedrofnts** [comment]
This is also happening on Typebot.io (cloud version). Notice how the webhook gets triggered just after the webhook starts, before the messages are sent and also before the wait block. This does not to seems a bug. Any way to adjust this behavior? @baptisteArno 

![Captura de Tela 2024-01-10 às 18 47 57](https://github.com/baptisteArno/typebot.io/assets/63073772/0bbbedba-2d8c-4629-aa0b-eb6eb4d04c5a)

**Comment by vforvilela** [comment]
"Under the hood, typebot always compute all the blocks between each input blocks."
Source: [https://docs.typebot.io/editor/blocks/logic/wait](https://docs.typebot.io/editor/blocks/logic/wait)

So the solution is to include a wait block with zero seconds and "pause the flow" enabled before the webhook call.

**Comment by pedrofnts** [comment]
If I enable "pause the flow", client needs to send a message before the flow continues. I need messages to be sent in a queue, without user interaction.

**Comment by vforvilela** [comment]
Have you tried?

![image](https://github.com/baptisteArno/typebot.io/assets/80433106/a4a5e67b-9c84-434e-9508-a4e9b8859bf1)

![image](https://github.com/baptisteArno/typebot.io/assets/80433106/72e9760c-dafd-41a7-baa0-3618543c5555)

**Comment by pedrofnts** [comment]
Yeah, unfortunately it only works on web. Through API the bot restarts.

![Captura de Tela 2024-01-10 às 23 45 42](https://github.com/baptisteArno/typebot.io/assets/63073772/d93ca6f0-81cc-43e5-8cc9-1df5e5ee4245)

<img width="1095" alt="Captura de Tela 2024-01-10 às 23 44 55" src="https://github.com/baptisteArno/typebot.io/assets/63073772/6a983b5b-69e4-4bc7-9fd9-2dfe96b04a74">

**Comment by baptisteArno** [comment]
Indeed that is a current limitation in WhatsApp. This is an issue because your webhook takes a long time to respond?

**Comment by pedrofnts** [comment]
Nope, it's an issue because I have the need to send documents to clients. These documents are personal and exclusive, so they are sent through an webhook that sends a doc through my WhatsApp API. I need to create a flow like:

[message] Here's your report.
[webhook] send file
[message] Here's your assessment.
[webhook] send file

With the actual scenario, when bot starts, and files are sent immediately, and messages are sent later. This breaks the entire flow.

**Comment by baptisteArno** [comment]
So the webhooks send WhatsApp messages? 🤔

**Comment by pedrofnts** [comment]
Yes! We need the webhook to send pdfs.

**Comment by baptisteArno** [comment]
Ok then I guess you could make it work directly on Typebot. Typebot should be able to send documents as text bubbles.

I'll work on that soon, then you won't need to use the webhook blocks.

Can you provide the PDF URLs you intend to use?

**Comment by MarksEliel** [comment]
I have the same problem here, the webhook is always sent before any other item even if different groups.

**Comment by uelintonpessoa** [comment]
@baptisteArno 

n fact, any API is triggered first.

We need the API to be triggered according to the construction of the flow, regardless of what the API is.

Example Flow:

>>Message sent<<
>>API triggered<<
>>Message sent<<
>>Message sent<<
>>Message sent<<
And finished with API being activated last
>>Final API Triggered<<

This is the big question we face!

**Comment by baptisteArno** [comment]
> I have the same problem here, the webhook is always sent before any other item even if different groups.

How do you see that? Can you record a video to show us?

I struggle to understand exactly why you need that.

**Comment by cbalbinos** [comment]
Hi @baptisteArno 


Webhooks are executed at the moment the flow is started, regardless of the position the block is in the flow

I have a use case where text and audio messages are sent with a wait between them and two webhooks that trigger workflows on the n8n, which should return personalized image links with information about the time the Workflow was started, after waits of 20 and 7 minutes , but as both are triggered when the flow starts, the images are generated at the same time

I even tried using n8n's wait, but it doesn't work because Typebot's webhook has a timeout of up to 120 seconds

I'm using Typebot self hosted with version selfhost 2.22.0

**Comment by baptisteArno** [comment]
Does that somehow help clarify things?

https://docs.typebot.io/editor/blocks/integrations/webhook#webhook-is-not-executed-in-the-right-order

**Comment by cbalbinos** [comment]
This works in the browser, but unfortunately it doesn't work on WhatsApp

**Comment by baptisteArno** [comment]
Indeed! It won't work in WhatsApp. That's a limitation of the Typebot engine 🙏

**Comment by flavioxx** [comment]
I also have the same problem, I use the WhatsApp API for integration and the webhook is always executed first unfortunately.

**Comment by baptisteArno** [comment]
> > Ok then I guess you could make it work directly on Typebot. Typebot should be able to send documents as text bubbles.
> > I'll work on that soon, then you won't need to use the webhook blocks.
> > Can you provide the PDF URLs you intend to use?
> 
> @baptisteArno any news on something like this?

Can you open a new issue and provide PDF urls as example?

**Comment by lhonay** [comment]
Did anyone manage to solve it?

**Comment by demesiooliveira** [comment]
Did anyone manage to solve it?

**Comment by lhonay** [comment]
yes, in my case it was the API
