### ISSUE TITLE
customChatsLimit is not showed to the end user anymore

### ISSUE THREAD

**Issue by SobPat** [baptisteArno/typebot.io#1147]
**Issue Summary:**

In the Workspace collection, there are attributes related to the plans of each workspace. We have the option to set a custom plan and select the custom number of conversations available to the user (customChatsLimit). However, after the update to version 2.21.0, the value that was previously displayed to the end user in the billing and usage modal consistently appears as "ilimited".

**Steps to Reproduce:**

Navigate to the Workspace collection.
Set a custom plan with a specific number of conversations.
Observe the displayed value in the billing and usage modal.
Expected Behavior:
The displayed value in the billing and usage modal should reflect the custom plan and the selected number of conversations.

**Actual Behavior:**
The displayed value in the billing and usage modal remains constant as "ilimited" after the update to version 2.21.0.

**Comment by baptisteArno** [comment]
Yep, sorry about that, this is fixed in 5d971f7b6ff60f87a4c01144da420172c43dd24c.

**Comment by baptisteArno** [comment]
You will need to wait for the next release 🙏
