### ISSUE TITLE
minio docker-compose setting

### ISSUE THREAD

**Issue by geniusshiun** [baptisteArno/typebot.io#115]
I follow this [page](https://docs.typebot.io/self-hosting/docker).
Using below config:
services:
  minio:
   ...
  typebot-builder:
    environment:
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=**minio**

And put them in the same docker network.
But I can't upload image, it keep rotating.

Based on this command ` /usr/bin/mc config host add minio http://minio:9000 minio minio123;`
It's able to connect by service name in the same docker network.
Please give me some advice, thank you.

**Comment by baptisteArno** [comment]
Have you followed this config? https://docs.typebot.io/self-hosting/docker#s3-storage

Make sure to include the `createbuckets` service so that it creates the bucket with correct policies on startup.

Also the S3 service **must** be publicly accessible with a public URL

**Comment by baptisteArno** [comment]
I'll close the issue for now, feel free to re-open 👍
