### ISSUE TITLE
Prefilled "channel" variable

### ISSUE THREAD

**Issue by MDXDave** [baptisteArno/typebot.io#1155]
If you want to conditonally control the flow (e.g. make an additional input field if the user is interacting with typebot via WhatsApp), this is currently only possible by defining a prefilled variable in the web and other platforms and check if the variable is not set to assume that the current channel is WhatsApp.

I think it would be helpful to prefill a variable (e.g. _channel_) with the current channel name (WhatsApp, Web, React, Wordpress etc.).

**Comment by baptisteArno** [comment]
<img width="666" alt="CleanShot 2024-01-16 at 15 22 01@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/7d9c2975-c276-40d6-94e7-398a0fdbdb66">

Have you checked the "Env name" value?

**Comment by MDXDave** [comment]
Oh sorry, i've missed that. Works as expected, thank you 😄
