### ISSUE TITLE
Cannot setup Custom OAuth Provider (Auth) - $NEXTAUTH_URL/api/auth/callback/???

### ISSUE THREAD

**Issue by K-J-VV** [baptisteArno/typebot.io#1156]
What is the redirect URL for the custom OAuth provider? Documentation includes for the other examples ($NEXTAUTH_URL/api/auth/callback/facebook ; $NEXTAUTH_URL/api/auth/callback/azure-ad ; etc.) but there is no example for custom OAuth provider

**Comment by K-J-VV** [comment]
Figured it out, URL below. Would recommend adding to documentation and consider instructions for custom oauth providers (Authentik, Keycloak, etc.) as I used other issues on Github to help troubleshoot

$NEXTAUTH_URL/api/auth/callback/custom-oauth

**Comment by baptisteArno** [comment]
Thanks for the report! I'll add this to the docs :)
