### ISSUE TITLE
Fetching User Geolocation 

### ISSUE THREAD

**Issue by cherrycharan** [baptisteArno/typebot.io#1157]
Is there any way I can get the user geo location from the browser by showing the dialog box which asks for the permission, if user allowed I need to get the current lat and long 

Tried the below javascript
https://www.w3schools.com/html/html5_geolocation.asp

When this javascript is being executed it's not prompting the dialog box and showing nothing in the browser console as well.

**Comment by baptisteArno** [comment]
You can do that with a Set variable code:

```
function getPosition(options) {
    return new Promise((resolve, reject) => 
        navigator.geolocation.getCurrentPosition(resolve, reject, options)
    );
}

if (navigator.geolocation) {
  const {coords} = await getPosition()
  return `${coords.latitude} ${coords.longitude}`
}
return 'Geolocation not available'
```

<img width="797" alt="CleanShot 2024-01-17 at 15 43 31@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/1cd1a042-b520-447e-96bc-514cee1a0c57">
