### ISSUE TITLE
Getting "process.env.NEXT_PUBLIC_VIEWER_URL is missing in env" when I try to preview any bot.

### ISSUE THREAD

**Issue by IzMichael** [baptisteArno/typebot.io#116]
Hiya, I'm self-hosting with vercel, and whenever I attempt to preview a bot (creating from a template, previewing before publishing, etc.), it just displays text saying "process.env.NEXT_PUBLIC_VIEWER_URL is missing in env". I'm not sure what can be done for my to rectify this. I've checked my vercel settings and the environment variable is set correctly. I've tried re-deploying, committing to trigger a new deployment, and nothing.
![image](https://user-images.githubusercontent.com/57115702/182827032-b651c221-4c3e-49e6-a5e0-b279e58b522b.png)

**Comment by baptisteArno** [comment]
Hey, thank you for filling an issue. Indeed, I forgot to update the Vercel build command lately, it has changed!

The doc has been updated: https://docs.typebot.io/self-hosting/vercel

**Comment by IzMichael** [comment]
Ah, ty!
