### ISSUE TITLE
Typebot on Oracle Cloud Free (ARM)

### ISSUE THREAD

**Issue by thepibrei** [baptisteArno/typebot.io#1160]
I started installing typebot on an Oracle Cloud Free VPS. (Ubuntu 22.04, ARM). After completing the installation, I cannot access typebot, I have already opened ports 3001 and 3002 and the notes were made by cloudflare normally. Any suggestions on how to resolve it? Or for some reason typebot doesn't work on ARM servers?

**Comment by baptisteArno** [comment]
What deployment guide did you follow?

Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by thepibrei** [comment]
> What deployment guide did you follow?
> 
> Can you provide the server logs? There should be a clear error there.
> 
> If you are self-hosting it with docker. Type this command in your terminal:
> 
> ```shell
> docker-compose logs
> ```
> 
> Paste all the logs here so that we can help you properly!

Thanks for your attention, friend! I decided to use EasyPanel, and now I have problems with the viewer, I had posted the screenshots on discord, but I will repost them here again.
![image](https://github.com/baptisteArno/typebot.io/assets/113221084/7983c08b-9522-4c49-8795-fb829357431f)
![image](https://github.com/baptisteArno/typebot.io/assets/113221084/0311569e-da89-4b20-a99c-a71595357a7c)

**Comment by thepibrei** [comment]
Solved!
Only add the line on the Environment of the Viewer:
NEXTAUTH_URL=https://xxx.yourdomain.com/
