### ISSUE TITLE
Is ther a way to use OpenAI Chat completion tools (function calling)

### ISSUE THREAD

**Issue by drauber** [baptisteArno/typebot.io#1161]
Is ther a way to use OpenAI integration with this [OpenAI Doc - Tools](https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools)?

This feature helps to use obtained info in chat completion with complex prompts, after all keys of body is filled, i want to call external webhook with all parameters, filled by OpenAI.

Thanks a lot.

**Comment by baptisteArno** [comment]
Soon possible #1162
