### ISSUE TITLE
Problem executing the flow with Cal.com

### ISSUE THREAD

**Issue by cbalbinos** [baptisteArno/typebot.io#1164]
I have a flow where I use the Cal.com block using Version: 2.21.3, in the builder it shows the blocks in the reservation sequence, but in the browser, I used Chrome and Firefox, the blocks in the sequence after the reservation in Cal. com are not displayed

![bloco_cal_ok](https://github.com/baptisteArno/typebot.io/assets/91399681/d96f7c55-6cc7-4190-866a-154fcf4d7319)

![bloco_cal_navegador](https://github.com/baptisteArno/typebot.io/assets/91399681/24bb51d1-8ad3-4057-9997-d7c934514e3c)

**Comment by cbalbinos** [comment]
Tested on self-hosted Typebot and SaaS

**Comment by baptisteArno** [comment]
It's an issue when the chatbox is too small it seems. We can't really fix that unfortunately as it's up to Cal.com to properly handle small screen sizes 🤔

For for the phone to appear, make sure to add a Phone as a location of your event in Cal.com

**Comment by baptisteArno** [comment]
Then your screenshot are not clear then!

You're saying it only works in the Preview?

**Comment by cbalbinos** [comment]
yes, only in Preview... using the Typebot link, blocks after Cal.com are not displayed (text bubble) or executed (sheets)

**Comment by baptisteArno** [comment]
Ok I managed to reproduce, thank you!

**Comment by cbalbinos** [comment]
Hi @baptisteArno 

What version will this bug be fixed in?  there is a forecast for updating the image on docker hub

**Comment by fabianob1m** [comment]
The same thing happened here. Waiting for this adjustment because this flow was sensational.

**Comment by baptisteArno** [comment]
1st of February!

**Comment by cbalbinos** [comment]
I updated my self-hosted Typebot to version 2.22.0, on my cell phone the Cal.com block and the ones that follow are working perfectly, but on the computer's browser (Chrome and Firefox) in full screen I can't see the modal that appears after select the time chosen on Cal.com, as shown in the video


https://github.com/baptisteArno/typebot.io/assets/91399681/5882d5db-19a7-4def-a864-d3079ee8cc5c
