### ISSUE TITLE
Issue when saving the webhook response in the variables created in the flow.

### ISSUE THREAD

**Issue by Telmosilva79** [baptisteArno/typebot.io#1166]
I am called Vinicius, and I am a monitor in Jeff's community.

I am facing this problem, and I don't know how else to try to resolve it. I made the API request and received a positive response (200), but when it comes to saving in the variables, they remain empty:

![01](https://github.com/baptisteArno/typebot.io/assets/145811430/b845cb27-d1d3-46a7-9c13-bdba16f899f9)
![02](https://github.com/baptisteArno/typebot.io/assets/145811430/8fae1701-136d-4eea-8f8a-7cdfe9be3051)
![03](https://github.com/baptisteArno/typebot.io/assets/145811430/bcc768c9-2e07-446b-9c9d-ebcf4db9805e)

I even set it to print, but nothing appears.

**Comment by baptisteArno** [comment]
Hmmm that should definitely work though. Can you provide a way for me to reproduce the issue?

**Comment by viniciuslemmos** [comment]
@baptisteArno Hi, I didn't realize I asked the question from another account, but let's proceed to the issue.

Can I add you as a member to my Typebot so you can check? Just send me your email, please.

**Comment by baptisteArno** [comment]
baptiste@typebot.io
