### ISSUE TITLE
Typeboot connected to the WhatsApp api is only starting from the second message.

### ISSUE THREAD

**Issue by Jorgeaceiro** [baptisteArno/typebot.io#1168]
It only starts from the second message, I wanted my bot to be more dynamic and I configured it to respond by identifying key words from the initial conversation but it does not identify the first message, only the second which makes it not work correctly.

I am using the latest version.

Flow
![Captura de tela 2024-01-19 071313](https://github.com/baptisteArno/typebot.io/assets/126033323/cf065dbc-d6ab-44ca-a70e-83e3aa35afd9)

Start
![Captura de tela 2024-01-19 071436](https://github.com/baptisteArno/typebot.io/assets/126033323/e8a3defe-6408-4525-aa36-b43462e61559)

Result 
![Captura de tela 2024-01-19 071456](https://github.com/baptisteArno/typebot.io/assets/126033323/04b5dcc5-c0ba-4ce1-a06a-439899d0132e)

**Comment by baptisteArno** [comment]
That should work in theory. What's your Typebot version? You can find it in the Settings & Members modal

**Comment by Jorgeaceiro** [comment]
My version is the 2.21.3

**Comment by patrickluizdev** [comment]
I also had the same observation

**Comment by baptisteArno** [comment]
Thank you guys, it was indeed a regression. 🙏

**Comment by Jorgeaceiro** [comment]
I updated to version 2.20 and the error continues

**Comment by baptisteArno** [comment]
We are on 2.22.0 now 🙏

**Comment by Jorgeaceiro** [comment]
Sorry, I typed it wrong, I'm on version 2.22.0. I even tested it on the official Typebot website and it didn't work.

**Comment by Jorgeaceiro** [comment]
Até no URL oficial somente funciona a partir da mensagem 2
![IMG-20240205-WA0008](https://github.com/baptisteArno/typebot.io/assets/126033323/8a9d444e-f080-4730-8fde-c7f2f926e359)
](url)

**Comment by Jorgeaceiro** [comment]
in version 2.22.1 it is also not working

**Comment by Jorgeaceiro** [comment]
hi friend, in version 2.22.2 not working to

**Comment by Jorgeaceiro** [comment]
Thank you very much for responding friend, congratulations on your work. I'm using whaticket pro version 2.2, I connect typebot via the share link and not via the token

**Comment by vforvilela** [comment]
It works for text messages but persists in the case of file uploads.

**Comment by baptisteArno** [comment]
Can you open an issue for that? @vforvilela 🙏
