### ISSUE TITLE
Module not found: Can't resolve 'utils'

### ISSUE THREAD

**Issue by razsa** [baptisteArno/typebot.io#117]
Steps I took: Copy apps/builder/.env.local.example to apps/builder/.env.local and Copy apps/viewer/.env.local.example to apps/viewer/.env.local then I `yarn dev` to start the builder/viewer.

```
./layouts/ErrorPage.tsx:2:0

  1 | import React from 'react'
> 2 | import { env, isEmpty } from 'utils'
  3 | 
  4 | export const ErrorPage = ({ error }: { error: Error }) => {
  5 |   return (

Import trace for requested module:
./layouts/TypebotPage.tsx
./pages/[[...publicId]].tsx
```

**Comment by baptisteArno** [comment]
Thank you for the bug report! 🙏

Typebot is now using `pnpm` and has upgraded its `dev` script. Check the [new instructions](https://github.com/baptisteArno/typebot.io#local-setup)!
