### ISSUE TITLE
Error! Could not reach server. Check your connection

### ISSUE THREAD

**Issue by essam-tobgi** [baptisteArno/typebot.io#1182]
I've created a GitHub codespace and built TybeBot. Internally when I try to test a bot or navigate to themes or settings.

I receive the following error messages.

![image](https://github.com/baptisteArno/typebot.io/assets/154793315/2b510dd8-a59f-4e99-8aa0-d7e651020d63)

![image](https://github.com/baptisteArno/typebot.io/assets/154793315/036c4fcd-bd90-4e20-b7c9-4c5903346780)

**Comment by essam-tobgi** [comment]
UPDATE! 
The State cookie problem was fixed and this is the new intern al server message.

![image](https://github.com/baptisteArno/typebot.io/assets/154793315/2a2a44f4-0fff-4bbc-b4fe-aea233cdef01)

**Comment by melsonic** [comment]
hey @ezhil56x let me work on this one you can grab #1193

**Comment by ezhil56x** [comment]
@melsonic I have started working on this 🥲 . Can you grab #1193?

**Comment by melsonic** [comment]
> @melsonic I have started working on this 🥲 . Can you grab #1193?
I have also started.

**Comment by ezhil56x** [comment]
@essam-tobgi
Can you share more on how to reproduce this issue? so that it'll be easy to troubleshoot

**Comment by essam-tobgi** [comment]
> @essam-tobgi Can you share more on how to reproduce this issue? so that it'll be easy to troubleshoot

- I've done all the steps for local installation. Provided the environmental variables necessary to authenticate using Azure. And I'm using supabase free online database. 
- When I provided the database link at first the generate command didn't work as the connection string started with "postgres" not "postgresql", this confused me at first as both should be working fine, but I generated the tables myself from the schema.prisma file found in /packages/prisma/postgresql/ directory.

**Comment by baptisteArno** [comment]
https://github.com/baptisteArno/typebot.io/issues/432

There are no bounties on that issue. There is an issue with Algora, the bounty auto created itself.

**Comment by ezhil56x** [comment]
@baptisteArno Is the project ready for codespace or yet to be implemented?

**Comment by baptisteArno** [comment]
#432 is opened so it's not validated wether or not Typebot can be run on a Github workspace

**Comment by jerossinilp** [comment]
Alguém tem alguma solução para este erro? O typebot funciona so não consigo publicar o script.

**Comment by Albatroxi** [comment]
3002 Port open
Só abrir a porta 3002.

**Comment by Albatroxi** [comment]
Open port 3002
Só abrir a porta 3002.
