### ISSUE TITLE
How to create a new custom component layout using The Forge

### ISSUE THREAD

**Issue by lucastorress** [baptisteArno/typebot.io#1188]
Hey, everyone!

I'm new to the project, I've already read the documentation a lot and discovered The Forge.

In particular, I need to create a customized component within the chat flow to display a layout like the one in the image below.

![image](https://github.com/baptisteArno/typebot.io/assets/11927792/c6c428c0-11a9-4f9a-9f2f-92af202c7ab4)

Using The Forge, is this possible? Or will I have to change the standard components of the builder application.

I'm a little confused and to avoid further rework, I would like your help.

Thanks. :)

**Comment by laertlucas** [comment]
Good idea, I need something very similar and I even thought about replicating one of the existing components and changing its functions and layout...

**Comment by baptisteArno** [comment]
This is not possible using the Forge. You can't create inputs with it!

You'd have indeed to create an input block without the Forge 👍
