### ISSUE TITLE
How can I listen to events from Iframe?

### ISSUE THREAD

**Issue by cherrycharan** [baptisteArno/typebot.io#1189]
I have a usecase where i show for maps and users would interact with it and these would be generating events . Within typebot how can I listen to those events and run the flow ? 

I have an existing webpage which handles the map showing and creating events and it's built using react and can customise it as well . 

Suggest the best approach to implement this.

For context in the typebot flow user would draw polygon on the map within Iframe and post that I need to run further conversation

**Comment by baptisteArno** [comment]
There is no way to do that indeed. I don't think it would be technically possible to set this up.

Or you'd have to create your own block like cal.com
