### ISSUE TITLE
How to access Typebot variables programmatically with Javascript?

### ISSUE THREAD

**Issue by marciovalim** [baptisteArno/typebot.io#1199]
I'm a Saas owner and I'm building a Typebot integration for my users and because of that I need to write a script that can be embedded in Typebot head code to integrate properly with my use case.

In that script I need to access url query parameters and also typebot variables.

Is that possible?

**Comment by baptisteArno** [comment]
Yes, sure!

https://docs.typebot.io/editor/blocks/logic/script

Let us know if you have any precise issue
