### ISSUE TITLE
Vercel Error when trying to load typebot via url

### ISSUE THREAD

**Issue by cvrlnolan** [baptisteArno/typebot.io#12]
<img width="847" alt="Screen Shot 2022-04-02 at 12 12 22 PM" src="https://user-images.githubusercontent.com/42778495/161380578-a3c77220-b916-41f1-9954-b1c340d31e5d.png">

**Comment by cvrlnolan** [comment]
Sorry, got a fix for this .. add `viewer` subdomain to your typebot url. Ex: `https://viewer.typebot.io/...`

**Comment by baptisteArno** [comment]
This was a temporary issue, it should be fixed even when using the `https://typebot...` URL :)

**Comment by cvrlnolan** [comment]
> This was a temporary issue, it should be fixed even when using the `https://typebot...` URL :)

Awesome ! Bien joué pour ce projet d'ailleurs .. Il est génial !  @baptisteArno
