### ISSUE TITLE
Turbo error: failed to parse turbo json

### ISSUE THREAD

**Issue by TZbooo** [baptisteArno/typebot.io#1201]
Hello. I cannot execute the command docker-compose -f docker-compose.build.yml up --build

Procedure:
1. cloned your repository
2. Created an .env with the required variables
3. Started running the command docker-compose -f docker-compose.build.yml up --build

An error occurred on line 17 of the Dockerfile
RUN turbo prune --scope=${SCOPE} --docker

=> ERROR [pruner 4/4] RUN turbo prune --scope=builder --docker 2.0s
------                                                                                                                                                                                                 
 > [pruner 4/4] RUN turbo prune --scope=builder --docker:                                                                                                                                              
0.541                                                                                                                                                                                                  
0.541 Warning:                                                                                                                                                                                       
0.541 Turborepo now collects completely anonymous usage telemetry.
0.541 This information is used to build the Turborepo roadmap and prioritize features.
0.541 You can learn more, including how to opt out of this anonymous program, by visiting the following URL:
0.541 https://turbo.build/repo/docs/telemetry
0.541 
0.885 Generate trimmed monorepo for builder in /app/out
0.910 - Added @typebot.io/bot-engine
0.914 - Added @typebot.io/cal-com-block
0.916 - Added @typebot.io/chat-node-block
0.918 - Added @typebot.io/dify-ai-block
0.923 - Added @typebot.io/emails
0.924 - Added @typebot.io/env
0.926 - Added @typebot.io/forge
0.927 - Added @typebot.io/forge-repository
0.928 - Added @typebot.io/forge-schemas
0.964 - Added @typebot.io/js
0.983 - Added @typebot.io/lib
0.983 - Added @typebot.io/mistral-block
0.983 - Added @typebot.io/nextjs
0.985 - Added @typebot.io/openai-block
1.006 - Added @typebot.io/prisma
1.008 - Added @typebot.io/qrcode-block
1.010 - Added @typebot.io/radar
1.014 - Added @typebot.io/react
1.057 - Added @typebot.io/schemas
1.058 - Added @typebot.io/tsconfig
1.062 - Added @typebot.io/variables
1.064 - Added @typebot.io/zemantic-ai-block
1.579 - Added builder
1.580 - Added eslint-config-custom
1.682 Turbo error: failed to parse turbo json
------
Dockerfile:17
--------------------
  15 | WORKDIR /app
  16 | COPY .
  17 | >>> RUN turbo prune --scope=${SCOPE} --docker
  18 |     
  19 | FROM base AS builder
--------------------
ERROR: Failed to resolve: process "/bin/sh -c turbo prune --scope=${SCOPE} --docker" failed to complete successfully: exit code: 1.
ERROR: The 'typebot-builder' service failed to build : Build failed

docker-compose version 1.29.2, build unknown
Client: Docker Engine - Community
 Version: 24.0.6
 API version: 1.43
 Go version: go1.20.7
 Git commit: ed223bc
 Built:             Mon Sep 4 12:31:44 2023
 OS/Arch: linux/amd64
 Context: default

Server: Docker Engine - Community
 Engine:
  Version: 24.0.6
  API version: 1.43 (minimum version 1.12)
  Go version: go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep 4 12:31:44 2023
  OS/Arch: linux/amd64
  Experimental: false
 containerd:
  Version: 1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version: 1.1.9
  GitCommit: v1.1.9-0-gccaecfc
 docker-init:
  Version: 0.19.0
  GitCommit: de40ad0

# Help please

**Comment by TZbooo** [comment]
Apparently it's a bug in the new version of turbo.
I changed the turbo version
RUN npm --global install turbo@1.11.3

Now everything works.

**Comment by baptisteArno** [comment]
Good to know, thank you!
