### ISSUE TITLE
Copy and Paste Blocks between Typebots

### ISSUE THREAD

**Issue by stgcompany** [baptisteArno/typebot.io#1208]
I loved the new update on select multiple blocks & copy and paste blocks. But I'd really like to be able to copy and paste blocks between different typebots, especially when we have multiple tabs on our browser.

**Comment by Trystan4861** [comment]
I'll explain this issue a little bit more specifically, the problem is to copy between different tabs, you can copy blocks from a typebot's flow, go back, open another typebot's flow and paste without problems, but copy from a navigator's tab to another tab... there is the problem.

**Comment by baptisteArno** [comment]
That is indeed not working if you switch tab. That is technically not possible to implement that. 🙏

I really suggest that you use Typebot on a single tab!

**Comment by stgcompany** [comment]
I already used a couple of web apps that supports this functionality.

**Comment by baptisteArno** [comment]
Maybe possible when this is implemented: #680
