### ISSUE TITLE
Feature: Horizontal Scrolling holding Alt

### ISSUE THREAD

**Issue by stgcompany** [baptisteArno/typebot.io#1214]
I'd love to be able to scroll on the x axis (horizontal) by holding some key as alt or shift.

**Comment by baptisteArno** [comment]
You should be able to do that with the shift key

**Comment by stgcompany** [comment]
I tried holding shift, alt, fn and alt gr... None of them worked.

**Comment by baptisteArno** [comment]
What's your instance version?

**Comment by stgcompany** [comment]
I tried not only on my self-hosted version but on Typebot cloud as well, my friend also verified that it doesn't work as well.

**Comment by baptisteArno** [comment]
Are you sure you enabled the Mouse navigation in the User preferences?

**Comment by stgcompany** [comment]
Yes, I've tested on both Mouse and Trackpad options.
