### ISSUE TITLE
File Upload block broke

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#1216]
It is uploaded but keeps saying this.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/e92439f9-2183-4b64-bfcd-f6f5f73263ec)
Nothing in logs but uploading images for metadata and using the UPLOAD button works just fine.

Im using MINIO

**Comment by baptisteArno** [comment]
Indeed, it was fixed with a recent commit. Make sure to upgrade to 2.22.1 🙏
