### ISSUE TITLE
Can't make events work with GA4

### ISSUE THREAD

**Issue by lpadula** [baptisteArno/typebot.io#122]
Hi!

I'm trying to send GA4 events on some flow steps:

![image](https://user-images.githubusercontent.com/1341504/186256485-dd2e6d8f-dd35-4260-863a-c03d885bd77e.png)

But the events never reach the GA account... Am I doing something wrong?

**Comment by baptisteArno** [comment]
It should work in the Preview tab.

Are you sure you are checking the Real-time page from Google Analytics?

Does it logs a "Visit" at least?

**Comment by baptisteArno** [comment]
Closing this for now as it needs more info. Feel free to reopen!
