### ISSUE TITLE
Outlook Email Magic Link

### ISSUE THREAD

**Issue by bbrooks205** [baptisteArno/typebot.io#1221]
Hello,

We are having issues with the Magic Link. When we use an account that is based in our outlook the magic link does not work. We have an advanced level of outlook for security. The link looks like this under the button:

https://nam12.safelinks.protection.outlook.com/?url=(magicURL)

When we use another account that is Gmail-based it works perfectly.

**Comment by baptisteArno** [comment]
So it sounds like Outlook is opening the link first so it invalidates it. Is there any chance you can disable that behavior on Outlook for the sign in links?

**Comment by baptisteArno** [comment]
Feel free to re-open
