### ISSUE TITLE
After new release file block still broken

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#1222]
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/aa133965-8261-418a-b5ae-16cbd34094e8)

I am still getting this after updating cloudron to the new release

**Comment by baptisteArno** [comment]
How can we be sure that Cloudron is using the latest image?

**Comment by CptPlastic** [comment]
This is true it says this.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/fa821bc6-2a81-4cf6-972e-a1acf2f19701)

**Comment by CptPlastic** [comment]
locally the fake URL populates. 
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/ae2fb930-42f6-43fb-b99f-1258d91c37a0)

**Comment by baptisteArno** [comment]
Is your storage URLs starts with `http://` or `https://`?

**Comment by CptPlastic** [comment]
> Is your storage URLs starts with `http://` or `https://`?
https

https://minio-api.app.p7n.net/nsn/public/tmp/qrcodes/rp3upx1awd195g43ebnmiti1ylcmgpenhzd150b80hf6tj1f.png

**Comment by baptisteArno** [comment]
I'm sorry I struggle to understand what's going on. Can you record a video that shows the issue?

**Comment by CptPlastic** [comment]
https://github.com/baptisteArno/typebot.io/assets/1010444/3af12c43-d488-4450-9820-258edc2a0ded

**Comment by CptPlastic** [comment]
https://nsncorp.app.nsnmindlabs.com/new-stuff-28l1d3a

Here is a link you can try it. The files are uploaded to MINIO but the block is saying invalid message.
