### ISSUE TITLE
New Input Block to accept any data type as an answer

### ISSUE THREAD

**Issue by stgcompany** [baptisteArno/typebot.io#1223]
I'd like to be able to collect the users answer input as any data type and then after that I'd use an script block to handle the data type of the answer.

I say this as I'd like to be able to accept not only text answers, but audio or video at any moment of the conversation, and after that I'd use an external API to make a speech-to-text transformation to store the text answer from the audio. Specially for my use case which I'm using an Whatsapp API that most people from my location tend to send messages using audios, and some times even videos.

**Comment by baptisteArno** [comment]
Duplicate https://github.com/baptisteArno/typebot.io/issues/854
