### ISSUE TITLE
SMTP login option doesn't work.

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#123]
I setup an SMTP config in my self hosted typebot machine. When I try to login using an email, I get the notification from typebot that I should check my inbox for an email. Though, no email is being sent nor received.

I checked through the logs of my SMTP server and the email wasn't sent. (The issue does come from typebot as my smtp server works with other applications.)

I followed the documentation to configure the SMTP options, but still it doesn't work.

**Comment by baptisteArno** [comment]
Thank you for creating this issue 😀

Have you checked the logs of typebot once the email is sent? `docker-compose logs typebot-builder`

What SMTP port have you configured?

**Comment by baptisteArno** [comment]
I just released a new version that don't use `SMTP_IGNORE_TLS` any more: https://github.com/baptisteArno/typebot.io/releases/tag/v2.7.0

Can you try it out?

**Comment by Lanhild** [comment]
I configured the port 25 as I hadn't setup an SSL certificate on my machine yet.

**Comment by Lanhild** [comment]
> Can you try it out?

I will try that ASAP

**Comment by baptisteArno** [comment]
I hope it worked out in the end! 😃
I'll close this, feel free to re-open if you still have this issue!
