### ISSUE TITLE
Flow data lost after on autosave

### ISSUE THREAD

**Issue by willph** [baptisteArno/typebot.io#1231]
I would like to inform you that when the autosave appears, all modifications made while it is at that moment are lost. Thus returning to the state when the autosave appeared.

Example:

I added a flow and I was typing text when the autosave appeared, while it was running, I added another text flow.
When the autosave ends, this second flow disappears.

I'll try to record a video demonstrating this. 
If I make it will post it here

I am currently using version 2.22.2

Using in Docker

**Comment by baptisteArno** [comment]
Indeed I had this bug several times! I think I found a way to fix that.
