### ISSUE TITLE
"Sign ups are disabled" Error when logging in or registering via Email

### ISSUE THREAD

**Issue by YousufRasheed** [baptisteArno/typebot.io#1235]
"Sign ups are disabled" Error when logging in or registering via Email. I have setup login with Github and it works fine.

- I have self hosted using the NGINX and PM2.
- I have UFW firewall disabled.
- I have made sure that the credentials and details for SMTP are correct.

**This is my .env file:**
![image](https://github.com/baptisteArno/typebot.io/assets/64773849/63b65510-93ec-4298-992d-99efc6fcc39a)

**This is the error I get:**
![image](https://github.com/baptisteArno/typebot.io/assets/64773849/20e0c72c-3b73-4807-bcc8-77e3265339e9)

**PM2 Error Log**
![image](https://github.com/baptisteArno/typebot.io/assets/64773849/bed21e7f-537d-445e-a522-4f209170d2c4)

**Comment by YousufRasheed** [comment]
The SMTP server is hosted on another server and I have no firewall disabling any ports of my current server.

The credentials are all good as I have checked those on other platforms.

Can you please specify what else do you mean by _"make sure your VPS can send emails"_.

Thank you.

**Comment by baptisteArno** [comment]
I don't know what else to suggest, it's not an issue related to Typebot. The error you are showing is from Nodemailer.

Maybe try another smtp provider? 🙏
