### ISSUE TITLE
CSS and JavaScript in Bubble

### ISSUE THREAD

**Issue by souzadeveloper** [baptisteArno/typebot.io#1239]
Good afternoon, I would like to know why the CSS and JavaScript defined in "Custom head code" do not work when we run the flow in a Bubble. It appears that all CSS and JavaScript are ignored. Thanks.

**Comment by baptisteArno** [comment]
That should not happen 🤔

Can you provide an example of what's not working? So that I reproduce the issue

**Comment by baptisteArno** [comment]
Feel free to re-open if you have a reproduction
