### ISSUE TITLE
prisma db:migrate not working with Vercel

### ISSUE THREAD

**Issue by sebiweise** [baptisteArno/typebot.io#1259]
When I try to host Typebot on Vercel I´m getting a strange error:
`@typebot.io/prisma:db:generate: PostgreSQL `DATABASE_URL` should start with postgresql://`

I think the prisma command `dotenv -e ./.env -e ../../.env -- tsx scripts/db-generate.ts` won´t use the Vercel environment vars, any ideas how to fix this?

**Comment by sebiweise** [comment]
postgres://default:<PASSWORD>@<HOST>/verceldb?sslmode=require
It is populated directly by the linked Vercel postgres db

**Comment by sebiweise** [comment]
Thats the error I´m getting
<img width="601" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/22999200/b42f1bd9-c7d5-4d3e-8161-e84aa8a8b7c9">

**Comment by baptisteArno** [comment]
Ok, I'm on it

**Comment by sebiweise** [comment]
I´m still getting a error, now just with the new error message.
```
@typebot.io/prisma:db:generate: Invalid `DATABASE_URL` format, it should start with `postgresql://` or `postgres://`
````

**Comment by baptisteArno** [comment]
Sorry I pushed another fix right away, can you update your branch again?

**Comment by sebiweise** [comment]
Worked nice thanks.
