### ISSUE TITLE
Typebot with Gateway Timeout error

### ISSUE THREAD

**Issue by MarceloFcAraujo** [baptisteArno/typebot.io#1269]
Hi guys, I need help. I was using normally TypeBot and suddenly (yesterday), my Typebot show this message: "**Gateway Timeout**". I can see this message in builder and view. Can someone help me?

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!
