### ISSUE TITLE
 401 error on `api/workspaces`  "message : not authenticated"

### ISSUE THREAD

**Issue by alihassan4198-tech** [baptisteArno/typebot.io#127]
Hi @baptisteArno,
![image](https://user-images.githubusercontent.com/61900292/189474093-af47f93e-ec5a-4476-83a9-c589d90d9bfb.png)

I wanted to deploy typebot on vercel with supabase attched.
I have set all the variables of builder as mentioned in image according to documentation.

But still 401 error on ` api/workspaces ` "message : not authenticated".

Also set the ` NEXTAUTH_URL_INTERNAL ` to ` http://localhost:3000 ` but still not working , so I removed.
As you mentioned in previous issue https://github.com/baptisteArno/typebot.io/issues/120#issuecomment-1219687356

Note : the ` api/workspaces ` is hitting the server as ` GET ` Request but I have searched in typebot's repo this api is implemented as ` PATCH, POST and DELETE ` request seems weird to me.

![image](https://user-images.githubusercontent.com/61900292/189329229-1ae543f0-3c87-4bc8-845b-e7aa5ccf9c68.png)

**Comment by alihassan4198-tech** [comment]
I have solved this with supabase connection pool was By-Default set to "Transaction", I set it to "Session", now solved.

![image](https://user-images.githubusercontent.com/61900292/189479995-bbd8bb7e-5b63-4fe6-b670-32573293f538.png)

**Comment by baptisteArno** [comment]
That's strange, mine is configured to "Transaction" and it works just fine. It would have been great to see what's the error on Vercel logs
