### ISSUE TITLE
MagicLink Emails not sending

### ISSUE THREAD

**Issue by Ahmer-hameed** [baptisteArno/typebot.io#1279]
I have tried to setup SMTP with my webmail SMTP & google SMTP as well,, but the when i tried to add the email on signin page, its just keeps loading and the connection timeout with the error in my log below.

[next-auth][error][SIGNIN_EMAIL_ERROR] 
https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
  error: {
    message: 'Email(s) could not be sent',
    stack: 'Error: Email(s) could not be sent\n' +
      '    at Object.s [as sendVerificationRequest] (/app/apps/builder/.next/server/chunks/524.js:1:3986)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async email (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
      '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
      '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_nodemailer@6.9.3_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async D (/app/apps/builder/.next/server/chunks/524.js:1:7848)\n' +
      '    at async K (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)\n' +
      '    at async U.render (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.22.9_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16981)',
    name: 'Error'
  },
  providerId: 'email',
  message: 'Email(s) could not be sent'

I have the following settings:

DATABASE_URL=postgresql://postgres:botty345x@botty-db:5432/botty
 NEXTAUTH_URL=https://debu.r6.se
 NEXT_PUBLIC_VIEWER_URL=https://debuc.r6.se
 ENCRYPTION_SECRET=pAFqCDerqYJeL2r1s0GX6r6A45bQaCF6
 ADMIN_EMAIL=**
 SMTP_USERNAME=dev@automationer.se
 SMTP_PASSWORD=**
 SMTP_PORT=465
 SMTP_SECURE=true
 SMTP_AUTH_DISABLED=false
 SMTP_HOST=mail.automationer.se
 NEXT_PUBLIC_SMTP_FROM=notifications@debu.r6.se
 S3_ACCESS_KEY=minio
 S3_SECRET_KEY=minio123
 S3_BUCKET=typebot
 S3_ENDPOINT=debus.r6.se
 DISABLE_SIGNUP=false
 DEBUG=true
 
 
 
 version: '3.3'
services:
  caddy-gen:
    image: 'wemakeservices/caddy-gen:latest'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - caddy-certificates:/data/caddy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - botty-builder
      - botty-viewer
  botty-db:
    image: postgres:13
    restart: always
    volumes:
      - dbb_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=botty
      - POSTGRES_PASSWORD=botty345x
  botty-builder:
    labels:
      virtual.host: 'debu.r6.se' # change to your domain
      virtual.port: '3000'
      virtual.tls-email: 'admin@r6.se' # change to your email
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - botty-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    env_file: .env

  botty-viewer:
    labels:
      virtual.host: 'debuc.r6.se' # change to your domain
      virtual.port: '3000'
      virtual.tls-email: 'admin@r6.se' # change to your email
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    env_file: .env

  minio:
    labels:
      virtual.host: 'debus.r6.se' # change to your domain
      virtual.port: '9000'
      virtual.tls-email: 'admin@r6.se' # change to your email
    image: minio/minio
    command: server /data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3_dataa:/data
  # This service just make sure a bucket with the right policies is created
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "
volumes:
  dbb_data:
  s3_dataa:
  caddy-certificates:
    driver: local
    
    
    
 I have installed the latest version and also tried some previous versions as well but nothing seems to work with them email, My SMTP settings are good as i am using it on different platforms & the applications hosted on other docker containers as well.
 
 I am attaching all the log files as well. Hoping to find the solution.
[_botty_caddy-gen_1_logs.txt](https://github.com/baptisteArno/typebot.io/files/14366438/_botty_caddy-gen_1_logs.txt)
[_botty_botty-viewer_1_logs.txt](https://github.com/baptisteArno/typebot.io/files/14366440/_botty_botty-viewer_1_logs.txt)
[_botty_botty-db_1_logs.txt](https://github.com/baptisteArno/typebot.io/files/14366441/_botty_botty-db_1_logs.txt)
[_botty_botty-builder_1_logs.txt](https://github.com/baptisteArno/typebot.io/files/14366442/_botty_botty-builder_1_logs.txt)

**Comment by baptisteArno** [comment]
You should upgrade your instance, we provide now a better error message for that kind of issue!

Feel free to re-open if you have more info
