### ISSUE TITLE
Implement streaming with Dify.AI block

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1281]

**Comment by sebastienallain56** [comment]
Receive this messages today
{
  "message": "Unterminated string in JSON at position 1 (line 1 column 2)"
}
OR
{
  "message": "Unexpected non-whitespace character after JSON at position 2 (line 1 column 3)"
}

**Comment by sebastienallain56** [comment]
Thx Baptiste for this push. Still have the same messages in return
{
  "message": "Unterminated string in JSON at position 5 (line 1 column 6)"
}

**Comment by baptisteArno** [comment]
Can you provide a way for me to reproduce the bug?
