### ISSUE TITLE
Video is not shown in Whastapp, but in web works fine

### ISSUE THREAD

**Issue by altomarketing** [baptisteArno/typebot.io#1282]
Im using docker with tag next,  version 2.22.?

In web flow audio and video is showed fine, you can test here = https://bot.chatconclientes.info/wasapventass 

In whastapp audio is sent ok but video is not sent .  The Test number sent to @baptisteArno  in discord

Video url is = https://raw.githubusercontent.com/altomarketing/cdn/main/uploads/ssinicial-aac.mp4 

Flow can be seen here = 

![errorwhastapp](https://github.com/baptisteArno/typebot.io/assets/474889/57858bad-f069-4afc-962f-f0bc4e0feafe)

**Comment by baptisteArno** [comment]
WhatsApp is rejecting this particular video, but we can't know why for sure :(

**Comment by baptisteArno** [comment]
Supported video types are:

video/mp4, video/3gpNotes. Only H.264 video codec and AAC audio codec is supported with a single audio stream or no audio stream.

**Comment by baptisteArno** [comment]
Ok, the link is the issue. Try to re-upload it on a Github comment for example. If you provide that new link, it works!
