### ISSUE TITLE
Typebot Discord server useless for people with no phone number

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#1283]
Hi,

I've joined the Typebot discord server since it's beginnings, but can't send messages at all because you've set the requirements to having a verified phone number.

I'm using an VoIP phone number, and can't verify it using discord since they don't allow VoIP numbers.

Could you drop the phone number requirement?
Regards.

**Comment by altomarketing** [comment]
you can use discord, but you can not write in forums without verification, 

and that is not an issue for typebot, please...

**Comment by Lanhild** [comment]
I mean... Anybody that's in the same case as me (VoIP phone number, which is very common in America) cannot chat at all in Typebot's discord, so yes, it a Typebot issue.

@baptisteArno Mind fixing the discord requirements? It'd be cool to be able to chat in the Discord server w/ other users.

**Comment by baptisteArno** [comment]
Ok that's a good point, I didn't know you couldn't verify a VoIP phone number on Discord. I just removed that restriction. 👍

Thank you for the heads up!
