### ISSUE TITLE
An error occured while signing in!!!

### ISSUE THREAD

**Issue by alexandrexgoulart** [baptisteArno/typebot.io#1289]
![image](https://github.com/baptisteArno/typebot.io/assets/78564138/e05bd4d8-c4f4-40ae-80a7-193515507e36)

I am trying to configure my typebot, but when i try to sign in, i received this message of error.
Can anyone help me ?
I am a beginner.

**Comment by alexandrexgoulart** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/78564138/f235ef72-a90a-4508-a5ee-42871c1a3ee1)
Another error now

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by estevaofernandesoliveira** [comment]
@alexandrexgoulart How did you fix the first error? Could you share? I am facing the same issue.
