### ISSUE TITLE
Error integrating with cal.com

### ISSUE THREAD

**Issue by PlaceConsultoria** [baptisteArno/typebot.io#1290]
I scheduled an event to happen on meet, but it saves the location as WhatsApp

![image](https://github.com/baptisteArno/typebot.io/assets/90437926/e2a9a840-e626-493e-8bb1-f31e27402d9b)

**Comment by altomarketing** [comment]
i use cal.com and it always do that, in place field, cal.com saves the number... i dont think its an typebot issue

**Comment by baptisteArno** [comment]
Indeed, try to ask Cal.com about that 🙏
