### ISSUE TITLE
Increased usage on Verceel

### ISSUE THREAD

**Issue by sebiweise** [baptisteArno/typebot.io#1294]
![image](https://github.com/baptisteArno/typebot.io/assets/22999200/381ad80a-c73d-4f98-bf1b-720ec84d3948)
We have some big usage on our Typebot instance on Vercel on the /signin route. Any idea why the usage is that high?

**Comment by sebiweise** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/22999200/98fa1cbf-35a9-4a76-95d0-e057f4e7948f)
Our Axiom stats. Any idea why the /signin endpoint gets called so often?

**Comment by baptisteArno** [comment]
That's indeed unexpected. We don't have such issue on the official hosting.

Someone is most likely spamming this endpoint, then?

**Comment by sebiweise** [comment]
I don´t really know. I´ve already disabled Betterstack Health check but the requests keep getting in. 3,5GB traffic so far 1GB since the issue creation. Any idea how to debug the request origin?

**Comment by baptisteArno** [comment]
Try adding Cloudflare proxy to have better insight on this maybe?

**Comment by baptisteArno** [comment]
I'll close this as it most likely have nothing to do with the project itself 🙏
