### ISSUE TITLE
Bug: Button cards break on WhatsApp if there is a "wait with pause" card is in the flow

### ISSUE THREAD

**Issue by amiraliemami** [baptisteArno/typebot.io#1295]
Thanks for the awesome software!

I'm self-hosting the `2.22.2` Docker containers on EC2 and connecting to WhatsApp. I found that if there is a "Wait" card with the "Pause the flow" option enabled in the flow, the "Buttons" cards that come after it break on WhatsApp (everything works as expected in the online viewer though).

Below is a bot that demonstrates this behaviour if you connect WhatsApp:

[typebot-whatsapp-buttons-bug.json](https://github.com/baptisteArno/typebot.io/files/14417459/typebot-whatsapp-buttons-bug.json)

**Comment by baptisteArno** [comment]
Hey, I can't reproduce on https://app.typebot.io

So this might have been fixed recently. Maybe try to pull `next` to see if that fixes the issue? Otherwise you can wait next release on the 1st of march 🙏

**Comment by amiraliemami** [comment]
Cool, thanks!


Amir Emami

*Data Scientist*

IDinsight | Improving lives with data and evidence.

Hauz Khas Village, New Delhi

IDinsight.org <http://www.idinsight.org/> | Twitter: @IDinsight | LinkedIn:
@idinsight | IDeas blog <https://www.idinsight.org/ideas-and-insights/blog/>
