### ISSUE TITLE
Integration with Anthropic's LLMs (Claude)

### ISSUE THREAD

**Issue by stergios-enchatted** [baptisteArno/typebot.io#1315]
Hi @baptisteArno,
as I have already shared in the Discord community, we were thinking of creating a new block, integrating Anthropic's Claude into Typebot. 
We thought this would be very useful considering Anthropic's focus on Responsible AI.
We are currently exploring this feature, after reviewing how you have implemented with the OpenAI block, and we think we could have it ready very soon. 
What do you think?

**Comment by baptisteArno** [comment]
The issue I see with this is that their product is in closed beta which means that:

- I won't be able to test it
- Users could mislead thinking that they can connect with Anthropic while they can't

**Comment by stergios-enchatted** [comment]
The API is publicly available for all as explained here: https://support.anthropic.com/en/articles/8114521-how-can-i-access-the-claude-api
Anyone who is interested can create API keys through "console.anthropic.com"
There is even a free Evaluation Plan does not require entering a payment option.

Do you still think it is not worth it?
