### ISSUE TITLE
Bloco de audio com problema para receber reposta do ElevenLabs.

### ISSUE THREAD

**Issue by ricardomatni** [baptisteArno/typebot.io#1319]
Fiz vários testes, tanto na interface da web, como no whatsapp, e funcionou muito bem até as 12:00hs.
Agora não está saindo as resposta do ElevenLabs.
Me certifiquei os audios estão sendo gerados.
Apenas parou de funcionar no bloco de audio corretamente.
![image](https://github.com/baptisteArno/typebot.io/assets/106673588/b21b24ea-f117-46d3-85ff-f7de2bd5ef29)
![image](https://github.com/baptisteArno/typebot.io/assets/106673588/e23462c0-6d53-480b-9cd5-e474c7083465)

**Comment by danteeb** [comment]
Hi Baptiste!
The same here, EllevenLabs don't work anymore in bubble audio.
Can you help about that?

Regards,
Dante

**Comment by baptisteArno** [comment]
Only english issues please! 🙏

**Comment by jdefranco** [comment]
the elevenlabs isnt working.. just tested it.. it returns an audio bubble with 0 seconds
