### ISSUE TITLE
Write a guide on how to run Typebot with Dokku

### ISSUE THREAD

**Issue by bukit-kronik** [baptisteArno/typebot.io#1322]
https://dokku.com/docs/getting-started/installation/

https://dokku.com/docs/community/plugins/

https://github.com/d1ceward/n8n_on_dokku

**Comment by baptisteArno** [comment]
It won't be an integration but more like a guide.

**Comment by baptisteArno** [comment]
I'm not familiar with Dokku enough so I'd appreciate help from someone for this :)

**Comment by baptisteArno** [comment]
Feel free to reopen
