### ISSUE TITLE
EllevenLabs Text to Speech don't work anymore

### ISSUE THREAD

**Issue by danteeb** [baptisteArno/typebot.io#1323]
For whatever reason (Text to Speech) doesn't work well since yesterday. The URL with audio link generated by Ellenven is coming up empty.

Flow image attached.

<img width="806" alt="Captura de Tela 2024-03-05 às 07 08 16" src="https://github.com/baptisteArno/typebot.io/assets/138946716/6e1c9326-25e1-4fc9-82f3-5d3673ef33c0">
<img width="499" alt="Captura de Tela 2024-03-05 às 07 08 32" src="https://github.com/baptisteArno/typebot.io/assets/138946716/aa37ea5d-e392-4b76-9885-3998dc93b118">

**Comment by danteeb** [comment]
Without any error, it just doesn't get the EllevenLabs audio URL.
Other friends have the same problem.

https://github.com/baptisteArno/typebot.io/assets/138946716/183149a0-81c8-453d-8b86-989204785e7f

**Comment by baptisteArno** [comment]
Oh my guess is that you don't have an S3 storage implemented.

Am I right? https://docs.typebot.io/self-hosting/configuration#s3-storage-media-uploads

**Comment by danteeb** [comment]
From what I understand, it doesn't even record anything on S3, because Ellevenlabs returns a URL and this URL is inserted inside the audio balloon... but the URL is empty (when I tell it to write on the screen).
No error appears in the log, but for some reason it is unable to record the audio on S3.
The tokens in EllenLabs are consumed, so EllevenLabs is generating the audio normally.
See attachment please.
![Captura de Tela 2024-03-05 às 22 14 27](https://github.com/baptisteArno/typebot.io/assets/138946716/72a51058-905b-4b13-b9c2-78280dbec492)

**Comment by baptisteArno** [comment]
Then I'm clueless as I can't reproduce the issue on app.typebot.io.

**Comment by Guizeera8** [comment]
poderia me enviar o json para eu conferir aqui?
