### ISSUE TITLE
Add new package.

### ISSUE THREAD

**Issue by ayushpateldevvspl** [baptisteArno/typebot.io#1326]
Hello i am useing "version": "2.15.1" of typebot. In that i need to add new npm packages in code so I simply type  pnpm add node-cron . it give me error like this :-

" 
The dependencies at "/home/vspl/codes/typebot/typebot.io-main/node_modules" are currently linked from the store at "/root/.local/share/pnpm/store/v3".

pnpm now wants to use the store at "/home/vspl/.local/share/pnpm/store/v3" to link dependencies.

If you want to use the new store location, reinstall your dependencies with "pnpm install".

You may change the global store location by running "pnpm config set store-dir <dir> --global".
(This error may happen if the node_modules was installed with a different major version of pnpm)
vspl@vspl-HP-EliteDesk-800-G1-DM:~/codes/typebot/typebot.io-main/apps/builder$ pnpm install node- "

also some of the package are installed also it add in package.json and node_module also but when i import in code it give me error for importing.

Can Any one have answer of it ?

**Comment by baptisteArno** [comment]
This error is out of Typebot scope. Just try to follow what the error message says :)
