### ISSUE TITLE
Setup Amazon's S3 Storage?

### ISSUE THREAD

**Issue by willdotcom** [baptisteArno/typebot.io#133]
Hello, has anyone managed to configure the upload of files to Amazon's S3 Storage?
I have tried to configure it and I can't see that it is possible, the documentation is not clear enough when it comes to storing in Amazon S3.

```
      - S3_ACCESS_KEY= Here I have put the credentials generated in IAM
      - S3_SECRET_KEY= Here I have put the credentials generated in IAM
      - S3_BUCKET= Here I have put the name of the bucket created in S3
      - S3_ENDPOINT=storage.domain.com
```

`- S3_ENDPOINT=storage.domain.com`

This is where the question arises, to really know what is being defined as "EndPoint", since in the documentation it specifies the subdomain created and pointed to the server IP. However when I do this, I can't send anything to Amazon S3, so I really want to know what the actual configuration would be.

The EndPoint Amazon S3 is here:
https://docs.aws.amazon.com/general/latest/gr/s3.html

**Comment by willdotcom** [comment]
Any here? lol

**Comment by baptisteArno** [comment]
For some reason, I didn't see this issue in my notifications inbox 🤔

I'll take a look ASAP, try to connect an S3 bucket from AWS and let you know to configure it :)

In the meantime, have you tried `s3.<REGION>.amazonaws.com` ? (by replacing <REGION> by your bucket region)
