### ISSUE TITLE
Locally: Error Login Callback Url

### ISSUE THREAD

**Issue by matheusfols** [baptisteArno/typebot.io#1338]
Hello, I'm trying to configure it locally, but when logging in it's giving me an error.

In Github I configured the callback url to http://localhost:3000/api/auth/callback/github, but when I log in instead of the port being 3000, it returns as 8080. I configured it for Google and it happens the same problem, change the port from 3000 to 8080.

Can you help me, please?

**Comment by baptisteArno** [comment]
Are you running it locally? https://docs.typebot.io/contribute/guides/local-installation

**Comment by baptisteArno** [comment]
Why don't your just use the credentials here:

```
GITHUB_CLIENT_ID=534b549dd17709a743a2
GITHUB_CLIENT_SECRET="7adb03507504fb1a54422f6c3c697277cfd000a9"
```

They should work right of the bat without you having to configure a Github app
