### ISSUE TITLE
Strange behavior when trying to delete a block.

### ISSUE THREAD

**Issue by Trystan4861** [baptisteArno/typebot.io#1345]
If you try to delete with the secondary button it doesn't work, but if you show the header of the block with the action buttons, it already works. If you undo the deletion, the secondary button stops displaying the custom menu. Delete from the top block actions menu if it works without problems

https://www.loom.com/share/ba2b148b8bba431abcab3e1092fe13f0?sid=c557a875-346b-4ff9-82cc-58dac90cf546

**Comment by baptisteArno** [comment]
That's something I can't reproduce, does it also happen on another new bot?

**Comment by Trystan4861** [comment]
with small typebots it seems to work well, but when you have many blocks... you can check it easily copy-pasting a couple of blocks several times...

**Comment by baptisteArno** [comment]
Can't reproduce :(
