### ISSUE TITLE
Testing the flow throws an exception

### ISSUE THREAD

**Issue by tgdn** [baptisteArno/typebot.io#1347]
![image](https://github.com/baptisteArno/typebot.io/assets/480050/992931d1-4c18-4318-ae50-62a944c3375e)

**Comment by baptisteArno** [comment]
How can I reproduce?

**Comment by semvgelooven** [comment]
I have the same error, you can reproduce using the quiz template for example. Clicking on a variable or clicking 'test' and switch from 'Web' to 'API'.

**Comment by baptisteArno** [comment]
Ok I'm working on a fix

**Comment by baptisteArno** [comment]
fixed with eaaa840cbf366ec38ea5cdd2d45944bfb0a77d49
