### ISSUE TITLE
ElevenLabs Voice List Missing Custom Voices

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#1348]
When selecting a voice there are the default ElevenLabs voices at the top and then only a few of my custom made voices appear below.  I have close to 30 custom voices in my account and only 4 of them appear in the selections.

**Comment by jdefranco** [comment]
Update:

I am able to access other voices, but had to go in and use the search.. although working, this is not intuitive, perhaps a button to view more results or an indicator to search that is greater?

**Comment by baptisteArno** [comment]
Indeed the select input displays only up to 50 items initially.

I guess we can remove that behavior!
