### ISSUE TITLE
Initial Load of Chat Bubble Too Slow 

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#1349]
When clicking to open the chat bubble an empty modal window opens immediately, but the chatbot takes a while to appear and initiate its messages.. it's so long that users can feel that something is broken. It needs to be faster or at least have something appear that indicates its loading...

**Comment by baptisteArno** [comment]
Can you provide a video or something showing the issue?

**Comment by jdefranco** [comment]
I think the issue may be the HTML/Javascript embed option.. I switched to Script embed and it loads right away...

**Comment by baptisteArno** [comment]
How are you embedding it? Is it on Wordpress?

**Comment by jdefranco** [comment]
Yes this instance is on wordpress, but I also have one embedded with react that is behaving similarly to how the HTML/Javascript was loading.. (taking a while to begin)

**Comment by baptisteArno** [comment]
OK, provide the React site example if possible!

**Comment by rohan-dave** [comment]
I am using a Carrd website and doing the HTML embed, having the same issue of slow loading of the first chat message.
