### ISSUE TITLE
Inquiry Regarding Randomized Question Sets for Customer Engagement

### ISSUE THREAD

**Issue by Mayureii** [baptisteArno/typebot.io#1353]
I have been thinking about ways to make our interactions with customers more engaging and dynamic. One idea that I have come up with is to use randomized question sets for our customer base.

To accomplish this, I have compiled a list of 100 questions that cover various aspects of our products, services, and customer preferences. To ensure that each interaction feels personalized and unique, I would like to explore the possibility of randomly selecting 5 questions from this pool for each customer engagement.

Before we proceed any further, I wanted to consult with you regarding the feasibility of such a feature within our existing infrastructure. Specifically, we're interested in understanding:

- Is it technically feasible to implement a system that can randomly select questions from a predefined set?
- What would be the potential implications in terms of workload and resources required to integrate this feature?
- Are there any considerations or challenges we should be aware of in implementing randomized question sets?

**Comment by cherrycharan** [comment]
You can store the set of questions in a DB and use the webhook component to hit your endpoint where the random logic lies, where the endpoint response can be stored in a variable and shown in the flow which you intend to build

**Comment by baptisteArno** [comment]
Yes you'd have to pull them from an external storage like Google Sheets or else. This is then out of Typebot's scope 🙏
