### ISSUE TITLE
Return to Source Typebot

### ISSUE THREAD

**Issue by drauber** [baptisteArno/typebot.io#1358]
Suposing i'm using three typebots, two sources and one destination.

Typebot source A -> Typebot Detail (After make all we need, i want to return to source a )
Typebot source B -> Typebot Detail (After make all we need, i want to return to source b)

Is there a way to identify from the Typebot Detail is called and jump to after specific option is called?

Thanks

**Comment by baptisteArno** [comment]
By default, when using  Typebot link block, when it finished triggering the block, it should continue the flow in the parent Bot.

Typebot A -> Typebot Detail -> (When Typebot Detail is ended) Typebot A
