### ISSUE TITLE
Anthropic streaming is stopping prematurely

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1359]

**Comment by baptisteArno** [comment]
Issue with underlying `ai` package: https://github.com/vercel/ai/issues/1159

**Comment by aleksander-pankow** [comment]
Problem the same. After first response - they stop showing messages.
Sometimes - I don't see a first response from Anthropic.

With OpenAI working perfectly.

**Comment by baptisteArno** [comment]
Can you share a reproduction?
