### ISSUE TITLE
WhatsApp Text Input After buttons. 

### ISSUE THREAD

**Issue by SweetJenna** [baptisteArno/typebot.io#1367]
I send buttons on WhatsApp. 

If the user manually enters text instead of choosing a button, I want to call openAI. 

How can I do this?

**Comment by papalardo** [comment]
Tried you make this? 
![image](https://github.com/baptisteArno/typebot.io/assets/17734894/e8b533bc-918b-45d3-a4b9-b39c45234fd6)

**Comment by baptisteArno** [comment]
For questions: https://typebot.io/discord
