### ISSUE TITLE
Outgoing proxy

### ISSUE THREAD

**Issue by InitSegner** [baptisteArno/typebot.io#1378]
Hi Baptiste,

we would like to use the typebot behind an outgoing proxy, but he ignores the variables http_proxy / HTTP_PROXY.

The first time a user wants to register himself, typebot wants to connect to github (I have no clue for what, could you please explain it to me?) and if it is unable to, the magiclink mail won't be send.

Best regards

Florian

EDIT:
I think I found the part, typebot checks the email blocklist.

```
    signIn: async ({ account, user }) => {
      if (restricted === 'rate-limited') throw new Error('rate-limited')
      if (!account) return false
      const isNewUser = !('createdAt' in user && isDefined(user.createdAt))
      if (isNewUser && user.email) {
        const { body } = await got.get(
          'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/master/disposable_email_blocklist.conf'
        )
        const disposableEmailDomains = body.split('\n')
        if (disposableEmailDomains.includes(user.email.split('@')[1]))
          return false
      }
```

EDIT2:

The problem is known in next-auth
https://github.com/nextauthjs/next-auth/issues/2509
https://next-auth.js.org/tutorials/corporate-proxy

**Comment by InitSegner** [comment]
Would it be possible to disable the disposableEmailDomains check at least?

**Comment by baptisteArno** [comment]
> Would it be possible to disable the disposableEmailDomains check at least?

How is it a problem in your case?

**Comment by InitSegner** [comment]
If you could disable the check typebot wouldn't need a proxy. The magic-link-mail doesn't get send, because it waits for the blocklist. Or you could "try" to get the list and if it fails the mail gets send without the check.
await got.get(
          'https://raw.githubusercontent.com/disposable-email-domains/disposable-email-domains/master/disposable_email_blocklist.conf'
        )

**Comment by baptisteArno** [comment]
The issue is with coporate incoming requests proxy. It's not related to Typebot at all.

**Comment by baptisteArno** [comment]
You are free to edit the code in your forked project! 👍
