### ISSUE TITLE
Error! Could not reach server. Check your connection.  {}

### ISSUE THREAD

**Issue by guilherme-paiva-castro** [baptisteArno/typebot.io#1379]
Boa tarde, pessol alguem porfavor consegue me ajudar a resolver o erro Error! Could not reach server. Check your connection.

{}. ??

Versão: 2.23.0

![erro, typebot](https://github.com/baptisteArno/typebot.io/assets/162342457/468db482-f6eb-42d8-94bc-22440f7fa32f)

**Comment by InitSegner** [comment]
Check the urls in your .env file (let them start with https://)

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by guilherme-paiva-castro** [comment]
Boa tarde, claro estou reinstalando para rever o erro novamente, assim que pegar aqui já envio, teria discord talvez [batisteArno](https://github.com/baptisteArno)?

**Comment by guilherme-paiva-castro** [comment]
[batisteArno](https://github.com/baptisteArno): 

 No commando docker-compose logs pediu isso!

Command 'docker-compose' not found, but can be installed with:

apt install docker-compose



segui essa instalçao! 




###Instalar typebot

git clone https://github.com/baptisteArno/typebot.io.git

cd typebot.io

git checkout -b 262f33f

cp .env.example .env

Ajustar o arquivo .env

npm install -g pnpm

pnpm install

NODE_OPTIONS=--max-old-space-size=4096

pnpm run build:apps --force

cd apps/builder

pnpm start -p 3001

npm install pm2 -g

pm2 start --name=typebotbuild pnpm -- start -p 3001

cd apps/viewer

pnpm start -p 3002

pm2 start --name=typebotviewer pnpm -- start -p 3002

pnpm prisma generate && pnpm db:migrate

**Comment by baptisteArno** [comment]
> Check the urls in your .env file (let them start with https://)

This 🙏

**Comment by guilherme-paiva-castro** [comment]
Bom dia, tudo bem? [batisteArno](https://github.com/baptisteArno) a configuração do .env!


ESTA https://

Clark Que editei as configurações do banco para encaminhar aqui e de email...

# Make sure to change this to your own random string of 32 characters (https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
ENCRYPTION_SECRET=do+UspMmB/rewbX22222222K/rskFmtgGSSZ8Ta
2
DATABASE_URL=postgresql://typebotusr:1222z@25.218229.1229.116.21:5432/typebot

NEXTAUTH_URL=https://www.chatbot.andromedanet.com.br
NEXT_PUBLIC_VIEWER_URL=https://bot.andromedanet.com.br

ADMIN_EMAIL=Email colocado...@gmail.com
NEXT_PUBLIC_SMTP_FROM='Andromeda' <Email colocado.@gmail.com>
SMTP_AUTH_DISABLED=false
SMTP_USERNAME=Email colocado.h@gmail.com
SMTP_PASSWORD=Password colocado
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_SECURE=true
DEFAULT_WORKSPACE_PLAN=UNLIMITED

S3_ACCESS_KEY=WklyLxYUasdaRMlRasdasdasdysd3FL9N
S3_SECRET_KEY=gasdasdasdasdast15sZ4numKJyKi
S3_BUCKET=typebot
S3_ENDPOINT=s3. colocado

# For more configuration options check out: https://docs.typebot.io/self-hosting/configuration
