### ISSUE TITLE
error when using gmail smtp

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#1380]
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/55d5984d-ba38-4b4d-9d7a-b989928e4490)

I used typebot a couple of weeks ago and it's working with Gmail's SMTP but now it doesn't work and I'm getting this error and I tested it with Sendgrid's SMTP and it worked, but I need it to be from Gmail

```
        - NEXT_PUBLIC_SMTP_FROM="'Typebot Notifications' <xxxxxx@gmail.com>"
        - SMTP_AUTH_DISABLED=false
        - SMTP_USERNAME=xxxxxx@gmail.com
        - SMTP_PASSWORD=pass-xxxxxx
        - SMTP_HOST=smtp.gmail.com
        - SMTP_PORT=587
        - SMTP_SECURE=true
```

**Comment by InitSegner** [comment]
My guess: your mailserver has a self signed certificate?

**Comment by RuanMD** [comment]
> My guess: your mailserver has a self signed certificate?

I use the traffic to generate the certificate with letsencrypt

**Comment by baptisteArno** [comment]
See https://nodemailer.com/usage/using-gmail/
