### ISSUE TITLE
Typebot Brand on Self-Hosted

### ISSUE THREAD

**Issue by lhyphendixon** [baptisteArno/typebot.io#1382]
Hey Baptiste / guys, 

I'm running self-hosted and am being told I need to upgrade to remove Typebot Branding from the theme.  I've been searching but can't find clarification anywhere.  What is required to remove the branding from a self-hosted installation?

**Comment by baptisteArno** [comment]
https://docs.typebot.io/self-hosting/configuration

See `ADMIN_EMAIL` and `DEFAULT_WORKSPACE_PLAN`
