### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [baptisteArno/typebot.io#1385]
Github Security Lab has found a potential vulnerability in typebot.io. Please enable [Private Vulnerability Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or provide an security contact so that we can report privately.

**Comment by baptisteArno** [comment]
Enabled! Thank you.
