### ISSUE TITLE
 Problèmes et retours d'expérience sur la plateforme de création de bots

### ISSUE THREAD

**Issue by marketingverso** [baptisteArno/typebot.io#1386]
Bonjour l'équipe de support,

Je tiens à vous faire part de quelques problèmes que nous rencontrons sur la plateforme de création de bots. Ces problèmes impactent notre expérience utilisateur et nous empêchent de tirer pleinement parti des fonctionnalités offertes. Voici un résumé des principaux points :

1. Bugs et difficultés de sauvegarde : Nous avons constaté des bugs récurrents où les modifications ne sont pas enregistrées correctement, ce qui nous oblige à recommencer plusieurs fois les modifications pour qu'elles soient prises en compte.

2. Perte de données lors de l'édition simultanée : Lorsque plusieurs personnes éditent le même bot en même temps, ou avec un délais très bref, nous avons remarqué que certaines modifications étaient parfois supprimées de manière inattendue, ce qui entraîne une perte de données et un manque de cohérence dans nos projets.

3. Problème d'affichage des GIF : Nous rencontrons des difficultés pour afficher les GIF avant que la réponse de ChatGPT ne soit générée, cela conduit à une longue attente avant qu'il n'apparaisse presque en même temps que la réponse. Cela rend l'expérience utilisateur moins fluide et limite notre capacité à communiquer visuellement avec nos utilisateurs.

4. Impossible de configurer le SMTP pour l'envoi d'emails : Nous avons essayé de configurer le SMTP pour envoyer des emails depuis notre adresse personnalisée, mais nous rencontrons des difficultés pour le faire fonctionner correctement. Cela limite notre capacité à communiquer efficacement avec nos utilisateurs par email.

5. Problèmes de formatage des emails : Lors de l'envoi d'emails, nous avons remarqué que le formatage n'est pas toujours correctement interprété. Les balises HTML telles que <br> restent visibles dans le corps des emails, ce qui impacte la présentation des contenus et nuit à la qualité de nos communications.
Le comportement de typebot est hératique, car au début les réglages fonctionnent correctement et puis après ils arrêtent de de fonctionner d'un coup.

Nous apprécierions grandement toute assistance ou solution que vous pourriez nous fournir pour résoudre ces problèmes et améliorer notre expérience utilisateur sur la plateforme.
Merci pour votre attention et votre assistance.

Cordialement,

La team People of Verso

**Comment by baptisteArno** [comment]
Hi team,

Please reach out by email so that we can talk about all this in french.

This Github repo is a place for verified technical issues. 🙏

**Comment by marketingverso** [comment]
Bonjour Baptiste,

Merci pour votre retour !

Nous vous re-transférons notre message :
Je tiens à vous faire part de quelques problèmes que nous rencontrons sur
la plateforme de création de bots. Ces problèmes impactent notre expérience
utilisateur et nous empêchent de tirer pleinement parti des fonctionnalités
offertes. Voici un résumé des principaux points :1. Bugs et difficultés de
sauvegarde : Nous avons constaté des bugs récurrents où les modifications
ne sont pas enregistrées correctement, ce qui nous oblige à recommencer
plusieurs fois les modifications pour qu’elles soient prises en compte.2.
Perte de données lors de l’édition simultanée : Lorsque plusieurs personnes
éditent le même bot en même temps, ou avec un délais très bref, nous avons
remarqué que certaines modifications étaient parfois supprimées de manière
inattendue, ce qui entraîne une perte de données et un manque de cohérence
dans nos projets.3. Problème d’affichage des GIF : Nous rencontrons des
difficultés pour afficher les GIF avant que la réponse de ChatGPT ne soit
générée, cela conduit à une longue attente avant qu’il n’apparaisse presque
en même temps que la réponse. Cela rend l’expérience utilisateur moins
fluide et limite notre capacité à communiquer visuellement avec nos
utilisateurs.4. Impossible de configurer le SMTP pour l’envoi d’emails :
Nous avons essayé de configurer le SMTP pour envoyer des emails depuis
notre adresse personnalisée, mais nous rencontrons des difficultés pour le
faire fonctionner correctement. Cela limite notre capacité à communiquer
efficacement avec nos utilisateurs par email.5. Problèmes de formatage des
emails : Lors de l’envoi d’emails, nous avons remarqué que le formatage
n’est pas toujours correctement interprété. Les balises HTML telles que
<br> restent visibles dans le corps des emails, ce qui impacte la
présentation des contenus et nuit à la qualité de nos communications.
Le comportement de typebot est hératique, car au début les réglages
fonctionnent correctement et puis après ils arrêtent de de fonctionner d’un
coup.Nous apprécierions grandement toute assistance ou solution que vous
pourriez nous fournir pour résoudre ces problèmes et améliorer notre
expérience utilisateur sur la plateforme.

Merci pour votre attention et votre assistance.

J'espère que nous pourrons résoudre ces problèmes ensemble,

Cordialement,

La team People of Verso

Le lun. 25 mars 2024 à 18:20, Baptiste Arnaud ***@***.***> a
écrit :
