### ISSUE TITLE
Bitdefender Identifying Typebot API as Phishing

### ISSUE THREAD

**Issue by gustavostz** [baptisteArno/typebot.io#1390]
I recently encountered an issue where Bitdefender flagged specific pages of the Typebot website as potential phishing threats (and blocking it). Here are the details of the alerts:

```
Phishing attempt detected
6 minutes ago

Feature:
Online Threat Prevention

We blocked this phishing page for your protection:
https://typebot.co/api/v1/sessions/clu7rvjoc00juzdhlkrlg32l7/continueChat
Phishing pages attempt to obtain sensitive information such as login credentials or credit card details by disguising as trustworthy entities. The stolen data can be then used for financial gain.
```

```
Phishing attempt detected
10 minutes ago

Feature:
Online Threat Prevention

We blocked this phishing page for your protection:
https://typebot.co/api/v1/typebots/cltxl1qqz000p9o2sl3cis9vv/preview/startChat
Phishing pages attempt to obtain sensitive information such as login credentials or credit card details by disguising as trustworthy entities. The stolen data can be then used for financial gain.
```

This blocking could significantly impact the user experience, as it prevents users from accessing the chat features. It might be worth looking into this issue to ensure users can use the chat without interruptions.

**Comment by baptisteArno** [comment]
How can I see the error myself?

**Comment by gustavostz** [comment]
The issue arises when Bitdefender identifies certain Typebot API requests as phishing threats, subsequently stopping the chat. The chat just stops answering.

Here's what the Bitdefender block notification looks like:

![Image of the Bitdefender blocking the API](https://github.com/baptisteArno/typebot.io/assets/48111506/c6fa8414-640c-42a6-8b80-b382c50e321e)

![Image of the Bitdefender blocking the API](https://github.com/baptisteArno/typebot.io/assets/48111506/a67079ee-ce22-4ba0-8978-1c04143461fc)

To bypass this on my end, I added "https://typebot.co/api" to Bitdefender's exceptions list. However, other users with Bitdefender might face the same disruption when attempting to use any Typebot component.

Could you confirm if the "typebot.co" domain is also associated with your services, in addition to "typebot.io"? This clarification will help ensure that I made the right choice by adding the "https://typebot.co/api" into the exceptions.

**Comment by baptisteArno** [comment]
I just sent them a message to remove the site from their blacklist. Hopefully it should be removed soon!

> Could you confirm if the "typebot.co" domain is also associated with your services, in addition to "typebot.io"? This clarification will help ensure that I made the right choice by adding the "https://typebot.co/api" into the exceptions.

Yes bots are deployed to typebot.co.
