### ISSUE TITLE
Bug when using ky package instead of got: `TypeError: Only absolute URLs are supported`

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1396]
Explained here: https://github.com/sindresorhus/ky/issues/568

How to reproduce:
1. Checkout the branch `ky-bug`
2. Start the project locally
3. Follow what I do here:

https://www.loom.com/share/2f7249910e8649949907a05a56104bda?sid=eedea581-e7cd-402c-a537-8bcf1ab664a8

**Comment by jemiluv8** [comment]
@baptisteArno this is an issue with node-fetch@v2.7.0 which is used indirectly 
as fallback by the ky package when the packate (ky) is used outside the browser

Your options
- use something like node-fetch for making requests server side if you expect to only be processing
  the requests in api routes 
- use isomorphic-unfetch - which is like ky but falls back to use node-fetch - I'm hoping it comes bundled with
  its own version of node-fetch.
- finally upgrade the version of the node-fetch in your project - this is used by the ky package.
  - I've seen that node-fetch is an indirect dependency for several packages so this option is not viable.

**Comment by jemiluv8** [comment]
![Screenshot 2024-03-28 at 1 15 23 PM](https://github.com/baptisteArno/typebot.io/assets/119384208/5017e337-db08-4be6-b486-ca0c267f3321)

**Comment by baptisteArno** [comment]
It should use `fetch` which is available since Node v18 (https://nodejs.org/dist/latest-v18.x/docs/api/globals.html). It should not use node-fetch. I just don't know why `fetch` resolves to `node-fetch` here.

As far as I know ky does not depend on any other external packages

**Comment by baptisteArno** [comment]
It's ky-universal who's job was to use `node-fetch` in the browser (https://github.com/sindresorhus/ky-universal)

**Comment by jemiluv8** [comment]
I read ky-universal is now merged with ky so ...
