### ISSUE TITLE
Get magic link via api or generate with secret hash

### ISSUE THREAD

**Issue by MarksEliel** [baptisteArno/typebot.io#1398]
It would be interesting to have some way of generating the magic link through the api, or showing how the access token can be generated, for example:

ENCRYPTION_SECRET + EMAIL + URL = access token

**Comment by baptisteArno** [comment]
I don't see a straightforward way to implement that.

Typebot uses Nextauth under the hood. Here is the associated doc: https://next-auth.js.org/providers/email

I don't really see the point to implement such mechanism

**Comment by baptisteArno** [comment]
I don't think that could be possible. 🙏

Feel free to re-open / contribute if you find something that could work
