### ISSUE TITLE
home button on the bot Editor

### ISSUE THREAD

**Issue by pyrotank41** [baptisteArno/typebot.io#1399]
While using the bot editor, I often get lost due to scrolling (due to infinite scrolling), it will be nice to have a button to bring me back to the flows.

**Comment by baptisteArno** [comment]
You could either refresh the page or go back to dashboard and open the bot again or even change the tab (for example go to Theme tab) and go back.

I think it's preferable that we focus on keeping typebot readable (#249) instead of adding features that says "It's ok to have big bots"
