### ISSUE TITLE
autofilled fields in typebot viewer not submitting

### ISSUE THREAD

**Issue by pyrotank41** [baptisteArno/typebot.io#1402]
the viewer is not accepting auto-filled input fields. When the fields are auto-filled by the browser (safari, on iPhone), I am not able to submit the response, while removing the autofill and typing myself allows to submit response.

![IMG_542F8A355FD7-1](https://github.com/baptisteArno/typebot.io/assets/52042038/bd7d01cd-4f4c-4942-8ce5-10bbd0456397)

**Comment by baptisteArno** [comment]
I thought it would be fixed by #878 but it seems not 🤔

**Comment by pyrotank41** [comment]
now I am getting another error, the autofilled information is showing not valid
![My typebot](https://github.com/baptisteArno/typebot.io/assets/52042038/5fb2a2c7-c183-4d91-b197-d41fc8feb89f)

**Comment by baptisteArno** [comment]
Sorry, it's hard for me to reproduce as autofill only happens on production application.

I'm pretty sure it should be fixed with the latest commit 👍
