### ISSUE TITLE
Blocks clipping in the editor graph

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#1407]
Would be very convenient to have the blocks automatically clip to points in the editor graph.

e.g., in n8n nodes clip automatically to keep the overall workflow neat and organized.
![image](https://github.com/baptisteArno/typebot.io/assets/73610779/e8785c89-8647-4c1b-a974-7d066d0c4c8d)

**Comment by baptisteArno** [comment]
I'm sorry I don't see how snapping to a grid would improve the UX. I find it clumsy. 👎

IMO the Typebot editor experience (nodes, edges, feel) is far superior from the N8N one. But that's maybe personal preference?

I'll close this issue as I really don't see myself implementing a grid for the official Typebot repo. 🙏

**Comment by Lanhild** [comment]
> I'm sorry I don't see how snapping to a grid would improve the UX. I find it clumsy. 👎

@baptisteArno how is clipping clumsy? It's all the opposite as it would prevent cases like the following;
![image](https://github.com/baptisteArno/typebot.io/assets/73610779/f2e55ec3-885a-4154-b50a-e9371cabf855)

> the Typebot editor experience (nodes, edges, feel) is far superior from the N8N one.

If we were to compare the two, I don't see how Typebot's is "far superior". Mind sharing some examples for this point?

**Comment by Lanhild** [comment]
Advice collected from users:
![image](https://github.com/baptisteArno/typebot.io/assets/73610779/bfa1c40f-ac1f-49b5-a12f-9cb08a24e1fe)
