### ISSUE TITLE
Block configuration full-screen view by default

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#1408]
IMO, the full-screen pop-up view of a block configuration should be opened by default when you click on a block.

For instance, when you click on the HTTP Request block in order to configure it, the small pop-up that appears besides the block is very small, and quite unusable.
>![image](https://github.com/baptisteArno/typebot.io/assets/73610779/aeaa2314-4195-479d-9632-3478224984cc)
>Small, hardly usable

It would be much more convenient to have only the large pop-up when configuring a block and would be more logical from a UX standpoint.
>![image](https://github.com/baptisteArno/typebot.io/assets/73610779/a2157592-5458-4c6e-a2d8-559238a43a16)
> Better and easier to use

**Comment by baptisteArno** [comment]
I agree that the expanded view for the HTTP request block or OpenAI block is in general more visible.

But for pretty much any other block or if you just need to quickly edit an existing HTTP request, I like the popover form factor. It's one of Typebot's UX advantage IMHO.

You are free to expand it any time with an additional click.
