### ISSUE TITLE
Transfer to Human Operator via Chatwoot on WhatsApp

### ISSUE THREAD

**Issue by giovanne-oliveira** [baptisteArno/typebot.io#1411]
Hey!

So, I was thinking about implementing the feature for transfering to a human operator with Chatwoot. 

I don't know if my approach will work, specially because I don't know how the data modeling for Typebot works, and I wanted your opinion: WhatsApp Cloud API only supports one Webhook URL right now (as far as I could see). 

So, my plan is: when the block to transfer to Chatwoot is called, it marks that session as "transfered" or something like that, and starts forwarding the WhatsApp notifications to Chatwoot, to be handled by it. After the session expires by the time you configure on WhatsApp integration, the bot assumes again, and the conversation on Chatwoot is marked "abandoned". 

Do you think it can work? If yes, I can try to implement it.

**Comment by baptisteArno** [comment]
Everything you described should be coded outside of Typebot so I'll close this issue 👍

For reference, we can chat about it here: https://discord.com/channels/1155799591220953138/1155883114455900190/1225060225942421617
