### ISSUE TITLE
Issue with docker container!

### ISSUE THREAD

**Issue by alfi4000** [baptisteArno/typebot.io#1414]
Hi i have a issue with Typebot in the docker version check the images please!:
<img width="1379" alt="Bildschirmfoto 2024-04-04 um 08 52 08" src="https://github.com/baptisteArno/typebot.io/assets/149228038/e26a0a41-9cd6-432f-9716-de8b627ec4d6">
<img width="1382" alt="Bildschirmfoto 2024-04-04 um 08 52 14" src="https://github.com/baptisteArno/typebot.io/assets/149228038/0c663f58-2f76-4bdd-9503-8531a69fc0f3">
<img width="1376" alt="Bildschirmfoto 2024-04-04 um 08 52 39" src="https://github.com/baptisteArno/typebot.io/assets/149228038/383d6e77-1449-4440-a59c-791ce49ffdce">
<img width="1363" alt="Bildschirmfoto 2024-04-04 um 08 54 26" src="https://github.com/baptisteArno/typebot.io/assets/149228038/5fcb3e24-aeca-4087-adc8-15fc8d8c6214">
<img width="1376" alt="Bildschirmfoto 2024-04-04 um 08 52 29" src="https://github.com/baptisteArno/typebot.io/assets/149228038/b1a5970b-2225-423a-87e5-d40b01a7f6f4">

The Only difference is I am using ip address to access, here my .env config:

# Make sure to change this to your own random string of 32 characters (https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)
ENCRYPTION_SECRET=do+UspMmB/rewbX2K/rskFmtgGSSZ8Ta

DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot

NEXTAUTH_URL=http://192.168.50.54:8080
NEXT_PUBLIC_VIEWER_URL=http://192.168.50.54:8080

ADMIN_EMAIL=example
# For more configuration options check out: https://docs.typebot.io/self-hosting/configuration
SMTP_USERNAME=example
SMTP_PASSWORD=example
SMTP_HOST=example
SMTP_PORT=25
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications'
SMTP_SECURE=false
SMTP_AUTH_DISABLED=false

where example is there is my email setup I have configured it just not there included!

**Comment by baptisteArno** [comment]
Are you sure that the builder container can make a request to the viewer IP address?

**Comment by alfi4000** [comment]
So there could be an issue between them!?

**Comment by alfi4000** [comment]
> Are you sure that the builder container can make a request to the viewer IP address?

I am not sure 🤔 I am not a dev all is like in repo only changes are made are in the compose I changed the ports to 192.168.50.54:8080:3000 and 192.168.50.54:8081:3000!

**Comment by alfi4000** [comment]
I could try a new repo clone because the one I use is one from a few months ago but there it weren’t working too I just stopped the container and focused on using different tools!

**Comment by alfi4000** [comment]
I was already on the newest I recognized and new repo clone same issue, I have no clue what’s wrong!
The only changes I have already mentioned could be the problem!?

**Comment by baptisteArno** [comment]
By default the viewer is running on port 8081 as mentioned in the doc.

So you need to change it:

NEXT_PUBLIC_VIEWER_URL=http://192.168.50.54:8081

**Comment by alfi4000** [comment]
Yeah thanks that was my issue!
