### ISSUE TITLE
Implement a "Wait" block

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#142]
A wait block should help you wait for a custom amount of time before displaying the next blocks

**Comment by shashicpontentwriter** [comment]
This block is no longer visible in the self-hosted version, but it is visible in the hosted version.

**Comment by baptisteArno** [comment]
You need to wait for the next release if you are pulling Typebot with the `latest` tag. Otherwise, you can pull the `main` tag to have the latest change (but things might not be stable)
