### ISSUE TITLE
Plans for an headless API?

### ISSUE THREAD

**Issue by schonert** [baptisteArno/typebot.io#1421]
Hi there,

Awesome project! I see a huge potential for a headless version where you can access the bot via API. This would allow creating AI flows instead of bots. Similar to https://github.com/FlowiseAI/Flowise

Instead of interacting with the bot you'd submit all the variables at once and let the bot execute and return the value.

I could see us use this to prototype and optimise our AI results before directly integrating them into the system.

This was just an idea - thought I'd throw it out there

**Comment by baptisteArno** [comment]
You can already start a flow using an API (https://docs.typebot.io/api-reference/chat/start-chat).

If the flow does not contain any input blocks, it will be entirely triggered with just a single call!

**Comment by schonert** [comment]
Ohh nice! Thanks 🚀
