### ISSUE TITLE
Vídeo aulas sobre integrações do Typebot / Video tutorials about Typebot integrations

### ISSUE THREAD

**Issue by kairosdm** [baptisteArno/typebot.io#1422]
Dear @baptisteArno,

I am Pedro Soares, a service provider in the capital of Brazil who uses Typebot to offer chatbots for restaurants, cafés, and other businesses.

I have been following your work with Typebot and greatly admire your expertise on the platform.

I would like to request video tutorials on how to use Typebot integrations. I believe this material would be extremely valuable for me and other platform users.

Integrations are a powerful feature of Typebot, but many people do not utilize them due to lack of knowledge. Video tutorials would facilitate learning and increase integration adoption.

With a better understanding of integrations, users can create more complex and efficient chatbots. This, in turn, can lead to increased customer satisfaction and improved sales for businesses using Typebot.

Here are some topics that the video tutorials could cover:

**Creating AI Agents with Personality:**
Exploring how to develop chatbots with human-like characteristics, including personality and tone of voice.
Using Elevem Labs to create realistic human voices and voice cloning.
**Simplified Notifications for Business Owners:**
Implementing a notification system for restaurant and business owners.
Sending sales alerts, order details, and other relevant information directly to them.
**PIX Payments within the Chatbot:**
Integrating with Brazilian companies that offer PIX payments.
Facilitating financial transactions within the chatbot.
**Using AI for Sales and Customer Support:**
Strategies for effectively using AI in sales generation and customer service.
I am confident that video tutorials created by you on Typebot integrations would be a great success.

Thank you for your consideration!

Best regards,

Pedro Soares

**Comment by baptisteArno** [comment]
Hi Pedro,

Thank you for the kind words and the suggestions! That's noted on my end.

Let's discuss further on the community server 👍 https://typebot.io/discord
