### ISSUE TITLE
Urgent: Problem with form page scrolling

### ISSUE THREAD

**Issue by jameswarley** [baptisteArno/typebot.io#1437]
Hello friends!

Who could help me by suggesting a solution to this problem?

Until yesterday, the form was working normally, however, today, when accessing it via cell phone, the page does not scroll...

Link:

https://typebot.co/teste-mocidade-em-movimento

**Comment by Juliandelcampo** [comment]
Same problem here!

**Comment by baptisteArno** [comment]
Thank you for the heads up! Pushing a fix now 8fe856aff3c462810b1a1c524959f6ea74895e9e
