### ISSUE TITLE
location return code stopped working

### ISSUE THREAD

**Issue by alemdodinheiro** [baptisteArno/typebot.io#1445]
I have a geolocation code that was working until yesterday, today it is giving an error and crashing my chat bot. what could be happening? (follow the code below)

async function obterLocalizacao() { try { const response = await fetch('https://get.geojs.io/v1/ip/geo.json'); const data = await response.json(); const cidade = data.city || "Local Desconhecido"; return cidade; } catch (error) { console.error('Erro ao obter a localização:', error); return "Local Desconhecido"; } } return await obterLocalizacao();

**Comment by baptisteArno** [comment]
Fixed f9bdcdc7a3e6f83d6c8e193ac822dbd375a5bbab
