### ISSUE TITLE
capture the customer's location when they share their location via WhatsApp with Chatwoot. /  capturar a localização do cliente quando ele compartilhar sua lozalização pelo whatsapp com chatwoot. 

### ISSUE THREAD

**Issue by Lohuama** [baptisteArno/typebot.io#1460]
Estou usando o typebot e o chatwoot, e preciso capturar a localização do cliente quando ele compartilhar sua lozalização eplo whatsapp. É possível receber a localizaçao o cliente pelo typebot através do chatwoot/whatsapp? se sim, como?

I'm using typebot and chatwoot, and I need to capture the customer's location when they share their location via WhatsApp. Is it possible to receive the customer's location via typebot via chatwoot/whatsapp? if yes, how?

**Comment by michaelvips** [comment]
The official typebot application does not yet accept native WhatsApp integration between typebot and chatwoot, you must be using a third-party application to carry out this integration (evolution api), if so, request the creation of this feature with them.

**Comment by baptisteArno** [comment]
That should be possible, just add a text input and the user can send his location, you will receive it formatted like this: `<LAT>, <LONG>`

**Comment by Lohuama** [comment]
> Isso deve ser possível, basta adicionar um input de texto e o usuário poderá enviar sua localização, você receberá formatado assim:`<LAT>, <LONG>`

It works in Chatwoot, but Typebot has an invalid format and I don't know how to switch from Chatwoot to Typebot.

no chatwoot funciona, mas o typebot vem formato inválido e eu não sei como passar essa informação do chatwoot pra o typebot.

**Comment by michaelvips** [comment]
@Lohuama are you using evolution api ?

**Comment by Lohuama** [comment]
> @Lohuamavocê está usando a API de evolução?
yes I am

**Comment by michaelvips** [comment]
The official typebot application does not yet accept native **evolution api** integration, your problem about *capture the customer's location* is not a typebot error / bug

**Comment by Lohuama** [comment]
> O aplicativo oficial do typebot ainda não aceita integração nativa **da API de evolução** , seu problema em _capturar a localização do cliente_ não é um erro/bug do typebot

I understand, I just wanted to know if it was possible. thanks.

**Comment by michaelvips** [comment]
This is a feature that the evolution-api application needs to include.
