### ISSUE TITLE
SMTP server problem, which file?

### ISSUE THREAD

**Issue by vitorcherulli** [baptisteArno/typebot.io#1461]
Hello everything is fine?

I have a TypeBot installation using Portainer, and I would like to know how I can change the SMTP server?

In the initial installation we used Brevo, but now I have a new SMTP.

Could anyone guide me which file I should change with the new information through Portainer?

**Comment by baptisteArno** [comment]
https://docs.typebot.io/self-hosting/configuration#email-auth-notifications

**Comment by vitorcherulli** [comment]
> https://docs.typebot.io/self-hosting/configuration#email-auth-notifications

I think I explained wrong.

I'm self hosting, and the magic link itself doesn't work. The login email does not arrive!

Should there be a file in the installation to configure SMTP?

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!
