### ISSUE TITLE
Unable to find script file during Docker build process image

### ISSUE THREAD

**Issue by wilsonfe** [baptisteArno/typebot.io#1466]
Hello,

I hope this message finds you well. I'm reaching out to report an issue I encountered while attempting to build a Docker image using your project's Dockerfile.

Issue Description:
During the Docker build process, I encountered an error related to the inability to find a script file specified in the Dockerfile. Here are the details of the error:

sql
Copy code
ERROR [runner 20/21] COPY scripts/-entrypoint.sh ./
------
 > [runner 20/21] COPY scripts/-entrypoint.sh ./:
------
Dockerfile:58
--------------------
  56 |     RUN ./node_modules/.bin/prisma generate --schema=packages/prisma/postgresql/schema.prisma;
  57 |     
  58 | >>> COPY scripts/${SCOPE}-entrypoint.sh ./
  59 |     RUN chmod +x ./${SCOPE}-entrypoint.sh
  60 |     ENTRYPOINT ./${SCOPE}-entrypoint.sh
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 4c12cd4e-98a1-4b64-b105-d6b107ae4953::g5zwrffoqs76jy2z97nuu3ds1: "/scripts/-entrypoint.sh": not found
Context:

Dockerfile Line: 58
Command: COPY scripts/${SCOPE}-entrypoint.sh ./
Error: /scripts/-entrypoint.sh": not found
Additional Information:

The script file ${SCOPE}-entrypoint.sh does not exist in the scripts directory.
The Dockerfile is being built in the correct context.
The value of ${SCOPE} is being provided and is expected to be correctly substituted in the Dockerfile.
Expected Behavior:
The Docker build process should successfully copy the script file specified in the Dockerfile without encountering any errors.

Request:
Could you please provide guidance on resolving this issue or any potential insights into what might be causing this error?

Thank you for your attention to this matter.

Best regards,

**Comment by baptisteArno** [comment]
To build your own builder Docker image

```sh
docker build -t typebot-builder --build-arg SCOPE=builder .
```

To build your own viewer Docker image

```sh
docker build -t typebot-viewer --build-arg SCOPE=viewer .
```

**Comment by bruno-growthsales** [comment]
> To build your own builder Docker image
> 
> ```shell
> docker build -t typebot-builder --build-arg SCOPE=builder .
> ```
> 
> To build your own viewer Docker image
> 
> ```shell
> docker build -t typebot-viewer --build-arg SCOPE=viewer .
> ```

I isued this comands but the issue show now:

[This issue](https://github.com/baptisteArno/typebot.io/issues/1570)
