### ISSUE TITLE
Failed Migrate Schema

### ISSUE THREAD

**Issue by mdestafadilah** [baptisteArno/typebot.io#1472]
> sudo pnpm prisma generate && pnpm db:migrate

![24-04-2024 14-02-35](https://github.com/baptisteArno/typebot.io/assets/5575882/545b8b58-c7b7-4af6-b1a8-a86c40056cdf)

I have no idea. 

# Info
- server: ubuntu 20.04 LTS
- typebot: latest
- pnpm: 9.*

**Comment by baptisteArno** [comment]
What are you trying to achieve? What guide are you following?

**Comment by mdestafadilah** [comment]
> What are you trying to achieve? What doc are you following?

i follow this intruction installation from here
> https://blog.remontti.com.br/7656

but stuck in migration.

**Comment by baptisteArno** [comment]
I suggest you follow an official guide

https://docs.typebot.io/self-hosting/get-started

**Comment by mdestafadilah** [comment]
> I suggest you follow an official guide
> 
> https://docs.typebot.io/self-hosting/get-started

Ya I know. I will report here, if i'm success follow from official guide.

**Comment by mdestafadilah** [comment]
Don't close this issue, i just follow from official 
> https://docs.typebot.io/self-hosting/deploy/manual

but still the same if i run prisma migrate
> # pnpm db:migrate

![25-04-2024 10-01-42](https://github.com/baptisteArno/typebot.io/assets/5575882/4e8804c8-3224-4c35-826e-c3127f2d0005)

everthying running, just migrate prisma failed.

![25-04-2024 10-03-13](https://github.com/baptisteArno/typebot.io/assets/5575882/976672eb-83ea-4737-a38a-cefa550ebe16)

## Info
- pnpm: 9.0.5
- typebot: latest

**Comment by baptisteArno** [comment]
Do you have a .env file with a DATABASE_URL variable setup ?

**Comment by mdestafadilah** [comment]
> Do you have a .env file with a DATABASE_URL variable setup, the variable should start with `postgres`

```DATABASE_URL=postgresql://bot:5380b12c98@127.0.0.1:5432/bot```

**Comment by mdestafadilah** [comment]
when i change to 
```DATABASE_URL=postgres://bot:5380b12c98@127.0.0.1:5432/bot```

show error 
![25-04-2024 15-17-14](https://github.com/baptisteArno/typebot.io/assets/5575882/b01624df-b637-494d-8d7e-d612deb12193)

**Comment by baptisteArno** [comment]
And if you revert it to `postgresql://bot:5380b12c98@127.0.0.1:5432/bot` it does not display that error?

**Comment by mdestafadilah** [comment]
> And if you revert it to `postgresql://bot:5380b12c98@127.0.0.1:5432/bot` it does not display that error?

still same error.

**Comment by baptisteArno** [comment]
Ok so that error means a database migration failed at some point. I suggest that you check the link they provide to understand how you can resolve this.

If your database is empty then I suggest you just reset your database and try again
