### ISSUE TITLE
 Error when placing a separator between grouped buttons using the Official WhatsApp API (Meta Busines)

### ISSUE THREAD

**Issue by elizeufranca** [baptisteArno/typebot.io#1476]
I have a bot that provides some options for the user to choose, they are grouped buttons, however for the user on their WhatsApp, an empty space appears between the buttons.
Below are prints

![image](https://github.com/baptisteArno/typebot.io/assets/139554820/2d6fd6da-0505-4224-b427-24698357b255)
![image](https://github.com/baptisteArno/typebot.io/assets/139554820/cac70827-6349-49d2-b598-5f6ce81b0b1a)

**Comment by baptisteArno** [comment]
See [WhatsApp limitations](https://docs.typebot.io/deploy/whatsapp/overview#limitations) 🙏
