### ISSUE TITLE
Option to disable controls on video and audio bubbles

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1485]

**Comment by smitgol** [comment]
can you explain more about this issue ?

**Comment by Ulrfis** [comment]
If you look at this example https://plastibot.dilemme-plastique.ch/experience (only provide random names in the first questions) you will see that the audio playback bubble is not needed. It would be very very cool if audio plays back automatically, without audio player (if chosen so), just showing text bubble and spoken text.
