### ISSUE TITLE
request With n8n and basewor 

### ISSUE THREAD

**Issue by biellil** [baptisteArno/typebot.io#1493]
Hello!

It would be very important to have integration with "Baserow", since google sheets has limitations of calls per request.

So I have to use n8n to do this integration with typebot! , With the changes in the new version of httprequest, n8n with basewor does not have time to process the request 
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💸Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount)<br/>💪 If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #1493</code> either in the PR description or in a PR's comment<br/><br/>👀 Also, everyone can tip any user commenting <code>/tip 20 @biellil</code> (replace <code>20</code> with the amount, and <code>@biellil</code> with the user to tip)<br/><br/>If you want to learn more, go to our <a href="https://docs.opire.dev">documentation</a></details>

**Comment by biellil** [comment]
I think it would be good in the flow to have the ability to choose the timeout time

**Comment by baptisteArno** [comment]
duplicate #1450
