### ISSUE TITLE
Buttons are not sync on second trigger

### ISSUE THREAD

**Issue by edmagnini** [baptisteArno/typebot.io#1496]
Hello everyone!

I have Typebot locally installed, version 2.18.0, and encountered a bug when relaunching a multi-choice button.

Here's my flow at the beginning and end:
![image](https://github.com/baptisteArno/typebot.io/assets/32701426/dad3eb14-6bbf-4b6d-99ab-3a0d5921667f)
begin flow
![image](https://github.com/baptisteArno/typebot.io/assets/32701426/0c4b56af-d9cb-4b32-ab8f-94042a1a06b8)
end flow

When it is triggered, the user's chat doesn't receive the second set of multi-choice values.

![image](https://github.com/baptisteArno/typebot.io/assets/32701426/b253433f-5e41-48fb-970e-7d5500ca2aa5)
First trigger
![image](https://github.com/baptisteArno/typebot.io/assets/32701426/42440880-32da-434b-87ec-bcbd09637ce6)
Second trigger

**Comment by baptisteArno** [comment]
This is most likely fixed if you upgrade your instance 🙏
