### ISSUE TITLE
possibility to disable Timeout if necessary

### ISSUE THREAD

**Issue by biellil** [baptisteArno/typebot.io#1498]
possibility to disable Timeout, as some webhook take more than 120 seconds depending on the user

**Comment by baptisteArno** [comment]
Indeed if you don't set `CHAT_API_TIMEOUT` you should not have any timeout. But I figured that we still had a timeout but it was fixed on 7d70f0243bc9a8a861346648c8ba4a3079add9c8

So next release will have that fix :)

**Comment by biellil** [comment]
I wish there wasn't a timeout for responding to an http request, I think it would be interesting to have an option to enable or disable the timeout

**Comment by biellil** [comment]
I wish there wasn't a timeout for responding to an http request, I think it would be interesting to have an option to enable or disable the timeout

**Comment by baptisteArno** [comment]
Like I said: "if you don't set CHAT_API_TIMEOUT you should not have any timeout"
