### ISSUE TITLE
UpgradeModal directory name

### ISSUE THREAD

**Issue by laurin-wolf** [baptisteArno/typebot.io#15]
The name of the directory of `UpgradeModal` (`apps/builder/components/shared/modals/UpgradeModal.`) ends with a dot, is this intentional?
The dot at the end of the directory name makes it impossible to check out the repository using Windows.

**Comment by baptisteArno** [comment]
Thank you for the heads up!

**Comment by laurin-wolf** [comment]
No problem, thanks for the quick fix!
