### ISSUE TITLE
"The connection is not secure" on share link

### ISSUE THREAD

**Issue by AymaBA** [baptisteArno/typebot.io#1500]
On my client's phone, there's a page saying, "The connection is not secure," and when they click to access the site, their carrier tells them, "Cyberfilter: This site is dangerous." My client's phone is an iPhone, and their carrier is Orange in France. The URL where this happens is: "https://typebot.co/movida-contact."

**Comment by baptisteArno** [comment]
Ultimately not an issue with the project but more the reputation of typebot.co domain.

Do you know what browser your client is using and did he install any "antivirus" type of application?
