### ISSUE TITLE
Option to reset remembered state if the typebot was updated

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1508]

**Comment by basuabhirup** [comment]
I think this is related to #1427 and #1429 (already resolved) and related to the discussions made in https://discord.com/channels/1155799591220953138/1225863426790789160

As far as I understood, the requirement is to display a prompt that says "Update typebot in existing sessions?" or something like that when the user attempts to publish new changes. 

And when the user selects `yes` i.e. they want to reset the remembered chats , then all the existing end-user sessions will remove the data already stored in their localStorage and sessionStorage and will reload the newly published chatbot from beginning, right ?

**Comment by basuabhirup** [comment]
> After thinking about it. I think it should be a default behavior. The `startChat` API endpoint should check for the `updatedAt` field on the published bot and if the chatSession is older, we would wipe the session saved in storage.

Yeah, that sounds good. So basically we will have to write a new prisma query to check if the `updatedAt` field of a particular published bot is older than the `updatedAt` field of the current `chatSession` and if not then it will execute `wipeExistingChatStateInStorage()` and behave similarly as if there is no chatState stored in the storage, right ?

**Comment by baptisteArno** [comment]
Yes, exactly 👌
