### ISSUE TITLE
Problem closing the bot session integrated with WhatsApp Cloud

### ISSUE THREAD

**Issue by cbalbinos** [baptisteArno/typebot.io#1511]
I noticed that the bot session integrated with WhatsApp is not being closed after the specified time

**Comment by baptisteArno** [comment]
How do you notice that? How to reproduce?

**Comment by cbalbinos** [comment]
This is occurring when I call the bot with a specific number

I tested it with another number and it worked

I believe it is related to this fix 👇

https://github.com/baptisteArno/typebot.io/commit/8351e20fd30a732d51c09bbe2552fbb4edeec872

**Comment by baptisteArno** [comment]
Yes most likely fixed by https://github.com/baptisteArno/typebot.io/commit/8351e20fd30a732d51c09bbe2552fbb4edeec872
