### ISSUE TITLE
WhatsApp not connecting to bot

### ISSUE THREAD

**Issue by cbalbinos** [baptisteArno/typebot.io#1513]
There appears to be an issue with WhatsApp Cloud API integration

I'm having problems with the flow created on 05/13/2024 in version 2.25.0 and with the old Typebot in 2.24.1
both self-hosted

I generated a new permanent token and created a new connection in the flow, but without success

Below is a log file

[log_typebot.txt](https://github.com/baptisteArno/typebot.io/files/15320930/log_typebot.txt)

![whatsapp](https://github.com/baptisteArno/typebot.io/assets/91399681/6a0b8c84-0671-455c-89d9-601d638fa192)

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

Also, are you sure that the webhook is correctly configured on Meta app?

**Comment by cbalbinos** [comment]
Follow the logs

[_typebotipyruia_typebotipyruia_builder.1.ovol4xle4ym6ydmeezc732isc_logs.txt](https://github.com/baptisteArno/typebot.io/files/15323484/_typebotipyruia_typebotipyruia_builder.1.ovol4xle4ym6ydmeezc732isc_logs.txt)
[_typebotipyruia_typebotipyruia_viewer.1.kja7h95hz32z9vp93z2lulmrg_logs.txt](https://github.com/baptisteArno/typebot.io/files/15323485/_typebotipyruia_typebotipyruia_viewer.1.kja7h95hz32z9vp93z2lulmrg_logs.txt)

The webhook is configured correctly in the Meta application
