### ISSUE TITLE
webhook error.

### ISSUE THREAD

**Issue by ayushpateldevvspl** [baptisteArno/typebot.io#1515]
decription :-
Webhook is not executing for the Hyebrew language payload.

Steps :-
1. import below file in editor.
2. click on test.
3. enter 1.
4. enter any Hyebrew.

output :-
popup show with error.

[typebot-export-my-typebot-240778-t65eozz.json](https://github.com/baptisteArno/typebot.io/files/15321812/typebot-export-my-typebot-240778-t65eozz.json)

Fail output:-
![Screenshot from 2024-05-15 18-26-25](https://github.com/baptisteArno/typebot.io/assets/145531640/4ddddb9e-cb4a-4d8a-9c08-2e4eae060d1a)

Success output :-
![image](https://github.com/baptisteArno/typebot.io/assets/145531640/39044afb-2908-4557-8914-6cd2b448e55b)

**Comment by baptisteArno** [comment]
This is a limitation with HTTP protocol (cf: https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header)

Only ASCII is guaranteed to work for header values

**Comment by ayushpateldevvspl** [comment]
but it header key's are same the payload are different.
if bot publish in some side . end user enter value in heybrew language it not process further .
that time what to do ?

**Comment by ayushpateldevvspl** [comment]
> This is a limitation with HTTP protocol (cf: https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header)
> 
> Only ASCII is guaranteed to work for header values

but it header key's are same the payload are different.
if bot publish in some side . end user enter value in heybrew language it not process further .
that time what to do ?

**Comment by baptisteArno** [comment]
I really don't suggest you let the user be able to add their own HTTP header value. That's really an anti pattern. You should let the user modify the body or the query params.

**Comment by ayushpateldevvspl** [comment]
> I really don't suggest you let the user be able to add their own HTTP header value. That's really an anti-pattern. You should let the user modify the body or the query parameters.

I think You not understand my scenario.

https://typebot.co/my-typebot-240778-h02zc6i this is my bot link ok . i use in my website for gether request from my user's. for english user it can enter value that time no problem but if my user enters the value in Hebrew. that time them data is not process to my webhook for what we do ?

**Comment by baptisteArno** [comment]
I am telling you that the problem resides in HTTP protocol header values limitation. **I can't do anything about it.**

I was just suggesting you change how your API behave. Relying on header values as dynamic value is a bad practice. You should rely on dynamic body or query params

**Comment by ayushpateldevvspl** [comment]
> I am telling you that the problem resides in HTTP protocol header values limitation. **I can't do anything about it.**
> 
> I was just suggesting you change how your API behave. Relying on header values as dynamic value is a bad practice. You should rely on dynamic body or query params

ok thank you , I test it bye my self sorry it my mistake to understand wrong.
