### ISSUE TITLE
Set default plan for Workspaces with environment variable

### ISSUE THREAD

**Issue by timokoessler** [baptisteArno/typebot.io#152]
It would be nice to be able to set the default plan for new workspaces using an environment variable.

This is especially useful if the tool is only used internally (in a company) and the login is done with OAuth or OpenID.

Thanks for this awesome tool,
Timo

**Comment by baptisteArno** [comment]
Hey @timokoessler,

Thank you for opening this issue 😀

Can you tell me exactly your use case? You have other users logging in, and you'd like them to have a Pro workspace automatically?

**Comment by timokoessler** [comment]
Hi @baptisteArno,
Yes, that is exactly our use case. Since the login via e-mail is deactivated, only employees can log in / register. They should then be able to use the tool automatically without restrictions, without anyone having to change this manually in the database.
