### ISSUE TITLE
Script block for WhatsApp

### ISSUE THREAD

**Issue by lewiswilliam** [baptisteArno/typebot.io#1521]
Feature request - Support script block on whatsapp for server side execution

As per documentation, we can see that script block will be skipped for WhatsApp. My understanding of this restriction is due to the fact that we can't run the scripts on the client for WhatsApp or is there any other reason?

Any chance we can be allowed to execute scripts on server in future for WhatsApp?

**Comment by lewiswilliam** [comment]
Pasting the reference discussion from Discord here:

Baptiste — 05/17/2024 1:25 PM
What would you like to execute with the Script block?

William Lewis — 05/17/2024 3:27 PM
i am getting a string input from the user, from which i need to do some processing on it...say substring it by removing some characters
I think as we create more useful bots...script blocks are going to play a major role in them...

Claudio Balbino — 05/17/2024 7:23 PM
Hi @William Lewis ,
You can use the Set variable block to do this
Select in Value = Custom

William Lewis — 05/17/2024 7:25 PM
thanks for pointing that out @Claudio Balbino , did not see that earlier
will need to do it for each variable though, as i have a few 🙂

**Comment by baptisteArno** [comment]
Script block (if client-side execution is unchecked) should work on WhatsApp.

**Comment by lewiswilliam** [comment]
Hi @baptisteArno 

https://docs.typebot.io/deploy/whatsapp/overview#limitations

I think you should update here according to your comment, because here it mentions that script block will be skipped for whatsapp.
