### ISSUE TITLE
wait condition wont work when you use a collect input.

### ISSUE THREAD

**Issue by wladiveras** [baptisteArno/typebot.io#1535]
wait condition wont work when you use a input collect.

way to reply:
use a collect variable input and put a wait after that, wait will be skipped.

**Comment by baptisteArno** [comment]
[Typebot export hdrwcrz.json](https://github.com/baptisteArno/typebot.io/files/15452846/Typebot.export.hdrwcrz.json)

Works fine on my end with that example.

Feel free to re-open with a reproducible example! 🙏
