### ISSUE TITLE
Bug with buttons

### ISSUE THREAD

**Issue by arthurbarret0** [baptisteArno/typebot.io#1540]
**What did I do?**

I created a form using buttons and did not make any customizations in the configuration of this form (I didn't even open the button block configuration) on the builder side.

**What happened?**

When I open the chat (user side), it appears blank and does not display the button block. Upon checking the console, it returns an error related to "isMultipleChoice" (or something like that, I don't remember exactly).

**How did I fix it?**

I open the block configuration, select and deselect the "Multiple choice" option.

**Comment by baptisteArno** [comment]
I can't reproduce the bug, can you provide a reproduction?

**Comment by arthurbarret0** [comment]
![typebot-bug1](https://github.com/baptisteArno/typebot.io/assets/54091091/8cd7c2c5-623a-4f32-9389-4b2edfc5397b)
![typebot-bug2](https://github.com/baptisteArno/typebot.io/assets/54091091/f3c4c1dd-e53a-401f-986e-fa8a5da02038)
![typebot-bug3](https://github.com/baptisteArno/typebot.io/assets/54091091/9de49107-527d-400b-b5e5-138433f8b90d)

Here's a screenshot of the console, widget and flow.

**Comment by baptisteArno** [comment]
Does it work in Test mode? If so, it is most likely an issue with your embed lib version being too old

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info

**Comment by Harizliewzw** [comment]
I had the exact same issue.

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/b0cec606-962c-4c5d-9302-98db7b5b8315" />

It works in Test mode, but gave the same error at the "Reiterate Course Choice" block :

> "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isMultipleChoice')"


I am using typebot 3.1.0.

I solved it by using the same method as OP.
