### ISSUE TITLE
Problem when typebot is activated by cell phone or mobile.

### ISSUE THREAD

**Issue by WaldaTzal** [baptisteArno/typebot.io#1546]
Problem when typebot is activated by cell phone or mobile.
When in a cell phone or mobile conversation the name of the conversation user is requested, the input field to add the name appears in the cell phone's footer so that it is not possible to view the field and therefore fill in the field to enter the name. This problem only occurs when the typebot is run on a cell phone or mobile phone.

Can you help with this solution?

**Comment by baptisteArno** [comment]
You are mostly talking about an issue with your Custom CSS or Custom code added to your bot. This is out of the project's scope 🙏
