### ISSUE TITLE
Facebook/Instagram messenger implementation 

### ISSUE THREAD

**Issue by shanky1712** [baptisteArno/typebot.io#1547]
@baptisteArn  Since I already wrote application but not in live for Facebook Messenger Conversations between your Facebook Business Page and Facebook users. I think we can plan for it and I can contribute on this. Here I added a video for facebook messenger implementation please let me know whether we can proceed and I can contribute on this.

https://youtu.be/j6w5gzxY0LA

**Comment by baptisteArno** [comment]
This would be a critical piece to implement. We are open to contributions but there is a good chance it won't fit the project's requirement. 🙏

**Comment by baptisteArno** [comment]
Duplicate #1588
