### ISSUE TITLE
Node 22 support

### ISSUE THREAD

**Issue by kuon** [baptisteArno/typebot.io#1554]
Node 22 is becoming the current version installed on more and more systems and at present typebot is not compatible with it due to the dependency on `isolated-vm` `4.7.2` which is not compatible with node 22. This has been fixed upstream in version `4.8.0` https://github.com/laverdet/isolated-vm/commit/1254a30af26cd5ce398e1b6ec4002551a8006a9d

**Comment by baptisteArno** [comment]
Thanks for reporting this!

**Comment by baptisteArno** [comment]
Had to revert because of this issue: https://github.com/laverdet/isolated-vm/issues/477
