### ISSUE TITLE
Add healthcheck API endpoints on all apps

### ISSUE THREAD

**Issue by Placidina** [baptisteArno/typebot.io#1555]
I'm creating a Helm Chart, to install on the Kubernetes cluster. However, I didn't find anything in the documentation/examples related to healthcheck for configuring Liveness, Readiness and Startup Probes.

**Comment by AndySchmitt** [comment]
Hi, is it possible to share the deployment yaml you did until now? I'm going the same direction of deploy typebot to k8s.

**Comment by Placidina** [comment]
> Hi, is it possible to share the deployment yaml you did until now? I'm going the same direction of deploy typebot to k8s.

Hi AndySchmitt,
But I need to check with the company I work for whether it will be public or private.
