### ISSUE TITLE
[BUG?] Does non-admin member create workspace?

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#1564]
[BUG?] I invited someone to my workspace as a member, but he can create his own workspace, was this behavior supposed to happen? I thought only admin could create

**Comment by baptisteArno** [comment]
Nope, that's how Typebot works, any user can create their own workspaces

**Comment by RuanMD** [comment]
> Nope, that's how Typebot works, any user can create their own workspaces

Oh I understand, I thought it was only for those who are admins. Is there any way to monitor the workspaces that are created? If I have an extra workspace, I want to delete it, so I don't ask for performance

**Comment by baptisteArno** [comment]
You are free to monitor your database table "Workspace" :)

**Comment by RuanMD** [comment]
> You are free to monitor your database table "Workspace" :)

Thank you very much Baptiste
