### ISSUE TITLE
Error! Could not reach server. Check your connection.

### ISSUE THREAD

**Issue by MiheretuTesh** [baptisteArno/typebot.io#1565]
![image](https://github.com/baptisteArno/typebot.io/assets/61537238/866fb0bd-9be6-43e2-869d-5583bb2ad415)

-- Deployed on vercel

**Comment by dallaccua** [comment]
Hi guys!

I have the same issue on TypeBot. I have tried to run the docker-compose logs command, but without sucess.

root@ZapSolutions:~# docker-compose logs
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

root@ZapSolutions:~#
root@ZapSolutions:~#
root@ZapSolutions:~#
root@ZapSolutions:~# docker-compose.yaml logs
docker-compose.yaml: command not found


I have checked, into the Portainer, in the ENV information and both URLs are set HTTPS. But https://botviewer.zapsolutions.com.br/chateaweb doesn't work.

**Comment by MehdiRazaNaqvi** [comment]
I also get this error when I click on '**Test**' when setting up with Docker. I am using latest docker images of builder as well as viewer. Also `docker-compose logs` gives no error. Any solution for this? 

Image attached for reference :
![image](https://github.com/user-attachments/assets/3567d8c2-3431-4035-a703-18e1d437dc39)

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info
