### ISSUE TITLE
Improve type error with nocodb integration

### ISSUE THREAD

**Issue by kuon** [baptisteArno/typebot.io#1568]
With the nocodb integration, if a string is inserted in a number column, the following error is produced:

```
{"msg":"insert into \"nc_ejwk___Réponses\" (\"ID_utilisateur\", \"created_at\", \"created_by\", \"updated_at\", \"updated_by\") values ($1, $2, $3, $4, $5) returning \"id\" as \"Id\" - invalid input syntax for type bigint: \"jgmd19s5u17aoy7r8syfvq3h\""}
```

I think this error should be catched and improved for non technical users.

**Comment by baptisteArno** [comment]
Hmmm, I'm not sure about this. It would be just too much work to try to "humanize" every messages from NocoDB. I feel like it should not be Typebot's job.

**Comment by kuon** [comment]
Maybe just parse the json and pretty print it? That would be a start.

--
Nicolas Goy
Developer & Engineer

https://kuon.ch
https://goyman.com
