### ISSUE TITLE
/bin/sh: 1: /app/builder-entrypoint.sh: not found

### ISSUE THREAD

**Issue by bruno-growthsales** [baptisteArno/typebot.io#1570]
Hi guys, after builder typebot image from my local pc from this recommendations:

**Step 1:** Build my own images with:

docker build -t typebot-builder --build-arg SCOPE=builder .
and
docker build -t typebot-viewer --build-arg SCOPE=viewer .

**Step 2:** docker push imagem to my docker hub

**Step 3:**  Execute stack in Docker Portainer 2.20.1 ( ubuntu 20.04 )

I receve this massage:
/bin/sh: 1: /app/builder-entrypoint.sh: not found

The same issue show local too!

Anyone, know what's the issue?

**Comment by bruno-growthsales** [comment]
![issue-typebot 2024-06-13 at 19 30 30](https://github.com/baptisteArno/typebot.io/assets/87706510/4f714bda-4bec-4c87-9cb9-2851663d2c01)

**Comment by kunal232i** [comment]
use this `dos2unix typebot.io/scripts/builder-entrypoint.sh`, must be Windows`CRLF` issue

ref: https://stackoverflow.com/a/67942312

**Comment by bruno-growthsales** [comment]
> dos2unix typebot.io/scripts/builder-entrypoint.sh

thank you @kunal232i

**Comment by bruno-growthsales** [comment]
> Hi guys, after builder typebot image from my local pc from this recommendations:
> 
> **Step 1:** Build my own images with:
> 
> docker build -t typebot-builder --build-arg SCOPE=builder . and docker build -t typebot-viewer --build-arg SCOPE=viewer .
> 
> **Step 2:** docker push imagem to my docker hub
> 
> **Step 3:** Execute stack in Docker Portainer 2.20.1 ( ubuntu 20.04 )
> 
> I receve this massage: /bin/sh: 1: /app/builder-entrypoint.sh: not found
> 
> The same issue show local too!
> 
> Anyone, know what's the issue?
