### ISSUE TITLE
Cant capture another interactive type message for whatsapp 

### ISSUE THREAD

**Issue by trigidigital** [baptisteArno/typebot.io#1574]
Hi, I’ve tried to capture variables with the button ID in the input block and it worked, but why doesn’t it apply to other types of interactive WhatsApp messages such as:
- WhatsApp Flow
- List Message
- Order Message

It seems that typebot only captures the reply_button parameter from WhatsApp type message, is there a possibility to add another whatsapp interactive message so we can capture it?

The type of interactive message you want to send. Supported values:
button: Use for Reply Buttons.
catalog_message: Use for Catalog Messages.
list: Use for List Messages.
product: Use for Single-Product Messages.
product_list: Use for Multi-Product Messages.
flow: Use for Flows Messages.

docs: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#interactive-object

**Comment by baptisteArno** [comment]
I don't understand, Typebot does not support WhatsApp Flow, List Message, Order Message. So what are you talking about?

**Comment by baptisteArno** [comment]
#1317
