### ISSUE TITLE
Add Pexels videos option to media popover

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1575]

**Comment by basuabhirup** [comment]
@baptisteArno I think this task is achievable using Pexels API to properly extract the video file and place it inside the video bubble. Pexels team provide free unlimited API usage if certain conditions are met: https://help.pexels.com/hc/en-us/articles/900005852323-How-do-I-get-unlimited-requests

I believe the Typebot application meets all the above criteria. Please let me know shall I proceed with this task with my own Pexel API_KEYS for the time being, and then replace it with your API_KEY and contact the Pexels team to provide unlimited access before merging & deploying it.

Pexels API to get a particular video: https://www.pexels.com/api/documentation/#videos-show

**Comment by baptisteArno** [comment]
That would be great, thank you so much!

Basically this feature should be equivalent to what we did with Unsplash for the Image picker.

I'm available if you need more info!
