### ISSUE TITLE
Disable new accounts being created

### ISSUE THREAD

**Issue by chknus** [baptisteArno/typebot.io#158]
Hi all,

I have pulled the latest typebot using docker.  It hasn't updated the version number in the 'Settings and Members' area.  Is this normal?

Also could anyone explain the best way to disable new account creation?

Cheers 👋

**Comment by baptisteArno** [comment]
Hi friend,

Indeed, I totally forgot to update the version number here 😂

It should work from v2.8.5.

To disable new signups, simply set the `DISABLE_SIGNUP ` env variable to `true` (more info: https://docs.typebot.io/self-hosting/configuration/builder#general)

**Comment by agemaranhado** [comment]
How can I remove access to - workspaces that have been created - the option for them to create other workspaces? I'd like to make just one workspace the (parent) workspace. Or disable workspace creation manually and only make it possible via the API / database.
