### ISSUE TITLE
Video block not working with Youtube clips and timestamped video

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1589]

**Comment by Anonymous961** [comment]
@baptisteArno Can you please share steps to reproduce this. I've tried putting a yt video link on video block and it's working. 
![image](https://github.com/baptisteArno/typebot.io/assets/96728156/213d869a-8c33-41e8-a598-76c989d36d44)

**Comment by thatguynef** [comment]
@Anonymous961 here's a screen recording of how I reproduced the issue: https://neferlopez.dubb.com/v/EQGkpp

Hope it's helpful.

**Comment by baptisteArno** [comment]
Hey @thatguynef. This will be an impossible one to achieve as the URL is totally different. You will need to select the embed option and paste the code content in a Embed bubble:

![CleanShot 2024-06-24 at 11 59 06@2x](https://github.com/baptisteArno/typebot.io/assets/16015833/5f566bb6-1209-450b-ba3c-235871181761)
