### ISSUE TITLE
Invalid line breaks for variables at the start of a text bubble

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1594]
![CleanShot 2024-06-19 at 08 55 06@2x](https://github.com/baptisteArno/typebot.io/assets/16015833/c44c05c4-e300-4ff1-91ef-6b89c5f90935)

**Comment by juniorbra** [comment]
Hi @baptisteArno I am facing the same problem... 
![image](https://github.com/baptisteArno/typebot.io/assets/56737502/8e91f460-683c-4f32-a7b1-4460f7a36b0b)
