### ISSUE TITLE
Change in API Keys needs to be reflected everywhere.

### ISSUE THREAD

**Issue by rohanatdehaat** [baptisteArno/typebot.io#1601]
I have exceeded my current qouta of chatgpt. Now the problem is that, I do not wanna add credits to the current email account I'm using. Now when I add credits to a different email account, it changes the API Key. Is there a way we can change it in all the blocks that I have used by changing it only once? I have a lot of blocks I'm using, I'll need to manually change API Keys everywhere. I would like to have a quicker way of doing it.

**Comment by baptisteArno** [comment]
No way to do that for now. Will be implemented this week. (#1567)
