### ISSUE TITLE
Api method publish doesn't work as expected

### ISSUE THREAD

**Issue by mzhirnov1** [baptisteArno/typebot.io#1603]
Hello! API method "Publish" doesn't publish a bot. Curl return "success" but bot is "404 The bot you're looking for doesn't exist" But if I press button "Publish" in admin panel - bot will start work. curl --request POST \
  --url https://typebot.yodo.im/api/v1/typebots/clxj1s9fj01izz3n3k99jsvtk/publish \
  --header 'Authorization: Bearer <API key>' \
  --header 'Content-Type: application/json' \
  -v
*   Trying 135.181.249.251:443...
* Connected to typebot.yodo.im (135.181.249.251) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=typebot.yodo.im
*  start date: May  9 11:59:01 2024 GMT
*  expire date: Aug  7 11:59:00 2024 GMT
*  subjectAltName: host "typebot.yodo.im" matched cert's "typebot.yodo.im"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> POST /api/v1/typebots/clxj1s9fj01izz3n3k99jsvtk/publish HTTP/1.1
> Host: typebot.yodo.im
> User-Agent: curl/7.81.0
> Accept: */*
> Authorization: Bearer pw8M8xc0K1FCiSC7F1Y2kVnF
> Content-Type: application/json
> 
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.24.0 (Ubuntu)
< Date: Sat, 22 Jun 2024 05:22:15 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Frame-Options: SAMEORIGIN
< Vary: Origin, Accept-Encoding
< 
* Connection #0 to host typebot.yodo.im left intact
{"message":"success"} 
[typebot-export-templatebot-99jsvtk.json](https://github.com/user-attachments/files/15935406/typebot-export-templatebot-99jsvtk.json)

**Comment by mzhirnov1** [comment]
any news about that?

**Comment by baptisteArno** [comment]
Because your typebot is probably missing a `publicId` field?
