### ISSUE TITLE
500 internal server error in localhost

### ISSUE THREAD

**Issue by asimovc** [baptisteArno/typebot.io#1607]
I installed typebot in docker for my localhost test and i getting 500 internal Server Error everytime.

Here the [docker-compose.yml](https://0x0.st/XmXj.yml) and [.env](https://0x0.st/XmX2.txt) that i'm using.

**Comment by baptisteArno** [comment]
For local installation, follow this guide: https://docs.typebot.io/contribute/guides/local-installation
