### ISSUE TITLE
wizard forms

### ISSUE THREAD

**Issue by AshishBhalsod** [baptisteArno/typebot.io#1617]
hello

wizard form not possible or addtionally possible osmething like

i need wizard form as  firnstmae lastname emial  password  birthdate etc etc and then last time next  button on submit and then next wizard form apear this way how possible anyone can helpme plz ?

**Comment by baptisteArno** [comment]
I don't understand, can you provide more context? What are you trying to achieve?

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info
