### ISSUE TITLE
Typebot post methood not allow 405, using AWS S3.

### ISSUE THREAD

**Issue by giovannisc** [baptisteArno/typebot.io#1626]
Hi, my issue is very simple, when I try to upload a file to AWS S3 Bucket with typebot, I receive error "POST method not allow 405". This happens because AWS S3 Bucket uses PUT method to upload files.

There is some workaround to this, without change s3 lib?

**Comment by giovannisc** [comment]
> Have you configured your bucket policies in AWS?

Yes, like documentation, https://docs.typebot.io/self-hosting/guides/s3
I try to do something like that too: https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html

But nothing works with AWS S3.

**Comment by Deyvi-dev** [comment]
It's strange that it's working perfectly, check your policy settings once again and take a look at this article https://zaccharles.medium.com/s3-uploads-proxies-vs-presigned-urls-vs-presigned-posts-9661e2b37932

**Comment by giovannisc** [comment]
Hi Deyvi, yes I've already found this tutorial on internet. Have you try deploy recently and works fine?

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info
