### ISSUE TITLE
Ability to use sessionID as variable

### ISSUE THREAD

**Issue by JoeyHoutenbos** [baptisteArno/typebot.io#1634]
Hi,

I noticed the Start chat API endpoint (https://docs.typebot.io/api-reference/chat/start-chat) returns a SessionID. This endpoint is always being called by Typebot, but there's no option to set this variable in the flow builder.

Why is this not there?
The resultID is available, so I would expect we can do exactly the same for the sessionID right?

I need the sessionID so I can post a message to the chat at any time I want. But to do this, I need to be able to get the variable from my webhook endpoint.

Thanks.

**Comment by baptisteArno** [comment]
I don't understand what you are trying to achieve, can you provide more details?

**Comment by JoeyHoutenbos** [comment]
@baptisteArno thanks for your reply.

I want to pass the SessionID of a chat to a webhook that I created. To do this I want to set a variable in my flow, but this is not available in the dropdown:
![image](https://github.com/user-attachments/assets/c96e5ed4-205b-43c7-8387-2c94419e9f44)

Why isn't that variable available?

Or maybe there's another way to pass the SessionID of a specific chat to the webhook? I am using the "HTTP Request" integration to call my webhook.

**Comment by baptisteArno** [comment]
Can you tell me why you'd need the session ID here? It's an internal ID, there is no point in passing it to a webhook

**Comment by baptisteArno** [comment]
Why would you want that? You are already chatting with the bot, afaik I don't see the point of having another runtime continuing the bot (in your case the webhook)

**Comment by JoeyHoutenbos** [comment]
The flow calls my endpoint and waits for a reply. But the HTTP Request integration only allows a timeout for up to 120 seconds. The endpoint might take 3 minutes to formulate an answer. But this answer cannot be sent to the chat, because it's not waiting anymore.

Another is that the endpoint might run into an error. This error triggers something, which might want to sent a message to the chat as well.

There are a lot of scenario thinkable why you'd want to be able to post to the chat. That's why it's supported by the API I guess.
I only need to be able to get this SessionID to my backend, so I can do whatever I want with it.

**Comment by baptisteArno** [comment]
But do you understand that if your webhook continues the chat, then it won't be reflected on the web chat?

Your webhook can't display things on the web chat, `continueChat` is only continuing the chat via an API.

**Comment by JoeyHoutenbos** [comment]
Hi @baptisteArno ,

I tested this before I created this issue and the message that I sent showed up in the web chat. At least I am pretty sure, but I started to doubt myself now.

I just tested it again, and indeed it doesn't show up in the web chat. Is there any way we can make this work?

At the moment I'm looking for any help on this. If you see any solutions, then I might make a pull request for the feature.

**Comment by baptisteArno** [comment]
You will need this: https://github.com/baptisteArno/typebot.io/issues/1531

**Comment by lucasvdutra** [comment]
Trying a different approach to help better understand this necessity.

We need to integrate with Chatwoot via API, we need to send a message to Chatwoot and have Chatwoot send a message back to Typebot.

This way we can interact with agents via Typebot, allowing communication using any channel, WhatsApp, Web, Instagram, etc., without depending on the Chatwoot widget.
