### ISSUE TITLE
[Feature request] Ability to disable a block in a group

### ISSUE THREAD

**Issue by asty8926** [baptisteArno/typebot.io#1637]
It would be very useful to be able to temporarily disable a block in a group, so that the flow execution skips it.
It might come in especially handy when the flow becomes quite big and instead of moving the block to an entire new group and link them back together, or instead of adding the block and deleting it later,   disabling it as an on/off switch would be useful.

For instance, we might want to quickly and temporarily disable an HTTP request block in order to prevent it from "consuming" a request (especially for paid APIs like OpenAI) while still keeping it in the flow and in its same location.

UI wise, a clickable 👁️ icon would fit. The eye icon would be crossed out, and the block would be greyed out, when the block is disabled.

Hopefully this feature has not already been suggested, although I checked the Projects page and other issues.

What do you think? n8n has it and it's a bless.

**Comment by baptisteArno** [comment]
I don't know, I don't really see the point of this. Why don't you just temporarily moving out the block from your group?

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info
