### ISSUE TITLE
error when installing typebot  on railway

### ISSUE THREAD

**Issue by Deyvi-dev** [baptisteArno/typebot.io#1642]
**I'm having this error when installing typebot**

![image](https://github.com/user-attachments/assets/a5a8c155-e8b5-471e-9693-ca122537db9e)

**Comment by baptisteArno** [comment]
Hey,

I'm having a hard time reproducing / understanding the issue. 

Can you clearly describe it by following this template:

1. Steps to reproduce
2. What's happening
3. What were you expecting

It's even better if you can provide a screen recording.

**Comment by Deyvi-dev** [comment]
**1. Steps to Reproduce**

1. Fork the repository.
2. Add two services on Railway: one for the database and another for Typebot.
3. Add the environment variables.
4. Change the root directory to: `apps/builder`.
5. Change the build command to:
   ```sh
   cd ../.. && pnpm turbo build --filter=builder... && pnpm db:migrate
   ```

**2. What's Happening**

Error during build.

![image](https://github.com/user-attachments/assets/131d03e1-cf7c-4223-93e7-1569a71500c1)


**3. What Were You Expecting**

Successful deployment.

**Comment by baptisteArno** [comment]
It seems it is executed with `npm` in your screenshot. Make sure that it uses `pnpm` instead.

**Comment by Deyvi-dev** [comment]
@baptisteArno Do you know how I can define it?
