### ISSUE TITLE
Prefilled variables not working when `isOnlyRegistering` is set to true

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1646]

**Comment by devlikepro** [comment]
Hi! I see it has been closed as `not planned`
Does it mean we can't use `isOnlyRegistering` and `prefilledVariables` at the same time? Because yeah, it looks like it doesn't work :cry: 

There's "123" in the messages:
```bash
curl -X POST -H "Content-Type: application/json" \
    -d '{ "textBubbleContentFormat": "markdown", "prefilledVariables": {"from": "123"}}' \
    https://typebot.example.com/api/v1/typebots/name-123/startChat
```

There's no "123" in the messages
```bash
curl -X POST -H "Content-Type: application/json" \
    -d '{ "textBubbleContentFormat": "markdown", "prefilledVariables": {"from": "123"}, "isOnlyRegistering": true }' \
    https://typebot.example.com/api/v1/typebots/name-123/startChat


curl -X POST -H "Content-Type: application/json" \
    -d '{ "message": "text", "textBubbleContentFormat": "markdown" }' \
    https://typebot.example.com/api/v1/sessions/123/continueChat
```

**Comment by baptisteArno** [comment]
Why do you use isOnlyRegistering?

**Comment by devlikepro** [comment]
Hi! 
We're building n8n integration for one project, and it's simpler there to register first and then to actually `/continueChat`, so we can have logic separated steps for "creating a session" and "send text"
https://waha-n8n-templates.devlike.pro/whatsapp-typebot/

Yeah, ideally we could use `/startChat` just the same way as `continueChat`, if we'd use normal code-approach, but with n8n it's a bit hard to reuse parts :) 

Just based on API description and how `isOnlyRegistering`register a session without first message, it should save all variables as well.
If it's not what API is for - that's fine, we can check how we can process messages from `/startChat` in parallel with `continueChat`

**Comment by devlikepro** [comment]
wow, that was fast!  :clap: 
thank you, waiting it in npm/docker! :rocket:
