### ISSUE TITLE
where can I find the list of allowed origins

### ISSUE THREAD

**Issue by Jean1dev** [baptisteArno/typebot.io#1648]
![image](https://github.com/user-attachments/assets/eefcc8bc-1adb-4df3-bb5b-f62d96f09b69)

I've been reading that part of the documentation and looking through the code, but I couldn't find the configuration file where I can add that list. It's a bit confusing. I would like to know where it is located, so I can update the documentation afterwards.

**Comment by baptisteArno** [comment]
It's a section in the Settings tab
![CleanShot 2024-07-18 at 16 20 17@2x](https://github.com/user-attachments/assets/7876aefc-b5db-4fd5-bd04-19ee3a77fd17)
