### ISSUE TITLE
Clicking on an old button in WhatsApp should navigate to that node. 

### ISSUE THREAD

**Issue by SweetJenna** [baptisteArno/typebot.io#1657]
If someone clicks on an old button in WhatsApp, it should navigate there. 

Users always want to explore the bot thoroughly, and it's so much easier to just click on an old button. 

Users regularly do this, and there's no way I'm able to handle this. 

If they click on an old button, they should be navigated to that part of the graph node.

**Comment by baptisteArno** [comment]
What do you mean by old button? Can you illustrate?

**Comment by avyaggarwal** [comment]
Let's say the conversation is as follows. Square brackets demote comma separated buttons:

User: Hi 
Bot: hellow, what can I help you with [Track Order, Place Order]
User:clicks on [track order]
Bot: please enter your order id to track
User:  clicks on [place order] <!note this is the initial button from the bot message>
Bot: oh no, wrong order id. Please choose again 

This shows a broken bot flow. It should ideally pick the first node button, place order, after the user clicked on it.

**Comment by baptisteArno** [comment]
Thanks for the details!

Unfortunately this is not how Typebot engine works. It always moves forward. So we can't enable that behavior. I understand that it might be useful to use it as a sort of menu. But Typebot is not design to work like this.
