### ISSUE TITLE
Allow Custom OpenAI API Endpoint Configuration

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1665]
Hi,

I'm using a relay proxy to connect to OpenAI, such as myopenai.com/xxx, instead of the official endpoint https://api.openai.com/v1/chat/completions.

Is it possible to customize the OpenAI API endpoint in the environment variables or configuration settings?

Thank you!

**Comment by baptisteArno** [comment]
Yes we could use the field `baseURL` (https://sdk.vercel.ai/providers/ai-sdk-providers/openai#provider-instance)

**Comment by ZimaBlueee** [comment]
@baptisteArno hey，

Hello, could you please tell me where the baseURL field is configured?

I mean, how to change the endpoint for this OpenAI component? I don't see a place to enter a URL in this OpenAI component.
![image](https://github.com/user-attachments/assets/3f1f0616-a5df-4b54-814b-bf6db4684ae6)
![image](https://github.com/user-attachments/assets/a24a07b4-80fe-4131-a79d-6a339bdb2c6a)

**Comment by baptisteArno** [comment]
It's not implemented yet. Using this issue to track the progress

**Comment by ZimaBlueee** [comment]
@baptisteArno 
Thank you very much for your support. Many people use ChatGPT 4's proxy interface

**Comment by 185cm** [comment]
Hey! @baptisteArno

This issue is really useful. When will it be released? 

Best wishes.

**Comment by mynamexyz** [comment]
+1

**Comment by damos2020** [comment]
we need it!!!!!!!!!!!!!!

**Comment by Falcon7382** [comment]
Would also love to see this as an addition!

**Comment by ZimaBlueee** [comment]
Hi!@baptisteArno 

This issue is really popular because it is really important. Will it be launched soon?

Best regards.

**Comment by ZimaBlueee** [comment]
Hi! @baptisteArno

You are awesome!!! When will the docker version including this update be released?

Best regards.

**Comment by baptisteArno** [comment]
1st of Sept 👌
