### ISSUE TITLE
Moment of the Day Conditional Branch Always Defaults to Else

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1666]
Hi,

![图片](https://github.com/user-attachments/assets/28bb7b01-2796-473e-850f-1ee7968e1a9b)

As shown in the attached image, I've followed the [documentation](https://docs.typebot.io/editor/blocks/logic/set-variable#moment-of-the-day) to set up the Moment of the Day, but the conditional branch always defaults to the Else branch, no matter how many times I try.

![图片](https://github.com/user-attachments/assets/6b044697-9c0e-42dd-adfc-da308a71fd85)

On the result page, the Moment variable has a value.

Could you please help me resolve this issue?

Thank you!

**Comment by baptisteArno** [comment]
Hey,

Can you clearly describe it by following this template:

1. Steps to reproduce
2. What's happening
3. What were you expecting

It's even better if you can provide a screen recording.

This ultimately allow me to reproduce the bug so that I can fix it properly.

**Comment by ZimaBlueee** [comment]
@baptisteArno Hi

## Steps to reproduce:

1. Set a variable using Moment of the Day as per the documentation.
2. The documentation states that the variable can only have one of the four possible values: morning, afternoon, evening, or night.
3. Use an if statement to check for all four possible values.

## What's happening:
No matter how I test the variable, the execution always goes to the else branch, which shouldn't be the case.

## What were you expecting:
I expected that the if statements would correctly match one of the four defined values (morning, afternoon, evening, night) and not fall into the else branch.

**Comment by baptisteArno** [comment]
I can't reproduce:

![CleanShot 2024-07-29 at 14 00 50@2x](https://github.com/user-attachments/assets/d528e55e-06c4-41bb-8e13-107ef3465389)

**Comment by baptisteArno** [comment]
Your second condition is missing an operator.

Here is an example with multi comparison: [Moment typebot export.json](https://github.com/user-attachments/files/16414973/Moment.typebot.export.json)

**Comment by baptisteArno** [comment]
You are adding a comparison that will always return false since it is empty. So it is expected.
