### ISSUE TITLE
Typebot bubbles cannot parse Markdown

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1667]
![图片](https://github.com/user-attachments/assets/592f482b-e536-4025-ae3b-0e33ac8bb47e)

What is the correct way to parse it? I want to display a table.

Or is there any other way to display a table besides markdown?

**Comment by baptisteArno** [comment]
It will only parse it if it comes from a variable. Otherwise you should use the text editor buttons:

![CleanShot 2024-07-29 at 11 03 41@2x](https://github.com/user-attachments/assets/40ffd21f-a26e-456f-80df-bebbb34e4e1c)
