### ISSUE TITLE
The width of the chat bubble cannot be set larger

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1668]
Hi,

As shown in the attached image, I've integrated Typebot into my project using HTML and JavaScript in bubble form. However, I've noticed that the width of the chat bubble cannot be set larger.

I adjusted the width in CSS, but found that the maximum width has an upper limit, and I can't break this limit. No matter how large the width is, it is still the default value.
```
<style>
typebot-bubble::part(bot) {
  width: 9000px;
}
</style>
```

How can I configure this?

![图片](https://github.com/user-attachments/assets/b56a1e1a-fd76-45ee-b781-14d777379bcd)

Here is the code I used to integrate Typebot into my project:

![图片](https://github.com/user-attachments/assets/a323b205-94bd-4df8-9559-c32d2c85dec7)

thanks!

**Comment by ZimaBlueee** [comment]
I tried adjusting the width here, but this should refer to the container and will not change the width of the entire chat box

![图片](https://github.com/user-attachments/assets/8c25c2ce-5a48-4951-a3b4-f558290df945)

**Comment by ZimaBlueee** [comment]
I adjusted the width in CSS, but found that the maximum width has an upper limit, and I can't break this limit. No matter how large the width is, it is still the default value.

```
<style>
typebot-bubble::part(bot) {
  height: calc(100% - 140px);
  width: 90000px;
}
</style>
```

**Comment by ZimaBlueee** [comment]
The height cannot be adjusted any higher

**Comment by baptisteArno** [comment]
Here is an example:

```js
<script type="module">
  import Typebot from 'https://cdn.jsdelivr.net/npm/@typebot.io/js@0.3/dist/web.js'

  Typebot.initBubble({
    typebot: 'my-typebot',
    theme: {
      chatWindow: { maxWidth: '100%' },
    },
  })
</script>

```
