### ISSUE TITLE
Add support for dragging bubble

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1670]
Hi!

When the information on the web page is very dense, the bubble will block part of the content no matter where it is placed. Can the bubble support dragging and moving?

thanks!

**Comment by baptisteArno** [comment]
Can you provide a screenshot that shows the readability issue?

**Comment by ZimaBlueee** [comment]
![图片](https://github.com/user-attachments/assets/0646e1d8-97a6-4883-a4f6-94d027363318)
This is my website. The button is already in the corner, but it still covers part of the content, so I hope the bubble can support dragging.

In addition, there is another method, which is to allow the bubble to be attached to the edge of the screen by default, and the complete bubble will be displayed when the mouse is hovered. This method will not cover the content of the web page.

Best wishes.

**Comment by baptisteArno** [comment]
This is not something I'd like to implement as I find this not intuitive. I suggest you add your own code that hides/shows the bubble based on mouse position 👍

**Comment by ZimaBlueee** [comment]
hello! @baptisteArno 

Can you reconsider this requirement? This is really important. The current bubble button is fixed in position and will definitely block the content of the website. Supporting draggable is the best way.

This is the pr of Dify's bubble drag solution. The code inside is for your reference: https://github.com/langgenius/dify/pull/5781
