### ISSUE TITLE
Facing embedding issue with the React library

### ISSUE THREAD

**Issue by Testuser1284** [baptisteArno/typebot.io#1673]
Hi,
I'm trying to add custom icons and styles across all messages directly on the source code. I have built it and then I can view the custom class names in the web.js file under dist. I am deploying the app on Docker using newly generated images. The custom changes are visible in the viewer page/URL and when embedded using an iframe. But when I try to embed it using React's Bubble component, I can no longer see the custom class names and styles. 

Thank you.

**Comment by baptisteArno** [comment]
Hey,

Can you clearly describe it by following this template:

1. Steps to reproduce
2. What's happening
3. What were you expecting

It's even better if you can provide a screen recording.

This ultimately allow me to reproduce the bug so that I can fix it properly.

**Comment by 1stdevfriend** [comment]
Hey hi i'm having same issue with self hosting

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info
