### ISSUE TITLE
Bot viewer using http:// but every think it's on and set to https://

### ISSUE THREAD

**Issue by kotasdev** [baptisteArno/typebot.io#1676]
Hi,

Im  hosting typebot behind Cloudflare (proxy enabled) and nginx (reverse proxy), Every think its working fine, but when i published a bot, viewer its trying to consume API by http, I rly don't understand why, every place I set https references, can some one help me?

**Viewer console browser Error**
892.55174397733be1ff.js:1 
 Mixed Content: The page at 'https://mari.kotas.plus/patrisio-teste' was loaded over HTTPS, but requested an insecure resource 'http://mari.kotas.plus/api/v1/typebots/patrisio-teste/startChat'. This request has been blocked; the content must be served over HTTPS.
![image](https://github.com/user-attachments/assets/7ff3c429-dc7b-4e1c-a096-b67baa71cf54)
![image](https://github.com/user-attachments/assets/d72b1932-3b90-4aa9-930e-3f81ea336712)

**.env**

ENCRYPTION_SECRET=XXXXXXX
DATABASE_URL=XXXX
NODE_OPTIONS=--no-node-snapshot
DEBUG=true
DISABLE_SIGNUP=false
NEXTAUTH_URL=https://typebot.kotas.plus
NEXT_PUBLIC_VIEWER_URL=https://mari.kotas.plus
NEXT_PUBLIC_CHAT_API_URL=https://mari.kotas.plus
NEXTAUTH_URL_INTERNAL=http://typebot-builder:8080 # Docker internal name
ADMIN_EMAIL=xxx@kotas.com.br

SMTP_USERNAME=xxx
SMTP_PASSWORD=xxx
SMTP_HOST=email-smtp.us-east-2.amazonaws.com
SMTP_PORT=587
SMTP_SECURE=true
SMTP_AUTH_DISABLED=false
NEXT_PUBLIC_SMTP_FROM=xxx

**Comment by baptisteArno** [comment]
I don't think it has something to do with Typebot though! It is Cloudflare specific issue 🙏

**Comment by abordin** [comment]
I have the same Issue. despite having configured https correctly, when the viewer tries to access the bot, the access address within the json comes as http, and the browser tries to access via http
![Seleção_238](https://github.com/user-attachments/assets/69a571b8-f179-4b73-ae23-fd06cb3e0efc)
![Seleção_239](https://github.com/user-attachments/assets/e8a6957c-5b39-4fb8-8f26-3454892fbf52)
![Seleção_240](https://github.com/user-attachments/assets/dffd9020-feea-4b7d-929e-31510e7763d1)
![Seleção_241](https://github.com/user-attachments/assets/5bb399cc-d402-47d1-a4b4-1bf207712f20)
![Seleção_242](https://github.com/user-attachments/assets/fb049e0f-764c-4c65-9d50-c175cfba6309)

**Comment by tech62** [comment]
I've actually the same problem with Haproxy, i've set `http-request add-header X-Forwarded-Proto https if { ssl_fc }` in my reverse configuration and it works !
