### ISSUE TITLE
Viewer not using correct paramenters - Using HTTP and not the link in .env 

### ISSUE THREAD

**Issue by abordin** [baptisteArno/typebot.io#1680]
I have the same Issue. despite having configured https correctly, when the viewer tries to access the bot, the access address within the json comes as http, and the browser tries to access via http
![Seleção_238](https://github.com/user-attachments/assets/69a571b8-f179-4b73-ae23-fd06cb3e0efc)
![Seleção_239](https://github.com/user-attachments/assets/e8a6957c-5b39-4fb8-8f26-3454892fbf52)
![Seleção_240](https://github.com/user-attachments/assets/dffd9020-feea-4b7d-929e-31510e7763d1)
![Seleção_241](https://github.com/user-attachments/assets/5bb399cc-d402-47d1-a4b4-1bf207712f20)
![Seleção_242](https://github.com/user-attachments/assets/fb049e0f-764c-4c65-9d50-c175cfba6309)

**Comment by abordin** [comment]
after dowgrade to verson v2.26.1 it works !

**Comment by baptisteArno** [comment]
Indeed! Make sure your reverse proxy config has this set up:

	 proxy_set_header X-Forwarded-Proto $scheme;
