### ISSUE TITLE
setVarible undefinied

### ISSUE THREAD

**Issue by GregMartela** [baptisteArno/typebot.io#1687]
setVariable function into script block returning undefinied error on 2.27.0

Works perfect in 2.24.0, when downgraded

**Comment by GregMartela** [comment]
1. I will take a time to reproduce
2. I get an error that says "setVariable() function is not definied"
3. I was expecting to update the value of a variable using the mentioned function into the script block

**Comment by baptisteArno** [comment]
Please provide a reproduction

**Comment by baptisteArno** [comment]
Closing. Feel free to re-open if you have more info

**Comment by MicaelHernandes** [comment]
The error occurs because the script is executed in client mode.
In this mode, setVariable is not available.
