### ISSUE TITLE
ELIFECYCLE Command Failed when running the install command

### ISSUE THREAD

**Issue by LucasGorgal** [baptisteArno/typebot.io#169]
When running the install command from pnpm, it results in error **ELIFECYCLE Command Failed**

Log:

> root@server:~/typebot.io$ pnpm i
> Scope: all 15 workspace projects
> Lockfile is up to date, resolution step is skipped
> Packages: +2096
> ++++++++++++
> Progress: resolved 2096, reused 2048, downloaded 0, added 0, done
> node_modules/.pnpm/@prisma+engines@4.6.1/node_modules/@prisma/engines: Running postinstall script...
>  ELIFECYCLE  Command failed.

The machine I am running is a Ubuntu 22.04.1 LTS, on a Google Cloud Compute Engine e2-micro machine, Intel Broadwell CPU.

**Comment by LucasGorgal** [comment]
Tested on another machine with 16GB RAM and 8 vCPU core, with a fresh Ubuntu 20.04.1 install and got the same results

**Comment by LucasGorgal** [comment]
Issue resolved by installing nodejs before running the command.

It may sound obvious, but I expected pnpm to check whetever node was installed. I suggest adding an initial step to install nodejs.

**Comment by baptisteArno** [comment]
Hi @LucasGorgal, so you had `pnpm` installed without `node`? The error is weird indeed.

**Comment by LucasGorgal** [comment]
Yes, that is right

Em sáb., 19 de nov. de 2022 às 07:58, Baptiste Arnaud <
***@***.***> escreveu:

**Comment by baptisteArno** [comment]
Ok, I won't add the instruction to install node first because it's pretty rare to have pnpm installed without node.

Thank you very much for the information though! 🙏
