### ISSUE TITLE
Location Service

### ISSUE THREAD

**Issue by Tint0ri** [baptisteArno/typebot.io#1690]
Is it possible to add a location service widget? It will get location and save the location information into a variable automatically.

**Comment by baptisteArno** [comment]
You can do this with Set variable block: https://docs.typebot.io/editor/blocks/logic/set-variable#get-users-geo-location

**Comment by Tint0ri** [comment]
According to my understanding,  only client broswer script is supported, it cannot be done through API endpoint.
