### ISSUE TITLE
Port is ignored for viewer URL

### ISSUE THREAD

**Issue by kuon** [baptisteArno/typebot.io#1696]
I am running the viewer in a staging environment where it runs on a non standard port (not 443).

I have `NEXT_PUBLIC_VIEWER_URL` and `NEXT_PUBLIC_CHAT_API_URL` set to the full host with port number.

The preview works in the builder, but when I open the viewer, it tries to do the `startChat` API call on the URL without the port number.

So, if I have this:

```
NEXT_PUBLIC_VIEWER_URL=https://dev.xxx.ch:10006
NEXT_PUBLIC_CHAT_API_URL=https://dev.xxx.ch:10006
```
It will do this call:

`https://dev.xxx.ch/api/v1/typebots/my-typebot-bpkjj7k/startChat`

Which fails.

It seems that this is due to this line which does not put a port number:

https://github.com/baptisteArno/typebot.io/blob/d49e006df08283a7ada7853e15566e1019fe8026/apps/viewer/src/pages/%5B%5B...publicId%5D%5D.tsx#L81

(also second occurence a few lines below)

If I fix with ``` url: `${protocol}://${forwardedHost ?? host}:10006${pathname}`, ``` it works properly.

**Comment by baptisteArno** [comment]
Can you share your reverse proxy settings?

**Comment by kuon** [comment]
Digging a bit into it, it seems that the problem is that `X-Forwarded-Host` does not include the port number, while `Host` does.

The problem is that the `X-Forwarded-Host` header is not standard. And because [heroku is using separated][1] `Host` and `Port` many application and frameworks expect it this way. [Amazon][2] also uses it.

After searching behavior of this in different projects, it seems that implementations look at `X-Forwarded-Host` and if it does not include a port number, then look for `X-Forwarded-Port`. Which means the port in the host header has precedence over the port in the port header.

[1]: https://devcenter.heroku.com/articles/http-routing#heroku-headers
[2]: https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/x-forwarded-headers.html#x-forwarded-port

**Comment by kuon** [comment]
Digging some more into it, there is a new `Forwarded` header which should take precedence over all the other ones.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded

In this header, the host does contain the port number.

So if the code is to be as portable as possible, it should do:

- Create a dictionary of `for` `host` `port` `scheme` `by` (`by` can be ignored in most cases)
- Check the `Forwarded` header, extract `for` `host` `port` `scheme` 
- If `for` is null, check `X-Forwarded-for` 
- If `scheme` is null, check `X-Forwarded-proto` 
- If `scheme` is null default to `https`
- If `host` is null, check `X-forwarded-host`
- If `host` is null, check `Host`
- If `port` is null, check `X-forwarded-host` for a port number
- If `port` is null, check `X-forwarded-port` for a port number
- If `port` is null, check `Host` for a port number
- If `port` is null, default to `scheme` port

**Comment by baptisteArno** [comment]
Thanks for the info!!
