### ISSUE TITLE
Logins are broken

### ISSUE THREAD

**Issue by JustinBack** [baptisteArno/typebot.io#170]
I just upgraded to 2.8.5 and I am unable to login even when `DISABLE_SIGNUPS` is set to false.

I suspect 570a780db1dd204c7d473f8f6c87f6ea8d789dcd causes this issue.
![EC3D5A97-5EDC-4897-BE48-18BCD6FEFE2F](https://user-images.githubusercontent.com/40178814/202873602-ccffe423-a708-445d-9768-36e1291fe0ac.jpeg)

I have checked the accounts table in case a migration caused data truncation but all original data is still there.

Logs dont show anything.

**Comment by baptisteArno** [comment]
Hey, it's a typo! The env name should be `DISABLE_SIGNUP` not `DISABLE_SIGNUPS`

**Comment by JustinBack** [comment]
Interesting has this been changed? It's worked in previous releases

**Comment by baptisteArno** [comment]
That's what I thought to, so I checked the history, but it has always been `DISABLE_SIGNUP` it seems 😅

I'll close this issue, feel free to re-open if you still have an issue 👌
