### ISSUE TITLE
error with use keycloak

### ISSUE THREAD

**Issue by amirmdehghanpour** [baptisteArno/typebot.io#1705]
hi 
i conf my keycloak server same as doc but i get error 
Try signing with a different account.
and when i check log of docker get this 
`[next-auth][error][SIGNIN_OAUTH_ERROR] 
https://next-auth.js.org/errors#signin_oauth_error Unable to find matching target resource method (For more on this error consult the server log at the debug level.) {
  error: {
    message: 'Unable to find matching target resource method (For more on this error consult the server log at the debug level.)',
    stack: 'OPError: Unable to find matching target resource method (For more on this error consult the server log at the debug level.)\n' +
      '    at processResponse (/app/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/helpers/process_response.js:38:13)\n' +
      '    at Issuer.discover (/app/node_modules/.pnpm/openid-client@5.6.5/node_modules/openid-client/lib/issuer.js:151:18)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
      '    at async openidClient (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/lib/oauth/client.js:16:14)\n' +
      '    at async getAuthorizationUrl (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/lib/oauth/authorization-url.js:70:18)\n' +
      '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/routes/signin.js:38:24)\n' +
      '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0___am5p4555usmjvg5xfootnx4hbe/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async z (/app/apps/builder/.next/server/chunks/5043.js:1:8413)\n' +
      '    at async K (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.24.0_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16545)',
    name: 'OPError'
  },
  providerId: 'keycloak',
  message: 'Unable to find matching target resource method (For more on this error consult the server log at the debug level.)'
}
 `
and this is Screenshot of the error when i click to login with keycloak i get
![Screenshot 2024-08-15 at 09-03-08 Sign In Typebot](https://github.com/user-attachments/assets/9b3b99ec-4940-44c9-a566-0fa3c081e566)

**Comment by baptisteArno** [comment]
Have you tried KEYCLOAK_BASE_URL=https://key.amirmdehghanpour.ir/ without end slash?

**Comment by baptisteArno** [comment]
I am not familiar with Keycloak so I am running out of idea 🤔

**Comment by baptisteArno** [comment]
The error is OPError: Unable to find matching target resource method (For more on this error consult the server log at the debug level.)

**Comment by brmattge** [comment]
Hi, @amirmdehghanpour, I checked, and your error seems similar to one I encountered.

I was able to authenticate successfully via Keycloak with the following settings:

![image](https://github.com/user-attachments/assets/aeb68024-b660-4d13-b53b-26578f9273fd)

* Make sure to use double quotes for KEYCLOAK_CLIENT_ID and KEYCLOAK_CLIENT_SECRET.

* The KEYCLOAK_BASE_URL needs to include /auth/realms in your Keycloak domain. For example: https://yourdomainkeycloak/auth/realms

In the Keycloak admin interface, I configured it as follows:

![image](https://github.com/user-attachments/assets/9eb6bbd8-6c5d-4a89-a8a5-ad00ec594777)

![image](https://github.com/user-attachments/assets/b8e33ab5-5399-446f-9785-eda5350cb9a2)

Let me know if this works for you too!

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
