### ISSUE TITLE
Manual instalation stuck

### ISSUE THREAD

**Issue by cristianormoraes** [baptisteArno/typebot.io#1711]
I doing a manual installation at ubuntu 24, 4gb ram vps and get installation stuck, the log bellow:

root@srv582143:/opt/typebot.io# pnpm run build:apps

> typebot-os@2.27.0 build:apps /opt/typebot.io
> turbo run build --filter=builder... --filter=viewer...

sh: 1: turbo: not found
 ELIFECYCLE  Command failed.
 WARN   Local package.json exists, but node_modules missing, did you mean to install?
root@srv582143:/opt/typebot.io# pnpm install
Scope: all 46 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +2390
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Downloading @tolgee/web@5.28.6: 11.13 MB/11.13 MB, done
Progress: resolved 2390, reused 2328, downloaded 36, added 2390, done

devDependencies:
+ @tolgee/cli 2.1.5
+ cross-env 7.0.3
+ cz-emoji 1.3.2-canary.2
+ husky 8.0.3
+ prettier 2.8.8
+ turbo 2.0.5

. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 45ms
Done in 11.2s
root@srv582143:/opt/typebot.io# pnpm run build:apps

> typebot-os@2.27.0 build:apps /opt/typebot.io
> turbo run build --filter=builder... --filter=viewer...

• Packages in scope: @typebot.io/ai, @typebot.io/anthropic-block, @typebot.io/billing, @typebot.io/bot-engine, @typebot.io/cal-com-block, @typebot.io/chat-node-block, @typebot.io/db-rules, @typebot.io/dify-ai-block, @typebot.io/elevenlabs-block, @typebot.io/emails, @typebot.io/env, @typebot.io/forge, @typebot.io/forge-repository, @typebot.io/js, @typebot.io/lib, @typebot.io/logic, @typebot.io/migrations, @typebot.io/mistral-block, @typebot.io/nextjs, @typebot.io/nocodb-block, @typebot.io/open-router-block, @typebot.io/openai-block, @typebot.io/playwright, @typebot.io/prisma, @typebot.io/qrcode-block, @typebot.io/radar, @typebot.io/react, @typebot.io/results, @typebot.io/schemas, @typebot.io/telemetry, @typebot.io/theme, @typebot.io/together-ai-block, @typebot.io/tsconfig, @typebot.io/variables, bot-engine, builder, eslint-config-custom, typebot-js, viewer
• Running build in 39 packages
• Remote caching disabled
@typebot.io/prisma:db:generate: cache bypass, force executing 750e78ce46696f90
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: > @typebot.io/prisma@0.1.0 db:generate /opt/typebot.io/packages/prisma
@typebot.io/prisma:db:generate: > dotenv -e ./.env -e ../../.env -- tsx scripts/db-generate.ts
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: Executing for PostgreSQL schema
@typebot.io/prisma:db:generate: Prisma schema loaded from postgresql/schema.prisma
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: ✔ Generated Prisma Client (v5.12.1) to ./../../node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client in 395ms
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate: import { PrismaClient } from '@prisma/client'
@typebot.io/prisma:db:generate: const prisma = new PrismaClient()
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate: import { PrismaClient } from '@prisma/client/edge'
@typebot.io/prisma:db:generate: const prisma = new PrismaClient()
@typebot.io/prisma:db:generate: ```
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate: ┌────────────────────────────────────────────────────────────────┐
@typebot.io/prisma:db:generate: │  Supercharge your Prisma Client with global database caching,  │
@typebot.io/prisma:db:generate: │  scalable connection pooling and real-time database events.    │
@typebot.io/prisma:db:generate: │  Explore Prisma Accelerate: https://pris.ly/cli/-accelerate    │
@typebot.io/prisma:db:generate: │  Explore Prisma Pulse: https://pris.ly/cli/-pulse              │
@typebot.io/prisma:db:generate: └────────────────────────────────────────────────────────────────┘
@typebot.io/prisma:db:generate:
@typebot.io/prisma:db:generate:
typebot-js:build: cache miss, executing 6eca207a3f91aee6
@typebot.io/env:build: cache miss, executing 06ff40d869488bc5
@typebot.io/env:build:
@typebot.io/env:build: > @typebot.io/env@1.0.0 build /opt/typebot.io/packages/env
@typebot.io/env:build: > esbuild env.ts --bundle --packages=external --format=esm --outfile=dist/env.mjs
@typebot.io/env:build:
typebot-js:build:
typebot-js:build: > typebot-js@2.2.17 build /opt/typebot.io/packages/deprecated/typebot-js
typebot-js:build: > tsup
typebot-js:build:
@typebot.io/env:build:
@typebot.io/env:build:   dist/env.mjs  13.6kb
@typebot.io/env:build:
@typebot.io/env:build: ⚡ Done in 8ms
@typebot.io/js:build: cache miss, executing f97cb8a45dd56439
typebot-js:build: CLI Building entry: src/index.ts
typebot-js:build: CLI Using tsconfig: tsconfig.json
typebot-js:build: CLI tsup v6.5.0
typebot-js:build: CLI Using tsup config: /opt/typebot.io/packages/deprecated/typebot-js/tsup.config.js
typebot-js:build: CLI Target: node14
typebot-js:build: ESM Build start
typebot-js:build: CJS Build start
typebot-js:build: IIFE Build start
typebot-js:build: IIFE dist/index.global.js     11.48 KB
typebot-js:build: IIFE dist/index.global.js.map 36.89 KB
typebot-js:build: IIFE ⚡️ Build success in 164ms
typebot-js:build: ESM dist/index.mjs     10.99 KB
typebot-js:build: ESM dist/index.mjs.map 36.51 KB
typebot-js:build: ESM ⚡️ Build success in 221ms
typebot-js:build: CJS dist/index.js     11.62 KB
typebot-js:build: CJS dist/index.js.map 36.92 KB
typebot-js:build: CJS ⚡️ Build success in 223ms
@typebot.io/js:build:  WARN  Issue while reading "/opt/typebot.io/packages/embeds/js/.npmrc". Failed to replace env in config: ${NPM_TOKEN}
@typebot.io/js:build:
@typebot.io/js:build: > @typebot.io/js@0.3.7 build /opt/typebot.io/packages/embeds/js
@typebot.io/js:build: > rollup --config rollup.config.js
@typebot.io/js:build:
typebot-js:build: DTS Build start
typebot-js:build: DTS ⚡️ Build success in 2299ms
typebot-js:build: DTS dist/index.d.ts 2.95 KB
bot-engine:build: cache miss, executing fbf2b7197a6fb964
@typebot.io/js:build:
@typebot.io/js:build: ./src/index.ts → dist/index.js...
bot-engine:build:
bot-engine:build: > bot-engine@0.1.0 build /opt/typebot.io/packages/deprecated/bot-engine
bot-engine:build: > tsup
bot-engine:build:
bot-engine:build: CLI Building entry: src/index.ts
bot-engine:build: CLI Using tsconfig: tsconfig.json
bot-engine:build: CLI tsup v6.5.0
bot-engine:build: CLI Using tsup config: /opt/typebot.io/packages/deprecated/bot-engine/tsup.config.js
bot-engine:build: CLI Target: es6
bot-engine:build: ESM Build start
bot-engine:build: CJS Build start
bot-engine:build: CJS dist/index.js     158.69 KB
bot-engine:build: CJS dist/index.js.map 472.87 KB
bot-engine:build: CJS ⚡️ Build success in 2152ms
bot-engine:build: ESM dist/index.mjs              155.24 KB
bot-engine:build: ESM dist/gtag-37GMA4K6.mjs      129.00 B
bot-engine:build: ESM dist/chunk-SGAXM4DC.mjs     1.43 KB
bot-engine:build: ESM dist/index.mjs.map          473.24 KB
bot-engine:build: ESM dist/gtag-37GMA4K6.mjs.map  71.00 B
bot-engine:build: ESM dist/chunk-SGAXM4DC.mjs.map 2.02 KB
bot-engine:build: ESM ⚡️ Build success in 2191ms
@typebot.io/js:build: created dist/index.js in 16.7s
@typebot.io/js:build:
@typebot.io/js:build: ./src/web.ts → dist/web.js...
@typebot.io/js:build: created dist/web.js in 22.3s
@typebot.io/react:build: cache miss, executing 0da4d14e43385b37
@typebot.io/react:build:  WARN  Issue while reading "/opt/typebot.io/packages/embeds/react/.npmrc". Failed to replace env in config: ${NPM_TOKEN}
@typebot.io/react:build:
@typebot.io/react:build: > @typebot.io/react@0.3.7 build /opt/typebot.io/packages/embeds/react
@typebot.io/react:build: > rollup --config rollup.config.js
@typebot.io/react:build:
@typebot.io/react:build:
@typebot.io/react:build: ./src/index.ts → ./dist/index.js...
@typebot.io/react:build: (!) Unresolved dependencies
@typebot.io/react:build: https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
@typebot.io/react:build: @typebot.io/js/dist/web (imported by "src/Standard.tsx", "src/Bubble.tsx" and "src/Popup.tsx")
@typebot.io/react:build: created ./dist/index.js in 12.9s
@typebot.io/nextjs:build: cache miss, executing a83eb152a2eaeffe
@typebot.io/nextjs:build:  WARN  Issue while reading "/opt/typebot.io/packages/embeds/nextjs/.npmrc". Failed to replace env in config: ${NPM_TOKEN}
@typebot.io/nextjs:build:
@typebot.io/nextjs:build: > @typebot.io/nextjs@0.3.7 build /opt/typebot.io/packages/embeds/nextjs
@typebot.io/nextjs:build: > rollup --config rollup.config.js
@typebot.io/nextjs:build:
@typebot.io/nextjs:build:
@typebot.io/nextjs:build: ./src/index.ts → ./dist...
@typebot.io/nextjs:build: (!) Unresolved dependencies
@typebot.io/nextjs:build: https://rollupjs.org/troubleshooting/#warning-treating-module-as-external-dependency
@typebot.io/nextjs:build: @typebot.io/js/dist/web (imported by "../react/src/Standard.tsx", "../react/src/Popup.tsx" and "../react/src/Bubble.tsx")
@typebot.io/nextjs:build: created ./dist in 12.8s
builder:build: cache miss, executing 76b1ae546dc218e7
viewer:build: cache miss, executing f8e79adef916a5ed
viewer:build:
viewer:build: > viewer@0.1.0 build /opt/typebot.io/apps/viewer
viewer:build: > dotenv -e ./.env -e ../../.env -- next build
viewer:build:
builder:build:
builder:build: > builder@0.1.0 build /opt/typebot.io/apps/builder
builder:build: > dotenv -e ./.env -e ../../.env -- next build
builder:build:
builder:build: - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
builder:build: - ready [next-runtime-env] wrote browser runtime environment variables to '/opt/typebot.io/apps/builder/public/__ENV.js'.
viewer:build: - event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
viewer:build: - ready [next-runtime-env] wrote browser runtime environment variables to '/opt/typebot.io/apps/viewer/public/__ENV.js'.
viewer:build:    ▲ Next.js 14.1.0
viewer:build:    - Experiments (use at your own risk):
viewer:build:      · outputFileTracingRoot
viewer:build:
builder:build:    ▲ Next.js 14.1.0
builder:build:    - Experiments (use at your own risk):
builder:build:      · outputFileTracingRoot
builder:build:
viewer:build:    Creating an optimized production build ...
viewer:build:  ✓ Compiled successfully
viewer:build:  ✓ Linting and checking validity of types
viewer:build:  ✓ Collecting page data
viewer:build:  ✓ Collecting build traces
viewer:build:  ✓ Finalizing page optimization
viewer:build:
viewer:build: Route (app)                                                                        Size     First Load JS
viewer:build: ┌ λ /api/integrations/openai/streamer                                              0 B                0 B
viewer:build: ├ λ /api/v1/sessions/[sessionId]/streamMessage                                     0 B                0 B
viewer:build: └ λ /api/v2/sessions/[sessionId]/streamMessage                                     0 B                0 B
viewer:build: + First Load JS shared by all                                                      0 B
viewer:build:
viewer:build: Route (pages)                                                                      Size     First Load JS
viewer:build: ┌   /_app                                                                          0 B            83.8 kB
viewer:build: ├ λ /[[...publicId]]                                                               3.13 kB         218 kB
viewer:build: ├ λ /404                                                                           6.29 kB        90.1 kB
viewer:build: ├ λ /api/[...trpc]                                                                 0 B            83.8 kB
viewer:build: ├ λ /api/health                                                                    0 B            83.8 kB
viewer:build: ├ λ /api/integrations/google-sheets/spreadsheets/[spreadsheetId]/sheets/[sheetId]  0 B            83.8 kB
viewer:build: ├ λ /api/integrations/stripe/createPaymentIntent                                   0 B            83.8 kB
viewer:build: ├ λ /api/mock/fail                                                                 0 B            83.8 kB
viewer:build: ├ λ /api/mock/success                                                              0 B            83.8 kB
viewer:build: ├ λ /api/publicTypebots/[typebotId]                                                0 B            83.8 kB
viewer:build: ├ λ /api/typebots                                                                  0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/blocks/[blockId]/executeWebhook                      0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/integrations/email                                   0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/results                                              0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/results/[resultId]                                   0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/results/[resultId]/answers                           0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/webhookBlocks                                        0 B            83.8 kB
viewer:build: ├ λ /api/typebots/[typebotId]/webhookSteps                                         0 B            83.8 kB
viewer:build: ├ λ /api/users/me                                                                  0 B            83.8 kB
viewer:build: └ λ /old/[[...publicId]]                                                           382 B           215 kB
viewer:build: + First Load JS shared by all                                                      83.9 kB
viewer:build:   ├ chunks/framework-544e890f2f568b75.js                                           45.2 kB
viewer:build:   ├ chunks/main-3646e5a6b0f65e02.js                                                36.4 kB
viewer:build:   └ other shared chunks (total)                                                    2.28 kB
viewer:build:
viewer:build: λ  (Dynamic)  server-rendered on demand using Node.js
viewer:build:
viewer:build:

**Comment by vishweshjha** [comment]
Have you configured your postgres URL correctly

**Comment by cristianormoraes** [comment]
yes, I did a test.

**Comment by baptisteArno** [comment]
Most likely forgot to run `pnpm install`?

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
