### ISSUE TITLE
Add support for constants and enums in flows

### ISSUE THREAD

**Issue by jwalsh-vori** [baptisteArno/typebot.io#1714]
Often times within a flow, I want to refer to a value, either to store it as a variable, or compare a variable value to it. Having the ability to define constants and enums, and being able to use them when setting variable values, would reduce the likelihood of errors in flows.

Might be nice to be able to define these at the workspace level also so they can be shared across flows.

**Comment by baptisteArno** [comment]
Can you use the templates provided please? There it lacks a lot of context 🙏
