### ISSUE TITLE
openai 4.0 mini integration error

### ISSUE THREAD

**Issue by Wesley232-oa** [baptisteArno/typebot.io#1715]
Good afternoon.
Self-hosted typebot, version 2.27.0
Integration with openai, when using openai 4.0 mini, viewing and testing, the error below is occurring:

{ "status": 400, "body": { "message": "Input validation failed", "code": "BAD_REQUEST", "data": { "code": "BAD_REQUEST", "httpStatus": 400, "path": "continueChat" }, "issues": [ { "code": "invalid_type", "expected": "string", "received": "object", "path": [ "message" ], "message": "Expected string, received object" } ] } }

Lower versions of openai work.

Is typebot not compatible with chatgpt openai 4.0 mini?

Below is my flow;

![Screenshot_2](https://github.com/user-attachments/assets/bc35f6e3-5ece-414c-aff3-f67ffe8d224a)

**Comment by baptisteArno** [comment]
Can you provide a way for me to reproduce the bug?

**Comment by Wesley232-oa** [comment]
If the video below helps;

https://github.com/user-attachments/assets/557fa14b-f570-4166-8b60-1cceb5e4d6a0

**Comment by baptisteArno** [comment]
Can you provide the typebot JSON export? https://docs.typebot.io/editor/export-import#export-import-a-typebot

**Comment by Wesley232-oa** [comment]
yes, follow the file.
[typebot-export-gpt-english-dwjplo3.json](https://github.com/user-attachments/files/16680027/typebot-export-gpt-english-dwjplo3.json)

**Comment by baptisteArno** [comment]
Ok so I am not reproducing the issue. I am guessing that it then come from your assistant in particular. Can you tell me how I can configure an assistant similar to yours?

**Comment by Wesley232-oa** [comment]
@baptisteArno .
I appreciate your willingness to help.
I managed to solve this problem by reinstalling Typebot, something I may have done wrong the first time I installed it.
Now everything works perfectly.
Thank you.

**Comment by baptisteArno** [comment]
👌
