### ISSUE TITLE
"Error! Could not reach server. Check your connection.

### ISSUE THREAD

**Issue by bielsilva713** [baptisteArno/typebot.io#1717]
When creating a variable, the error "Error! Could not reach server. Check your connection." appears. how to solve this?? I've gone back to previous versions and nothing.
![Captura de tela 2024-08-17 191917](https://github.com/user-attachments/assets/19b3a64c-a81a-458f-8074-4bd33da90669)

**Comment by bielsilva713** [comment]
Hello, I installed typebot using easypanel and I see that there is a problem with the typebot viewer that occurs with any version. I'm using the ia groq ai and all the variables only work if you activate "Execute on client?" nothing and gives the error "gateway bad".

**Comment by baptisteArno** [comment]
Please provide a reproduction 🙏

**Comment by bielsilva713** [comment]
> Por favor, forneça uma reprodução 🙏

Hello, how can you see everything, even the webhook only works if you activate the client run and when the AI ​​responds, the viewer drops.

video: https://drive.google.com/file/d/1I21bPIhLvMzntIUwmBDqllQAlfWpADrD/view?usp=sharing

**Comment by bielsilva713** [comment]
I upgraded to Ubuntu 22 and I'm still having the same problem, but when typebot-viewer drops in overview this appears.
![image](https://github.com/user-attachments/assets/fad1a20f-e3cd-4254-a81b-43cc232c4639)

**Comment by baptisteArno** [comment]
Make sure you have this env set up: `NODE_OPTIONS=--no-node-snapshot`

**Comment by euvictorsanto** [comment]
Estou com o mesmo problema! Porém nao sei como resolver. Estava tudo funcionando normalmente, e sábado, de repente caiu a estrutura com esse mesmo erro: Error! Could not reach server. Check your connection! 

O que devo fazer?

**Comment by juliocarneiro** [comment]
aqui nao funciona tambem... mesmo erro

**Comment by eumarcosdeoliveira** [comment]
Alguem conseguiu resolver??? mesmo erro aq

**Comment by marciotisouza** [comment]
I updated to version 3.0.1 and I have the same error, any fixes?

**Comment by mhyeganeh** [comment]
In my case the issue was related to my CDN DDoS protection. By disabling, the issue is gone!
