### ISSUE TITLE
The onboarding bot redirects me to app.typebot.io away from my own self-hosted instance

### ISSUE THREAD

**Issue by ovizii** [baptisteArno/typebot.io#173]
All seems to have worked well, then I access https://my.builder.tld/ and register via email, get the email and sign in with the link.  

Running Version: 2.8.7 via docker-compose.yml

Then comes the onboarding typebot which asks me for my name, company, etc. and then redirects me to [https://app.typebot.io/signin...](https://app.typebot.io/signin?redirectPath=%2Ftypebots%2Fcreate%3FisFirstBot%3Dtrue) 

I hit the back button and am back on my own instance and can start working but whenever I refresh this page: [https://my.builder.tld/typebots](https://l.facebook.com/l.php?u=https%3A%2F%2Fmy.builder.tld%2Ftypebots%3Ffbclid%3DIwAR19pu9AKgl3gABSGTPiv1nZ6k8YzFxI1ZXxW6lfSRg8vSHuZjHX8-gn4cY&h=AT0Uoh9ZH-6Qdq9FFXVF73kLTMGsX0KmzUVw15z-sa7MyH0Vvnmie6Mm2XbGtCscfNJc6PmuC1pHK8Mw9Qt6y45gpRzR5xKmRRzYN5RJEZtmiZn1f4QU83wi9OiUtNGl_rKm&__tn__=-UK-R&c[0]=AT36M9cif1C54EpRBClUpz2kwLALYkYWIiKtA5wqbf973qWN442UGxYz9cIDNKWjEzBZrbVeuGlPdCX8RJY9HtDir59CliyMMI51twEaV-zxhyO8UspqiAj13aY1UgLRFrrqSksEToHldRFJdMRBQJ0y4-tF9EuZoN7-Ueg) the onboarding bot starts again and will redirect me away from my self-hosted instance. 

Am I doing something wrong or can this be fixed? 
Also, every time I access [https://my.builder.tld/typebots](https://my.builder.tld/typebots?fbclid=IwAR3O2R7L8IWaN2MfS47LjIoQI868FVMeyjkeiWOTXGjsa322I4Gh2MmRBY8) the page loads quite long, I guess it loads this onboarding bot externally hence the waiting time?

**Comment by baptisteArno** [comment]
Indeed, the redirect is hard-coded to app.typebot.io. I need to fix that 👌

The onboarding bot shouldn't appear again if you have at least a typebot created. Do you confirm?

**Comment by ovizii** [comment]
Glad you found and issue, and it was not just me making some dumb mistake :-)
Yes, I can confirm I saw the issue before creating my first typebot. I have now created a typebot and cannot recreate the issue.
