### ISSUE TITLE
Google Sheet sign in Access Blocked

### ISSUE THREAD

**Issue by JOduMonT** [baptisteArno/typebot.io#1730]
**Describe the bug**

In Typebot editor; when I added Sheets integration and want to Connect Spreadsheets;
after clicked to Connect Spreadsheets
Google give me that error: 

![image](https://github.com/user-attachments/assets/f04ed42e-6ec8-4f74-897d-be5c44a88373)

Since nobody else reported that issue before; I understand it's probably on my side; but I don't really understand where and what to look for.

So, I'm kindly asking for guidance please.

- What and Where I should look for what ?

**Comment by baptisteArno** [comment]
Did you correctly configured Google Sheets?

https://docs.typebot.io/self-hosting/configuration#google-sheets
