### ISSUE TITLE
Unable to Customize OpenAI Base URL in Version 2.27.0 (Docker Deployment)

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1734]
Hi~

I have updated to the latest version (2.27.0) and deployed the application using Docker. However, I am still unable to customize the OpenAI base URL as shown in the screenshot.
![图片](https://github.com/user-attachments/assets/32278c2d-cfbe-4cc2-aa86-e13ba09dc005)

I have confirmed that the saas version is OK. Is it that the docker version has not been updated synchronously?
![图片](https://github.com/user-attachments/assets/660739df-9613-41cf-b9c4-8955eea5dbd4)

Thank you!

**Comment by baptisteArno** [comment]
It will be available on next monthly version release v2.28.0 (https://docs.typebot.io/self-hosting/get-started#releases)
