### ISSUE TITLE
Suggestion for Bulk Export of Flows to Improve Workflow Management

### ISSUE THREAD

**Issue by levidiorginis** [baptisteArno/typebot.io#1737]
We are utilizing a structure in our project where a main flow branches into multiple sub-flows. This approach helps us maintain, modify, and organize our code more efficiently, avoiding duplication by isolating repeated sections into individual flows that are called in various places.

Currently, to export flows, we need to enter each flow individually and export it as a JSON file. This becomes challenging when dealing with larger projects that involve many flows (we have around 20 flows in our project). It would be incredibly helpful to have the ability to:

1. Export an entire folder containing multiple flows at once, which would be the ideal solution.
2. Select multiple flows for export without needing to enter each one individually, which would also greatly assist in managing the project.
3. If those are not feasible, even having the option to export flows without entering each flow would already make the process much easier.

Any of these improvements would be greatly appreciated and would significantly enhance our ability to manage larger projects. Thank you for considering this suggestion.

**Comment by baptisteArno** [comment]
You can use the API for this. I don't really see the point of adding this to the official project.
