### ISSUE TITLE
[Whatsapp] Wait with Pause Flow closing ChatSession

### ISSUE THREAD

**Issue by FelipeSVidal** [baptisteArno/typebot.io#1739]
**Describe the bug**
On wait block using _Pause Flow = true_ is closing / delete ChatSession, causing flow break.
Discord thread: https://discord.com/channels/1155799591220953138/1275515365149118516

**To Reproduce**
1. Create a Group with wait block
2. Set pause flow to true
3. Create input block
4. Bubble Text after to test proposal
5. Test on whatsapp

**Example Typebot**
`{"version":"6","id":"cm05i11tq000emvppu70xs1vy","name":"Whatsapp wait bug report","events":[{"id":"ca2393n9kkw4vmmty43zczkb","outgoingEdgeId":"s0kii9ra3zyei3k68jyecibt","graphCoordinates":{"x":0,"y":0},"type":"start"}],"groups":[{"id":"dnbuy5zjqunjmsgpj46h9ggd","title":"Group #1","graphCoordinates":{"x":322,"y":45},"blocks":[{"id":"hft6kzal77k70of7e5fq3zak","type":"text","content":{"richText":[{"type":"p","children":[{"text":"First msg"}]}]}},{"id":"lbzc5r30oad1e32pi9h7du86","type":"Wait","options":{"secondsToWaitFor":"0","shouldPause":true}},{"id":"ft8maglo35lqmo7crmvc324c","type":"text input","options":{"variableId":"vgp4fce3r6xzgwisqlsldbvcm"}},{"id":"g9a5yfucnn2p0ny333v92kam","type":"text","content":{"richText":[{"type":"p","children":[{"text":"{{response}}"}]}]}}]}],"edges":[{"id":"s0kii9ra3zyei3k68jyecibt","from":{"eventId":"ca2393n9kkw4vmmty43zczkb"},"to":{"groupId":"dnbuy5zjqunjmsgpj46h9ggd"}}],"variables":[{"id":"vgp4fce3r6xzgwisqlsldbvcm","name":"response","isSessionVariable":false}],"theme":{},"selectedThemeTemplateId":null,"settings":{"whatsApp":{"isEnabled":true}},"createdAt":"2024-08-22T16:30:23.102Z","updatedAt":"2024-08-22T16:31:33.194Z","icon":null,"folderId":null,"publicId":"whatsapp-wait-bug-report-70xs1vy","customDomain":null,"workspaceId":"clvkvyab60001b2f9zg60ch9y","resultsTablePreferences":null,"isArchived":false,"isClosed":false,"whatsAppCredentialsId":"a0rsj9mwdb4bgmt494gleugn","riskLevel":null}
`

**Expected behavior**
Equals web bot, flow pause, when user reply, bot continue with input = reply

**Screen recording**
With pause flow: ( bug cause start chat again )
![image](https://github.com/user-attachments/assets/7fc65b1e-00e9-49d3-9697-76538b6ffcd3)

Without pause flow:
![image](https://github.com/user-attachments/assets/1a9741b7-975a-4968-b9c8-ab3c52ac13b9)

**Comment by baptisteArno** [comment]
Placing a Wait block before an input does not make sense.
It should be placed before a long running HTTP request block or something similar

**Comment by FelipeSVidal** [comment]
This is just example to reproduce ChatSession close... 

I'm using this:
![image](https://github.com/user-attachments/assets/e123b5d6-6423-4c37-800a-16a1181a4efe)

**Comment by baptisteArno** [comment]
I tried on my end with webhook.site http request, just like your setup and it works fine!

**Comment by FelipeSVidal** [comment]
With whatsapp, in preview ( web ) work, but using whatsapp no... Ok, i will try again on next release!!!
