### ISSUE TITLE
Question about the self-hosted version and usage (chats/storage)

### ISSUE THREAD

**Issue by ovizii** [baptisteArno/typebot.io#174]
I am Running Version: 2.8.7 via docker-compose.yml and I noticed the chats/storage counters and am wondering how these limits apply to my self-hosted instance. 
Are these counted on my installation or are they reported to the hosted typebot instance? 
Seeing that I have not added S3 storage to my instance, yet this looks like its talking about the hosted storage space? 

Could somebody please point me towards where I can read up how the self-hosted and the hosted version are still connected?

**Comment by baptisteArno** [comment]
That's the max limit I have on the Cloud managed Typebot.

What you can do is overwrite it in the Database:

`Workspace` > `customStorageLimit` (In GB)

**Comment by ovizii** [comment]
thanks for explaining, all good, will close this ticket.
