### ISSUE TITLE
Response waiting time

### ISSUE THREAD

**Issue by bielsilva713** [baptisteArno/typebot.io#1748]
Hello, I need your help, how do I get my typebot to continue with the flow if the user responds within a certain time and if there is no response the bot automatically moves to another block??? Could you do this with n8n or typebot ????

**Comment by AudiXP** [comment]
@bielsilva713  conseguiu algum resultado para isso? um tempo de expiração para uma entrada do utilizador, caso não haja resposta, feche a sessão em evolução.
