### ISSUE TITLE
How to debug S3 connection?

### ISSUE THREAD

**Issue by ovizii** [baptisteArno/typebot.io#175]
I am trying my hand with the self-hosted version and added my minio details. I see no errors in the logs but when I try to use the file upload feature, I get this error: `An error occured while uploading the file`

**Comment by ovizii** [comment]
btw. I made slight progress by changing `S3_ENDPOINT=s3.mydomain.tld` to `S3_ENDPOINT=https://s3.mydomain.tld` and now I see a progress bar which is stuck. Still no errors.

Your [docs and examples](https://docs.typebot.io/self-hosting/docker) don't state I need a protocol just the endpoint so not sure what is wrong here. 

![image](https://user-images.githubusercontent.com/837902/204833722-4524c5e7-418b-44be-98be-30d749f3c976.png)

**Comment by baptisteArno** [comment]
Have you configured like this ? https://docs.typebot.io/self-hosting/docker#s3-storage

**Comment by ovizii** [comment]
I can add more details though: 

I already had a running minio instance, so I didn't use your instructions for it. This minio has a bucket and an access key+secret configured which I tested with winscp as a S3 client. 

![image](https://user-images.githubusercontent.com/837902/204844404-675f2d82-7a8f-4bb6-82bd-c69f0015f9a0.png)

![image](https://user-images.githubusercontent.com/837902/204844458-7149cda5-6b9d-4c3c-9b90-4f4c2a57c7fb.png)


I used these settings for the builder and the viewer:
```
    environment:
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123
      - S3_BUCKET=typebot
      - S3_ENDPOINT=storage.domain.com
```

The results are described in my first 2 posts. Is  `S3_ENDPOINT=s3.mydomain.tld` to `S3_ENDPOINT=https://s3.mydomain.tld` correct?

**Comment by baptisteArno** [comment]
That's wrong it needs to be `s3.mydomain.tld`, I'll update the config doc to make this clear 👌

Here is how you can configure a Minio storage for typebot:

## CLI

1. `mc mb minio/typebot`
2. `mc policy set public minio/typebot/public`

## Console dashboard

1. Create a bucket named `typebot`
2. Click on `Manage`
3. Change the access policy to:
   ```
    {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": [
                        "*"
                    ]
                },
                "Action": [
                    "s3:GetBucketLocation",
                    "s3:ListBucketMultipartUploads"
                ],
                "Resource": [
                    "arn:aws:s3:::typebot"
                ]
            },
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": [
                        "*"
                    ]
                },
                "Action": [
                    "s3:ListBucket"
                ],
                "Resource": [
                    "arn:aws:s3:::typebot"
                ],
                "Condition": {
                    "StringEquals": {
                        "s3:prefix": [
                            "public"
                        ]
                    }
                }
            },
            {
                "Effect": "Allow",
                "Principal": {
                    "AWS": [
                        "*"
                    ]
                },
                "Action": [
                    "s3:AbortMultipartUpload",
                    "s3:DeleteObject",
                    "s3:GetObject",
                    "s3:ListMultipartUploadParts",
                    "s3:PutObject"
                ],
                "Resource": [
                    "arn:aws:s3:::typebot/public*"
                ]
            }
        ]
    }
    ```
4. Add an access rule:
   - Prefix: public
   - Access: readwrite

Here is a video to show you the local dev config:

https://user-images.githubusercontent.com/16015833/205043951-ca1b6b9d-ade8-4578-adef-fd91d51d61ef.mp4

**Comment by baptisteArno** [comment]
I just upgraded my minio image and it seems the command: `mc policy set public minio/typebot/public` doesn't work anymore.

It needs to be: `mc anonymous set public minio/typebot/public`

**Comment by ovizii** [comment]
Thanks for all the details. I have spotted the problem to my instance: mine isn't public. It wasn't clear to me that it had to be public even though typobot has access to the bucket with its credentials.

**Comment by fawwal** [comment]
Just leaving this here for google to index and perhaps help someone. Please ignore. 

Configuring Linode(akamai) Object Storage with Typebot

Contrary to Linode docs for similar apps your config should look like this.  Where "apps" is _your_ bucket name, 


<img width="793" alt="ScreenShot 2023-03-31 at 23 41 48@2x" src="https://user-images.githubusercontent.com/14047152/229264053-76adf231-bd5a-458a-ad4d-7b8225d4ad87.png">

**Comment by anzacloud** [comment]
What works for me is S3_ENDPOINT : https://s3-api.example.com

**Comment by mcDcall** [comment]
getting crasy with this upload error...

i can access minio by https:// URL;
i created a container as per instructions and in Minio it creates the Typebot bucket with custom policies;

createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc config host add minio http://minio:9000 minio minio123;
      /usr/bin/mc mb minio/typebot;
      /usr/bin/mc anonymous set public minio/typebot/public;
      exit 0;
      "

i can access minio and manually upload files into the Typebot bucket;
I have the ENV 

I set ENV in both containers (viewer and builder):
S3_BUCKET=typebot
S3_ENDPOINT=s3.xxxx.xxxxx
S3_ACCESS_KEY=xxxxx
S3_SECRET_KEY=xxxxx

... and both logs (viewer and builder) show a S3 API access error if i try to upload files.

Something went wrong C: S3 API Requests must be made to API port.

    at /app/apps/viewer/.next/server/pages/api/[...trpc].js:363:70089

    ... 3 lines matching cause stack trace ...

    at async th.getBucketRegionAsync (/app/apps/viewer/.next/server/pages/api/[...trpc].js:367:3046) {

  code: 'INTERNAL_SERVER_ERROR',

  name: 'TRPCError',

  [cause]: C: S3 API Requests must be made to API port.

      at /app/apps/viewer/.next/server/pages/api/[...trpc].js:363:70089

      at eL (/app/apps/viewer/.next/server/pages/api/[...trpc].js:363:70208)

      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

      at async th.makeRequestStreamAsync (/app/apps/viewer/.next/server/pages/api/[...trpc].js:367:2681)

      at async th.getBucketRegionAsync (/app/apps/viewer/.next/server/pages/api/[...trpc].js:367:3046) {

    code: 'InvalidArgument',

    requestid: 0,

    amzRequestid: undefined,

    amzId2: undefined,

    amzBucketRegion: undefined

  }

}

**Can somebody help with some orientation?**

For reference my Minio container was installed with this:

version: '3.3'
volumes:
  minio-data:

services:
  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9090"
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: xxxxx
      MINIO_ROOT_PASSWORD: xxxxxx
    volumes:
      - minio-data:/data

    networks:
      - my-net
  

networks:
  my-net:
    external: true
