### ISSUE TITLE
On `tsc --build`, implicit any type issue when it's not supposed to

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1750]
**Describe the bug**
I am currently refactoring the monorepo to use typescript project references to have a better IDE Intellisense experience.

I am almost done but there is still an issue remaining when running `pnpm tsc --build`

It shows `packages/logic/computeResultTranscript.ts:213:10 - error TS7006: Parameter 'item' implicitly has an 'any' type.`

But when checking on any IDE, there is no issue, the type is inferred correctly so I don't know what's going on

**To Reproduce**
1. Clone the repo
2. Checkout `refacto/ts-project-references` branch
3. Run `pnpm install`
4. Run `pnpm turbo db:generate`
5. Run `pnpm tsc --build`

I need help from a Typescript wizard 🙏

**Comment by varshith257** [comment]
Interesting!  I would like to reproduce this first before an attempt

**Comment by syedbarimanjan** [comment]
@baptisteArno can you help with this error 
![Screenshot from 2024-08-28 22-15-29](https://github.com/user-attachments/assets/06b58932-3676-4f98-9f46-ceab5f1aab6b)

**Comment by baptisteArno** [comment]
Oh right, you need to run `pnpm turbo db:generate`

**Comment by baptisteArno** [comment]
Removing the bounty for this, I decided to not use project references in the end 🙏 Thank you for attempting this
