### ISSUE TITLE
OAuth login/signup providers don't work

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#176]
Using docker-compose typebot latest image, trying to connect to the builder with a provider like Google or Github doesn't work and return an `error=Callback`.

I double-checked my configuration and it does not have any typo, and the callback URL I provided in Google console if the right one, which means that you can deduct this login method doesn't work.
How can I achieve login/registering with Google OAuth then?

**Comment by baptisteArno** [comment]
Are you sure you have provided the callback URL to the right credentials?

https://console.developers.google.com/apis/credentials

The "Authorized redirect URIs" used when creating the credentials must include your full domain and end in the callback path: `https://{YOUR_DOMAIN}/api/auth/callback/google`

**Comment by Lanhild** [comment]
Yes, 100% sure.

**Comment by baptisteArno** [comment]
Can I have more info then? What exactly is happening?

**Comment by Lanhild** [comment]
1. click the `login with` button
2. Typebot attempts to login but doesn't work, and return an `error=Callback`
3. A message on typebot interface says to try to login with a different account

**Comment by baptisteArno** [comment]
Any server log after having the error `docker-compose logs`? You should a more helpful message than just `error=Callback` 😁

**Comment by Lanhild** [comment]
Somehow my logs returned that my DB credentials are incorrect. I'll fix that ASAP and reply in this thread if the issue persists.

**Comment by Lanhild** [comment]
```v
typebot-builder_1  | Authentication failed against database server at `typebot-db`, the provided database credentials for `postgres` are not valid.
typebot-builder_1  | 
typebot-builder_1  | Please make sure to provide valid database credentials for the database server at `typebot-db`. {
typebot-builder_1  |   message: '\n' +
typebot-builder_1  |     'Invalid `prisma.account.findUnique()` invocation:\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     'Authentication failed against database server at `typebot-db`, the provided database credentials for `postgres` are not valid.\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     'Please make sure to provide valid database credentials for the database server at `typebot-db`.',
typebot-builder_1  |   stack: 'Error: \n' +
typebot-builder_1  |     'Invalid `prisma.account.findUnique()` invocation:\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     'Authentication failed against database server at `typebot-db`, the provided database credentials for `postgres` are not valid.\n' +
typebot-builder_1  |     '\n' +
typebot-builder_1  |     'Please make sure to provide valid database credentials for the database server at `typebot-db`.\n' +
typebot-builder_1  |     '    at RequestHandler.handleRequestError (/app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/@prisma/client/runtime/index.js:34316:13)\n' +
typebot-builder_1  |     '    at RequestHandler.request (/app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/@prisma/client/runtime/index.js:34293:12)\n' +
typebot-builder_1  |     '    at async PrismaClient._request (/app/node_modules/.pnpm/@prisma+client@4.6.1_prisma@4.6.1/node_modules/@prisma/client/runtime/index.js:35273:16)\n' +
typebot-builder_1  |     '    at async getUserByAccount (/app/apps/builder/.next/server/chunks/6207.js:99:29)',
typebot-builder_1  |   name: 'Error'
typebot-builder_1  | }
typebot-builder_1  | [next-auth][error][OAUTH_CALLBACK_HANDLER_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#oauth_callback_handler_error 
typebot-builder_1  | Invalid `prisma.account.findUnique()` invocation:
typebot-builder_1  | 
```

**Comment by Lanhild** [comment]
I used the correct password, so I have no idea why this issue appears.

**Comment by Lanhild** [comment]
Even when using the default docker-compose configuration, the same error is returned.

**Comment by baptisteArno** [comment]
I just can't reproduce the issue. It definitely means that your `DATABASE_URL` value is invalid.

Let's say you have this docker-compose service as your database:

```yaml
typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - build_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot123
```

Then your `DATABASE_URL` value should be: `postgresql://postgres:typebot123@typebot-db:5432/typebot`
