### ISSUE TITLE
Embedded Typebot not loading in Facebook Messenger's in-app browser, displays "The bot you're looking for doesn't exist."

### ISSUE THREAD

**Issue by ChrisVo** [baptisteArno/typebot.io#1765]
**Describe the bug**  
When accessing the webpage with the embedded Typebot, the message "The bot you're looking for doesn't exist." appears when opening the link from Facebook Messenger's in-app browser. However, the bot loads properly when accessed via an external browser.

**To Reproduce**  
1. Go to Facebook Messenger and send the link to the webpage containing the embedded bot.  
2. Open the link from within the Facebook Messenger browser.  
3. Observe the error message stating "The bot you're looking for doesn't exist."

**Expected behavior**  
The embedded bot should load and function properly, displaying the chat interface without the error message, regardless of the browser used.

**Comment by baptisteArno** [comment]
That's strange. Can you provide the link to a bot that fails?

**Comment by Estrategista07** [comment]
Eu estou tendo o mesmo problema , hospedei o typebot em um servidor próprio e ele parou de funcionar poderiam me ajudar 


I'm having the same problem, I hosted typebot on my own server and it stopped working, could you help me?

the bot link that fails : 
https://app.lbdsprodutosdigitais.com/como-educar-filhos-felizes-e-realizados-mx84aj2


![Captura de tela 2024-09-09 070315](https://github.com/user-attachments/assets/5f4b36d2-b2df-48f5-86db-664591ce06f3)
