### ISSUE TITLE
Error when Previewing the flow

### ISSUE THREAD

**Issue by 7Beeai** [baptisteArno/typebot.io#1766]
Version 2.28.0
Describe the bug

When clicking on "Preview" to test the flow, the following message appears:

"Error! Could not reach server. Check your connection. {}"

Steps already taken:

Checked the connection
Cleared the cache
Opened in a different browser
Expected behavior

The "Preview" field should open, allowing the tests to be performed normally.

Screen recording
![Captura de Tela 2024-09-04 às 16 46 55](https://github.com/user-attachments/assets/8b54cbda-ba78-4037-ae91-3627c5342c80)

**Comment by MehdiRazaNaqvi** [comment]
Hey @7Beeai why did you marked this as closed? Did you find any solution for this? I am also getting this error when setting up with docker.
