### ISSUE TITLE
Multi Viewer URLs support

### ISSUE THREAD

**Issue by Tint0ri** [baptisteArno/typebot.io#1768]
TypeBot is amazing! 

I use it built a bot and published with a domain url in internet with NAT. I works in internet. Because of router/NAT limitation, I cannot access the domain url from LAN. I have to change the hosts file to make it works.

I wonder that if it possbile to have separate viewer urls to make it works in internet and LAN such as internal/external viewer url . 

And again, Typebot is awesome!

**Comment by Mahesh7741** [comment]
Solution: You want to have two separate URLs—one for internal use (LAN) and one for external use (internet). This is possible by setting up internal DNS (Domain Name System) or using a split DNS configuration. In this setup, your internal network resolves the domain to the local IP, while external users resolve it to your public IP.

Internal URL: This will work within your LAN and resolve to your local IP.
External URL: This will work on the internet and resolve to your public IP.

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
