### ISSUE TITLE
Issue with generated d.ts files in packages that imports zod

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#1777]
I am currently doing a huge update on the monorepo tooling. 

I stumbled upon an issue that boils down to that simple reproduction:
https://github.com/baptisteArno/zod-d-ts-issue

You will find the detailed context here: https://twitter.com/baptisteArno/status/1832004266950627672

package-three imports package-two that imports package-one that imports zod

The schema imported in package-three is of type any because the declaration file of package-two is not correct.

1. pnpm install
2. pnpm turbo build --filter=package-three...
3. See error because schema is of type any

I'd like to understand clearly why the generated d.ts file on package-two is generated with inlined `import("zod")` and how it should be fixed.

These are not valid fixes as it just works around this issue:
- Explicitely define the type.
- Install zod on package-two

**Comment by yaodingyd** [comment]
It doesn't seem to 100% reproducible though, my run actually works with no error

```
☁  zod-d-ts-issue [main] ⚡  pnpm turbo build --filter=package-three...
turbo 2.1.1

• Packages in scope: package-one, package-three, package-two
• Running build in 3 packages
• Remote caching disabled
┌ package-one#build > cache miss, executing a377b4763f866303
│
│
│ > package-one@1.0.0 build ~/javascripts/zod-d-ts-issue/packages/package-one
│ > tsc
└────>
┌ package-two#build > cache miss, executing edf1dfab4c2a0464
│
│
│ > package-two@1.0.0 build ~/javascripts/zod-d-ts-issue/packages/package-two
│ > tsc
└────>
┌ package-three#build > cache miss, executing 1f02fa28f2b36efa
│
│
│ > package-three@1.0.0 build ~/javascripts/zod-d-ts-issue/packages/package-three
│ > tsc
└────>

 Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
  Time:    2.676s
```

**Comment by namukang** [comment]
@baptisteArno It also doesn't reproduce on my machine:

```
~/Code/tmp/zod-d-ts-issue on main 
› pnpm turbo build --filter=package-three
turbo 2.1.1

• Packages in scope: package-three
• Running build in 1 packages
• Remote caching disabled
┌ package-one#build > cache miss, executing be87cf83d0e9882f 
│ 
│ 
│ > package-one@1.0.0 build /Users/dk/Code/tmp/zod-d-ts-issue/packages/package-one
│ > tsc
└────>
┌ package-two#build > cache miss, executing 682a1d4948d0eecb 
│ 
│ 
│ > package-two@1.0.0 build /Users/dk/Code/tmp/zod-d-ts-issue/packages/package-two
│ > tsc
└────>
┌ package-three#build > cache miss, executing 61cbeeeeb6845db7 
│ 
│ 
│ > package-three@1.0.0 build /Users/dk/Code/tmp/zod-d-ts-issue/packages/package-three
│ > tsc
└────>

 Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
  Time:    2.622s 
```

**Comment by baptisteArno** [comment]
My bad, package-three was indeed not showing the error properly. You may pull the new changes and try to build again 🙏 @namukang @yaodingyd

**Comment by namukang** [comment]
@baptisteArno Submitted a fix here: https://github.com/baptisteArno/zod-d-ts-issue/pull/2

Regardless of whether you consider this a valid fix, I don't need the bounty as I'm happy to just help a fellow indie hacker :) Big fan of what you've built with Typebot!

**Comment by baptisteArno** [comment]
Thank you @namukang, love the spirit 🙏🙏
