### ISSUE TITLE
404 ERROR - Typebot with DigitalOcean and Easypanel

### ISSUE THREAD

**Issue by teamlowticket** [baptisteArno/typebot.io#1779]
I have installed Typebot using DigitalOcean and Easypanel, Typebot is working but no 100% of the time

When I access the builder or viewer url I get the 404 error

When that happens I usually can access it using incognito or mobile data, but these also get the same error sometimes

To be honest, I don't even know what screenshots or codes I should add here to get help with this problema

I need help

**Comment by Estrategista07** [comment]
I have the same problem, did you manage to solve it?

**Comment by Estrategista07** [comment]
@baptisteArno  Hello, can you help us here?

**Comment by baptisteArno** [comment]
I have no idea what's going on, you need to provide more information like logs or anything that could help us investigate

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
