### ISSUE TITLE
Current block not found error api sendMessage

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#179]
Hello, I'm trying to test the message sending api but I have this error when trying to go to the second block passing the sessionId "message: Current block not found, code: INTERNAL_SERVER_ERROR"

![flowimg1](https://user-images.githubusercontent.com/52453013/206014043-24b01498-0b9d-4e5a-93ec-d00b138f2218.png)

**Comment by baptisteArno** [comment]
Hey, thank you for writing this issue. The Chat API is under heavy development and is still very experimental. I'll take this into account and let you know when there's a fixed version available 👌

**Comment by baptisteArno** [comment]
It will be fixed when #190 will be deployed
