### ISSUE TITLE
Missing developerKey in API Requests After OAuth Authentication

### ISSUE THREAD

**Issue by WilliamAlmeida** [baptisteArno/typebot.io#1790]
**Describe the bug**
To troubleshoot the issue with the developerKey not being sent when viewing sheets in Typebot Viewer (v2.28), here are some key points to consider:

OAuth Authentication Success: You mentioned that the OAuth authentication is working fine, which means the initial handshake with the API is successful.

Missing developerKey: The developerKey is not being included in the request when you attempt to view the sheets. This is likely why you're not able to see the sheets unless you manually add the key.

Manual Intervention Works: When you manually navigate to the URL and include the developerKey, the sheets are listed correctly. This indicates that the issue is specific to the way the key is being handled or transmitted by the Typebot Viewer.

**Expected behavior**
The developerKey should be automatically included in the request when viewing sheets within the Typebot Viewer after a successful OAuth authentication. The sheets should be listed correctly without the need for any manual intervention.

**Screen recording**
developerKey (empty)
![google sheet error developer key empty](https://github.com/user-attachments/assets/4022260a-a7fc-40f4-be82-2fee1a263a53)

developerKey (filled)
![google sheet error developer key filled](https://github.com/user-attachments/assets/2bf9e749-caae-4bc1-abe9-90ce5e87d46a)

**Comment by neehhaa06** [comment]
Hello @WilliamAlmeida :)

fix: #1790

Please ensure that the developerKey is properly appended to the request URL or included in the request headers. Check the request formation logic and configuration settings to confirm that the key is being correctly integrated with the OAuth token.

**Comment by WilliamAlmeida** [comment]
> Hello @WilliamAlmeida :)
> 
> fix: #1790
> 
> Please ensure that the developerKey is properly appended to the request URL or included in the request headers. Check the request formation logic and configuration settings to confirm that the key is being correctly integrated with the OAuth token.

But it is the Typebot application that needs to send the developerKey, as the developerKey has been added to the environment variable
