### ISSUE TITLE
Viewer not working, install using traefik portainer v. 2.28.2

### ISSUE THREAD

**Issue by UniVersos1** [baptisteArno/typebot.io#1796]
**Describe the bug**
Viewer 

not working

**To Reproduce**
1. login to builder then navigate to viewer, not working

**Expected behavior**
Viewer working

**Screen recording**
![Screenshot_30](https://github.com/user-attachments/assets/881602d2-4a81-4ca8-8edb-a7ba931feb17)

![Screenshot_31](https://github.com/user-attachments/assets/7002c734-287c-4b94-ad30-7cd378e60614)

**Comment by baptisteArno** [comment]
Can you provide the server logs? There should be a clear error there.

If you are self-hosting it with docker. Type this command in your terminal:

```sh
docker-compose logs
```

Paste all the logs here so that we can help you properly!

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
