### ISSUE TITLE
share link is https://undefined/

### ISSUE THREAD

**Issue by matsukky** [baptisteArno/typebot.io#180]
Hi. When I tried to share a typebot for the first time, i realized that the default link is `https://undefined/`. I wish to find out how I can solve this problem ? 
You should know that in my environment variables ``NEXT_PUBLIC_VIEWER_URL`` is well defined as ``https://bot.exemple.com/``, and i have no problem to access a typebot with ``https://bot.exemple.com/supercooltypebot``.

Thanks in advance for your help

I use Docker
Version of typebot : 2.8.8

**Comment by baptisteArno** [comment]
My guess is that `NEXT_PUBLIC_VIEWER_URL` is not declared in the builder's environment?

It should be declared in both the builder and viewer services 👍

Let me know if it works.

**Comment by matsukky** [comment]
I had put a stupid space when defining the variable... sorry for wasting your time...
