### ISSUE TITLE
Google Auth always enabled when using Google Sheets

### ISSUE THREAD

**Issue by lgaitan** [baptisteArno/typebot.io#1805]
Hello!

First of all, thank you very much for the effort you and the collaborators put in this awesome app.

I'm just trying Typebot self hosted, and I found out that you cannot disable Google Authentication when using the Google Sheets integration.

Since the environment variables are the same for both integrations, there is no way to disable each individually.
The variables are:
 - `GOOGLE_CLIENT_ID`
 - `GOOGLE_CLIENT_SECRET`
 - `NEXT_PUBLIC_GOOGLE_API_KEY`

I've also noticed that Google Fonts uses the NEXT_PUBLIC_GOOGLE_API_KEY. If the API is set to restrict, and the Web Fonts Developer API is not enabled, it throws an error when trying to customize fonts.

Do you think that creating flags for each integration would suffice?
I'm happy to take this one.

Thank you very much,
Lucius

**Comment by baptisteArno** [comment]
Indeed, that's an issue. Will see what I can do ASAP.

**Comment by lgaitan** [comment]
Do you need help?
I'd be happy to create a PR for this one.

I was able to find the code in question:
https://github.com/baptisteArno/typebot.io/blob/706a09535c880aa73d11b8a78096b945c701eec4/apps/builder/src/pages/api/auth/%5B...nextauth%5D.ts#L81-L87

Maybe we could created an env variable to explicitly disable Google Auth, something like `GOOGLE_AUTH_ENABLED` and set it by default as true if the other variables exist, so we maintain the current behaviour and don't lock people outside their typebot.

**Comment by baptisteArno** [comment]
a94f0f7ce7bcb2a9a3c71656f345487c8d3764b9
