### ISSUE TITLE
Regex in condition block doesn't work

### ISSUE THREAD

**Issue by kaminske** [baptisteArno/typebot.io#1806]
**Describe the bug**
"Matches regex" option in the condition blocks is not working  ( the string never matches the regex) I tried with the regex in the docs **/[0-9]+/** and the bot went to the flow where the string doesn't match the regex even though it does.

**Steps to Reproduce**
1. Add text input block
2. add condition block with match regex option and set regex 
3. set 2 flows one where the regex matches the other when it doesn't
4. Write string that should confirm with the regex 

**Expected behavior**
if the string matches the regex , the condition block should change the flow of the bot

**Comment by baptisteArno** [comment]
I could not reproduce the issue. Your regex matches any digits and it worked on my end 🤔

Can you provide a better reproduction?

**Comment by kaminske** [comment]
I tested it again and it seems to be working fine for me too , I'm not sure exactly what I did wrong for it not to work
also it seems that the "/" shouldn't exist in the regex contrary to what's in the documentation
