### ISSUE TITLE
Support both Transaction connection pooler and Session connection pooler for postgres

### ISSUE THREAD

**Issue by systems-move-dev** [baptisteArno/typebot.io#1808]
**Is your feature request related to a problem? Please describe.**
Right now we are forced to use `Session mode` connection to supabase as from .env we can only configure 1 database url and prisma migrations required session mode. This creates many db connections on supabase, which sometimes run out.

**Describe the solution you'd like**
Support the directUrl in `schema. prisma`. Internally Prismic would select the best connection for each 

**Describe alternatives you've considered**
I tried doing 2 runs - one for migrations where the db connection string in env is set to the session mode string, and when all migrations are ran, update db connection string env to the transaction mode string. But while the migrations are successful as expected, the next run fails to connect to the db as it still tries to run some migration ops that expects the session mode connection.

Other alternative I can think of is to turn off prisma migrations using env, but couldn't find that option.

**Comment by baptisteArno** [comment]
https://github.com/baptisteArno/typebot.io/issues/1712
