### ISSUE TITLE
Finish WhatsApp Session

### ISSUE THREAD

**Issue by arturritzel** [baptisteArno/typebot.io#1809]
i dont know if im in the right place to ask a question but its the "rightest" place that i could find

is there a way to finish an ongoing session of an user? for example, if the user is in the middle of a session, i want to finish it so the user can start it again. is there a way to do it using an api request or something like this?

**Comment by arturritzel** [comment]
self hosted btw

**Comment by arturritzel** [comment]
someone on discord suggested using jump node. i dont know if i was clear enough but i want to finish the session externally at any time so i dont think a node or any layout inside the bot would help me

**Comment by baptisteArno** [comment]
You can delete the associated results in the Results tab, it should also delete the linked session.
