### ISSUE TITLE
Viewer Problem - Error! Could not reach server. Check your connection {}

### ISSUE THREAD

**Issue by badibadey** [baptisteArno/typebot.io#1810]
Hey, 

I have a problem with my viewer, and I can't deal with it for a few days. The builder works very well, and when I try to test the bot I get the message “Error! Could not reach server. Check your connection {}”. The application is set up on vercel and supabase and has redirects to the domain. The logs from Vercel show as if there is not enough time to fulfill the request, maxDuration is set to 10 sec. 

It seems as if everything is running fine until the viewer is called. I am very much asking for your help !

Logs from: vercel, viewer, developer tools.

<img width="477" alt="Zrzut ekranu 2024-09-28 o 10 05 49" src="https://github.com/user-attachments/assets/1cd887e4-56cd-4940-a580-318e4d6aedb8">
<img width="533" alt="Zrzut ekranu 2024-09-28 o 10 06 38" src="https://github.com/user-attachments/assets/b80ecb16-db1c-416c-a651-291143165f69">
<img width="2238" alt="Zrzut ekranu 2024-09-28 o 10 10 51" src="https://github.com/user-attachments/assets/08e8d182-7c06-4e11-af7d-f2b763f26ca0">
<img width="372" alt="Zrzut ekranu 2024-09-28 o 10 13 07" src="https://github.com/user-attachments/assets/8bfa11f9-9253-49bc-8915-f32ad3644107">
<img width="996" alt="Zrzut ekranu 2024-09-28 o 10 18 52" src="https://github.com/user-attachments/assets/a3eca6af-db88-4c52-b227-c7f58f683a3f">
<img width="729" alt="Zrzut ekranu 2024-09-28 o 10 27 43" src="https://github.com/user-attachments/assets/31cd1200-e9a4-4246-a899-aca5f83d8146">

**Comment by baptisteArno** [comment]
It seems it times out. Is it happening with the lead generation template for example?

**Comment by baptisteArno** [comment]
Can you show your viewer environment variables?

**Comment by badibadey** [comment]
Yesterday it worked in the new bots, I checked now and today again there is the same error as in the template. I haven't made any changes since yesterday.

Here is my env variables:

<img width="1856" alt="Zrzut ekranu 2024-10-1 o 20 46 48" src="https://github.com/user-attachments/assets/dd81dd10-4969-464c-ab3c-f712eef864a2">


viewer variables in vercel (the same like builder):
<img width="460" alt="image" src="https://github.com/user-attachments/assets/b6e7304f-5467-41c8-a8e1-6d7d11ff5980">

viewer logs:
<img width="2223" alt="image" src="https://github.com/user-attachments/assets/e71cbcae-3a50-4fd3-8990-30dca92778ab">


max Duration is setting to 10.

**Comment by baptisteArno** [comment]
So it sounds like it is unstable. Can you increase the function limit?

**Comment by badibadey** [comment]
I can try to increase but it doesn't do anything, what value do you think would be appropriate?  

As far as I know vercel also doesn't accept more than 10 seconds in the hobby plan right? 

Do you think to try with heroku though or buying the plan will fix it?

Thanks.

**Comment by baptisteArno** [comment]
No I don't think so, you are it happens 100% with any bot? Or special situations?

There is a lack of information here I can't know what's wrong

**Comment by badibadey** [comment]
Yes, this happens every time you fire up the viewer on vercel, the previous information was wrong. 

I've really been trying to solve this for a month almost and I don't know what's wrong, does anyone have any ideas?

**Comment by baptisteArno** [comment]
Most likely due to your environment variables setup on the viewer, try delete most of them, try other database services. If none of this works, try to deploy somewhere else

**Comment by badibadey** [comment]
> open port 3002...
> 
> 
> 
> 

What do you mean?

**Comment by MudassarTariq** [comment]
Try opening it in Firefox or an incognito window. It worked for me, so it might work for you as well. I've attached screenshots for reference.
![Screenshot from 2024-10-08 20-08-56](https://github.com/user-attachments/assets/aa8f731a-ab49-4332-b966-cc107b8ddba3)
![Screenshot from 2024-10-08 20-09-07](https://github.com/user-attachments/assets/e5245b9a-f9aa-497d-91c1-f535d6058f9c)

**Comment by theervilha** [comment]
@badibadey I was facing the same issue. Increasing the function timeout limit solved for me.

In the file `apps/viewer/vercel.json`, change the `maxDuration` keys to 60

**Comment by badibadey** [comment]
Oh, thanks for respond Ueniry.

I purchased the pro plan on vercel and the viewer start working.
________________________________
Od: Ueniry ***@***.***>
Wysłane: Wednesday, October 30, 2024 3:04:57 PM
Do: baptisteArno/typebot.io ***@***.***>
DW: badibadey ***@***.***>; Mention ***@***.***>
Temat: Re: [baptisteArno/typebot.io] Viewer Problem - Error! Could not reach server. Check your connection {} (Issue #1810)


@badibadey<https://github.com/badibadey> I was facing the same issue. Increasing the function timeout limit solved for me.

In the file apps/viewer/vercel.json, change the maxDuration keys to 60

**Comment by tksgo-marcio** [comment]
> @badibadeyEu estava enfrentando o mesmo problema. Aumentar o limite de tempo limite da função resolveu para mim.
> 
> No arquivo `apps/viewer/vercel.json`, altere as `maxDuration`chaves para 60

Hi, I'm facing the same problem. How do I access this file? which command? thanks.

**Comment by mhyeganeh** [comment]
In my case the issue was related to my CDN DDoS protection. By disabling, the issue is gone!

**Comment by gittoptus** [comment]
@badibadey é erro de CORS no .env do view adicione 
=========================
 CORS (CRÍTICO)
=========================
ALLOWED_ORIGINS=https://dominio.com.br.
