### ISSUE TITLE
Google Auth Configuration

### ISSUE THREAD

**Issue by rahul-newtuple** [baptisteArno/typebot.io#1811]
The variable names to configure the auth client for Google are wrongly [mentioned](https://docs.typebot.io/self-hosting/configuration#google-auth) in the docs

They should be as following

```
GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET
```

where as in the docs they are mentioned as below which is incorrect

```
GOOGLE_AUTH_CLIENT_ID
GOOGLE_AUTH_CLIENT_SECRET
```

**Comment by baptisteArno** [comment]
You are right, the doc was updated too soon for the release of tomorrow. It will make sense with next release 🙏

**Comment by delcain** [comment]
> The variable names to configure the auth client for Google are wrongly [mentioned](https://docs.typebot.io/self-hosting/configuration#google-auth) in the docs
> 
> They should be as following
> 
> ```
> GOOGLE_CLIENT_ID
> GOOGLE_CLIENT_SECRET
> ```
> 
> where as in the docs they are mentioned as below which is incorrect
> 
> ```
> GOOGLE_AUTH_CLIENT_ID
> GOOGLE_AUTH_CLIENT_SECRET
> ```

Tanks a very lot. Two days trying to connect.
