### ISSUE TITLE
"NEXT_PUBLIC_E2E_TEST" is not recognized as internal or external command

### ISSUE THREAD

**Issue by Jorgelig** [baptisteArno/typebot.io#182]
After installing the dependencies and copying the .env files, in windows 10, with docker I get the error: "NEXT_PUBLIC_E2E_TEST" is not recognized as internal or external command. I looked for information in the configuration pages and I did not find what I should put as a value in the .env file for that variable or what dependency I would need to install

**Comment by baptisteArno** [comment]
Can you tell me what instructions you have followed?

**Comment by Jorgelig** [comment]
1. Clone the repo
2. Install dependencies
3. Set up environment variables
```
Copy apps/builder/.env.local.example to apps/builder/.env.local
Copy apps/viewer/.env.local.example to apps/viewer/.env.local
Copy packages/db/.env.example to packages/db/.env
```
4. Start the builder and viewer
``
pnpm dev
``
![image](https://user-images.githubusercontent.com/581672/207164148-a4dc5616-82be-485a-997c-17c6f6fc0827.png)


ñññ

**Comment by Jorgelig** [comment]
I already managed to make it compatible with windows 10, adapt the dev script:


`    "dev": "pnpm docker:up && cross-env NEXT_PUBLIC_E2E_TEST=false && turbo run dev --filter=builder... --filter=viewer... --parallel --no-cache",`
