### ISSUE TITLE
OpenAI Realtime Voice Intergration 

### ISSUE THREAD

**Issue by nkeilar** [baptisteArno/typebot.io#1820]
**Is your feature request related to a problem? Please describe.**
Add ability to talk using voice to bot using OpenAI (or Moshi) voice interface

https://platform.openai.com/docs/guides/realtime/concepts

**Describe the solution you'd like**
End user should be able to have a voice chat on our website

**Describe alternatives you've considered**
NA

**Comment by baptisteArno** [comment]
Realtime sounds not made for Typebot which is a step by step chat experience. I don't really see the use case here. 🙏
