### ISSUE TITLE
Typebot does not carry the flows

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#1836]
I was using Typebot and out of nowhere when I enter Typebot it does not carry the flow, I already looked at the Typebot and Postgres Logs and has no mistakes, I already did several tests, and Typebot only comes back when I create a new bank. Data in Postgres and I put this new bank on Typebot, but it comes zero that is what I do not, but I know the problem is not at stack and seems to be something related to the bank that was being used

I'm using the version typebot 2.23.0

typebot
<img width="891" alt="image" src="https://github.com/user-attachments/assets/a8326c83-39d0-41d0-9b6b-dd4d041f0c19">

postgres
<img width="986" alt="image" src="https://github.com/user-attachments/assets/c57b8ac1-2f53-4c60-a9c2-d7597bb7f31d">

typebot viewer
<img width="697" alt="image" src="https://github.com/user-attachments/assets/d6977d9c-7e43-430f-9ed5-b0480a2f9fb7">

typebot builder
<img width="703" alt="image" src="https://github.com/user-attachments/assets/fa7b46d5-3fd2-48e0-bc01-563ab5bae849">

**Comment by baptisteArno** [comment]
What do you mean by "bank"?

**Comment by RuanMD** [comment]
> What do you mean by "bank"?

I managed to solve it, there were some users who did not have access to any workspace, and therefore no typebot was loaded.
