### ISSUE TITLE
codições , 

### ISSUE THREAD

**Issue by shell2096** [baptisteArno/typebot.io#1837]
o bloco de condições esta com erro , não vou conseguir explicar direito mas vou tentar 
![Captura de tela 2024-10-14 050302](https://github.com/user-attachments/assets/9436e871-d121-464a-a58f-b9b59046aeb1)
nesse caso , os "status1,2,3" que tiver como "aguardando oponente" , era para ativar uma vairavel que esta com "aposta1,2 e 3 . 
assim aparecer essas variaveis no bloco de texto , mas aparece somente a aposta 1 . e ja testei , esta indo tudo bem , a condição que esta impedindo

**Comment by shell2096** [comment]
só para acrecentar , na condição coloquei todos como "status 1 " para ver se ia , mas só ler o primeiro

**Comment by baptisteArno** [comment]
English please 🙏

**Comment by shell2096** [comment]
the condition block has an error, I won't be able to explain it properly, but I'll try
Screenshot 2024-10-14 050302
In this case, the "status1,2,3" that had "waiting for opponent" was to activate a variable that has "bet1,2 and 3".
so these variables appear in the text block, but only bet 1 appears. and I've already tested it, everything is going well, a condition that is preventing

**Comment by shell2096** [comment]
just to add, in the condition I put them all as "status 1" to see if it would, but only read the first one
