### ISSUE TITLE
Test Button Does not work for whatsapp bots with set variable

### ISSUE THREAD

**Issue by SweetJenna** [baptisteArno/typebot.io#1840]
**Describe the bug**
Let us say I am using the test button, and my flow has a set variable that uses WhatsApp name or contact. Later, I call an API using that set variable, but it is impossible to test it from the test window because the set variable doesn't work.

**Expected behavior**
When testing from the panel, if I have a set variable with WhatsApp, the testing panel should prompt me to give a dummy user WhatsApp number and contact name so the flow works as expected and I don't need to go to WhatsApp to test.

**Comment by baptisteArno** [comment]
How can I reproduce? Step by step guide or video or typebot file please 🙏

**Comment by baptisteArno** [comment]
Closing, feel free to re-open
