### ISSUE TITLE
Webhook feature not working in v3.1.0

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#1871]
**Describe the bug**
The new [Webhook feature](https://github.com/baptisteArno/typebot.io/pull/1815#issue-2561979420) doesn't seem to be working

**To Reproduce**
I've set the ```NEXT_PUBLIC_PARTYKIT_HOST``` env variable to `partykit.<my-domain>`

**Expected behavior**
The webhook should get triggered properly and the incoming data passed on to the next block, when called. 
Instead, seeing these errors in the browser console:
```
WebSocket connection to 'wss://partykit.<my-domain>/parties/main/umxjy82z5vlctwkvgb9i417b/cm2zpu3j400058ofrua4bhkn8/webhooks?_pk=c23331e4-228b-43d0-8739-8676106fe41a' failed
```

**Comment by baptisteArno** [comment]
Well it sounds like your partykit server is not deployed. Are you sure it is?

> The PartyKit configuration is located in packages/partykit folder. You can deploy the server into production using bun deploy

**Comment by arladmin** [comment]
> Well it sounds like your partykit server is not deployed. Are you sure it is?
> 
> > The PartyKit configuration is located in packages/partykit folder. You can deploy the server into production using bun deploy

@baptisteArno 

I'm using the Docker method for deploying Typebot (https://docs.typebot.io/self-hosting/deploy/docker) and i didn't find anything there, regarding how/why to deploy PartyKit.

Also, no such information is available in the **Webhook** block documentation either (https://docs.typebot.io/editor/blocks/logic/webhook).

**Comment by baptisteArno** [comment]
More info: https://docs.typebot.io/self-hosting/configuration#partykit

**Comment by arladmin** [comment]
> More info: https://docs.typebot.io/self-hosting/configuration#partykit

@baptisteArno Why did you close this issue without resolving it? 

The docs only say:  "You can deploy the server into production using bun deploy."

Whereas, this cannot be executed in the docker based setup!

**Comment by baptisteArno** [comment]
For now Partykit cannot be selfhosted but will be at some point. Here is how you can deploy your partykit server https://docs.partykit.io/guides/deploying-your-partykit-server/

So indeed if you deploy your app with docker, you will have to deploy your partykit server manually on the side
