### ISSUE TITLE
NEXTAUTH_URL_INTERNAL exists only in the documentation

### ISSUE THREAD

**Issue by timoa** [baptisteArno/typebot.io#1875]
**Describe the bug**
Hi!

I started to write the Helm Chart to deploy TypeBot on Kubernetes.

I set the env variables, including `NEXTAUTH_URL` (https://chatbot.example.com) and `NEXTAUTH_URL_INTERNAL` (http://typebot-builder.typebot.svc.cluster.local:3000), but the `NEXTAUTH_URL_INTERNAL` env variable is never used.

I looked into the code and found that `NEXTAUTH_URL_INTERNAL` is not mentioned except in the documentation, where it is everywhere.

**To Reproduce**
Steps to reproduce the behaviour:
1. Search in the code the `NEXTAUTH_URL_INTERNAL` in your IDE (VScode, for example)
2. Only the related documentation will mention this ENV variable, not any code-related.

**Expected behavior**
Call internally the builder instead of its public URL

**Comment by baptisteArno** [comment]
Thanks for the heads up!
