### ISSUE TITLE
HTTP request being sent first than text

### ISSUE THREAD

**Issue by FelipeArruda** [baptisteArno/typebot.io#1876]
**Describe the bug**
I have a simple flow than sent a message and then a HTTP request that send a list of options throw Evolution API

<img width="629" alt="Sem título" src="https://github.com/user-attachments/assets/1f7bf71f-fe7f-41df-a017-adf150c5990c">

But I recevied the http request first than message.

![image](https://github.com/user-attachments/assets/839b8b7f-15e7-4190-a310-c0849ed9280f)

**To Reproduce**
Create a simple flow like the second image.

**Expected behavior**
First send the message and then the Http request.

**Comment by baptisteArno** [comment]
Expected! https://docs.typebot.io/editor/blocks/integrations/http-request#webhook-is-not-executed-in-the-right-order
