### ISSUE TITLE
stripe credential error

### ISSUE THREAD

**Issue by yd-915** [baptisteArno/typebot.io#188]
Hi, 

I have encountered this error after inserting my live public stripe key
![strpe](https://user-images.githubusercontent.com/74731447/208577950-f75ae62e-b67a-4087-938b-91afeeb701a2.png)

The loader on the button keeps spinning maybe I'm missing something.

Great project btw!

**Comment by baptisteArno** [comment]
What are you trying to achieve?

My guess is that you just want to have the Pro plan for your workspace?

Have you registered with the email corresponding to `ADMIN_EMAIL`?

**Comment by yd-915** [comment]
I just want to be able to link it to my stripe account so users can subscribe 

Or do I have to make my own products from my stripe account?

**Comment by baptisteArno** [comment]
Ok, check out the "Others" section in the configuration: https://docs.typebot.io/self-hosting/configuration/builder#others

You'll see all the Stripe variables that you need to add 👍
