### ISSUE TITLE
Global Navigation Trigger Word

### ISSUE THREAD

**Issue by avyaggarwal** [baptisteArno/typebot.io#1883]
I need a way such that whenever and wherever in the flow a user types some specific keyword (like main menu or menu), the bot jumps to a specific block. 

This is because many times the user is stuck in a long flow and we need some way to go to main menu or home on WhatsApp. 

Adding a button or a listener after each block is extremely hard to manage. 

I would really like to prioritise this if possible, this is very important to me, so if we can add this as an issue, I would love to sponsor!

**Comment by baptisteArno** [comment]
Duplicate https://github.com/baptisteArno/typebot.io/issues/1592
