### ISSUE TITLE
http request - Problem

### ISSUE THREAD

**Issue by patrickmdx** [baptisteArno/typebot.io#1885]
Hi, I hope you're doing well.

I would like to report an issue I'm experiencing with the HTTP Request block.
I need certain texts to be displayed before the HTTP Request, without requiring user inputs.
I watched your video about the wait block, but it doesn’t solve the problem since it requires a message to proceed.
Could you adjust it so that when the time is set to (-1), it bypasses the need for user input?
Here in Brazil, we use Typebot a lot with the Evolution API to integrate Typebot with WhatsApp, and this has been an issue for many users.
If you could implement this feature at some point, I would be eternally grateful.

Example:

![image](https://github.com/user-attachments/assets/842ec51d-c5ae-48fa-90b1-99909adde8ed)

https://github.com/EvolutionAPI/evolution-api/issues/540

**Comment by baptisteArno** [comment]
The wait block always expects the client to "re-request the server" that is how it works. You should make your client automatically send another request with "undefined" message

**Comment by patrickmdx** [comment]
I understand, but you could put in a future update a way to configure so that the flow follows the order of execution without executing the http request in front.
