### ISSUE TITLE
Avatar upload is looking for a json file instead of an image

### ISSUE THREAD

**Issue by GhaziTriki** [baptisteArno/typebot.io#1887]
**Describe the bug**
Click on change photo of the admin user. It asks for a json file.

**Expected behavior**
It should ask for a photo format file.

![image](https://github.com/user-attachments/assets/cb1b9b55-7156-4cd6-b0d3-129348d4c90c)

**Comment by baptisteArno** [comment]
That's odd. input accept attribue is `image/*` do you confirm? Can you inspect the input element and confirm that it has this `accept` attribute?

**Comment by GhaziTriki** [comment]
I tested it again and I can see image formats. Is there any area in the code that is looking for json files to upload? 🤔

**Comment by baptisteArno** [comment]
Yes, the import typebot input

![CleanShot 2024-11-18 at 08 26 24@2x](https://github.com/user-attachments/assets/9a1c4e9b-4bb8-4029-b5aa-ca9fb46d717d)

**Comment by baptisteArno** [comment]
I can reproduce on MacOS. Thank you for the report!
