### ISSUE TITLE
WhatsApp test token API

### ISSUE THREAD

**Issue by hiagodotme** [baptisteArno/typebot.io#1891]
**Describe the bug**
When trying to use the test number token that was provided to me on WhatsApp, Typebot does not accept it.

**To Reproduce**
Go to https://developers.facebook.com/apps/609642677156011/whatsapp-business/wa-dev-console , copy the access token for testing, and then follow the instructions to link WhatsApp to Typebot.

When you enter the token in Typebot and click continue, the message appears:

Token expiration was not set to *never*. Create the token again with the correct expiration.

**Expected behavior**
I was hoping to be able to use a test token while developing my bot, without exposing my production numbers.

**Comment by baptisteArno** [comment]
I am a bit confused, I am not really sure what you are talking about. Can you provide screenshots?

**Comment by MotazHakim** [comment]
i think he means that he can't use Whatsapp Business cloud API using the TEST NUMBER that META gives 
and integrate it with Typebot !

**Comment by hiagodotme** [comment]
This is because when you access the meta console and go to "WhatsApp" > "Api Settings", an access token for the test number is provided on this screen.

I wanted to use it so I wouldn't have to use my production number when building the bots.

However, when I use it, TypeBot refuses with the error in the issue. I believe that since this token is temporary, the backend is checking that it has an "expiration" period and denies its use.

**Comment by baptisteArno** [comment]
Right, you are misunderstanding this token is not what Typebot is asking for.

You need a System User token, that's not it. Please follow the instructions carefully, this should be clear enough 🙏
