### ISSUE TITLE
dify Could not create stream

### ISSUE THREAD

**Issue by diegobmg** [baptisteArno/typebot.io#1892]
**Describe the bug**
When testing dify blocks, it gives the error message

{
  "message": "Could not create stream"
}

**Expected behavior**
so that it returns the message coming from dify

**Comment by baptisteArno** [comment]
Can you share a reprodution? https://docs.typebot.io/editor/export-import#export-import-a-typebot

**Comment by diegobmg** [comment]
I managed to find the error in the part of not creating the stream, then in the typebot test it works, when I integrate it with my WhatsApp, it doesn't call dify and it stays frozen
[typebot-export-dify-mr4pey7.json](https://github.com/user-attachments/files/17850849/typebot-export-dify-mr4pey7.json)

**Comment by bielsilva713** [comment]
Hello. I have this same problem. Have you managed to resolve this yet?

**Comment by bielsilva713** [comment]
https://github.com/user-attachments/assets/461a3a0a-136c-426a-96bd-1f1806c26a78

**Comment by baptisteArno** [comment]
I can't reproduce so it is most likely an error in your inputs or config. Let me add a better error message for this.

**Comment by bielsilva713** [comment]
I tested it here and returned this "{
  "message": "TimeoutError: Request timed out"
}".

**Comment by bielsilva713** [comment]
I managed to solve the problem. On the dify endpoint you have to use https and it was http so it didn't work

**Comment by aolmkt** [comment]
> Consegui resolver o problema. No endpoint dify você tem que usar https e era http então não funcionou

Salvou aqui. Obrigado @bielsilva713
