### ISSUE TITLE
WhatsApp error: in reply state undefined.

### ISSUE THREAD

**Issue by m4ary** [baptisteArno/typebot.io#1903]
**Describe the bug**
The bot is functioning properly on fresh phone numbers but fails to work on one specific phone number that as contacting other bot. Each time a message is sent to the bot ,  the following log appears:
`Known WhatsApp error: Is in reply state undefined.`

**Expected behavior**
The bot should respond to messages sent or reset the session.

**Comment by m4ary** [comment]
I fixed it by delete all record in ChatSession, maybe a button or something inside the bot builder to do that.

Thank you

**Comment by baptisteArno** [comment]
This should not happen so if you find a way to reproduce that bug, please feel free to re-open! 🙏
