### ISSUE TITLE
Auto-scroll of very small chat window not correct

### ISSUE THREAD

**Issue by abdessalaam** [baptisteArno/typebot.io#1912]
**Describe the bug**
I want to make a tiny chatbot, 400px width by 145px height, and embed it on my page as a newsletter subscription form. So it will be very minimal, starting with the email input field.
However, the chat doesn't auto scroll correctly, and the answers and follow up questions are cropped below the form (unless the user scrolls manually, which is not intuitive).

**To Reproduce**
I have designed a flow.
I have specified max width and max height in Theme -> Chat -> Container as 400px x 145px
I have added the following to Custom CSS:

```
.typebot-chat-view {
  height: 145px;
}
```

**Expected behavior**
Chat auto-scrolls so the current answer or prompt is always visible in the middle, or at the bottom, but above the crop.

(Optionally, instead of auto-scroll, perhaps the follow up prompts could fade in and replace the old prompts in their exact places.)

thanks!

**Comment by baptisteArno** [comment]
Do you have a video? What flow should I create to see this?

**Comment by abdessalaam** [comment]
Hello. The flow is:
<img width="1099" alt="Screenshot 2024-12-08 at 1 28 04 pm" src="https://github.com/user-attachments/assets/0865f067-feef-40a9-b6cf-5df8e1376b55">

and the video:

https://github.com/user-attachments/assets/3bed4201-e62c-4f91-8a63-86143e786a27

As you can see, I need to scroll after each prompt / output, even though height 145px is specified both in the embed code:  
```
<typebot-standard style="width: 400px; height: 145px; "></typebot-standard>
```

 and in the Typebot - Theme settings, and even in the custom CSS field. Thanks!
