### ISSUE TITLE
[suggestion] Improvements to the field interface

### ISSUE THREAD

**Issue by brunoalbim** [baptisteArno/typebot.io#1928]
My request is not linked to an issue per se, just an update was made visually to the chat.

In the "@typebot.io/js@0.2.85/dist/web.js" version, the fields were more attractive, both the input text and the input textarea, being inside the box. However, in the recent versions I tested "@typebot.io/js@0.3.12/dist/web.js" the button is outside the box. This stops the input text until it doesn't hurt as much, but for the input textarea it has a bad structure.

I would like to be able to bring this, as I think this field interface could be improved, bringing a more optimized structure. I think it would be interesting to see the possibility of adding the button to the box.

before:
![image](https://github.com/user-attachments/assets/a0a9ac73-ff7c-4ed8-beae-85bc79caabfb)

after:
![image](https://github.com/user-attachments/assets/0b21fd6d-1f7f-4eab-9861-894982de90c0)

before:
![image](https://github.com/user-attachments/assets/2d14067b-a636-4ee7-83cf-a6e6baad7011)

after:
![image](https://github.com/user-attachments/assets/dcb257a0-e053-4c9a-9f64-d59f4cd6ac4a)

**Comment by baptisteArno** [comment]
Really not easy to implement that option as the structure is really different...

For me the semantic of having the button outside is more correct and it does not impact the look and feel that much. So I don't see myself implementing that as an option 🙏

**Comment by brunoalbim** [comment]
Thanks for the feedback.

Okay, as it was already a previous typebot structure, I thought it would be easier to go back.
