### ISSUE TITLE
Docker Images Not Updated Since October - Any Changes to Update Strategy?

### ISSUE THREAD

**Issue by ZimaBlueee** [baptisteArno/typebot.io#1929]
Hello,

I've noticed that the Docker images haven't been updated since October. I'm wondering if the Docker images are still being maintained and updated regularly? Has there been any change in the community's strategy regarding the updates of these images?

Thank you for your attention to this matter.

Best regards.

**Comment by baptisteArno** [comment]
Last update is 9 days ago:

- https://hub.docker.com/r/baptistearno/typebot-builder/tags
- https://hub.docker.com/r/baptistearno/typebot-viewer/tags

**Comment by ZimaBlueee** [comment]
@baptisteArno 
Thank you. I have been following your discord for a long time. I thought you hadn't updated since you posted a message. 
Thanks again.
