### ISSUE TITLE
Merge and improve Block and Variables Panels in one sidebar to clear the canvas and to improve UX

### ISSUE THREAD

**Issue by bst1n** [baptisteArno/typebot.io#1930]
I find that the two panels aren't very intuitive. I have to do a lot of clicking and concentrating to find what I want.

Here's a list of suggestions for improving the UX:
- we could unify the two panels because when both are open at the same time, the canvas is almost invisible
- in this new unified panel in a side bar, we'd have two sections, a block section and a variable section
- we could choose to collapse or expand this sidebar, and the display parameter would be preserved between sessions (currently it always returns to lock by default)
- this unified sidebar would be a little busier, so we'd need to be able to reduce the internal sections of the sidebar
- it would be nice to have a background colour different from that of the canvas to better define our vision when we're working
- we could remove the menu --- in the top right-hand corner of the canvas and place it in the navbar above to clear the canvas even better

**Comment by bst1n** [comment]
Within the variables section, there could be a system for filtering and sorting by creation date, variable name and type.

**Comment by baptisteArno** [comment]
> when both are open at the same time, the canvas is almost invisible

You could hide one of the sidebar easily. The right side bar is not meant to be opened all time, just when you need to either:
- Test the bot
- Have a better view of all the variables

I'm sorry, I really don't dig this. I don't really get what we're trying to fix with this. I find it great to have that right side bar to display additional menu like the variables list and other.

Think about Figma, they offer both sidebars, removing the right one is clearly impossible in the long run we'll have more options for the right sidebar

**Comment by bst1n** [comment]
Thanks @baptisteArno, I understand your point of view, you're the manufacturer. I'm simply providing my own user experience.

Figma is not a good comparison here. Figma is a tool for web designers who generally work on large HD screens.

Personally, I use Typebot during my holidays on a 15-inch screen and I don't know, my Typebot UX isn't as good as the product is. Maybe what I'm proposing isn't the right solution. But overall, the editing experience is pretty frustrating. A lot of clicks are needed, not always in the same place. Centralising the management of blocks and variables makes sense to me. We lat need to conduct a user survey to find out what users think of the edit experience, and maybe we'll come up with better ideas than that.

**Comment by baptisteArno** [comment]
> For example: the side bar on the left with the blocks is always open by default. I try to reduce it every session, but every time I reopen Typebot, it's locked again

That's a very good point, thank you! Created an issue for that https://github.com/baptisteArno/typebot.io/issues/1933

> my Typebot UX isn't as good as the product is. Maybe what I'm proposing isn't the right solution. But overall, the editing experience is pretty frustrating. A lot of clicks are needed, not always in the same place.

So yes, I basically am very interested in any frustration with an example. Then I can come up with a UX solution.

For example on your screenshot, I don't really get why the variables management panel button would be better placed on the left, what is wrong with it being on the right?

**Comment by bst1n** [comment]
Thank you for your time.

For me, the screen would be more naturally structured like this:

Left: Management (Block+Variable) / Centre: Canvas / Right: Test

But I agree that this is something that may not be true for everyone. Putting it on the left would be cognitively beneficial but that's up for discussion.

**On the other hand:**

I don't understand what _the little menu with the three little dots_ (export, documentation, settings) at the top right of the canvas does. I find that it gets in the way of the canvas, and creates confusion with the variables button which is right next to it. Couldn't it just be in the navbar?

Placing these two little buttons side by side _forces us to concentrate and aim correctly every time we want to open the variables panel_. And that creates frustration during editing.

In comparison, the block panel is perfect! Just slide the mouse to the left and the panel opens. You don't have to concentrate or be precise. In my opinion, the variables panel should be just as fluid, with a hover zone to open it instead of the click required.

**Comment by bst1n** [comment]
I'll try to import my UX comments into this thread bit by bit if that helps.

**Comment by baptisteArno** [comment]
Thanks.

Once again, I'm interested in detailed frustration (what currently happens and what you expected), not really improvement suggestions as these are totally subjective.

The variable management panel is really meant to be opened **rarely** so I don't want to make its button too present. I might even move that into the three dots button

**Comment by bst1n** [comment]
The frustration is described: I very often open the variables panel to reorganise and rename them, and this panel gives me a mental perspective on the progress of my bot's construction.

It's perhaps on this point that we don't understand each other. I open the variables panel as often, if not more, than the blocks panel. Because as I progress in the construction of my bot, I realise that I haven't named certain variables correctly, that others are useless, or that others can be combined.

When you add to that the fact that variables can't be ordered by type, date or name, and the fact that you have to click a very small button to access them, you end up with this famous frustration.
