### ISSUE TITLE
Webhook is not executed by sendMessage API

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#206]
I'm doing some tests and the webhook is not executed by the /sendMessage api, and also does not have any return from the api that indicates that there is a block with webhook
It's the same with google sheets and probably sending email

![Screenshot_1](https://user-images.githubusercontent.com/52453013/210268669-88ffd059-fd25-4e8d-baff-7d8a4b93aeb7.png)

**Comment by jtapeg** [comment]
I believe it is because the execution of the webhook is a frontend call

**Comment by baptisteArno** [comment]
Webhooks should work just fine with the API execution. I could not reproduce!

Can you provide a reproducible case?

**Comment by jtapeg** [comment]
I understand the problem is in isPreview true that's why the webhook didn't run, but if isPreview is false I can't restart the loop in any way through the API, I'll give you an example

See in the image below my example that I'm running through the API, in it I want that when the client has already passed through the bot, he writes something and starts again with his defined name, and this works very well in isPreview mode: true, but with isPreview: false he no longer responds after choosing what he wants to receive

Error answering 2:
Error: Request failed with status code 500
```JAVASCRIPT
{
data: {
      message: '\n' +
        'Invalid `prisma.answer.create()` invocation:\n' +
        '\n' +
        '\n' +
        'Unique constraint failed on the fields: (`resultId`,`blockId`,`groupId`)',
      code: 'INTERNAL_SERVER_ERROR'
    }
}
```

(He does not respond anymore after the place I marked in red)
![Screenshot_4](https://user-images.githubusercontent.com/52453013/210440711-380f296f-2461-4666-a363-0c59f75580bb.png)

An example of how it looked on whatsapp:
![image](https://user-images.githubusercontent.com/52453013/210440856-18dfc46f-a2e2-47f2-a2b5-ab9ec0306b4d.png)

**Comment by baptisteArno** [comment]
Thank you for reporting the bug! I can reproduce 👍

**Comment by baptisteArno** [comment]
I would love to know more how you implemented the WhatsApp "adapter" 👌

**Comment by jtapeg** [comment]
@baptisteArno so I already have a whatsapp chat system and I integrated it directly into the backend of my system, so I can control by code whether or not the contact enters the message flow, If you want, I can provide you with an account for you to test, you just need to send me a typebot token and a typebotId

I send the message I received on whatsapp to /sendMessage and parse the return to reply on whatsapp, that's basically it
![image](https://user-images.githubusercontent.com/52453013/210704688-6b6a4284-16a8-4461-b108-3496d493e007.png)

When the message arrives, check if the user has already started a bot, if not, it starts and if so, it continues
![image](https://user-images.githubusercontent.com/52453013/210705102-4f17ce43-9a57-4851-97c2-c85f20e3fbd9.png)

**Comment by jtapeg** [comment]
My code is still a bit messy and with repetitions as you can see but it's still in testing

And here's how I made the text parser to work on whatsapp
![image](https://user-images.githubusercontent.com/52453013/210705709-bc7d88be-0701-4047-9724-2051cbe760f5.png)

**Comment by baptisteArno** [comment]
That's nice 👏

**Comment by jtapeg** [comment]
@Jorgelig here is how i did the implementation in whatsapp

**Comment by fabiojiparana** [comment]
I have a problem with the webhook, typebot does not load the data into the variable with the api return. Does anyone have any idea what it could be?
