### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by josimarcordeiro** [baptisteArno/typebot.io#207]
Is it possible to include translations? How to translate? I could contribute with translations...

**Comment by baptisteArno** [comment]
Typebot for now is only available in English. I'm definitely planning on adding other languages soon! I will gladly have the help of native speakers for translations.

I guess you can translate Portuguese?

**Comment by josimarcordeiro** [comment]
Multi language support will be amazing. I'll be happy to help translate to Portuguese.

**Comment by baptisteArno** [comment]
Closing this in favor of #210
