### ISSUE TITLE
Add Portuguese, French and Deutsch language support

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#210]
- [x] account
- [x] analytics
- [x] auth
- [x] billing
- [ ] blocks
- [ ] collaboration
- [ ] credentials
- [ ] customDomains
- [x] dashboard
- [x] editor
- [x] folders
- [ ] graph
- [ ] preview
- [ ] publish
- [ ] results
- [ ] settings
- [ ] telemetry
- [ ] theme
- [ ] typebot
- [ ] variables
- [x] workspace

**Comment by jtapeg** [comment]
Hello @baptisteArno, as soon as you define the technology/method you are going to use to do the translation, I can start translating into Portuguese (pt-BR)

**Comment by fabioaraujobh13** [comment]
I also contribute with the translation

**Comment by denerFernandes** [comment]
Hi @baptisteArno I'm very impressed by your work and because it's an open source project, I started working on translation support and I wanted to send a pull request, but want to align my approach with what you've been thinking, I'm using react-intl, my idea is that language detection is automatic, not passed as a parameter in the url, but that it is available as a configuration on settings.

I am the translations as follows:

{page}.{text}, but it could be something like {component}.{text}, what do you think?

```
{
    "common.submit": "Submit",
    "common.more_info": "More info",
    "signin.dont_have_account": "Don't have an account?",
    "signin.sign_up_for_free": "Sign up for free",
    "signin.signin": "Sign In",
    "sigin.create_an_account": "Create an account",
    "sigin.register": "Register",
    "sigin.or_with_your_email": "Or with your email",
    "sigin.spam_message": "A sign in email was sent. Make sure to check your SPAM folder.",
    "sigin.continue_with": "Continue with",
    "workspace.members": "Membros",
    "workspace.upgrade_message": "Upgrade your plan to work with more team members, and unlock awesome power features 🚀"
}
```

I can make this available in a few days.

**Comment by baptisteArno** [comment]
Thank you for wanting to contribute to Typebot 💙

I actually was thinking of using https://github.com/QuiiBz/next-international. It's made by a friend, it is type safe and small.

I would prefer to push a version of Typebot using this lib (so that I can do proper testing), then you could maybe build on top. I can probably deploy that this week.

Would that work for you?

**Comment by yfffy** [comment]
> Thank you for wanting to contribute to Typebot 💙
> 
> I actually was thinking of using https://github.com/QuiiBz/next-international. It's made by a friend, it is type safe and small.
> 
> I would prefer to push a version of Typebot using this lib (so that I can do proper testing), then you could maybe build on top. I can probably deploy that this week.
> 
> Would that work for you?

Any progress on localization support?

**Comment by denerFernandes** [comment]
> Thank you for wanting to contribute to Typebot 💙
> 
> I actually was thinking of using https://github.com/QuiiBz/next-international. It's made by a friend, it is type safe and small.
> 
> I would prefer to push a version of Typebot using this lib (so that I can do proper testing), then you could maybe build on top. I can probably deploy that this week.
> 
> Would that work for you?

Hi @baptisteArno i'm sorry, I had a lot of work the last few days and I totally forgot about it.

Works for me, can you send that version? How do you suggest to organize the tags? I usually like to work by page or screen scope.

**Comment by baptisteArno** [comment]
Sorry guys, still in the pipes! I'm currently translating the Dashboard page and set up everything. Will be deployed fairly soon. I will notify you here.

**Comment by dfernandesbsolus** [comment]
Need help with this? I'm available if needed.

**Comment by baptisteArno** [comment]
I just deployed the translation strategy alongside the translation of `dashboard` and `folders` features  (#322).

We can now translate the application incrementally.

The easiest way for you to help if you are non-technical is just to provide the translations of specific pages in plain text in this issue. I'll do my best to translate everything asap.

**Comment by baptisteArno** [comment]
I've worked on more translations!

Can someone tell me how we can improve the current Portuguese translations? Look for the `pt.ts` file:

https://github.com/baptisteArno/typebot.io/pull/436/files#diff-4b3cc59d04ad00fb8a57e6f48c65c5a6d63f0c732a25dfa728268836fd559777

**Comment by baptisteArno** [comment]
Currently the application is ~40% translated. I will introduce even more translations soon.

For information I migrated the i18n lib to Tolgee to have an improved collaboration system. If you'd like to help with translating the application you should join the translation platform:

Portuguese: https://tolgee.server.baptistearno.com/accept_invitation/gIgHRUECUwFxHSbmsmIHfgHQKagCbIqEqBehpzjTQQIngCDYXt

German: https://tolgee.server.baptistearno.com/accept_invitation/fbIESVWDpLdYwQheyaptKKdDGupvunAXjsDYGfxRQEUIgwuddm

**Comment by baptisteArno** [comment]
#995
