### ISSUE TITLE
webhook error with linked Typebot flows

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#22]
We have created two Typebot flows (Flow 1 & Flow 2), each containing a webhook. We have linked the end of Flow 1 to the start of Flow 2 using Logic->Typebot (Jump to). 

The webhook in Flow 1 fires correctly.

After Flow 2 begins, there is an error (below), and the webhook in Flow 2 does not fire:

```
viewer:dx: error - (api)/pages/api/typebots/[typebotId]/blocks/[blockId]/steps/[stepId]/executeWebhook.ts (41:25) @ handler
viewer:dx: TypeError: Cannot read properties of null (reading 'blocks')
viewer:dx:   39 |       include: { webhooks: true },
viewer:dx:   40 |     })) as unknown as Typebot & { webhooks: Webhook[] }
viewer:dx: > 41 |     const step = typebot.blocks
viewer:dx:      |                         ^
viewer:dx:   42 |       .find(byId(blockId))
viewer:dx:   43 |       ?.steps.find(byId(stepId)) as WebhookStep
viewer:dx:   44 |     const webhook = typebot.webhooks.find(byId(step.webhookId))
```

Seems related to https://github.com/baptisteArno/typebot.io/issues/13

**Comment by baptisteArno** [comment]
Hey @teq-dev!

Can you tell me how I can reproduce it? I've tried with a minimal example, it worked well:


https://user-images.githubusercontent.com/16015833/162583561-80264c77-56f1-4511-b646-674d244a0e76.mp4

**Comment by teq-dev** [comment]
Hello! It does work for me in Preview mode, but when I make the Typebot public and share it, then the error happens:

https://user-images.githubusercontent.com/90119409/162584384-d653c0e3-bae9-492b-b8b0-c6f10c33feba.mp4

**Comment by baptisteArno** [comment]
Ok, managed to reproduce and it is fixed with the latest commit on main. Thank you Jason!
