### ISSUE TITLE
The zoom of the groups loses the sharpness of the image

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#223]
I don't know if it's possible to improve this maybe it's something in the browser but when editing the title it focuses on the texts and it's sharp and it has some more behaviors that make it sharp too even with zoom

![image](https://user-images.githubusercontent.com/52453013/211051481-f0ce3f4e-c0cd-4039-a895-eab9aa35e1a9.png)

![image](https://user-images.githubusercontent.com/52453013/211051969-2b0203ee-0a66-4416-a63d-a1b62cda58fd.png)

**Comment by baptisteArno** [comment]
That's a weird one 😅

I'm not sure if we can even do something about this. This is probably due to how your web browser renders the site. I can't really reproduce (Chrome on MacOS)

**Comment by jtapeg** [comment]
I think it's a system thing
