### ISSUE TITLE
Custom OAuth callback URL doesn't work it uses the wrong method

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#229]
Issue #224 commit did not fix anything, the same error is coming up.

**Comment by Lanhild** [comment]
I did set `CUSTOM_OAUTH_ENABLE_ID_TOKEN` to `true`.
I'm using https://github.com/goauthentik/authentik as my OAuth provider.

If you want to take a look at my configuration:
https://auth.konvergo.app/application/o/konvergo-bot/.well-known/openid-configuration

**Comment by baptisteArno** [comment]
I tested locally and made the appropriate changes. You need this config to make it work with Authentik:

```sh
CUSTOM_OAUTH_WELL_KNOWN_URL=http://localhost:9001/application/o/typebot/.well-known/openid-configuration
CUSTOM_OAUTH_CLIENT_ID=...
CUSTOM_OAUTH_CLIENT_SECRET=...
CUSTOM_OAUTH_USER_ID_PATH=sub
```
