### ISSUE TITLE
Add more options in the bot button menu in the dashboard

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#232]
![image](https://user-images.githubusercontent.com/73610779/211374551-ac659888-2fcf-455c-bd81-93552a44388d.png)
Add options in the menu to Close, Unpublish/publish a typebot instead of having to open its editor

**Comment by baptisteArno** [comment]
It's deployed on main 🎉

I just added the Unpublish option because I don't see why anyone would want to publish a bot from the dashboard.
