### ISSUE TITLE
Possibility to use a variable as Button's value

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#236]
Using a variable as Button value will help us to create conditions without having to repeat values.

**Comment by baptisteArno** [comment]
You already can insert variables in buttons, that should work (i.e., "{{Name}}") 😀

**Comment by erickriva** [comment]
There's no button to 'add variable', like in other operations, so I got a little bit confused 🥲

**Comment by baptisteArno** [comment]
Indeed, that could be an improvement!

**Comment by baptisteArno** [comment]
- [ ] Add multiline editor
- [ ] Add variables button

**Comment by baptisteArno** [comment]
This issue is stalling. The ratio "difficulty of implementing / usefullness" is too big for this.
