### ISSUE TITLE
Variable containing 'value' and 'label'

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#241]
It's already possible to do it, with condition and 'set variable' blocks, adding a second variable to keep 'transformed' value from main variable... but would be nicer to have 'value' and 'label' scheme deepier integrated into the platform.

It tends to become messy when done multiple times.

**Comment by baptisteArno** [comment]
It shouldn't be messy if done right! You can simply add a "Set variable" below your input to format the answer.

<img width="359" alt="CleanShot 2023-01-13 at 08 15 47@2x" src="https://user-images.githubusercontent.com/16015833/212260196-f1f875e4-e385-4e02-b1d4-c2ca8a5bbb56.png">

That looks clean to me!

Do you have a specific use case in mind?

**Comment by baptisteArno** [comment]
I understand the issue. Unfortunately, I can't think of an intuitive way to display this in the builder. And it would require major changes on how the typebot saves the answers.

We will eventually have a "Custom block" feature (#249) where we'll be able to aggregate a specific flow into a block that is reusable. That will definitely help with the mess you are talking about.

I'll mark this issue as not planned for now 👍
