### ISSUE TITLE
Readonly prefix/suffix in Input components

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#242]
**Use case:**
I'm asking for user's linkedin.com URL using a website block. I would like to ask only for linkedin username, but with a visual indication of that.
`https://linkedin.com/in/` would be the readonly prefix visible to the user, that would be added to the final value when setting on a variable.

I know it can be done through Set Variable block, asking only for 'username', but there is no 'visual indication' nowadays.

Not much important, but just a hint.

**Comment by baptisteArno** [comment]
That can be nice!

Visually, it could look a bit like that: https://chakra-ui.com/docs/components/input/usage#left-and-right-addons

**Comment by Jorgelig** [comment]
@baptisteArno Are you seeing it as a new component or as options to the current Input Text ?

**Comment by baptisteArno** [comment]
New options on the existing text input block

**Comment by erickriva** [comment]
Prefix/Suffix will have an option to append/prepend value (so it can be visual-only or added to final value)?

Do you think it can be used in both ways?

**Comment by baptisteArno** [comment]
I think it should always be added to final value! I can't think of a use case where you don't want it to be added?

**Comment by erickriva** [comment]
Just dropping ideas to discuss. Can't think of an use-case right now.

**Comment by baptisteArno** [comment]
Issue stalled
