### ISSUE TITLE
[typebot-js] onNewVariableValue not being called

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#243]
[typebot-js] `onNewVariableValue` callback not being called when an answer is changed by the user

https://user-images.githubusercontent.com/2746558/212133659-f856e88c-86d9-4a72-8116-1f5dc046acb4.mp4

**Comment by baptisteArno** [comment]
Indeed!

But, answer editing will soon be removed from the product. Its UX is just bad.
