### ISSUE TITLE
Button behavior

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#246]
I believe that either I didn't understand the behavior of Default or it has a bug, I wanted to use it that way but I can't because when I get an invalid response it doesn't go to the Default block

![image](https://user-images.githubusercontent.com/52453013/212263325-91ca0e5b-ae80-45e3-95f0-ea6fec3e0e95.png)

![image](https://user-images.githubusercontent.com/52453013/212263428-b46cc5c6-bb49-47f0-b637-076d02e04ad9.png)

**Comment by jtapeg** [comment]
If I answer the same he acts as expected

![image](https://user-images.githubusercontent.com/52453013/212263867-1cd98e23-a661-4c9e-80a1-d2f2484585e8.png)

**Comment by jtapeg** [comment]
This works great, but using the button would be better because you don't need to collect the variable
![image](https://user-images.githubusercontent.com/52453013/212264482-133bcd2c-da1c-4dc7-b24c-e5a7f31d26ac.png)

**Comment by baptisteArno** [comment]
Your single choice "Button" input is expected to receive Yes or No input value only. That's totally expected.

Default item is just here to connect all the non-connected choices.
