### ISSUE TITLE
Migrate all typebots default background type

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#248]
Currently, the default typebot is "None" which should correspond to a transparent background. But in reality, a white background is currently hard-coded everywhere.

We need to:

- [x] Change the default background type to `Color` with default value of `#ffffff`
- [ ] Migrate all the existing bots default background (would be nice to do that with a prisma SQL migration)

**Comment by Jorgelig** [comment]
For the first point, are you talking about this line?

![Image](https://user-images.githubusercontent.com/581672/212459113-361a3df5-923e-4418-b385-07e8f13fe783.png)

**Comment by baptisteArno** [comment]
Yes! But don't bother with this, I'll do it soon 👌
