### ISSUE TITLE
Add a Back button in bots

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#251]

**Comment by tgdn** [comment]
Hey @baptisteArno, thanks for the awesome work on Typebot.io! 

I came here looking for this, this means that there is not "edit" button on the chatbots? 

I find it difficult to use a solution that doesn't allow for editable inputs, as this usually tends to be needed when users make mistakes etc.

Do you have any idea when such a solution could be implemented? 

Thanks!

**Comment by baptisteArno** [comment]
Editing in a web based experience is easy. But what about WhatsApp? How do you offer the editing feature?

**Comment by tgdn** [comment]
@baptisteArno the back / edit button would only be available in environments that allow it. In WA, this wouldn't be possible.

**Comment by ortizroberto** [comment]
Hi @baptisteArno, I saw on the typebot's roadmap website that you said it's possible to edit by clicking on the bubble, but I can't seem to make it work, is there a setting toggle that I should be looking for? Thanks

**Comment by baptisteArno** [comment]
I'd like to re-introduce message editting (like all chat platforms are doing). #1079 

I've decided not to implement any type of back button as it is against a propre chat UX which always go forward.

**Comment by tgdn** [comment]
The "go back" doesn't necessarily need to go back. It can go forward, and instead jump back to the previous message (with the next messages pre-filled).
