### ISSUE TITLE
Implement an "OpenAI" block

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#253]

**Comment by bunny66** [comment]
Getting 400 response. probably this could help https://stackoverflow.com/questions/75650840/openai-chatgpt-gpt-3-5-turbo-api-error-400-bad-request-migrating-from-gpt But thanks so much guys for the prompt delivery of this issue. Fastest in the market🙌

**Comment by baptisteArno** [comment]
Hmmm, Can you tell me how I can reproduce it? Because it works fine on my end.
