### ISSUE TITLE
We have discovered that the Typebot input file feature does not currently work on iPhones. We have tested it on an iPhone 13 and have confirmed that it does not appear

### ISSUE THREAD

**Issue by marcosmarf27** [baptisteArno/typebot.io#257]
We have discovered that the Typebot input file feature does not currently work on iPhones. We have tested it on an iPhone 13 and have confirmed that it does not appear?

**Comment by baptisteArno** [comment]
Could you provide a reproduction?

I tested out on an iPhone 12, on Safari, it works fine!

**Comment by baptisteArno** [comment]
I'll close this for now. Feel free to re-open if you can tell me how I can reproduce 👍
