### ISSUE TITLE
How about a export ALL bots feature ?

### ISSUE THREAD

**Issue by altomarketing** [baptisteArno/typebot.io#263]
If you have more than 20 bots, to export all one by one, by hand **its a waste of time**.

How about a button, **to export all bots**, folders and configurations, so it can be imported again in case of crash of disaster or typebot vps instance ?

**Comment by baptisteArno** [comment]
I'm not sure whether that would be relevant.

You should be able to be safe against a disaster on your VPS by doing regular backup of the database associated to Typebot
