### ISSUE TITLE
Set variable code error in self-hosting

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#266]
I have this problem when trying to run a code can you help me

![image](https://user-images.githubusercontent.com/52453013/213511454-253336a1-7196-488f-8306-583cd2739e1d.png)

![image](https://user-images.githubusercontent.com/52453013/213511958-ca466214-73f1-4c21-b8ba-52d62e0679c7.png)

**Comment by baptisteArno** [comment]
I can't reproduce on the official Typebot app.

My guess is that your server proxy is adding Content Security Policy directives?

**Comment by jtapeg** [comment]
Thank you very much @baptisteArno, I managed to solve the problem with your tip!

![image](https://user-images.githubusercontent.com/52453013/213772556-6ddae7e4-18d0-45d0-9929-427961816802.png)

**Comment by bhuvnesh-vcti** [comment]
hey, @jtapeg  I'm also facing same issue. Where did you add these lines of code?
