### ISSUE TITLE
Auth providers

### ISSUE THREAD

**Issue by odmincheg** [baptisteArno/typebot.io#27]
@baptisteArno I trying to run the app with docker... that app is building and starting fine. 

Next step, I try to use nginx over that docker and proxy requests with the domain app.example.com

I set **NEXTAUTH_URL=https://app.example.com**
What I should set in .env.production to get something more like this https://monosnap.com/file/xs17jNNfoXlbR8Ah3eFJ2Emil6Zj5b ?
For example, I want to have Google auth, and regular authorization by email... Maybe somewhere is a list of correct values?

**Comment by baptisteArno** [comment]
Please check https://docs.typebot.io/self-hosting/configuration. Everything is explained here. If you want to set up Google Auth, you'll have to create your own Google application: https://console.cloud.google.com/apis/credentials?project=typebot-v2

> NEXTAUTH_URL=https://app.example.com/
This won't work, you need to set the real public URL

**Comment by baptisteArno** [comment]
I'm closing it as there's no issue here. Feel free to create a discussion post if you just have questions :)

**Comment by odmincheg** [comment]
Yes, I set the real public URL for the  NEXTAUTH_URL ... also, which correct URL should be for the viewer (created bots)? should be that like some sub URL for example **/bot**? And under docker containers, which param I should use to explain builder and viewer communicate with each other and use docker host values?

**Comment by odmincheg** [comment]
@baptisteArno which **Authorization callback URL** I should use for GitHub app configuration? As I understand, there should be something like https://my_domain.here/api/oauth ? And also will be the same URL for each auth provider?

**Comment by baptisteArno** [comment]
Sorry for the late reply!

It should be: `$NEXTAUTH_URL/auth/github/callback`
