### ISSUE TITLE
The string did not match the expected pattern.

### ISSUE THREAD

**Issue by j-dogcoder** [baptisteArno/typebot.io#270]
When using a webhook, I get the error `The string did not match the expected pattern.` Unsure as to what is wrong here...

**Comment by baptisteArno** [comment]
Where do you get this error?

Is there any issue? Because, it can also just be an informational message.

**Comment by j-dogcoder** [comment]
It also continues to try the request... it it waiting for a response from the webhook?

**Comment by j-dogcoder** [comment]
Thoughts on this @baptisteArno?

**Comment by baptisteArno** [comment]
Can you provide a way for me reproduce the issue?

**Comment by baptisteArno** [comment]
Will close this. Feel free to re-open if you have a minimalist reproduction 🙏
