### ISSUE TITLE
Google Fonts (DSGVO)

### ISSUE THREAD

**Issue by freshwebs** [baptisteArno/typebot.io#271]
Good day,

how can i disable google fonts?

Google Fonts are not legal in Germany without consent.

**Comment by baptisteArno** [comment]
Are you talking about Google Fonts in the builder or in the bot? Can you show me where you want Google Fonts to disappear?

**Comment by freshwebs** [comment]
Thank you for your reply.

I'm talking about the public part (i.e. the viewer).

Can you please add a function to the backend so that no Google Fonts CDN is integrated. You can use the Custom CSS Field to decide for yourself whether you want to include fonts from external sources.

**Comment by baptisteArno** [comment]
Indeed, if you leave the Font theme input empty, it shouldn't load any Google Fonts CDN URL.

That's a current issue.

**Comment by freshwebs** [comment]
![image](https://user-images.githubusercontent.com/3452287/214784512-b55d2dd0-39c4-48a8-b0cf-d80f9c607886.png)
![image](https://user-images.githubusercontent.com/3452287/214784581-238aa68e-1505-4532-9172-9d25980e63ac.png)

Good morning, if you leave the field for the Google Fonts empty, it will still include the URL. Although this causes an error because the font specification is missing, the user is still contacting Google's US servers at this moment, and this unfortunately constitutes a violation of the GDPR.

The whole URL should no longer load if the field is empty.

**Comment by baptisteArno** [comment]
That's what https://github.com/baptisteArno/typebot.io/commit/14e6ee373fa141af6d3b2aa39a93b5a7b1f862ec fixes

You need to wait for the next release or pull the image tagged `main`

**Comment by freshwebs** [comment]
Thank you, i pulled ``main`` and it works flawless :-)
