### ISSUE TITLE
Add a new UNLIMITED plan for self-hosting version

### ISSUE THREAD

**Issue by shashicpontentwriter** [baptisteArno/typebot.io#273]
Hi baptisteArno, Could you please share the env variable to increase the default file storage?

**Comment by baptisteArno** [comment]
There's a hard limit at 10 Go. I should probably set up a new UNLIMITED plan for the self-hosting version.

**Comment by shashicpontentwriter** [comment]
Good bro, Because that makes sense, and we already have more storage than that, we can use it once you make it unlimited; is there an ETA on this?

**Comment by baptisteArno** [comment]
Will do that today 👌

**Comment by shashicpontentwriter** [comment]
Awesome bro
