### ISSUE TITLE
The file upload URL is not detected in webhooks

### ISSUE THREAD

**Issue by realsubinbabu** [baptisteArno/typebot.io#278]
Hi bro, When I send file-uploaded webhook data to Pabbly Connect or other third-party apps, the file-uploaded url is detected as "http://fake-upload-url.com".
![file upload issue typebot](https://user-images.githubusercontent.com/92963823/215039907-a2b938be-fdce-47d8-92a5-c5afa21c279e.PNG)

**Comment by baptisteArno** [comment]
It's expected.

What you see here is a generated data. It just helps you to display all the possible inputs.

**Comment by realsubinbabu** [comment]
I understand that, in that case, it appears that the issue is related to the generation of the file URL in the webhook. There is likely an issue with the code or logic that is generating the URL, which is causing it to be incorrectly set to "http://fake-upload-url.com/". Can you check once?

**Comment by realsubinbabu** [comment]
Leave webhooks, bro. But I need to show the URL of the uploaded file link to users, and here it shows the same fake URL. I saved uploaded file data to a variable called "{{files}}" and linked to it in the text block. Please check.
![webhooks file url issue](https://user-images.githubusercontent.com/92963823/215142734-e1bfd93b-fa12-4396-a414-42830bda114a.PNG)

**Comment by realsubinbabu** [comment]
Ok, I hope we will get a solution soon for this 👍😊
