### ISSUE TITLE
profile image loading and remove ads banner

### ISSUE THREAD

**Issue by shashicpontentwriter** [baptisteArno/typebot.io#283]
Actually we are in unlimited plan, so why these ads banner? Can you please disable this? And after updating to 2.9.4, I am unable to upload a profile images or files. It's loading...

![why these ads](https://user-images.githubusercontent.com/123541173/215912590-14f6df20-5014-46da-a01f-0fbb3e557a2f.PNG)

![minio](https://user-images.githubusercontent.com/123541173/215923931-545b8e4e-f41d-45fe-b414-0a9be2fe7743.PNG)

![loading](https://user-images.githubusercontent.com/123541173/215912688-dfd87458-9df2-4d98-a35b-17ef036816a1.PNG)

I think its related to Minio/storage.

**Comment by baptisteArno** [comment]
Thank you, the fact that you see the banner is a bug.

For the file upload, can you open another issue? (Have you set up correctly a S3 storage?) https://docs.typebot.io/self-hosting/docker#s3-storage

**Comment by shashicpontentwriter** [comment]
Okay, I hope you were able to resolve the bug soon. And, yes, file upload worked prior to the update; after the update, only this issue arise.

**Comment by baptisteArno** [comment]
Open a new issue with the server logs, you should find an error.
