### ISSUE TITLE
The webhooks block doesn't import values

### ISSUE THREAD

**Issue by shashicpontentwriter** [baptisteArno/typebot.io#284]
I built a bot using the SMS API that verifies the SMS after the user submits it, and it works flawlessly. However, after exporting that bot, one of the users who attempted to import it received zero values, indicating that all blocks were imported but the webhooks block did not import the data. Can you please check?.

![webhooks not there](https://user-images.githubusercontent.com/123541173/215956069-bdcd9fec-3ad8-4ba0-a219-4df4c0ba5925.PNG)

**Comment by baptisteArno** [comment]
Is the user you are sending the bot to is using the same Typebot instance?

Because when importing a typebot, it tries to duplicate the webhook as well but they need to exist in the database.

**Comment by arladmin** [comment]
I'm facing the same issue in the latest version.

When i import a flow, the Webhook blocks lose all of their config data.

I've tried importing in the same instance, as well as Typebot's cloud platform.

**Comment by baptisteArno** [comment]
The Webhook configuration behavior have been improved. There's a great chance it has been fixed 🙏
