### ISSUE TITLE
After the update, file uploads are not working.

### ISSUE THREAD

**Issue by shashicpontentwriter** [baptisteArno/typebot.io#285]
After the update, file uploads are not working, so I opened a new issue here. Please check.

![215923931-545b8e4e-f41d-45fe-b414-0a9be2fe7743](https://user-images.githubusercontent.com/123541173/215978615-b8472b4e-f6cc-4fb1-bdf6-795a4ccb2e7e.png)

**Comment by baptisteArno** [comment]
We need the logs 🙏

**Comment by shashicpontentwriter** [comment]
I apologise for removing Typebot from the server. and installed a fresh copy using the configuration (screenshot), which now works perfectly. I didn't save the logs; sorry for that.

![cob](https://user-images.githubusercontent.com/123541173/215983087-b22a58b4-e688-43f7-8bfe-d5215c1425ed.PNG)
