### ISSUE TITLE
Migrate to Planetscale database

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#287]
This concerns the cloud deployed Typebot and should not impact existing self-hosted versions.

Mysql and Postgresql clients should co-exist.

The goal is to have 0 downtime.

- [x] Try to convert some `Json` types to `Json?`. If ok, then update `[]` values to `NULL`.
- [x] Add `createdAt` and `updatedAt` fields where necessary.
- [x] Add `updatedAt` temporary indices
- [x] Dump the initial data
- [x] Deploy project with both possible Prisma client (Postgresql and Mysql)
- [x] Prepare Planetscale schemas
- [x] Inject a bunch of data
- [x] Test in dev branch to see if there are any query optimizations to make
- [x] Launch a sync between the 2 databases
- [x] Deploy with new `DATABASE_URL`

**Comment by shashicpontentwriter** [comment]
Can we do it with self-hosting, so we can save some money? Are there any instructions available?

**Comment by baptisteArno** [comment]
What do you mean saving money? Planetscale is a paid service! 😂

**Comment by shashicpontentwriter** [comment]
Bro, they have a free plan; that's why I asked.

![free](https://user-images.githubusercontent.com/123541173/216809512-8ea984a4-d90f-4fe3-9b8e-f05f4fe5e90e.PNG)

**Comment by baptisteArno** [comment]
Oh, yeah, I forgot 👍

Will write a guide once I migrated the cloud version.

**Comment by shashicpontentwriter** [comment]
Thanks bro

**Comment by baptisteArno** [comment]
If you're looking for a free PostgreSQL database, take a look at Supabase 👌

**Comment by shashicpontentwriter** [comment]
Yes, but the limits are extremely low if you use their cloud version. Database storage of up to 500 MB and file storage of up to 1 GB with 2 GB of bandwidth are available, but Planetscale's free plan appears to be more generous.
