### ISSUE TITLE
Multiple console logs

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#289]
These console logs, when evaluating string-valued variables, are showing all the time. It distract us from real application's logs when integrating with a website.

![image](https://user-images.githubusercontent.com/2746558/216710777-df8d729a-93a1-4c91-a8e1-a52d111fd28e.png)

**Comment by baptisteArno** [comment]
Indeed, that's for debugging purpose, but I don't think anyone really had to use it
