### ISSUE TITLE
Files are not uploading

### ISSUE THREAD

**Issue by shashicpontentwriter** [baptisteArno/typebot.io#294]
Hi Bro, I wanted to bring your attention to an issue I am currently facing with file uploads on my server. I upgraded my server to a higher configuration recently and since then, the files are not uploading. I have a log output for you to see.

I wanted to mention that this issue happened before as well, but I didn't see the logs. Same problem arise when I updated the Typebot last time. Can you please take a look and let me know if there is a solution to this? Thank you!

![logs](https://user-images.githubusercontent.com/123541173/216810835-257daf2e-045c-4f64-b63d-54bdb5a28b66.PNG)

**Comment by baptisteArno** [comment]
Can you tell me exactly where you upload a file and what kind of file you are uploading? Any error it displays on the app? Any other error in the logs?

**Comment by shashicpontentwriter** [comment]
I will explain.

I hosted Typebot on a $5 droplet from Digital Ocean, and I upgraded to a $10 plan, so if you need to upgrade, you obviously need to shut down the server, right? Okay, everything works perfectly after the successful upgrade, but I can't change my profile and can't upload files in blocks. This is the story.

There are no errors on the app, and I only have these logs.

**Comment by baptisteArno** [comment]
Try to upload a text file in a bot with a file upload input. What does it do? Loading indefinitely?

**Comment by shashicpontentwriter** [comment]
Yes tried, here is the log, and file upload screenshot:

![erroe](https://user-images.githubusercontent.com/123541173/216924352-96d70233-fec8-40bc-90ce-969537548821.PNG)

**Comment by baptisteArno** [comment]
These logs are associated to the builder, that's not it. You should have error logs for the viewer. What command are you running to see the logs?

`docker-compose logs` should do the trick`

**Comment by shashicpontentwriter** [comment]
I am using this "docker-compose logs typebot-builder" and may i know the reason for this error?

**Comment by baptisteArno** [comment]
This should be ignored. You must have something else after trying to upload a file.

**Comment by shashicpontentwriter** [comment]
OK, let me uninstall it and I will reinstall it again 😂
