### ISSUE TITLE
"Set variable" block – inconsistent behaviour

### ISSUE THREAD

**Issue by abedef** [baptisteArno/typebot.io#296]
It seems that when preceded by an input (i.e. text or date), the "set variable" block does not correctly _set_ the variable.

I attach a screenshot to illustrate this more clearly. In the first case, I set a value to variable `A` and display it.  Next, I collect a text input, and as before I set a value to variable `B`. However, in this case it seems that it is not set as I expected it to be.

It is worth noting this issue is only a minor annoyance, since it can be mitigated by moving the "set variable" block to the beginning of its own group.

![unexpected](https://user-images.githubusercontent.com/6138405/216851636-2264a61b-ff72-48bb-a23d-c0675308133f.png)

P.S. I admire the level of quality and polish in this product. Amazing work! I look forward to using it in many future projects.

**Comment by baptisteArno** [comment]
Hey friend,

Indeed, it's a known issue (#40). Only happening on the preview bot.

Once #211 is deployed, it won't be an issue anymore 👌
