### ISSUE TITLE
Dropdown select block

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#308]
A block that would allow for dropdown values. Ideally, we could fill it with variables values coming from a sheet, etc.

**Comment by arladmin** [comment]
Just found about this!

Had already opened a discussion regarding the same feature
https://github.com/baptisteArno/typebot.io/discussions/336#discussion-4896421

**Comment by Lanhild** [comment]
Hey @baptisteArno , any updates on this?

**Comment by baptisteArno** [comment]
No update. I am still not sure what form it should have. Would something like the first example here: https://chakra-ui.com/docs/components/select/usage would suit your need?

**Comment by arladmin** [comment]
> No update. I am still not sure what form it should have. Would something like the first example here: https://chakra-ui.com/docs/components/select/usage would suit your need?

@baptisteArno i would say, for the first version, this sir be sufficient. Maybe upgraded later to a component that's better/more functionality (like also search option within the select, e.g. https://codepen.io/vdhug/pen/xxbPoJe).

There's also this library that i sometimes use: https://choices-js.github.io/Choices/

**Comment by Lanhild** [comment]
>No update. I am still not sure what form it should have. Would something like the first example here: https://chakra-ui.com/docs/components/select/usage would suit your need?

That would be fine, yes. The most important part would be that I'm able to fill the dropdown values from a variable

**Comment by Lanhild** [comment]
>No update. I am still not sure what form it should have. Would something like the first example here: https://chakra-ui.com/docs/components/select/usage would suit your need?

That would be fine, yes. The most important part would be that I'm able to fill the dropdown values from a variable

**Comment by Lanhild** [comment]
Hey @baptisteArno 
Do you have an ETA about when this might be released?

**Comment by baptisteArno** [comment]
Working on a better solution right now. Will ship it today

**Comment by baptisteArno** [comment]
Scrollable and searchable list of choices. Preview:

https://user-images.githubusercontent.com/16015833/234626708-942ed4ba-e1d8-4fbe-970a-ba25889c774a.mp4

Would that suit your need?

I'm just not a fan of the dropdown UX, so I think I won't implement it.

**Comment by baptisteArno** [comment]
Closing this in favor of #473
