### ISSUE TITLE
Non-docker install instructions

### ISSUE THREAD

**Issue by joho1968** [baptisteArno/typebot.io#31]
Really nice work!

Are there any non-docker install instructions available?

I write about open source solutions (be it commercial or non-commercial) at https://oppetmoln.se (Swedish), and I often exclude docker-only-type packages/services simply because everyone doesn't want to take that road.

**Comment by baptisteArno** [comment]
Sure, I should write a doc about how to run the apps without docker! Thank you for suggesting that.

For now, there is a [Deploy on Vercel](https://docs.typebot.io/self-hosting/vercel) doc but it's probably too specific to Vercel.

**Comment by baptisteArno** [comment]
Thank you again for the suggestion.

Deploying Typebot on a VPS without Docker is way more complicated than expected.

So, for now, I decided to only support Docker deployment.
