### ISSUE TITLE
Integration with google account and deleted answers appearing

### ISSUE THREAD

**Issue by alvesnutri** [baptisteArno/typebot.io#316]
Hello Baptiste, first I would like to congratulate you for the excellent tool!

I'm facing problems when trying to sync my google drive account and google sheets spreadsheet in typebot. An error appears on the screen when trying to connect with the google account, with the words "Application error: a client-side exception has occurred (see the browser console for more information).".

In addition, in the results tab, the answers that I delete continue to appear in the line, but without any information, only the registration date remains.

**Comment by baptisteArno** [comment]
Can you create another issue for the Google Sheets bug? If possible, can you provide logs from the console when it has crashed?

**Comment by alvesnutri** [comment]
For sure.

I believe I configured it correctly, as it was working fully before, today during the morning the synchronization stopped working

[app.typebot.io-1676295345211.log](https://github.com/baptisteArno/typebot.io/files/10722710/app.typebot.io-1676295345211.log)
