### ISSUE TITLE
Make the expanded block options window bigger

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#321]
>Users should be able to freely resize the block edition window and not just "toggle" a fullscreen mode. It's not convenient at all when putting code variables or having long strings.
![image](https://user-images.githubusercontent.com/73610779/219113369-40d40181-9604-4946-aa5e-fc25dea6161c.png)

**Comment by Lanhild** [comment]
Yeah, I get the technical difficulty. Then why not make the full screen view a bit larger? It feels like there is no size difference between the popover and full screen view right now.

The full screen view seems too small to be considered a full screen view, it should be at least 50% larger

**Comment by baptisteArno** [comment]
I aggree 👍

**Comment by baptisteArno** [comment]
It will feel better 👌

<img width="1465" alt="CleanShot 2023-02-22 at 09 25 52@2x" src="https://user-images.githubusercontent.com/16015833/220563973-6c851999-b252-4d80-85d0-425761e36e59.png">
