### ISSUE TITLE
Postgres url issue with v2.10.3

### ISSUE THREAD

**Issue by b4oshany** [baptisteArno/typebot.io#324]
Getting the following error using a Postgres database in version 2.10.3. Please note, the same postgres URL works in version 2.10.1

![image](https://user-images.githubusercontent.com/1830494/219874495-3c3ed6c8-2d5c-47bb-ba78-22f70631275b.png)

**Comment by baptisteArno** [comment]
Thank you 🙏

Will be fixed on next release.
