### ISSUE TITLE
Bug when publishing for the first time

### ISSUE THREAD

**Issue by jtapeg** [baptisteArno/typebot.io#327]
When saving for the first time, the flow disappears, and the name does not save either
https://user-images.githubusercontent.com/52453013/220125473-830db5e4-bb07-45b4-a3d1-dac7c8843aa1.mp4

**Comment by jtapeg** [comment]
Apparently everything is ok in the requests
https://user-images.githubusercontent.com/52453013/220126719-c0924362-e64e-4e21-b389-20fc359f1cca.mp4

**Comment by baptisteArno** [comment]
I'm talking about server logs (`docker-compose logs`)

**Comment by jtapeg** [comment]
These tests are on the official typebot website (https://app.typebot.io)

**Comment by jtapeg** [comment]
> These tests are on the official typebot website (https://app.typebot.io)

I also tested it on another computer with another account and I have the same problem

**Comment by baptisteArno** [comment]
It looks like the save requests are not working as expected in your case. Can you inspect the "PUT" method and show me the Response?

Here is how I do it:

https://user-images.githubusercontent.com/16015833/220134443-04170ebb-c784-4f1c-bd63-83ef8d0ac3c6.mp4

**Comment by jtapeg** [comment]
https://user-images.githubusercontent.com/52453013/220135028-07a72feb-cc1b-4ff1-9738-82264ee1dd51.mp4

**Comment by baptisteArno** [comment]
Wow, ok, must be a timezone issue 😲

I'm pushing a potential fix

**Comment by baptisteArno** [comment]
Can you refresh the app and try again?

**Comment by jtapeg** [comment]
Wow, that was it, now it's working fine!
