### ISSUE TITLE
Issues with Typing Emulation and Blank Screen

### ISSUE THREAD

**Issue by alvesnutri** [baptisteArno/typebot.io#330]
I'm facing two issues with Typebot.

First problem: I disabled typing emulation, but it still keeps happening.

Second problem: I sent my typebot form to a customer, but Typebot's screen is blank, she doesn't receive any programmed message from typebot on her iphone, she already tried to open in Chrome and Safari.

**Comment by baptisteArno** [comment]
This will fix the first problem. I will release a new version today.

For the second issue, can you reproduce the issue yourself with an iPhone? If so, can you create another issue with as many details as possible?

**Comment by alvesnutri** [comment]
I can't reproduce the problem on my iphone, it's only happening on my client's iphone. I will attach the print of her iphone (image 01) and the print of what is supposed to happen normally (image 02).

The first messages programmed into typebot are:

- Image with my logo;
- Next: Welcome texts and guidance on the form.

She is only receiving the first image, subsequent texts are not being sent.

![image 01](https://user-images.githubusercontent.com/125273820/220995462-973ed5ff-66bb-44f8-b9ce-20814cb45c6c.jpg)
![image 02](https://user-images.githubusercontent.com/125273820/220995472-0c7e74bb-485b-4ab3-bd8d-87ade9900d0f.png)

**Comment by baptisteArno** [comment]
Oh, you are using the cloud managed version? If so, can you send a support request on the tool directly? 🙏
