### ISSUE TITLE
[@typebot-io/react] Missing field name in `onAnswer` callback

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#334]
When integrating to website, I've been using this:
![image](https://user-images.githubusercontent.com/2746558/221035730-b85d4d18-39a5-4cf7-90a4-01592d9e2339.png)
This way, I get value from this variable and send to an API.

So, suddenly, today (23/02), typebot stopped sending `onNewVariableValue`. The website is broken right now, because it has a entire flow based on typebot.
I need the variable name to compare, and not the block id, all my flow is built above variable name and now I have no way to get it.

How this situation would be repaired?

![image](https://user-images.githubusercontent.com/2746558/221035440-9367e9fc-6327-413d-9a9e-03e72a5cb650.png)

**Comment by baptisteArno** [comment]
Sorry I couldn't answer earlier. You are using the new bot engine then. It's very different as everything happens on the backend now. We can't really know when a new variable is set.

The `onAnswer` callback should give you all the user answers in real time, so you should be able to do whatever you need, right?

**Comment by erickriva** [comment]
Well, I have some questions about it:

- Then, is it all API-based now?
- There is no way I can get a 'legible' block information, like a name that I can define?
- I was using `postMessage` to my website. It will not work anymore?

**Comment by baptisteArno** [comment]
> Then, is it all API-based now?

Basically, yes, even you can consume the API (https://docs.typebot.io/api/send-a-message) and implement your own client. It's one step closer to other chat platform integration 👍

> There is no way I can get a 'legible' block information, like a name that I can define?

onAnswer returns the block id, you can use it to determinate what block the user answered to. Did I understand your question correctly?

> I was using postMessage to my website. It will not work anymore?

The embed lib is not based on iframe anymore! So you can directly talk to your website without using postMessage 🤘
