### ISSUE TITLE
Bots with background transparent still have a white background

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#335]

**Comment by baptisteArno** [comment]
Can't reproduce: https://codesandbox.io/s/typebot-react-standard-n86hid?file=/src/App.tsx

Are you sure you set the background to "none" in the Theme tab of your bot?

**Comment by erickriva** [comment]
Not happening anymore. Looks like it is doing joke of me 🤡.
It has happened when I duplicated an already published bot (old engine), and published with the new engine.
It had a `div` with white background above `<typebot-standard>`, so since it had background set as 'none', this background showed.

**Comment by baptisteArno** [comment]
No worries! 😀
