### ISSUE TITLE
[HELP] Setting up google auth

### ISSUE THREAD

**Issue by crikeym8** [baptisteArno/typebot.io#337]
I'm a little lost on how to set up Google Auth on the server or where to enter what details and what steps to follow from this point forward.

![image](https://user-images.githubusercontent.com/121785917/221385662-6e928ba8-c68f-4a02-be04-50b9848181ac.png)

This is currently what I am seeing. I'm unsure what I need to enter in the Google console or where to even start. I am hosting on digital ocean. Is there any steps on what to do next from here in more detail for the less tech savy people?

**Comment by manoelcfeliciano** [comment]
Hello @crikeym8,

I guess this is not the proper place to ask this kind of question. Probably you should use the Discussion[https://github.com/baptisteArno/typebot.io/discussions] for this.

But I guess I can help you. You just need to go to the `app/buider/.env.local` file and add there the following variables:

```
GOOGLE_CLIENT_ID=your_id_here
GOOGLE_CLIENT_SECRET=your_secret_here
```

Remember to change `your_id_here` and `your_secret` to your actual values. If you don't know how to get these values, just follow the instructions on this page: https://medium.com/@thomashellstrom/use-google-as-login-in-your-web-app-with-oauth2-352f6c7f10e6

**Comment by crikeym8** [comment]
> 

Awesome thanks so much!

**Comment by mannutech** [comment]
How do I redirect back the user after logging on our frontend Embed?
