### ISSUE TITLE
[Webhook] Request failed, caused by 'wrong' url

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#347]
![image](https://user-images.githubusercontent.com/2746558/222260576-4d96b7b4-df52-49fd-a4c3-956e64009224.png)

When clicked 'test request', received this message:
```
{
  "statusCode": 500,
  "data": {
    "message": "Error from Typebot server: RequestError: 'url' must not start with a slash"
  }
}

**Comment by baptisteArno** [comment]
For the test request to work you need to add a Variable value for test option in the Webhook block settings. Does that help?

**Comment by erickriva** [comment]
Oh, it worked!
I didn't know that even URL variables should be added to 'variable values for test'.
Thank you!
