### ISSUE TITLE
[Webhook] 'save in variables' returning wrong data to add to variable

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#351]
Webhook returned data format:
![image](https://user-images.githubusercontent.com/2746558/222463669-e8beca84-1626-498a-afda-64f772aa99eb.png)

Piece of data already being set to a variable:
![image](https://user-images.githubusercontent.com/2746558/222463965-b859ad0d-efce-4e84-b9df-7286ffea8520.png)

But when I'll try to create another entry to it:
![image](https://user-images.githubusercontent.com/2746558/222464296-3a434f78-1b7b-4bd3-94d9-cc3db4c7fe13.png)

**Comment by erickriva** [comment]
I had no problem with it until yesterday. Maybe something that got in production yesterday/today?

**Comment by baptisteArno** [comment]
omg... Totally my bad here.

Will release another version with the fix ASAP 🙏
