### ISSUE TITLE
Add search input in blocks sidebar

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#359]

**Comment by KavitaR45** [comment]
Hi, I have added the search input, below is the screen recording, if its what you expected. I will raise PR. If some changes needed let me know. Thanks :)

[
[screen-capture.webm](https://github.com/baptisteArno/typebot.io/assets/99713335/144a56e0-6b64-4c24-a758-c9bb60813a20)
](url)

**Comment by KavitaR45** [comment]
Hi, @baptisteArno Did you get a chance to review it?

**Comment by baptisteArno** [comment]
Hey, looks great. I'd be happy to review it.

Though it also need to work with "description" and "tags" fields of forged blocks (https://docs.typebot.io/contribute/the-forge/block)

So this will probably need a bit more work. But that could be a great starting point!

**Comment by KavitaR45** [comment]
So should I raise PR or it should be done with "tags" field of forged blocks ?

**Comment by KavitaR45** [comment]
So this search functionality with  "tags" fields of forged blocks, it should be done in the Same PR or separate PR will be raised ?

**Comment by baptisteArno** [comment]
Same PR, but you can create yours and I'll add what's necessary for it to work
