### ISSUE TITLE
Checking if answer contains word in array

### ISSUE THREAD

**Issue by eduazy** [baptisteArno/typebot.io#363]
The feature where you can check if the user's answer contains a string of text stored in a variable is checking _strictly_ for that word, instead of simply checking if the string contains that word.

For example here, the word "fine" is not triggering the appropriate response, the only way to trigger it is by only typing "fine" without anything else:

[https://i.imgur.com/gBl5LyW.png](https://i.imgur.com/gBl5LyW.png)

It's acting as if it was set to `"is equal"` instead of `"contains"` - the string of text I wrote contains the word "fine" so it should trigger the `PositiveAnswer` outcome and not the `else` fallback.

I'd swear this was working correctly a few days ago? I'm looking for a way to avoid manually inputting ALL possible combinations of multiple words so I can check if the user has typed that word and redirect them to a specific path.

**Comment by erickriva** [comment]
If you try `fine` capitalized, like `I am Fine`? It works?

**Comment by baptisteArno** [comment]
Hmm, I'm not sure what to think here…

`['fine', 'bad'] contains "I am fine"`
I can't make it match here, that is fundamentally wrong

`"I am fine" contains ['fine', 'bad']`
This, on the other hand, makes sense! But it looks like it doesn't work, so I'll push a fix for this ASAP!

**Comment by eduazy** [comment]
Hi Baptiste, I was using the solution you provided on an email a few days ago: [https://i.imgur.com/xngw9F7.png](https://i.imgur.com/xngw9F7.png)

It does make more sense if the logic is: `{{Answer}} contains PositiveAnswer` and `{{Answer}} contains NegativeAnswer`
however that wasn't working either.

Awaiting on your fix for this, it's crucial for the way I'm implementing the bot so I hope it's something you can easily mend.

Thank you for your work!

**Comment by baptisteArno** [comment]
> I was using the solution you provided on an email a few days ago: https://i.imgur.com/xngw9F7.png

I was clearly wrong, sorry for this 😅

Will push that today.
