### ISSUE TITLE
[API] Error getting webhook result example

### ISSUE THREAD

**Issue by erickriva** [baptisteArno/typebot.io#364]
Observation: the hidden word in the error message in return is `groups`

![223306431-ef81e53f-79ad-4ef7-bd29-658c71e722b4](https://user-images.githubusercontent.com/2746558/223307680-ba772a9b-cb02-4f63-9775-9b94ea853b97.png)

**Comment by baptisteArno** [comment]
That's really strange. Also, I can't reproduce 🤔

Any chance you can share a typebot that reproduces the issue?

**Comment by baptisteArno** [comment]
You probably misuderstood what this endpoint does, it is expecting a webhook block so that it can give you an example of what could go through the webhook.

Does that make sense? Can you let me know what you were expecting?

The error message isn't explicit enough, though, so I'll fix that.

**Comment by baptisteArno** [comment]
Oh, in fact, it seems there is a bug as well.

**Comment by erickriva** [comment]
> You probably misuderstood what this endpoint does, it is expecting a webhook block so that it can give you an example of what could go through the webhook.

I misunderstood that part before. But now you told what it does, it makes so much sense 😅.

> Can you let me know what you were expecting?

I wasn't expecting nothing really, just testing all the endpoints to understand what they do.
