### ISSUE TITLE
Issues with vercel deployment

### ISSUE THREAD

**Issue by rohanrajpal** [baptisteArno/typebot.io#38]
Hey, I just followed the guide to deploy on vercel and can't find any option to sign in.

![image](https://user-images.githubusercontent.com/7023147/168562255-a12c7179-e7d1-4a3c-9ea2-cdf259eb78a5.png)

here's how my supabase looks like
![image](https://user-images.githubusercontent.com/7023147/168562346-2036b505-0b16-4c37-b469-009b1c05d29b.png)

**Comment by rohanrajpal** [comment]
same for the signup page
![image](https://user-images.githubusercontent.com/7023147/168602523-2ed07c8c-86d9-46ad-9453-78d1b4bc5b1d.png)

i've set the following environment variables in vercel
![image](https://user-images.githubusercontent.com/7023147/168602734-6e6bcc2f-ee12-4fb2-afcf-24768e3c5f01.png)

would appreciate some help!

**Comment by rohanrajpal** [comment]
> Hey @rohanrajpal,
> 
> It seems you added your environment variables after deploying the app.
> 
> With a Next.js project, when you add a new variable, you need to rebuild the application. So you need to click on "Redeploy" on the deployment page:
> 
> ![CleanShot 2022-05-16 at 07 43 07@2x](https://user-images.githubusercontent.com/16015833/168619387-c8b12bfd-83b4-4a17-aecb-cb678aa3d081.png)

We'll i did try redeploying, but that didn't work out either :/

I made a small change in the code, commited and that worked! I guess there's a bug in vercel.

**Comment by baptisteArno** [comment]
That is very strange! But glad it works now ☺️
