### ISSUE TITLE
Better Integration architecture for easier contributions

### ISSUE THREAD

**Issue by EchoAGI** [baptisteArno/typebot.io#380]
You need a better Integration architecture for easily integrations.
like zapier, developers can create a integration node, and describe the schema, then zapier can render a integration node by the predefined schema.

More about dynamic extensions, You can refer to another related open source software n8n. (https://github.com/n8n-io/n8n)

**Comment by newtalentxp** [comment]
if i wan't to add a new integraion app, i don't wan't to hard code

**Comment by baptisteArno** [comment]
Hey, thank you for creating this issue. I agree, if anyone now would like to create his node, it still is not easy to understand how to do it.

We can imagine a CLI to add the required files. And also maybe an interface that would list the node metadata.

Here is what n8n offer: https://github.com/n8n-io/n8n/tree/master/packages/node-dev

**Comment by newtalentxp** [comment]
Thanks for answer.
you can refers to n8n, which provide a node interface for 3rd developers to extends their own nodes(integrations).
you need to implement a smart form builder to render the node schema. 
About extensions / integrations for iPaaS, the best practices is Zapier, which is more powerful than n8n.

**Comment by baptisteArno** [comment]
Also Activepieces does an amazing job at that: https://www.activepieces.com/docs/developers/building-pieces/create-action
