### ISSUE TITLE
Embed (Script) : "The bot you're looking for doesn't exist" on retrigger

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#382]
I've embedded a bot in my app, using the HTML Script option, inside a div container.

The issue that i'm facing is, that if the bot container is closed, at some point before the completion, and then retriggered, then an error message is displayed instead of the bot:
`The bot you're looking for doesn't exist`

Console log:
![image](https://user-images.githubusercontent.com/64059154/224524324-dd9b9373-2c93-4c88-b5c6-4a6eb32fc557.png)

To make the bot reappear, i have to Hard Refresh the browser every time.

**Comment by baptisteArno** [comment]
"if the bot container is closed" => I'm not sure what it means!

Can you tell me how I can reproduce the error exactly? If you can, give me access to your site so that I can check. If you don't want to share it publicly, shoot an email to support@typebot.io

**Comment by arladmin** [comment]
> "if the bot container is closed" => I'm not sure what it means!
> 
> Can you tell me how I can reproduce the error exactly? If you can, give me access to your site so that I can check. If you don't want to share it publicly, shoot an email to [support@typebot.io](mailto:support@typebot.io)

@baptisteArno 
It's a react based app. So, on clicking a button, i 'mount' a container which contains the entire bot visual within it. Once the bot flow reaches the end, i send a signal to the app which then 'unmounts' the container.
Now, if i click on the button again, a new container is mounted again but the bot inside it doesn't load. Instead, just shows the error shown above.

Will send you a corresponding webpage to test, soon.

**Comment by baptisteArno** [comment]
Can you reproduce that on a code sandbox?
