### ISSUE TITLE
Cannot postMessage with variables data

### ISSUE THREAD

**Issue by os-mmasse** [baptisteArno/typebot.io#390]
When use postMessage (or alert) in script, it's not possible to use variables (values aren't mapped).
Example for postMessage :
data : "{\"firstname\":\"vk4fvw3f4tb9jbdlc6wm3wi14\",\"lastname\":\"vt7x0ct5z60rxoh54ajhrl4xj\"}"

**Comment by baptisteArno** [comment]
Variables in script are not parsed, they are evaluated. So it should be used as if it were real javascript variables.

Example: `console.log({{My variable}})` instead of `console.log("{{My variable}}")`

**Comment by os-mmasse** [comment]
Thanks a lot.
Maybe it would be good to update documentation this way (with exactly this example).

**Comment by baptisteArno** [comment]
Yes good idea 👍
