### ISSUE TITLE
Add Group Options input

### ISSUE THREAD

**Issue by os-mmasse** [baptisteArno/typebot.io#391]
Group options can be good inputs (a button option).

As a flow designer, i would be able use buttons with peers {label : btn1, value: id1},{label : btn2, value: id2} (label displayed, value set in variable as a result).
This would be useful to manage custom scripts.

**Comment by baptisteArno** [comment]
If I understood correctly, what you are saying, you basically would want something like this? https://github.com/baptisteArno/typebot.io/issues/241

Unfortunately, that would be complicated to implement. But with [Custom blocks](https://github.com/baptisteArno/typebot.io/issues/249) coming soon, you will be able to clean it up.

**Comment by os-mmasse** [comment]
Thanks a lot. #241 is a good solution for my current needs.
I'll watch the Custom Block feature progress carefuly, this can be a very good opportunity for many things we need.
