### ISSUE TITLE
ChatGPT integration

### ISSUE THREAD

**Issue by sanjayws** [baptisteArno/typebot.io#393]
Hi, thank you for this amazing project. 

Was trying to test out ChatGPT integration on my own infra. But hit a problem and have no clue where to start looking? Using latest version on docker. 

Any advice would be highly appreciate.

So, the scenario is;
1) Key inserted
2) Start conversation, asked ChatGPT a question, it doesn't respond to the answer instead echoes what i wrote. I am using straight off template and just add key.

Side note: Online/SaaS works 

![image](https://user-images.githubusercontent.com/25242465/225331134-5d24634d-1db0-4521-86a0-936e78bf7de6.png)

**Comment by baptisteArno** [comment]
Sorry to hear that. Can you check the docker compose logs? Can you see any interesting error?

**Comment by baptisteArno** [comment]
That's strange. If I had to guess, there maybe is an issue with your `ENCRYPTION_SECRET`.

Can you try to generate a new one (256-bit): https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx

And make sure that it's set on both builder and viewer environment

Then create a new OpenAI credentials and try again.

**Comment by sanjayws** [comment]
Will try it again and let you know. Thanks.

**Comment by sanjayws** [comment]
Hi Baptiste, the new key on both viewer and builder didn't fix the issue.

**Comment by baptisteArno** [comment]
Can you share your docker-compose logs?

**Comment by dytrip77** [comment]
Hi @baptisteArno 

Attached is requested log

[docker-compose.log](https://github.com/baptisteArno/typebot.io/files/10981557/docker-compose.log)

**Comment by baptisteArno** [comment]
Can you try it out in published mode and see the results log?

https://docs.typebot.io/editor/results#logs

**Comment by sanjayws** [comment]
Btw, am collaborating with my colleague, @dytrip77 

So we didn't see logs.

![image](https://user-images.githubusercontent.com/25242465/225360041-6fb6d03a-3b3f-458f-9c4d-47ecc0a872cd.png)

**Comment by sanjayws** [comment]
oopps, i am on self hosted, and it only allows just one user :(

**Comment by baptisteArno** [comment]
You are not limited to one user at all, you can still invite me on a self-hosted Typebot

**Comment by sanjayws** [comment]
Oh you're right, i just did

**Comment by baptisteArno** [comment]
I don't see anything wrong with your setup. I'll push a new release with more logs to see what's going on. I'll let you know once you can upgrade the app

**Comment by baptisteArno** [comment]
Alright, you can pull v2.11.5 try again and you should see interesting logs 🙏

**Comment by sanjayws** [comment]
Hello and thanks for pushing this update. So we did do the update but still no logs appear, strange...

![image](https://user-images.githubusercontent.com/25242465/225482189-9726b69e-9676-4a61-807b-202ae4fb54c0.png)

**Comment by sanjayws** [comment]
Hi, ok so ChatGPT works now but no logs tho, really cool :-D great vision and product mate.

**Comment by baptisteArno** [comment]
Ok glad to hear that the issue was fixed 👌
