### ISSUE TITLE
Invalid key length | GPT Integration

### ISSUE THREAD

**Issue by VikingDadMedic** [baptisteArno/typebot.io#394]
I am unable to "Add OpenAI account" with the GPT Integration. It's throwing the following error (see below). I have tried latest, main, and 2.11.4 docker versions - all with the same issue.

**GUI**
<img width="1652" alt="GUI" src="https://user-images.githubusercontent.com/91684138/225364058-dc9481f5-5e32-46ac-9e49-7d71baf9eebb.png">

**Console**
<img width="1202" alt="console" src="https://user-images.githubusercontent.com/91684138/225364129-4eb103f2-9c56-4339-8675-413dc76a8bc5.png">

**Network**
<img width="840" alt="network" src="https://user-images.githubusercontent.com/91684138/225364192-4a92216e-9be7-4ca1-b461-3adcd80efbc3.png">

**Logs**
<img width="1168" alt="logs" src="https://user-images.githubusercontent.com/91684138/225364253-90eb93f6-b607-4bbe-b2e8-57438bbb0d7d.png">

**Comment by baptisteArno** [comment]
Your `ENCRYPTION_SECRET` does not have the right format. Can you generate a new one and replace it with your existing one?

Here is the command to do so:

```sh
openssl rand -base64 24 | tr -d '\n' ; echo
```

**Comment by VikingDadMedic** [comment]
Nailed it - that did the trick! Merci infiniment pour votre aide!
