### ISSUE TITLE
Bubble doesn't display a variable set before on a particular set up

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#40]
For some reason, this works, it displays "yolo":
<img width="406" alt="CleanShot 2022-05-16 at 10 06 38@2x" src="https://user-images.githubusercontent.com/16015833/168646296-1c14f4ee-d422-4c59-8709-8f099b014e3f.png">

But this doesn't, it displays nothing after answering the input:
<img width="438" alt="CleanShot 2022-05-16 at 10 08 14@2x" src="https://user-images.githubusercontent.com/16015833/168646431-1992fe2e-9ffb-4e6e-8ecf-537a4d138a94.png">

I investigated but couldn't understand why.

**Comment by teq-dev** [comment]
This works properly in 2.0, but maybe you knew that already.
![CleanShot 2022-05-16 at 16 17 45](https://user-images.githubusercontent.com/90119409/168675575-45193ee6-0629-4728-8bcd-867c4ed03a18.gif)

**Comment by baptisteArno** [comment]
Actually, no, I didn't know 😨

That's very strange then. could you send the JSON file so that I can import your example?

**Comment by teq-dev** [comment]
Sure. This one works in the previous version:
[typebot-export-my-typebot-7agevly.json.zip](https://github.com/baptisteArno/typebot.io/files/8704383/typebot-export-my-typebot-7agevly.json.zip)

**Comment by baptisteArno** [comment]
My guess is that it was introduced after upgrading the packages (React 18).

Still not sure why it's happening...

**Comment by teq-dev** [comment]
Just so you know, with the latest code release, this problem still exists in the Builder (preview mode):

https://user-images.githubusercontent.com/90119409/170313690-25662f12-bc5b-4d95-8414-d8b6eaf93389.mp4




**But it appears to be fixed in the Viewer after publishing the Typebot:**



https://user-images.githubusercontent.com/90119409/170313796-a01d3142-b90b-4b9a-85ff-2f2867d8c613.mp4

**Comment by baptisteArno** [comment]
Ok interesting, I'll investigate more on this

**Comment by baptisteArno** [comment]
Closing this as it's not critical and will soon be fixed because the execution layer will be ported to the server 👌
