### ISSUE TITLE
Implement Whatsapp integration

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#401]
### Blocks parsing

- [x] Text bubble
- [x] Image bubble
- [x] Video bubble
- [x] Audio bubble
- [x] Text input
- [x] Number input
- [x] Email input
- [x] Website input
- [x] Date input
- [x] Phone input
- [x] Buttons
- [x] Pic choice
- [x] Rating input
- [x] File upload
- [x] OpenAI disable stream
- [x] Webhook disable client side exec
- [x] Extract contact information in variable

### Preview

- [x] Instructions
- [x] Launch preview bot from editor
- [x] Publish preview webhook

### Share

- [x] Instructions

### Session

- [x] Start condition
- [x] How to avoid session start concurrency issue
- [x] Better session expiration

### Beta

- [x] Set up feature flag

### Misc

- [x] Self-host config doc

**Comment by newtalentxp** [comment]
This demand is very strong

**Comment by Vittitow** [comment]
Any ETA on this? Would love to be able to do the same for telegram.

**Comment by baptisteArno** [comment]
I honestly have no ETA… I am pushing some AI features first.

I'm still in the exploration phase on how to properly display all the available blocks. I will give frequent update on this thread. 🙏

**Comment by chrxoficial** [comment]
It would be a dream to integrate with Baileys

**Comment by baptisteArno** [comment]
Baileys? The liquor? 🤪

**Comment by chrxoficial** [comment]
> Baileys? O licor?🤪

https://github.com/adiwajshing/Baileys ❤️

**Comment by baptisteArno** [comment]
It won't be the case. Typebot will integrate with the official WhatsApp API.

**Comment by anoop0567** [comment]
Hi @baptisteArno any update on this?

**Comment by baptisteArno** [comment]
Actively working on it! Launch expected next week max

**Comment by richbowen** [comment]
How's this going?
