### ISSUE TITLE
GPT Moderation | Contribute?

### ISSUE THREAD

**Issue by VikingDadMedic** [baptisteArno/typebot.io#402]
I wasn't sure if you were already working on adding moderation to the GPT integration - so I thought I would ask.

If you're not, can you outline the required files that would need to be be created or edited to add moderation filtering so I could create a community integration.

**Comment by baptisteArno** [comment]
Hi friend 👋

Can you explain a bit what's your requirement, and you'd like to have as a solution ideally?
