### ISSUE TITLE
magic links are redirecting to localhost

### ISSUE THREAD

**Issue by realsubinbabu** [baptisteArno/typebot.io#403]
Hello bro, after the latest update to v2.11.5, all of my magic links are redirecting to localhost.

![magic link](https://user-images.githubusercontent.com/92963823/225802280-84bcd290-af73-4b28-8387-bfac5759af86.png)

**Comment by baptisteArno** [comment]
I'm thinking maybe `NEXTAUTH_URL_INTERNAL` is overriding this. Do you confirm that you have this variable set up to `http://localhost:3000`?

**Comment by realsubinbabu** [comment]
Do you confirm that you have this variable set up to http://localhost:3000?

yes bro

**Comment by baptisteArno** [comment]
Ok, I've opened an issue on nextauth repo https://github.com/nextauthjs/next-auth/issues/6983

Thank you for the info 🙏

**Comment by arladmin** [comment]
@baptisteArno 
Hi.
I'm facing the same problem.

I'm now unable to log into the app at all!

If i remove the env variable `NEXTAUTH_URL_INTERNAL` from the config, then also the app just doesn't work.

**Comment by arladmin** [comment]
Hi @baptisteArno .

I just downloaded the latest release (v2.11.7).

Now, although the link in the mail starts with my actual domain, it ultimately redirects to `localhost:3000`

So, the magic link is still not working.

**Comment by arladmin** [comment]
@baptisteArno 
Just checked the browser console.

When i enter the magic link in the url, the response is a 302 redirect to `http://localhost:3000` (`NEXTAUTH_URL_INTERNAL`), which , i think, should instead be `NEXTAUTH_URL` .

**Comment by baptisteArno** [comment]
Argh that's a pain in the ass
