### ISSUE TITLE
Add a check on the encryption key length on container start

### ISSUE THREAD

**Issue by os-mmasse** [baptisteArno/typebot.io#408]
It seems that openai api keys are not correctly validated :
<img width="635" alt="image" src="https://user-images.githubusercontent.com/120925348/226629319-fc01b32b-7c6f-46d7-8b4b-94b8719e443e.png">

**Comment by os-mmasse** [comment]
Here is the docker container error :
<img width="656" alt="image" src="https://user-images.githubusercontent.com/120925348/226633166-f76b1b82-729b-4a47-8730-8a316ca174b5.png">

**Comment by os-mmasse** [comment]
Nevermind, this is due to the docker container encryption key length.

**Comment by baptisteArno** [comment]
Can you tell us how you fixed the issue?

Do you confirm that the command in the docs is generating a valid encryption key length?

```sh
openssl rand -base64 24 | tr -d '\n' ; echo
```

**Comment by os-mmasse** [comment]
Yes it solved my issue. I missed a character when i copy pasted the generated key (maybe a control on builder start would be great so it can warn about this before any user action)
