### ISSUE TITLE
OAuth2 OpenID Connect Auth Provider

### ISSUE THREAD

**Issue by MDXDave** [baptisteArno/typebot.io#42]
Besides Github, GitLab and Google, a generic OAuth 2 OpenID Connect Auth Provider should be possible to configure.

**Comment by baptisteArno** [comment]
Yes, totally possible. Typebot uses NextAuth.js under the hood. And [this is the doc for custom OAuth provider](https://next-auth.js.org/configuration/providers/oauth#using-a-custom-provider).

But do you think we should be able to configure it with environment variables?

**Comment by whallin** [comment]
Ideally, we'd have the option to configure it via environment variables. I see this as a feature that could very well be used by many, including me.

**Comment by Lanhild** [comment]
> Ideally, we'd have the option to configure it via environment variables. I see this as a feature that could very well be used by many, including me.

Very true, that would be a really useful feature.

**Comment by baptisteArno** [comment]
I'll try to have a look soon! That should be fairly easy to implement 😀

**Comment by Lanhild** [comment]
Any news or advancement on this side?
