### ISSUE TITLE
Ability to manually set a characters number limit on text input blocks

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#420]

**Comment by Lanhild** [comment]
The character counter could be something like this:
![image](https://github.com/baptisteArno/typebot.io/assets/73610779/6bc71116-4592-487c-a3fc-c47471e10c35)

**Comment by bjoliveau** [comment]
+1

**Comment by Lanhild** [comment]
@baptisteArno Any idea if this might be implemented soon?

**Comment by baptisteArno** [comment]
Issue stalled
