### ISSUE TITLE
[selfhosted] Authorization keep failing with "Try signing with a different account"

### ISSUE THREAD

**Issue by taro350** [baptisteArno/typebot.io#423]
I keep getting a message "Try signing with a different account." with the following URL:
`https://mysubdomain.mydomain.com/signin?callbackUrl=https%3A%2F%2Fmysubdomain.mydomain.com%2Ftypebots%3F&error=Callback`

Host: Vercel

Configuration done on Vercel Environment Variables:
- on Builder
`ENCRYPTION_SECRET`
`NEXTAUTH_URL`
`NEXT_PUBLIC_VIEWER_URL`
`GOOGLE_CLIENT_ID`
`GOOGLE_CLIENT_SECRET`
`GITHUB_CLIENT_ID`
`GITHUB_CLIENT_SECRET`

- on Viewer
`ENCRYPTION_SECRET`
`NEXTAUTH_URL`
`NEXT_PUBLIC_VIEWER_URL`

******************************************************************************************
Google Cloud 

Publishing status: Testing
User type: External
App domain: https://mysubdomain.mydomain.com
Authorized domains: mydomain.com
Your non-sensitive scopes: /auth/userinfo.email
Test users: mydomain@gmail.com

Authorized redirect URIs (in OAuth 2.0 Client IDs): https://mysubdomain.mydomain.com/api/auth/callback/google

******************************************************************************************
Github

Homepage URL: https://mysubdomain.mydomain.com
Authorization callback URL: https://mysubdomain.mydomain.com/api/auth/callback/github

******************************************************************************************

Any clue to make authorization work?

**Comment by taro350** [comment]
I followed a log on Vercel, and it turns out that DATABASE_URL is required. Your documentation has been saying that I need to host postgres or some other providers, but I was just putting it off later, only to try to get into the authorization process😅
I used Supabase and it worked perfect!

I took an another look at your documentation and now it has "Parameters marked with * are required" message in the Configuration page! That's nice!
Thank you! @Lanhild

**Comment by lhyphendixon** [comment]
I'm having the same issue but I do indeed have a database_url set (curtesy of Supabase integration on Vercel).  I have logs attached.  Anyone have any other ideas?

[logs_result.csv](https://github.com/baptisteArno/typebot.io/files/14486074/logs_result.csv)

**Comment by baptisteArno** [comment]
> I'm having the same issue but I do indeed have a database_url set (curtesy of Supabase integration on Vercel). I have logs attached. Anyone have any other ideas?
> 
> [logs_result.csv](https://github.com/baptisteArno/typebot.io/files/14486074/logs_result.csv)

What does your DATABASE_URL look like? Please provide as much info as possible to avoid back and forth messages.

**Comment by lhyphendixon** [comment]
Sorry for the lack of detail and no worries, I figured it out!  For anyone else having this issue, turns out there was an issue migrating the Prisma schema in the build process.  

I had to add ?pgbouncer=true to the end of my database url, per the link below:


https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/pgbouncer
