### ISSUE TITLE
After deletion of workspace, editor does not work

### ISSUE THREAD

**Issue by jovantehno** [baptisteArno/typebot.io#424]
I got following error:

"Application error: a client-side exception has occurred (see the browser console for more information)."

here is the screenshot with console opened:
https://app.screencast.com/8KNyxXQnvdPKn

**Comment by jovantehno** [comment]
This could be related to rapid increase of disk space used.

Nothing special is active/only I am testing a bot, and disk space is rapidly populated:

https://app.screencast.com/cChhxTk8YCgZj

**Comment by jovantehno** [comment]
I have upgraded typebot with:

```
docker-compose down --remove-orphans
docker-compose pull typebot-builder
docker-compose pull typebot-viewer
docker-compose up -d
```

And now I can login and my account is empty, all bots are lost ?! Any idea how to find previus workspace in database?

**Comment by baptisteArno** [comment]
That's strange, have you change any setting related to the database volume?

What's volume are you using for the typebot database? You can list your volumes `docker volume ls`

**Comment by jovantehno** [comment]
Yes, very strange. I did not change anything regarding the base. Only decided to update because, after login, I could not get dashboard to work. Now it works but does not see any previous workspace.

I think root cause of the problem is deleting additional empty workspace. (I had autocreated workspace, one empty, and one shared)

Here is docker volume ls:

local     d569b0f890447f5c097e501e43c6e9d17d10576fc3e3453eeb77d5b35157e6e0
local     e7b401a762c53fbbc377208de75326b7bd28a18bd92695fdd9489236bf288190
.... a lots of similar...
local     efa7114cda524d7fb66e61d5c36f12abb95bf54648eaa5d9352320c38eb8d395
local     f2fb6f9ec86fa55f3ffc620deeaf23ac27ddea7955b1f8b5f3748e79db497d76
local     f043dd44b917f9a34397304ddfc74a34396e76fe1f558fa844779c3923ddb1b0
local     typebotio_caddy-certificates
local     typebotio_db_data
local     typebotio_s3_data

Any ideas? How can I access database/check if there are any "unassigned" workspaces in database?

Thnx

**Comment by baptisteArno** [comment]
To explore your database, you can use any `psql` client.

NocoDB is a popular open-source one (https://www.nocodb.com/) You can set up a cloud account in a few minutes and check what's inside your DB.

Let me know what you find

**Comment by jovantehno** [comment]
I have deleted all the containers, volumes. 

Changed docker-compose.yml to 
use default container name typebot-db 
and default volume:
- db_data:/var/lib/postgresql/data
only database password is custom.

I have updated docker images and run docker. 
I am able to login (database works) but if I try to edit, still get:
Application error: a client-side exception has occurred (see the browser console for more information).

sreenshot with console: https://app.screencast.com/kpIMe4UuCWI9G

Any ideas?

**Comment by baptisteArno** [comment]
> I have deleted all the containers, volumes.

If you have deleted volumes then you have lost your database data... Because your database relies on a specific volume that was named `typebotio_db_data`.

By changing the container name, you changed the pointed volume: from `typebotio_db_data` to `typebot-baza_db_data`.

If by any chance you didn't delete your volume `typebotio_db_data` then renaming it with the correct name should do the trick

I'm closing this as it has nothing to do with Typebot. 🙏

**Comment by jovantehno** [comment]
I understand, data was already lost, so I have deleted everything to be sure that problem is not related to old installation.

I am still experiencing error "Application error: a client-side exception has occurred (see the browser console for more information)." on fresh instance of typebot.

**Comment by baptisteArno** [comment]
Can you explain when it happens exactly? On bot load? When editing X?

And can you provide the typebot file here so that we can try?

**Comment by jovantehno** [comment]
Yes, fresh typebot instance without any typebots. 
choose create typebot, choose any template, "use this template" and I see the error

if it helps, URL is domin.../typebots/mzfih1s9vfn6d5y85gdgfah4/edit

If I go back, I see fresh typebot from template, but if I "edit" the same /edit page shows the same error.

PS I have tried emptying browser cache. Browser is Safari 15.3. 
Now I have tried other browser (Brave) and there is no error.

**Comment by baptisteArno** [comment]
Any server side error logs? `docker-compose logs`

**Comment by jovantehno** [comment]
Only this (probably unrelated)

typebot-builder_1  | Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production

createbuckets_1    | Added `minio` successfully.
createbuckets_1    | mc: <ERROR> Unable to make bucket `minio/typebot`. Your previous request to create the named bucket succeeded and you already own it.
createbuckets_1    | Access permission for `minio/typebot/public` is set to `public`

This client side error is probably safari related?

**Comment by baptisteArno** [comment]
Oh indeed, that's the issue! (https://caniuse.com/?search=Array.at)

Can you update your Safari browser?

**Comment by jovantehno** [comment]
Sorry not now. It's a pitty that I have updated typebot (trying to solve this) and somehow lost database (even it was on persistent volume)

Thank you. Lets close this.
