### ISSUE TITLE
@typebot.io/prisma"' has no exported member 'Model' with ELIFECYCLE  Command failed

### ISSUE THREAD

**Issue by taro350** [baptisteArno/typebot.io#425]
I tried to build typebot Builder and Viewer on Vercel, and Builder has been built but Viewer gave me a error.

```
bot-engine:build: src/components/TypebotViewer.tsx(15,15): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Log'.
...
bot-engine:build: ../../schemas/features/answer.ts(2,15): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Answer'.
...
bot-engine:build: ../../schemas/features/workspace.ts(8,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Plan'.
bot-engine:build: ../../schemas/features/workspace.ts(8,16): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'WorkspaceRole'.
bot-engine:build:  ELIFECYCLE  Command failed with exit code 2.
bot-engine:build: ERROR: command finished with error: command (/vercel/path0/packages/deprecated/bot-engine) pnpm run build exited (1)
@typebot.io/js:build:  ELIFECYCLE  Command failed.
```

I tried `import {type Answer} from '@typebot.io/prisma` syntax

I checked if `schemas/package.json` has `@typebot.io/prisma` development dependency.

This stackoverflow page (https://stackoverflow.com/questions/42308879/how-to-solve-npm-error-npm-err-code-elifecycle) gives me a hint, but I don't want to mess up with Typebot codebase because, most importantly, I'm not familiar with Turborepo workspace features. 
How do I make `deprectated/bot-engine/src` and `../../schemas/features` paths (maybe `deprectated` and `schemas` workspaces) to recognize `prisma` workspace? So that'd probably get these errors away?

**Comment by baptisteArno** [comment]
Have you configured the environment properly with required params? https://docs.typebot.io/self-hosting/configuration/viewer

**Comment by taro350** [comment]
> Have you configured the environment properly with required params? https://docs.typebot.io/self-hosting/configuration/viewer
Yes, I set all the four variables. 

We don't need `pnpm prisma generate` for deploying the Viewer?

**Comment by taro350** [comment]
@baptisteArno 
Hey! I might just find something you could improve. I was setting `DATABASE_URL` with `postgres://` of Supabase postgres, which is the scheme you start with the Supabase 'Connection string', and the deployment does not work. But when I changed to `postgresql://`, the no exported name error went away! (I still got another error though... I opened [another issue](https://github.com/baptisteArno/typebot.io/issues/426)).

**Comment by baptisteArno** [comment]
That's strange! I don't think starting the URI connection string with `postgres://` would ever work and I don't have that on my Supabase options:

<img width="343" alt="CleanShot 2023-03-27 at 08 34 42@2x" src="https://user-images.githubusercontent.com/16015833/227859701-656dfdd3-b2f9-4e81-bdd8-e679793ce5f3.png">

But, glad you found the issue 🙏
