### ISSUE TITLE
"apps/builder/.next/routes-manifest.json" couldn't be found when buidling Viewer.

### ISSUE THREAD

**Issue by taro350** [baptisteArno/typebot.io#426]
I tried to build typebot Builder and Viewer on Vercel, and Builder has been built but Viewer gave me a error.

```
Error: The file "/vercel/path0/apps/builder/apps/builder/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.
```

I changed `output directory` to `.next` and other possible out dir I can think of some times and tried to deploy, but no luck. 

How do I fix it? Does it automatically create `.next/routes-manifest.json` for me by default?

**Comment by rohan-dave** [comment]
@baptisteArno @taro350 I'm getting this error deploying the builder as well. Any ideas on how you fixed it?
