### ISSUE TITLE
Limit of 50 "Typebot" logic links?

### ISSUE THREAD

**Issue by eduazy** [baptisteArno/typebot.io#429]
Hi, I've ran into an issue where I can't modify Typebot link nodes, they're stuck on "Loading..." and I can't select which block I want them to go to, the bot names aren't showing up either. This happens on previous blocks I added, and new blocks too. I've tried deleting and adding them back but the issue continues. Tried on Chrome and Firefox, same issue.

This is happening on a bot where I currently have 50 Typebot link blocks. Is that the limit, or just a bug? The ones I linked before this issue started are working correctly, but the names don't show up (just an empty blue square).

![Desktop Screenshot](https://user-images.githubusercontent.com/50171834/228004848-29952de4-e3f3-4dba-bc95-8c608efa006c.png)

**Comment by baptisteArno** [comment]
Can you see any error on the browser console or on the server (`docker-compose logs`)?

My guess is that the payload is too large, so it has a hard time fetching the linked typebots. We probably need to paginate this query. But I need to make sure. You should see some error logs somewhere.

**Comment by baptisteArno** [comment]
Ok, 50 typebot link block is a lot, I must say. Are all your link blocks pointing to a different typebot?

Are you using the cloud managed version? If so, would you mind sharing your bot URL to support@typebot.io?

**Comment by eduazy** [comment]
Most of them are pointing to 2 bots only (30 to one and 20 to another) but to different blocks in them.

I've sent you an email with the bot URL. Thanks!

**Comment by baptisteArno** [comment]
Hopefully this fixes it. Can you try again in 10 minutes and let me know?

**Comment by eduazy** [comment]
I have 46 Typebot link blocks working fine (linking to 5 bots in total), but as soon as I add the 47th block linking to a specific bot, I get this error:

![Desktop Screenshot 2023 03 30 - 10 42 58 60](https://user-images.githubusercontent.com/50171834/228782836-99a96f05-1d1c-4c2e-809b-34a45cf89f57.png)

And then all blocks turn into this:

![error](https://user-images.githubusercontent.com/50171834/228783035-44da425f-52cc-4f26-8c22-402429e1c64c.PNG)

This has fixed it for the most part, but now It's only happening when I link to that specific bot, linking to any of the others seems to work fine.

Thanks!
