### ISSUE TITLE
Add a profile picture upload block

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#433]
Currently there is indeed an image/file upload block, but a very useful feature would be a wizard/popup asking the user to crop/center their picture. Then, the cropped picture URL would be saved in a variable and reusable in later blocks.
![image](https://user-images.githubusercontent.com/73610779/228327634-2b151f33-86ac-4cb4-9e30-1c13f8a5e5a3.png)

**Comment by baptisteArno** [comment]
Typebot widget must:
- Work on several clients (web, whatsapp, messenger)
- Be lightweight

This kind of block, unfortunately, doesn't fit these 2 points... I hope you understand.
