### ISSUE TITLE
The bot you're looking for doesn't exist

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#44]
Hi guys.

I have a problem with self-hosted version of your great application

As far as I can see, everything is configured correctly. I am using docker installation method

The problem is that when I click on the "Sign in" button in the received email, I am being redirected to the builder domain, but the only thing that I receive is the following

![image](https://user-images.githubusercontent.com/3791124/169236178-61eacc59-3f3d-4269-83b7-436f3ffb18f5.png)

Basically, the frontend part of the application is working correctly. My email (configured in the .env file) is correctly recognized, I receive an email message which should allow me to log in to the builder, but the builder part doesn't recognize my email address or the initial bot is not created.

Can you point me into the right direction and point out what am I missing in my setup?

I am sure that I am missing something obvious but can't figure it out, what exactly

My apps/builder/.ev.production file content is the following

> DATABASE_URL=postgresql://postgres:typebot@db:5432/typebot
> NEXT_PUBLIC_VIEWER_URL=https://typebot.mihha-hosting.com
> ENCRYPTION_SECRET=my_secret_key
> ADMIN_EMAIL=my_email_value
> NEXTAUTH_URL=https://app.typebot.mihha-hosting.com
> NEXTAUTH_URL_INTERNAL=http://host.docker.internal:8080 #should I remove this
> SMTP_USERNAME=my_smtp_user_name
> SMTP_PASSWORD=my_smtp_password
> SMTP_HOST=my_smtp_host
> SMTP_PORT=465
> NEXT_PUBLIC_SMTP_FROM=my_sender_email

My apps/viewer/.env.production file content is the following

> DATABASE_URL=postgresql://postgres:typebot@db:5432/typebot
> NEXT_PUBLIC_VIEWER_URL=https://typebot.mihha-hosting.com
> ENCRYPTION_SECRET=my_secret_key
> ADMIN_EMAIL=my_email_value
> SMTP_USERNAME=my_smtp_user_name
> SMTP_PASSWORD=my_smtp_password
> SMTP_HOST=my_smtp_host
> SMTP_PORT=465
> NEXT_PUBLIC_SMTP_FROM=my_sender_email

Thank you in advance!

**Comment by baptisteArno** [comment]
Hey, @mihha thank you for posting this detailed issue.

It's your `NEXT_AUTH_URL` that doesn't look right: https://app.typebot.mihha-hosting.com/, this is an invalid URL. It should be your builder app URL ☺️

**Comment by mihha** [comment]
I don't understand

Viewer URL is contained in NEXT_PUBLIC_VIEWER_URL
Builder URL is contained in NEXTAUTH_URL

Viewer URL is the frontend of the site, so it is https://typebot.mihha-hosting.com
Builder URL is the backend (app part) and in my case this is https://app.typebot.mihha-hosting.com

Am I understanding this wrong?

**Comment by mihha** [comment]
I was following your documentation and similar to my setup, I can see in your documentation

![image](https://user-images.githubusercontent.com/3791124/169327538-83907d03-4f15-478e-ba22-0a03c974fb72.png)

**Comment by baptisteArno** [comment]
Oh ok, I see how it can be confusing! On the doc, I just give what I use for the official Cloud version!

But a URL with 2 subdomains is simply invalid: `sub1.sub2.domain.com` => you can't do that 😅

May I suggest in your case, for example:
For builder: https://typebot.mihha-hosting.com/
For viewer: https://bot.mihha-hosting.com/

**Comment by mihha** [comment]
Your reply about URL with 2 subdomains is not correct

https://en.wikipedia.org/wiki/Domain_name#Domain_name_syntax

> Next are third-level domains, which are written immediately to the left of a second-level domain. There can be fourth- and fifth-level domains, and so on, with virtually no limitation. An example of an operational domain name with four levels of domain labels is sos.state.oh.us. Each label is separated by a [full stop](https://en.wikipedia.org/wiki/Full_stop) (dot). 'sos' is said to be a sub-domain of 'state.oh.us', and 'state' a sub-domain of 'oh.us', etc. In general, [subdomains](https://en.wikipedia.org/wiki/Subdomain) are domains subordinate to their parent domain. An example of very deep levels of subdomain ordering are the [IPv6](https://en.wikipedia.org/wiki/IPv6) reverse resolution [DNS zones](https://en.wikipedia.org/wiki/DNS_zone), e.g., 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa, which is the reverse DNS resolution domain name for the IP address of a [loopback](https://en.wikipedia.org/wiki/Loopback) interface, or the [localhost](https://en.wikipedia.org/wiki/Localhost) name.

**Comment by mihha** [comment]
Guys, this is really not working

Now I have tried to set domains for both viewer and builder as a subdomain.domain.tld

viewer: typebot.mihha-hosting.com
builder: typebotapp.mihha-hosting.com

I have the same problem

I am obviously missing something in the configuration

Is there a way to debug this?

Maybe I have an issue with the Apache which is configured as reverse proxy for this docker installation?

Do you have a suggestion how to properly configure Apache Vhost for this?

**Comment by Famku** [comment]
Hi

I have the same problem ...

And I cannot upload images to a flow or as Avatar.

I can choose a local image but nothing happen when I click on upload.

Docker (Ubuntu) same config as mihha

**Comment by baptisteArno** [comment]
Hi guys,

For Next.js apps, when you change environment variables, you need to rebuild the app. Did you rebuild your containers?

@Famku See "S3 Storage" in the config doc: https://docs.typebot.io/self-hosting/configuration

**Comment by Famku** [comment]
The containers has been rebuilt after I changed variables.

"S3 Storage" means I need to buy AWS storage to upload images?

**Comment by baptisteArno** [comment]
When you click on the Sign In button, what email does that redirect you to?

> "S3 Storage" means I need to buy AWS storage to upload images?
It means any S3 compatible storage, it can be your own self-hosted Minio for example.

**Comment by Famku** [comment]
you mean the link from the sign in mail?

https://typebot.****.net:8443/api/auth/callback/email?callbackUrl=https%3A%2F%2Ftypebot.****.net%3A8443%2Fsignin&token=9163ca89861c16c271306a04b08656deb980d3a9ffbcd77efaffb2894df632e9&email=joerg%40****.net

**** - my domain

**Comment by baptisteArno** [comment]
I mean when you see the "404" message, what is your URL?

**Comment by Famku** [comment]
https://typebotview.****.net:8443/lead-generation-copy-waezfev

**Comment by baptisteArno** [comment]
Oh ok, so it doesn't happen when you click on the Sign-in button from the Email. It's not the same issue as @mihha.

Did you published the bot?

**Comment by Famku** [comment]
oh, sorry, I thought it was the same behavior. (it is the same message)

Yes I published the bot

**Comment by baptisteArno** [comment]
That's odd! Do you mind sending me the entire URL to baptiste@typebot.io? I can't guess what's happening!

**Comment by baptisteArno** [comment]
> I mean when you see the "404" message, what is your URL?

@mihha I need this info to help you out

**Comment by Famku** [comment]
I sent you the full url

Thanks for your help

**Comment by mihha** [comment]
@baptisteArno 

I have sent you full URL to your email as requested

I rebuild the docker image every time i change variable in the .env.* file

**Comment by mihha** [comment]
If it helps, I have checked the builder container logs and this is what I see there

```
https://next-auth.js.org/errors#client_fetch_error invalid json response body at https://typebotapp.mihha-hosting.com/api/auth/session reason: Unexpected token < in JSON at position 0 {
  error: {
    message: 'invalid json response body at https://typebotapp.mihha-hosting.com/api/auth/session reason: Unexpected token < in JSON at position 0',
    stack: 'FetchError: invalid json response body at https://typebotapp.mihha-hosting.com/api/auth/session reason: Unexpected token < in JSON at position 0\n' +
      '    at /app/node_modules/next/dist/compiled/node-fetch/index.js:1:49606\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)',
    name: 'FetchError'
  },
  path: 'session',
  header: {
    host: 'localhost:38080',
    'cache-control': 'max-age=0',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'sec-gpc': '1',
    'sec-fetch-site': 'none',
    'sec-fetch-mode': 'navigate',
    'sec-fetch-user': '?1',
    'sec-fetch-dest': 'document',
    'accept-encoding': 'gzip, deflate, br',
    'accept-language': 'en-GB,en-US;q=0.9,en;q=0.8,hr;q=0.7',
    cookie: '__Host-next-auth.csrf-token=1f0fb411cbcd9b08189bcf0e1c84b26db1bc5fa960a9dbb5ca633ab4c2d76507%7C8d29cda1b2fbd3c4b8dbbd57f7a35070a0af8ebc550aec694a98e48a71c21aba; __stripe_mid=bff1cda1-190e-4acf-91e2-fed9db6034eb28d3e0; __Secure-next-auth.callback-url=https%3A%2F%2Ftypebotapp.mihha-hosting.com',
    dnt: '1',
    'x-forwarded-for': '213.147.96.240',
    'x-forwarded-host': 'typebot.mihha-hosting.com',
    'x-forwarded-server': 'typebot.mihha-hosting.com',
    connection: 'Keep-Alive'
  },
  message: 'invalid json response body at https://typebotapp.mihha-hosting.com/api/auth/session reason: Unexpected token < in JSON at position 0'
}
```

**Comment by mihha** [comment]
OK. Another update

I have configured properly NEXTAUTH_URL_INTERNAL variable and now there is no JSON error in the log

Unfortunately, the issue is still present. When I click the link from the email, I still get "The bot you're looking for doesn't exist"

**Comment by mihha** [comment]
During the building process there is a warning (don't know if this is important)

```
warning " > bot-engine@0.1.0" has unmet peer dependency "react@^18.1.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-frame-component@5.2.2-alpha.1" has unmet peer dependency "prop-types@^15.5.9".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-frame-component@5.2.2-alpha.1" has unmet peer dependency "react@>= 16.3".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-frame-component@5.2.2-alpha.1" has unmet peer dependency "react-dom@>= 16.3".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-phone-number-input@3.1.52" has unmet peer dependency "react@>=0.16.8".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-phone-number-input@3.1.52" has unmet peer dependency "react-dom@>=0.16.8".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-scroll@1.8.7" has unmet peer dependency "react@^15.5.4 || ^16.0.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-scroll@1.8.7" has unmet peer dependency "react-dom@^15.5.4 || ^16.0.0 || ^17.0.0 || ^18.0.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-transition-group@4.4.2" has unmet peer dependency "react@>=16.6.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > react-transition-group@4.4.2" has unmet peer dependency "react-dom@>=16.6.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > @typescript-eslint/eslint-plugin@5.23.0" has unmet peer dependency "@typescript-eslint/parser@^5.0.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > eslint-config-next@12.1.6" has unmet peer dependency "next@>=10.2.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > bot-engine > eslint-plugin-prettier@4.0.0" has unmet peer dependency "prettier@>=2.0.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > db > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > next@12.1.6" has unmet peer dependency "react@^17.0.2 || ^18.0.0-0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > next@12.1.6" has unmet peer dependency "react-dom@^17.0.2 || ^18.0.0-0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core@11.0.0" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core@11.0.0" has unmet peer dependency "react-dom@>=16.8.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core@11.0.0" has unmet peer dependency "slate@>=0.66.1".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core@11.0.0" has unmet peer dependency "slate-history@>=0.66.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core@11.0.0" has unmet peer dependency "slate-react@>=0.74.2".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > next > styled-jsx@5.0.2" has unmet peer dependency "react@>= 16.8.0 || 17.x.x || ^18.0.0-0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core > jotai@1.6.6" has unmet peer dependency "react@>=16.8".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core > use-deep-compare@1.1.0" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core > @udecode/zustood > react-tracked@1.7.9" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core > @udecode/zustood > react-tracked@1.7.9" has unmet peer dependency "scheduler@>=0.19.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core > @udecode/zustood > react-tracked > use-context-selector@1.3.10" has unmet peer dependency "react@>=16.8.0".
warning "workspace-aggregator-72ada6ba-7029-46de-9848-e2702c80cc48 > models > @udecode/plate-core > @udecode/zustood > react-tracked > use-context-selector@1.3.10" has unmet peer dependency "scheduler@>=0.19.0".

```

Similar warnings happen when the builder part is being built

**Comment by teq-dev** [comment]
Hello. I have been following this issue because I am self-hosting Typebot with Docker as well. I am not seeing these issues with my deployment.

When I look at your Typebot URLs, it seems like maybe you have the two applications swapped in your Apache reverse-proxy configuration?

When I visit https://typebotapp.mihha-hosting.com, I see the Viewer interface, and when I visit https://typebot.mihha-hosting.com I am seeing the Builder interface. That seems to be the opposite of what you are expecting to see.

If so, would you mind posting (or sending to me) the relevant portions of your Apache reverse proxy configuration and the output of `docker ps` for the Typebot containers?

**Comment by mihha** [comment]
Sign up page is on
https://typebot.mihha-hosting.com/signin

**Comment by mihha** [comment]
Guys, I finally did it!!!!

I didn't understand the configuration documentation quite well and hence the all confusion around it

I have confused NEXT_PUBLIC_VIEWER_URL and NEXTAUTH_URL config parameters

After few iterations, I managed to get this right

Everything is working now

Sorry to bother you with this problem

**Comment by mihha** [comment]
I spoke too soon 😥

I believe that there is a great confusion about the configuration variables that needs to be set so can you please confirm what I have to write where

I have two subdomains:
1. https://typebot.mihha-hosting.com/
2. https://typebotapp.mihha-hosting.com/

**My builder environment configuration is this** (just parameters that have domain as a value)

```
NEXT_PUBLIC_VIEWER_URL=https://typebot.mihha-hosting.com
NEXTAUTH_URL=https://typebot.mihha-hosting.com
NEXTAUTH_URL_INTERNAL=http://host.docker.internal:38080
```

**My viewer environment configuration is this** (just parameters that have domain as a value)

`NEXT_PUBLIC_VIEWER_URL=https://typebot.mihha-hosting.com
`

**My Apache virtual hosts are the following** (just proxy part, since other parameters are not important here)
1. for the domain, https://typebot.mihha-hosting.com/

```
ProxyPass / http://localhost:38080/
ProxyPassReverse / http://localhost:38080/
```

2. for the domain, https://typebotapp.mihha-hosting.com/

```
ProxyPass / http://localhost:38081/
ProxyPassReverse / http://localhost:38081/
```

**My docker-compose file is**
```
version: '3.9'
services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  builder:
    depends_on:
      - db
    build:
      context: .
      args:
        - SCOPE=builder
    ports:
      - '38080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      - './apps/builder/.env.production'
    entrypoint: >
      /bin/sh -c "
      ./node_modules/.bin/prisma generate;
      echo 'Waiting 5s for db to be ready...';
      sleep 5;
      ./node_modules/.bin/prisma migrate deploy;
      node server.js;"
  viewer:
    depends_on:
      - db
    restart: always
    build:
      context: .
      args:
        - SCOPE=viewer
    ports:
      - '38081:3000'
    env_file:
      - './apps/viewer/.env.production'
    entrypoint: >
      /bin/sh -c "
      ./node_modules/.bin/prisma generate;
      node server.js;"
volumes:
  db_data:
  s3_data:

```

**Comment by baptisteArno** [comment]
NEXTAUTH_URL should be set to https://typebotapp.mihha-hosting.com/

**Comment by mihha** [comment]
What about Apache proxy configurations?

Are they correct?

**Comment by mihha** [comment]
It would be helpful if you would provide your docker-compose file, configuration files and Apache proxy parameters for comparison

It is obviously that we are running in circles here

I have tried already every possible configuration that I could think

The last one that worked apparently correctly produced a new error when I tried to see published bot

When I accessed bot URL, I got "page not found" error

**Comment by baptisteArno** [comment]
Clearly the issue here is that your NEXTAUTH_URL should be the builder URL not the viewer.

If you have other issues when doing so open a new issue :)

**Comment by mihha** [comment]
I already changed that parameter and rebuild everything with no luck

Can you please provide your .env files, your docker-compose file and your Apache proxy configurations so I can compare working environment with my own?

**Comment by mihha** [comment]
OK

I did just as you suggested and double-checked everything

I also rebuilt docker using "--no-cache" parameter to be sure that everything will be rebuilt from the beginning

I have the same issue as before

After this, I believe that I will just stop working on this. I really like Typebot (I have signed up for your hosted version and tried it), but running like this in circles without any progress is just too much

Thank you all for your effort and time spent on this.

Maybe I will return to this at some later time, but for now, since I don't know what else I can do, I think it is enough

**Comment by mihha** [comment]
It is set like this

![image](https://user-images.githubusercontent.com/3791124/169619505-ab69ec54-c0f2-40cb-951f-b932a5525d2d.png)

**Comment by baptisteArno** [comment]
Oooh maybe the bug comes from `NEXTAUTH_URL_INTERNAL`, you don't need to set that because your `NEXTAUTH_URL` is publicly accessible.

**Comment by baptisteArno** [comment]
I understand the struggle and I'm sorry it didn't work out well for you. I'll close this for now but feel free to re-open it.

**Comment by mihha** [comment]
Hi guys!

First, thank you very much for all your help you were willing to provide in this ticket. After a long, long struggle, it seems that I finally managed to resolve the main issue (mixture of builder and viewer domains and authentication)

Now, I have a different problem as it seems

When I publish a bot and try to access it using a viewer URL created from the builder backend interface, I have (again) the same problem with error 404 (The bot you're looking for doesn't exist)

As it seems, builder interface is now working correctly. I can create a bot, add all the elements to it and even test it in the Preview. If I publish the bot and then try to access the URL to see it in the production, it shows me error 404

I honestly don't know where to look further

**Comment by mihha** [comment]
Hi,

1. My `apps/viewer/.env.production` has a valid `NEXT_PUBLIC_VIEWER_URL` value (https://typebot.mihha-hosting.com/)
2. `docker-compose logs` shows nothing special

```
viewer_1   | Prisma schema loaded from prisma/schema.prisma
viewer_1   |
viewer_1   | ✔ Generated Prisma Client (3.14.0 | library) to ./node_modules/@prisma/client in 625ms
viewer_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
viewer_1   | ```
viewer_1   | import { PrismaClient } from '@prisma/client'
viewer_1   | const prisma = new PrismaClient()
viewer_1   | ```
viewer_1   | info  - Loaded env from /app/.env.production
viewer_1   | Listening on port 3000

```

**Comment by baptisteArno** [comment]
The value should not end with a trailing slash. Make sure it is `https://typebot.mihha-hosting.com`.

**Comment by mihha** [comment]
It doeysn0't end with the trailing slash

This is something GitHub added when I pasted my URL

![image](https://user-images.githubusercontent.com/3791124/169874300-f9240644-16c7-457c-ae36-a1fb91abf689.png)

**Comment by baptisteArno** [comment]
Perfect, to have relevant logs, first load the page that displays the "404" error and only then print the logs

**Comment by baptisteArno** [comment]
Oh, I think we don't have the logs because it was added after you pulled the repository. Can you pull the latest modifications on main and re-deploy the app?

**Comment by mihha** [comment]
Now when I recreated the container after the 'git pull' I have this in logs

```
viewer_1   | Couldn't find customDomain: localhost:38081/contact_me
viewer_1   | Couldn't find customDomain: localhost:38081/favicon.ico
```

**Comment by baptisteArno** [comment]
Ok, it seems the `host` HTTP header is being overwritten by your reverse proxy. I'll implement something shortly that should work in theory.

**Comment by baptisteArno** [comment]
Can you pull this commit and let me know? 😀

**Comment by mihha** [comment]
Your comment led me to the solution

I have added the following in my Apache Vhost configuration

`ProxyPreserveHost On`

Final Apache Vhost for reverse proxy, for the Viewer domain now looks like this

```
ProxyPreserveHost On
ProxyPass / http://localhost:38081/
ProxyPassReverse / http://localhost:38081/
```

Final Apache Vhost for reverse proxy, for the Builder domain now looks like this

```
ProxyPass / http://localhost:38081/
ProxyPassReverse / http://localhost:38081/

```

You might want to create a documentation article for reverse proxy configuration and add this info there. Change the port obviously to some generic port number, which you are using elsewhere in the documentation

**Comment by baptisteArno** [comment]
Awesome, glad it works now 🔥

**Comment by mihha** [comment]
Yes, finally 😀

Thank you a lot for your effort and provided help
