### ISSUE TITLE
self-host docker installation not working

### ISSUE THREAD

**Issue by zawyetun** [baptisteArno/typebot.io#441]
I tried to install open source version via docker.

But it only shows login page and doesn't work for both email auth and google auth.

For email auth, it shows magic link email was sent but I never received it. Do I need to configure magic link email feature somewhere?

Can anyone successfully iinstall self-hosted docker version? Appreciate someone can show steps by steps guide aside from guides from typebot because I followed it the same and not sure what additional things need to configure aside from that guide.

**Comment by zawyetun** [comment]
Hosted in AWS Light Sail, Ubuntu.

Below is Docker log:

Attaching to ubuntu_typebot-builder_1, ubuntu_typebot-viewer_1, ubuntu_typebot-db_1
typebot-builder_1  | env.sh loaded
typebot-builder_1  | Matched inline env:
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@mydomain.com>
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=https://mydomain.com:8081
typebot-builder_1  | Reading ./apps/builder/.env.production...
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM=
typebot-builder_1  | NEXT_PUBLIC_GOOGLE_API_KEY=
typebot-builder_1  | NEXT_PUBLIC_GIPHY_API_KEY=
typebot-builder_1  | NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
typebot-builder_1  | NEXT_PUBLIC_SENTRY_DSN=
typebot-builder_1  | NEXT_PUBLIC_VIEWER_INTERNAL_URL=
typebot-builder_1  | NEXT_PUBLIC_E2E_TEST=
typebot-builder_1  | NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@mydomain.com>
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=https://mydomain.com:8081
typebot-builder_1  | Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
typebot-builder_1  | Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
typebot-builder_1  | env.sh done
typebot-builder_1  |
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  |
typebot-builder_1  |  Generated Prisma Client (4.11.0 | library) to ./node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client i
n 789ms
typebot-builder_1  | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-builder_1  | ```
typebot-builder_1  | import { PrismaClient } from '@prisma/client'
typebot-builder_1  | const prisma = new PrismaClient()
typebot-builder_1  | ```
typebot-builder_1  | Waiting 5s for db to be ready...
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"
typebot-builder_1  |
typebot-builder_1  | 50 migrations found in prisma/migrations
typebot-builder_1  |
typebot-builder_1  | No pending migrations to apply.
typebot-builder_1  | ┌─────────────────────────────────────────────────────────┐
typebot-builder_1  | │  Update available 4.11.0 -> 4.12.0                      │
typebot-builder_1  | │  Run the following to update                            │
typebot-builder_1  | │    npm i --save-dev prisma@latest                       │
typebot-builder_1  | │    npm i @prisma/client@latest                          │
typebot-builder_1  | └─────────────────────────────────────────────────────────┘
typebot-builder_1  | info  - Loaded env from /app/apps/builder/.env.production
typebot-builder_1  | Listening on port 3000 url: http://416a37218761:3000
typebot-builder_1  | (node:344) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
typebot-builder_1  |
typebot-builder_1  | Please migrate your code to use AWS SDK for JavaScript (v3).
typebot-builder_1  | For more information, check the migration guide at https://a.co/7PzMCcy
typebot-builder_1  | (Use `node --trace-warnings ...` to show where the warning was created)
typebot-db_1       | The files belonging to this database system will be owned by user "postgres".
typebot-db_1       | This user must also own the server process.
typebot-db_1       |
typebot-db_1       | The database cluster will be initialized with locale "en_US.utf8".
typebot-db_1       | The default database encoding has accordingly been set to "UTF8".
typebot-db_1       | The default text search configuration will be set to "english".
typebot-db_1       |
typebot-db_1       | Data page checksums are disabled.
typebot-db_1       |
typebot-db_1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
typebot-db_1       | creating subdirectories ... ok
typebot-db_1       | selecting dynamic shared memory implementation ... posix
typebot-db_1       | selecting default max_connections ... 100
typebot-db_1       | selecting default shared_buffers ... 128MB
typebot-db_1       | selecting default time zone ... Etc/UTC
typebot-db_1       | creating configuration files ... ok
typebot-db_1       | running bootstrap script ... ok
typebot-db_1       | performing post-bootstrap initialization ... ok
typebot-db_1       | syncing data to disk ... ok
typebot-db_1       |
typebot-db_1       | initdb: warning: enabling "trust" authentication for local connections
typebot-db_1       | You can change this by editing pg_hba.conf or using the option -A, or
typebot-db_1       | --auth-local and --auth-host, the next time you run initdb.
typebot-db_1       |
typebot-db_1       | Success. You can now start the database server using:
typebot-db_1       |     pg_ctl -D /var/lib/postgresql/data -l logfile start
typebot-db_1       |
typebot-db_1       | waiting for server to start....2023-04-03 03:48:45.387 UTC [47] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-p
c-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
typebot-db_1       | 2023-04-03 03:48:45.390 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
typebot-db_1       | 2023-04-03 03:48:45.399 UTC [48] LOG:  database system was shut down at 2023-04-03 03:48:45 UTC
typebot-db_1       | 2023-04-03 03:48:45.405 UTC [47] LOG:  database system is ready to accept connections
typebot-db_1       |  done
typebot-db_1       | server started
typebot-db_1       | CREATE DATABASE
typebot-db_1       |
typebot-db_1       |
typebot-db_1       | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
typebot-db_1       |
typebot-db_1       | 2023-04-03 03:48:45.904 UTC [47] LOG:  received fast shutdown request
typebot-db_1       | waiting for server to shut down....2023-04-03 03:48:45.911 UTC [47] LOG:  aborting any active transactions
typebot-db_1       | 2023-04-03 03:48:45.927 UTC [47] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
typebot-db_1       | 2023-04-03 03:48:45.928 UTC [49] LOG:  shutting down
typebot-db_1       | 2023-04-03 03:48:45.948 UTC [47] LOG:  database system is shut down
typebot-db_1       |  done
typebot-db_1       | server stopped
typebot-db_1       |
typebot-db_1       | PostgreSQL init process complete; ready for start up.
typebot-db_1       |
typebot-db_1       | 2023-04-03 03:48:46.077 UTC [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (De
bian 10.2.1-6) 10.2.1 20210110, 64-bit
typebot-db_1       | 2023-04-03 03:48:46.081 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
typebot-db_1       | 2023-04-03 03:48:46.082 UTC [1] LOG:  listening on IPv6 address "::", port 5432
typebot-db_1       | 2023-04-03 03:48:46.086 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
typebot-db_1       | 2023-04-03 03:48:46.093 UTC [62] LOG:  database system was shut down at 2023-04-03 03:48:45 UTC
typebot-db_1       | 2023-04-03 03:48:46.098 UTC [1] LOG:  database system is ready to accept connections
typebot-db_1       | 2023-04-03 05:53:03.670 UTC [326] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-04-03 06:03:41.584 UTC [348] LOG:  could not receive data from client: Connection reset by peer
typebot-viewer_1   | env.sh loaded
typebot-viewer_1   | Matched inline env:
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=https://mydomain.com:8081
typebot-viewer_1   | Reading ./apps/viewer/.env.production...
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=
typebot-viewer_1   | NEXT_PUBLIC_E2E_TEST=
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=https://mydomain.com:8081
typebot-viewer_1   | Got index from inline env: 0, replacing NEXT_PUBLIC_VIEWER_URL
typebot-viewer_1   | env.sh done
typebot-viewer_1   |
typebot-viewer_1   | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-viewer_1   |
typebot-viewer_1   |  Generated Prisma Client (4.11.0 | library) to ./node_modules/.pnpm/@prisma+client@4.11.0_prisma@4.11.0/node_modules/@prisma/client i
n 1.68s
typebot-viewer_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-viewer_1   | ```
typebot-viewer_1   | import { PrismaClient } from '@prisma/client'
typebot-viewer_1   | const prisma = new PrismaClient()
typebot-viewer_1   | ```
typebot-viewer_1   | info  - Loaded env from /app/apps/viewer/.env.production
typebot-viewer_1   | Listening on port 3000 url: http://51f4eb7d6ede:3000

**Comment by baptisteArno** [comment]
I don't see any error in the logs.

> but I never received it

Can you check email transactions logs from your email provider? Can you see anything?

**Comment by zawyetun** [comment]
I tried with sendinblue smtp, no log there and now I tried with normal email account, nothing in sent item also.

**Comment by zawyetun** [comment]
> I don't see any error in the logs.
> 
> > but I never received it
> 
> Can you check email transactions logs from your email provider? Can you see anything?


I tried with sendinblue smtp, no log there and now I tried with normal email account, nothing in sent item also.

**Comment by baptisteArno** [comment]
Are you sure you checked typebot's server logs after trying to log in?

Without any error somewhere, I can't guess what's wrong, unfortunately 🤔

Is your VPS allowed to send emails?

**Comment by zawyetun** [comment]
> Are you sure you checked typebot's server logs after trying to log in?
> 
> Without any error somewhere, I can't guess what's wrong, unfortunately 🤔
> 
> Is your VPS allowed to send emails?

Like I mentioned, emails are not sent from VPS. Emails are sent from Sendinblue SMTP or a legit email account.

May I know where to get logs for typebot aside from docker log?

**Comment by baptisteArno** [comment]
Typebot connects to an SMTP server using the specified port. Sometimes these ports are blocked even for outgoing requests.

But then you would not have the success message on Typebot. So I'm a bit clueless! 🤔

**Comment by zawyetun** [comment]
Aside from these guides, https://docs.typebot.io/self-hosting/docker and https://docs.typebot.io/self-hosting/configuration/builder and viewer, do I need to configure any others extra?
Sorry, I am new to docker also. But followed everything in the guides.

**Comment by baptisteArno** [comment]
This is not an issue with your docker config whatsoever, but an issue with your SMTP configuration. Are you sure you have nothing in the Transactional > Logs page in Sendinblue?

**Comment by zawyetun** [comment]
> This is not an issue with your docker config whatsoever, but an issue with your SMTP configuration. Are you sure you have nothing in the Transactional > Logs page in Sendinblue?

yes, nothing.

**Comment by zawyetun** [comment]
> What typebot version have you pulled?

pulled with this command,  wget https://raw.githubusercontent.com/baptisteArno/typebot.io/latest/docker-compose.yml

So I assume, it is latest version.

**Comment by zawyetun** [comment]
<img width="380" alt="Screenshot 2023-04-03 at 11 32 12 PM" src="https://user-images.githubusercontent.com/20561945/229557496-4677848e-722c-4e21-828c-106c03f5fcce.png">

I was using this and since it doesn't work, I changed to normal email account. But tomorrow I will try Sendinblue SMTP with new VPS.

**Comment by zawyetun** [comment]
I just tried with new VPS with new sendinblue SMTP key, still the same, no email received and no log in Sendinblue also. :'(

**Comment by baptisteArno** [comment]
My SMTP config:

```
SMTP_USERNAME=baptiste@typebot.io
SMTP_PASSWORD=...
SMTP_HOST=smtp-relay.sendinblue.com
SMTP_PORT=587
NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@typebot.io>
```

**Comment by zawyetun** [comment]
In my SMTP settings, I have SMTP_SECURE and SMTP_AUTH_DISABLED "false" also. I have removed them and tried only with your SMTP config. No luck, not receiving any email.

**Comment by baptisteArno** [comment]
Can you try to just set `notifications@mydomain.com` as `NEXT_PUBLIC_SMTP_FROM`?

Also, maybe you have to create an appropriate sender here: https://app.sendinblue.com/senders/list

But again, I find it strange that you don't have any error 🤔

**Comment by baptisteArno** [comment]
Feel free to re-open 👌
