### ISSUE TITLE
Conditional rendering of variables in text

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#445]
### Discussed in https://github.com/baptisteArno/typebot.io/discussions/444

<div type='discussions-op-text'>

<sup>Originally posted by **altomarketing** April  3, 2023</sup>
i wrote several bots for different uses cases, lets call them _Cases_..  

then all bots redirects to a single bot called (_sender_)

this final sender bot, send results using Mail feature by mailgun, but every cases bot, has different variables,

 **is it possible to send only all variables that are defined ?** 

Now i use like this

![imagen](https://user-images.githubusercontent.com/474889/229627454-d6ffc115-d803-4409-810c-aa1b51254623.png)
</div>

**Comment by rishi-raj-jain** [comment]
@baptisteArno 

- Is there an function/API call that will help locate the available variables?
- Are you looking to reward via Algora?
