### ISSUE TITLE
OpenAI Invalid Key Length

### ISSUE THREAD

**Issue by caoramos** [baptisteArno/typebot.io#446]
In version 2.1.1.9 I cannot enter OpenAI secret key. It keeps saying that it is invalid key length. My key is correct. It is working in my test account in saas version, but not in my hosted version.

![Screenshot - 2023-04-04T205452 778](https://user-images.githubusercontent.com/11988813/229948920-70474bc7-6b79-43ce-b144-d7988d6f02ad.png)

**Comment by baptisteArno** [comment]
I understand that it is confusing. It has nothing to do with your OpenAI credentials.

It means your `ENCRYPTION_SECRET` environment variable has an invalid length. Can you replace it with a valid one and try again?
