### ISSUE TITLE
Option to set bubble height and width

### ISSUE THREAD

**Issue by lpadula** [baptisteArno/typebot.io#458]
Hi! It would be great to be able to set bubble chat height and width.

**Comment by baptisteArno** [comment]
Are you referring to this?

![CleanShot 2023-04-14 at 09 47 04@2x](https://user-images.githubusercontent.com/16015833/231979158-a18fd564-fa62-46b6-a0d7-c10378dddde2.png)

**Comment by lpadula** [comment]
Yes!

**Comment by satoshinotdead** [comment]
Related: I was need to hard-edit the JS file in order to prevent that bubble button width and height 'scale after click' and not in loading.

My knowledge coding is very little but BTW I hope it helps :)

**Comment by baptisteArno** [comment]
> to prevent that bubble button width and height 'scale after click' and not in loading.

Can you explain? I'm not sure to understand

**Comment by lpadula** [comment]
He edited a js file to achieve that. I think that the user should be able to add some parameters on the installation script or maybe directly on the "theme" options.

**Comment by rishi-raj-jain** [comment]
@baptisteArno

Is it open to new attempts?

**Comment by mithleshfantezie** [comment]
/attempt https://github.com/baptisteArno/typebot.io/issues/458
