### ISSUE TITLE
Having trouble with web.js

### ISSUE THREAD

**Issue by fawwal** [baptisteArno/typebot.io#464]
Embedding from the self-hosted version of this, this was working, and I haven't changed anything - to my knowledge - I'm seeing browser errors from the Javascript  

TypeError on https://cdn.jsdelivr.net/npm/@typebot.io/js@0.0/dist/web.js:1

Uncaught (in promise) TypeError: e is undefined

Thoughts? Fixes? 

<img width="461" alt="ScreenShot 2023-04-14 at 23 43 27@2x" src="https://user-images.githubusercontent.com/14047152/232181298-48edb37d-d080-4ab9-b9ae-b746c7225f0e.png">

**Comment by fawwal** [comment]
Changing the Url to ./js@0.0.9/.. seems to have fixed the issue.

**Comment by baptisteArno** [comment]
Indeed, that's an issue. For self-hosting version, it needs to point to a non-aliased jsdelivr endpoint to avoid mismatch between viewer and JS embed.

`./js@0.0.34/..` should work and. Do you confirm?

**Comment by baptisteArno** [comment]
Will be fixed in the next release 🙏

**Comment by crishnakh** [comment]
Same error here, I confirm this

> ./js@0.0.34/.. should work 

Fix the problem

**Comment by panzer9** [comment]
I have very little to no experience with code, so it was very lucky that I managed to fix this.

I change the URL to https://cdn.jsdelivr.net/npm/@typebot.io/js@0.0.34/dist/web.js

and it worked!
