### ISSUE TITLE
api/v1/sendMessage - missing ) after argument list

### ISSUE THREAD

**Issue by crowtechAI** [baptisteArno/typebot.io#465]
this is the JSON body to the API
{
  "message": "my-message",
  "sessionId": "...6pj6dhf3dlkod"
}

response is:
{
    "message": "missing ) after argument list",
    "code": "INTERNAL_SERVER_ERROR"
}

Logs: 

Something went wrong SyntaxError: missing ) after argument list
    at Function (<anonymous>)
    ... 8 lines matching cause stack trace ...
    at async next (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:460:32) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: SyntaxError: missing ) after argument list
      at Function (<anonymous>)
      at /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1615:22
      at Array.reduce (<anonymous>)
      at executeWebhookBlock (/app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1611:64)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2837:327
      at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2292:84
      at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:416:30)
      at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:452:32)
      at async next (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:460:32)

tried to get to the issue myself but couldn't access the file

**Comment by baptisteArno** [comment]
Can you share the error log you have on the server?

`docker-compose logs`

**Comment by crowtechAI** [comment]
typebot-viewer_1   | Something went wrong SyntaxError: missing ) after argument list
typebot-viewer_1   |     at Function (<anonymous>)
typebot-viewer_1   |     ... 8 lines matching cause stack trace ...
typebot-viewer_1   |     at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:297:24) {
typebot-viewer_1   |   code: 'INTERNAL_SERVER_ERROR',
typebot-viewer_1   |   name: 'TRPCError',
typebot-viewer_1   |   [cause]: SyntaxError: missing ) after argument list
typebot-viewer_1   |       at Function (<anonymous>)
typebot-viewer_1   |       at /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1615:22
typebot-viewer_1   |       at Array.reduce (<anonymous>)
typebot-viewer_1   |       at executeWebhookBlock (/app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1611:64)
typebot-viewer_1   |       at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2837:327
typebot-viewer_1   |       at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2292:84
typebot-viewer_1   |       at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:416:30)
typebot-viewer_1   |       at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:452:32)
typebot-viewer_1   |       at async next (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:460:32)
typebot-viewer_1   |       at async outputMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:297:24)
typebot-viewer_1   | }
typebot-viewer_1   | Something went wrong SyntaxError: missing ) after argument list
typebot-viewer_1   |     at Function (<anonymous>)
typebot-viewer_1   |     ... 8 lines matching cause stack trace ...
typebot-viewer_1   |     at async next (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:460:32) {
typebot-viewer_1   |   code: 'INTERNAL_SERVER_ERROR',
typebot-viewer_1   |   name: 'TRPCError',
typebot-viewer_1   |   [cause]: SyntaxError: missing ) after argument list
typebot-viewer_1   |       at Function (<anonymous>)
typebot-viewer_1   |       at /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1615:22
typebot-viewer_1   |       at Array.reduce (<anonymous>)
typebot-viewer_1   |       at executeWebhookBlock (/app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:1611:64)
typebot-viewer_1   |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
typebot-viewer_1   |       at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2837:327
typebot-viewer_1   |       at async /app/apps/viewer/.next/server/pages/api/v1/[...trpc].js:2292:84
typebot-viewer_1   |       at async resolveMiddleware (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:416:30)
typebot-viewer_1   |       at async callRecursive (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:452:32)
typebot-viewer_1   |       at async next (file:///app/node_modules/.pnpm/@trpc+server@10.18.0/node_modules/@trpc/server/dist/index.mjs:460:32)
typebot-viewer_1   | }

**Comment by crowtechAI** [comment]
its really strange as I can call a webhook from within the builder web hook block, but when I try the preview/publish/ use the typebot API it returns this,

**Comment by baptisteArno** [comment]
Oh ok, so the issue is with a Webhook block. Can you share your webhook block configuration?

Is the Test request working?

**Comment by crowtechAI** [comment]
so the test request works fine, I don't have any parameters on the configuration, literally just the url  as a POST request. I had a look at the ...trpc.js. there was an issue here: 


const func = Function("data", `return data.${(0,_features_variables_parseVariables__WEBPACK_IMPORTED_MODULE_10__/* .parseVariables */ .e)(typebot.>



 was missing closing parenthesis. I thought it may have fixed it but I don't think the change took effect as you have to create another image to save changes? I dunno not experienced with docker at all. but the error I got sent me to this.

```
const newVariables = block.options.responseVariableMapping.reduce((newVariables, varMapping)=>{
        if (!varMapping?.bodyPath || !varMapping.variableId) return newVariables;
        const existingVariable = typebot.variables.find((0,_typebot_io_lib__WEBPACK_IMPORTED_MODULE_3__/* .byId */ .L7)(varMapping.variableId));
        if (!existingVariable) return newVariables;
        const func = Function("data", `return data.${(0,_features_variables_parseVariables__WEBPACK_IMPORTED_MODULE_10__/* .parseVariables */ .e)(typebot.>
        try {
            const value = func(webhookResponse);
            return [
                ...newVariables,
                {
                    ...existingVariable,
                    value
                }
            ];
        } catch (err) {
            return newVariables;
        }
    }, []);
```

**Comment by baptisteArno** [comment]
If you don't provide a way to reproduce the bug, I can't help, really!

Can you create a minimal bot that reproduces the issue? Then you can share the file here so that we can try it.

**Comment by crowtechAI** [comment]
it does it with the openai block too. literally, just add a new openai block, add your key set the variables for the input and response and run it. not much else to it. it maybe my install so when I get a chance ill re-install it and see

**Comment by baptisteArno** [comment]
Can you share the typebot that is failing with the OpenAI block and the error message that you see?

**Comment by baptisteArno** [comment]
Feel free to re-open 👌
