### ISSUE TITLE
Docker builder could not connect to database

### ISSUE THREAD

**Issue by tboulogne** [baptisteArno/typebot.io#468]
Hello Baptiste,

Since 2.12.1, docker-builder image could not connect to database (postgres). Works well on image 2.12.0.
![image](https://user-images.githubusercontent.com/6205275/233057737-d853cb60-2103-42bb-8df0-4bdafb8ae57d.png)

Let me know if you want more info in PM :-).

Regards,

Thierry

**Comment by baptisteArno** [comment]
Happens every time you start the docker-compose? Can we get more logs?

Nothing has changed on that part so I don't know what's going on

**Comment by tboulogne** [comment]
I don't user docker-compose :-). I use [easypanel](https://easypanel.io).

I think there is something with prisma client (upgrade between 2.12.0 to 2.12.1, if i don't make a mistake...)

```

Prisma schema loaded from packages/prisma/postgresql/schema.prisma

✔ Generated Prisma Client (4.12.0 | library) to ./node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 376ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
``
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
``
Waiting 5s for db to be ready...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
Datasource "db": PostgreSQL database "chatbot", schema "public" at "chatbot_typebot-db:5432"

Error: P1001: Can't reach database server at `chatbot_typebot-db`:`5432`

Please make sure your database server is running at `chatbot_typebot-db`:`5432`.
info  - Loaded env from /app/apps/builder/.env.production
```

**Comment by baptisteArno** [comment]
I think the issue is due to the fact that your hostname `chatbot_typebot-db` contains an underscore, which is forbidden? Can you try change the name accordingly?

**Comment by tboulogne** [comment]
working well since i start using typebot 2.10.x to 2.12.0 :-).

What was the change there ?

Could not change name, it's easypanel format for networking. So it's mean i will be stick on 2.12.0....

**Comment by baptisteArno** [comment]
The error is from the psql client used by Prisma, which doesn't change at all.

It clearly says that it can't reach the database server. Nothing to do with Typebot code base… Maybe easypanel is changing something under the hood when you upgrade the image 🤷

You are saying 2.12.0 is working fine but 2.12.1 is not?

**Comment by tboulogne** [comment]
```
You are saying 2.12.0 is working fine but 2.12.1 is not?
```

Yes, 2.12.0 is working fine, 2.12.1, 2.12.2 not...

**Comment by baptisteArno** [comment]
Wow, what a mystery then (changelog for 2.12.1: https://github.com/baptisteArno/typebot.io/releases/tag/v2.12.1).

I'm confused

**Comment by tboulogne** [comment]
ok got it :-).

I force a rebuild and it works.
