### ISSUE TITLE
BUG IMPORT URL WEBHOOK

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#472]
![image](https://user-images.githubusercontent.com/44640884/233740034-5e66d6b6-f411-4c2c-8838-3d538b236ddf.png)

I think I found another bug, when I import a workflow to another typebot, it doesn't go to the webhook url

**Comment by baptisteArno** [comment]
Ok, so that explains it. Webhooks for now can't be shared from 1 instance to another.

It will be fixed when #313 is closed!
