### ISSUE TITLE
Getting Open AI Block Error

### ISSUE THREAD

**Issue by realsubinbabu** [baptisteArno/typebot.io#474]
I have identified the reason for the issue, and it is not related to Typebot. Thank you.

**Comment by realsubinbabu** [comment]
Log:
--------
"{\n  \"message\": \"Request failed with status code 429\",\n  \"name\": \"Error\",\n  \"stack\": \"Error: Request failed with status code 429\\n    at createError (/app/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/core/createError.js:16:15)\\n    at settle (/app/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/core/settle.js:17:12)\\n    at IncomingMessage.handleStreamEnd (/app/node_modules/.pnpm/axios@0.26.1/node_modules/axios/lib/adapters/http.js:322:11)\\n    at IncomingMessage.emit (node:events:525:35)\\n    at IncomingMessage.emit (node:domain:489:12)\\n    at endReadableNT (node:internal/streams/readable:1359:12)\\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\",\n  \"config\": {\n    \"transitional\": {\n      \"silentJSONParsing\": true,\n      \"forcedJSONParsing\": true,\n      \"clarifyTimeoutError\": false\n    },\n    \"transformRequest\": [\n      null\n    ],\n    \"transformResponse\": [\n      null\n    ],\n 
-------

**Comment by baptisteArno** [comment]
Status code 429. It means "Too Many Requests".

There is a good chance your account is now limited by OpenAI. You need to add a credit card on your OpenAI account.

**Comment by baptisteArno** [comment]
Ok, let us know. Closing this for now!
