### ISSUE TITLE
Upload Files

### ISSUE THREAD

**Issue by ruiandersonsantos** [baptisteArno/typebot.io#477]
When I upload a file, the system uploads the file but then it is interrupted and displays the following message:

Something went wrong HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
    ... 5 lines matching cause stack trace ...
    at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: HTTPError: Response code 403 (Forbidden)
      at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
      at Object.onceWrapper (node:events:628:26)
      at Request.emit (node:events:525:35)
      at Request.emit (node:domain:489:12)
      at Request._onResponseBase (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:726:22)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
    input: undefined,
    code: 'ERR_NON_2XX_3XX_RESPONSE',

In the image below we can see that the upload request is successfully processed.
![image](https://user-images.githubusercontent.com/10409838/235239484-f40269cf-cc90-4ff7-b54a-4bb244675304.png)

The following request the error occurs
![image](https://user-images.githubusercontent.com/10409838/235239878-2aa22fcf-8aba-44b1-963d-0c819d9da8df.png)

![image](https://user-images.githubusercontent.com/10409838/235240054-52483608-7a31-45b0-b8ca-6980ef541888.png)

**Comment by itzomen** [comment]
I think this is similar to #462 
What storage are you using??

**Comment by ruiandersonsantos** [comment]
> I think this is similar to #462 What storage are you using??

I tried it with S3 AWS and also Minio with self-hosted S3.

**Comment by ruiandersonsantos** [comment]
follow the file with the entire error stack in the docker log

      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: true
    }
  }
}
Something went wrong HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
    ... 5 lines matching cause stack trace ...
    at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: HTTPError: Response code 403 (Forbidden)
      at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
      at Object.onceWrapper (node:events:628:26)
      at Request.emit (node:events:525:35)
      at Request.emit (node:domain:489:12)
      at Request._onResponseBase (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:726:22)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
    input: undefined,
    code: 'ERR_NON_2XX_3XX_RESPONSE',
    timings: {
      start: 1682647242904,
      socket: 1682647242904,
      lookup: 1682647242904,
      connect: 1682647242905,
      secureConnect: 1682647242906,
      upload: 1682647242906,
      response: 1682647242909,
      end: 1682647242910,
      error: undefined,
      abort: undefined,
      phases: [Object]
    },
    options: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: undefined,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: undefined,
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'GET',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: URL {
        href: 'https://s3.digitalmultas.com.br/testecoleta/public/results/clgzwoxd6000rlr6lf18gsob3/bz58kcktacpeefnwu1rrbo6o/salgados.jpg',
        origin: 'https://s3.digitalmultas.com.br',
        protocol: 'https:',
        username: '',
        password: '',
        host: 's3.digitalmultas.com.br',
        hostname: 's3.digitalmultas.com.br',
        port: '',
        pathname: '/testecoleta/public/results/clgzwoxd6000rlr6lf18gsob3/bz58kcktacpeefnwu1rrbo6o/salgados.jpg',
        search: '',
        searchParams: URLSearchParams {},
        hash: ''
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: true
    }
  }
}
Something went wrong HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
    ... 5 lines matching cause stack trace ...
    at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: HTTPError: Response code 403 (Forbidden)
      at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
      at Object.onceWrapper (node:events:628:26)
      at Request.emit (node:events:525:35)
      at Request.emit (node:domain:489:12)
      at Request._onResponseBase (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:726:22)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
    input: undefined,
    code: 'ERR_NON_2XX_3XX_RESPONSE',
    timings: {
      start: 1682647381658,
      socket: 1682647381658,
      lookup: 1682647381659,
      connect: 1682647381659,
      secureConnect: 1682647381661,
      upload: 1682647381661,
      response: 1682647381664,
      end: 1682647381664,
      error: undefined,
      abort: undefined,
      phases: [Object]
    },
    options: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: undefined,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: undefined,
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'GET',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: URL {
        href: 'https://s3.digitalmultas.com.br/testecoleta/public/results/clgzwrhq9000vlr6lpao4ttsx/bz58kcktacpeefnwu1rrbo6o/salgados.jpg',
        origin: 'https://s3.digitalmultas.com.br',
        protocol: 'https:',
        username: '',
        password: '',
        host: 's3.digitalmultas.com.br',
        hostname: 's3.digitalmultas.com.br',
        port: '',
        pathname: '/testecoleta/public/results/clgzwrhq9000vlr6lpao4ttsx/bz58kcktacpeefnwu1rrbo6o/salgados.jpg',
        search: '',
        searchParams: URLSearchParams {},
        hash: ''
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: true
    }
  }
}
Something went wrong HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
    ... 5 lines matching cause stack trace ...
    at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: HTTPError: Response code 403 (Forbidden)
      at Request.<anonymous> (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/as-promise/index.js:86:42)
      at Object.onceWrapper (node:events:628:26)
      at Request.emit (node:events:525:35)
      at Request.emit (node:domain:489:12)
      at Request._onResponseBase (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:726:22)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Request._onResponse (file:///app/node_modules/.pnpm/got@12.6.0/node_modules/got/dist/source/core/index.js:765:13) {
    input: undefined,
    code: 'ERR_NON_2XX_3XX_RESPONSE',
    timings: {
      start: 1682647654111,
      socket: 1682647654111,
      lookup: 1682647654112,
      connect: 1682647654112,
      secureConnect: 1682647654113,
      upload: 1682647654114,
      response: 1682647654116,
      end: 1682647654117,
      error: undefined,
      abort: undefined,
      phases: [Object]
    },
    options: {
      request: undefined,
      agent: { http: undefined, https: undefined, http2: undefined },
      h2session: undefined,
      decompress: true,
      timeout: {
        connect: undefined,
        lookup: undefined,
        read: undefined,
        request: undefined,
        response: undefined,
        secureConnect: undefined,
        send: undefined,
        socket: undefined
      },
      prefixUrl: '',
      body: undefined,
      form: undefined,
      json: undefined,
      cookieJar: undefined,
      ignoreInvalidCookies: false,
      searchParams: undefined,
      dnsLookup: undefined,
      dnsCache: undefined,
      context: {},
      hooks: {
        init: [],
        beforeRequest: [],
        beforeError: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: []
      },
      followRedirect: true,
      maxRedirects: 10,
      cache: undefined,
      throwHttpErrors: true,
      username: '',
      password: '',
      http2: false,
      allowGetBody: false,
      headers: {
        'user-agent': 'got (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate, br'
      },
      methodRewriting: false,
      dnsLookupIpVersion: undefined,
      parseJson: [Function: parse],
      stringifyJson: [Function: stringify],
      retry: {
        limit: 2,
        methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
        statusCodes: [
          408, 413, 429, 500,
          502, 503, 504, 521,
          522, 524
        ],
        errorCodes: [
          'ETIMEDOUT',
          'ECONNRESET',
          'EADDRINUSE',
          'ECONNREFUSED',
          'EPIPE',
          'ENOTFOUND',
          'ENETUNREACH',
          'EAI_AGAIN'
        ],
        maxRetryAfter: undefined,
        calculateDelay: [Function: calculateDelay],
        backoffLimit: Infinity,
        noise: 100
      },
      localAddress: undefined,
      method: 'GET',
      createConnection: undefined,
      cacheOptions: {
        shared: undefined,
        cacheHeuristic: undefined,
        immutableMinTimeToLive: undefined,
        ignoreCargoCult: undefined
      },
      https: {
        alpnProtocols: undefined,
        rejectUnauthorized: undefined,
        checkServerIdentity: undefined,
        certificateAuthority: undefined,
        key: undefined,
        certificate: undefined,
        passphrase: undefined,
        pfx: undefined,
        ciphers: undefined,
        honorCipherOrder: undefined,
        minVersion: undefined,
        maxVersion: undefined,
        signatureAlgorithms: undefined,
        tlsSessionLifetime: undefined,
        dhparam: undefined,
        ecdhCurve: undefined,
        certificateRevocationLists: undefined
      },
      encoding: undefined,
      resolveBodyOnly: false,
      isStream: false,
      responseType: 'text',
      url: URL {
        href: 'https://s3.digitalmultas.com.br/testecoleta/public/results/clgzwwebo000zlr6litks4fyc/bz58kcktacpeefnwu1rrbo6o/salgados.jpg',
        origin: 'https://s3.digitalmultas.com.br',
        protocol: 'https:',
        username: '',
        password: '',
        host: 's3.digitalmultas.com.br',
        hostname: 's3.digitalmultas.com.br',
        port: '',
        pathname: '/testecoleta/public/results/clgzwwebo000zlr6litks4fyc/bz58kcktacpeefnwu1rrbo6o/salgados.jpg',
        search: '',
        searchParams: URLSearchParams {},
        hash: ''
      },
      pagination: {
        transform: [Function: transform],
        paginate: [Function: paginate],
        filter: [Function: filter],
        shouldContinue: [Function: shouldContinue],
        countLimit: Infinity,
        backoff: 0,
        requestLimit: 10000,
        stackAllItems: false
      },
      setHost: true,
      maxHeaderSize: undefined,
      signal: undefined,
      enableUnixSockets: true
    }
  }
}

**Comment by baptisteArno** [comment]
I don't think it's related to the file upload. As you can see, with the first request you are showing, it successfully uploaded the file.

Only then you have a 403 error. Is it also happening in Preview mode?

**Comment by baptisteArno** [comment]
Any way we can easily reproduce the issue? Can you provide a minimal reproduction?

**Comment by ruiandersonsantos** [comment]
I was able to find the solution. I modified Bucket's permission rules and problem was solved. Honestly, I couldn't understand, because the upload was always completed, the problem was in the reading that Typebot requests in the callback.
Thank you very much for everyone's attention.

**Comment by ruiandersonsantos** [comment]
I was able to find the solution. I modified Bucket's permission rules and problem was solved. Honestly, I couldn't understand, because the upload was always completed, the problem was in the reading that Typebot requests in the callback.
Thank you very much for everyone's attention.

**Comment by itzomen** [comment]
@ruiandersonsantos can you provide the storage you are using and the steps taken?

**Comment by arladmin** [comment]
I'm facing exactly the same issue.
File's getting uploaded. `POST /sendMessage` is getting `500 Internal Server Error`.

Would be nice to know the solution for this.

**Comment by baptisteArno** [comment]
Your URL should be public so you don't need an AWS Signature of any sort!

Make sure you have the right public policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicRead",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::<BUCKET_NAME>/public/*"
    }
  ]
}
```

**Comment by arladmin** [comment]
@baptisteArno 

> Your URL should be public so you don't need an AWS Signature of any sort!
> 
> Make sure you have the right public policy:
> 
> ```
> {
>   "Version": "2012-10-17",
>   "Statement": [
>     {
>       "Sid": "PublicRead",
>       "Effect": "Allow",
>       "Principal": "*",
>       "Action": "s3:GetObject",
>       "Resource": "arn:aws:s3:::<BUCKET_NAME>/public/*"
>     }
>   ]
> }
> ```

That doesn't seem very security/privacy friendly.

Is this the only available option within Typebot?

**Comment by baptisteArno** [comment]
Yes for now that's the only way!

https://github.com/baptisteArno/typebot.io/issues/772

**Comment by arladmin** [comment]
> #772

Looking forward to this.

Because, until then, it's not at all feasible to request users to upload their documents/files.
