### ISSUE TITLE
New Docker Installation : "Unauthorized. Sign ups are disabled."

### ISSUE THREAD

**Issue by tuxpilot** [baptisteArno/typebot.io#479]
Greetings,

I was looking to make my first Docker installation of typebot, sadly i get stuck to the step where i want to sign in for the first time.

No matter what i do i still get the same error : "Unauthorized, Sign ups are disabled."

This is my environment: 
Virtual Machine:
- Debian11
- 2GB of RAM
- 2 vCPUs

The instance runs behind an Apache2 Reverse-Proxy, installed on another Front server, and the WAF is disabled.

This is my docker-compose.yml

version: '3.3'
services:
  mail:
    image: bytemark/smtp
    restart: always
  typebot-builder:
    environment:
      - SMTP_HOST=mail
      - NEXT_PUBLIC_SMTP_FROM=mymail.mydomain.com
  typebot-viewer:
    - SMTP_HOST=mail
    - NEXT_PUBLIC_SMTP_FROM=mymail.mydomain.com
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=https://mybot.mydomain.com
      - NEXT_PUBLIC_VIEWER_URL=https://mybot.mydomain.com
      - ENCRYPTION_SECRET=MYSECRETKEYOFENCRYPTION
      - ADMIN_EMAIL=mymail.mydomain.com
	  - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - SMTP_USERNAME=mymail.mydomain.com
      - SMTP_PASSWORD=mypassword
      - SMTP_HOST=mail.domain.com
      - SMTP_PORT=25
      - NEXT_PUBLIC_SMTP_FROM=mymail.mydomain.com
      - SMTP_SECURE=false
      - DISABLE_SIGNUP=false
      - SMTP_AUTH_DISABLED=false
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=https://bot.domain.com
      - ENCRYPTION_SECRET=MYSECRETKEYOFENCRYPTION
      - NEXTAUTH_URL=mybot.domain.com
      - ADMIN_EMAIL=mymail.mydomain.com
      - SMTP_USERNAME=mymail.mydomain.com
      - SMTP_PASSWORD=mymail.mydomain.com
      - SMTP_HOST=mail.domain.com
      - SMTP_PORT=25
      - SMTP_FROM=mymail.mydomain.com
      - SMTP_SECURE=false
      - DISABLE_SIGNUP=false
      - SMTP_AUTH_DISABLED=false
volumes:
  db_data:

This is the view of all  my dockers on this server, dedicated to Typebot:

425a408d976f   baptistearno/typebot-viewer:latest    "/bin/sh -c ./${SCOP…"   About a minute ago   Up About a minute   0.0.0.0:8081->3000/tcp   typebotio_typebot-viewer_1

a77ab37f116b   baptistearno/typebot-builder:latest   "/bin/sh -c ./${SCOP…"   10 minutes ago       Up 10 minutes       0.0.0.0:8080->3000/tcp   typebotio_typebot-builder_1

7d0f50f69803   bytemark/smtp                         "docker-entrypoint.s…"   41 minutes ago       Up 41 minutes       25/tcp                   typebotio_mail_1

93ceaddc69a1   postgres:13                           "docker-entrypoint.s…"   51 minutes ago       Up 51 minutes       5432/tcp                 typebotio_typebot-db_1

I don't have more clues about where to look at, the documentation is pretty clear though, and i still struggle to see where i messed up.

Thank you for your help.

Kind regards,

**Comment by baptisteArno** [comment]
Can you provide the error found in the server logs after trying to sign up? (`docker-compose logs`)

**Comment by tuxpilot** [comment]
Thank you for taking time to answer me.

I don't know which part could be interesting, so here is the whole thing:













Attaching to typebotio_typebot-builder_1, typebotio_typebot-viewer_1, typebotio_mail_1, typebotio_typebot-db_1
mail_1             |     1 LOG: MAIN
mail_1             |     1   exim 4.89 daemon started: pid=1, -q30m, listening for SMTP on port 25 (IPv6 and IPv4)
typebot-builder_1  | env.sh loaded
typebot-builder_1  | Matched inline env:
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM=myemail@mydomain.com
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=https://bot.mydomain.com
typebot-builder_1  | Reading ./apps/builder/.env.production...
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM=
typebot-builder_1  | NEXT_PUBLIC_GOOGLE_API_KEY=
typebot-builder_1  | NEXT_PUBLIC_GIPHY_API_KEY=
typebot-builder_1  | NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
typebot-builder_1  | NEXT_PUBLIC_SENTRY_DSN=
typebot-builder_1  | NEXT_PUBLIC_VIEWER_INTERNAL_URL=
typebot-builder_1  | NEXT_PUBLIC_E2E_TEST=
typebot-builder_1  | NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
typebot-builder_1  | NEXT_PUBLIC_UNSPLASH_APP_NAME=
typebot-builder_1  | NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM=myemail@mydomain.com
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=https://bot.mydomain.com
typebot-builder_1  | Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
typebot-builder_1  | Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
typebot-builder_1  | env.sh done
typebot-builder_1  | 
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | 
typebot-builder_1  | ✔ Generated Prisma Client (4.12.0 | library) to ./node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 1.37s
typebot-builder_1  | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-builder_1  | ```
typebot-builder_1  | import { PrismaClient } from '@prisma/client'
typebot-builder_1  | const prisma = new PrismaClient()
typebot-builder_1  | ```
typebot-builder_1  | Waiting 5s for db to be ready...
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"
typebot-builder_1  | 
typebot-builder_1  | 51 migrations found in prisma/migrations
typebot-builder_1  | 
typebot-builder_1  | 
typebot-builder_1  | No pending migrations to apply.
typebot-builder_1  | ┌─────────────────────────────────────────────────────────┐
typebot-builder_1  | │  Update available 4.12.0 -> 4.13.0                      │
typebot-builder_1  | │  Run the following to update                            │
typebot-builder_1  | │    npm i --save-dev prisma@latest                       │
typebot-builder_1  | │    npm i @prisma/client@latest                          │
typebot-builder_1  | └─────────────────────────────────────────────────────────┘
typebot-builder_1  | info  - Loaded env from /app/apps/builder/.env.production
typebot-builder_1  | Listening on port 3000 url: http://baa42e2f8e6f:3000
typebot-builder_1  | (node:364) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
typebot-builder_1  | 
typebot-builder_1  | Please migrate your code to use AWS SDK for JavaScript (v3).
typebot-builder_1  | For more information, check the migration guide at https://a.co/7PzMCcy
typebot-builder_1  | (Use `node --trace-warnings ...` to show where the warning was created)
typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Email(s) could not be sent',
typebot-builder_1  |     stack: 'Error: Email(s) could not be sent\n' +
typebot-builder_1  |       '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/3699.js:330:15)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async Promise.all (index 0)\n' +
typebot-builder_1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder_1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder_1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)\n' +
typebot-builder_1  |       '    at async handler (/app/apps/builder/.next/server/chunks/3699.js:527:12)\n' +
typebot-builder_1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
typebot-builder_1  |       '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:514:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Email(s) could not be sent'
typebot-builder_1  | }
typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Email(s) could not be sent',
typebot-builder_1  |     stack: 'Error: Email(s) could not be sent\n' +
typebot-builder_1  |       '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/3699.js:330:15)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async Promise.all (index 0)\n' +
typebot-builder_1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder_1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder_1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)\n' +
typebot-builder_1  |       '    at async handler (/app/apps/builder/.next/server/chunks/3699.js:527:12)\n' +
typebot-builder_1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
typebot-builder_1  |       '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:514:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Email(s) could not be sent'
typebot-builder_1  | }
typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Email(s) could not be sent',
typebot-builder_1  |     stack: 'Error: Email(s) could not be sent\n' +
typebot-builder_1  |       '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/3699.js:330:15)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async Promise.all (index 0)\n' +
typebot-builder_1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder_1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder_1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)\n' +
typebot-builder_1  |       '    at async handler (/app/apps/builder/.next/server/chunks/3699.js:527:12)\n' +
typebot-builder_1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
typebot-builder_1  |       '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:514:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Email(s) could not be sent'
typebot-builder_1  | }
typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Email(s) could not be sent',
typebot-builder_1  |     stack: 'Error: Email(s) could not be sent\n' +
typebot-builder_1  |       '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/3699.js:330:15)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async Promise.all (index 0)\n' +
typebot-builder_1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder_1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder_1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)\n' +
typebot-builder_1  |       '    at async handler (/app/apps/builder/.next/server/chunks/3699.js:527:12)\n' +
typebot-builder_1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
typebot-builder_1  |       '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:514:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Email(s) could not be sent'
typebot-builder_1  | }
typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Email(s) could not be sent',
typebot-builder_1  |     stack: 'Error: Email(s) could not be sent\n' +
typebot-builder_1  |       '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/3699.js:330:15)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async Promise.all (index 0)\n' +
typebot-builder_1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder_1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder_1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)\n' +
typebot-builder_1  |       '    at async handler (/app/apps/builder/.next/server/chunks/3699.js:527:12)\n' +
typebot-builder_1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
typebot-builder_1  |       '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:514:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Email(s) could not be sent'
typebot-builder_1  | }
typebot-builder_1  | [next-auth][error][SIGNIN_EMAIL_ERROR] 
typebot-builder_1  | https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
typebot-builder_1  |   error: {
typebot-builder_1  |     message: 'Email(s) could not be sent',
typebot-builder_1  |     stack: 'Error: Email(s) could not be sent\n' +
typebot-builder_1  |       '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/3699.js:330:15)\n' +
typebot-builder_1  |       '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
typebot-builder_1  |       '    at async Promise.all (index 0)\n' +
typebot-builder_1  |       '    at async email (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
typebot-builder_1  |       '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
typebot-builder_1  |       '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:253:26)\n' +
typebot-builder_1  |       '    at async NextAuthHandler (/app/node_modules/.pnpm/next-auth@4.21.0_next@13.2.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:24:19)\n' +
typebot-builder_1  |       '    at async handler (/app/apps/builder/.next/server/chunks/3699.js:527:12)\n' +
typebot-builder_1  |       '    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)\n' +
typebot-builder_1  |       '    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.2.4_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:514:9)',
typebot-builder_1  |     name: 'Error'
typebot-builder_1  |   },
typebot-builder_1  |   providerId: 'email',
typebot-builder_1  |   message: 'Email(s) could not be sent'
typebot-builder_1  | }
typebot-db_1       | 
typebot-db_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
typebot-db_1       | 
typebot-db_1       | 2023-05-02 15:23:14.565 UTC [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
typebot-db_1       | 2023-05-02 15:23:14.565 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
typebot-db_1       | 2023-05-02 15:23:14.565 UTC [1] LOG:  listening on IPv6 address "::", port 5432
typebot-db_1       | 2023-05-02 15:23:14.660 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
typebot-db_1       | 2023-05-02 15:23:14.723 UTC [27] LOG:  database system was interrupted; last known up at 2023-05-02 14:33:13 UTC
typebot-db_1       | 2023-05-02 15:23:15.381 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
typebot-db_1       | 2023-05-02 15:23:15.429 UTC [27] LOG:  redo starts at 0/1747C18
typebot-db_1       | 2023-05-02 15:23:15.429 UTC [27] LOG:  invalid record length at 0/1747D00: wanted 24, got 0
typebot-db_1       | 2023-05-02 15:23:15.429 UTC [27] LOG:  redo done at 0/1747CC8
typebot-db_1       | 2023-05-02 15:23:15.850 UTC [1] LOG:  database system is ready to accept connections
typebot-db_1       | 2023-05-02 15:23:25.423 UTC [35] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:27:34.135 UTC [40] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:27:34.177 UTC [41] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:30:14.658 UTC [45] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:46:54.999 UTC [66] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:46:55.047 UTC [67] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:49:10.955 UTC [72] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 16:05:01.195 UTC [98] LOG:  could not receive data from client: Connection reset by peer
typebot-viewer_1   | env.sh loaded
typebot-viewer_1   | Matched inline env:
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=https://bot.mydomain.com
typebot-viewer_1   | Reading ./apps/viewer/.env.production...
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=
typebot-viewer_1   | NEXT_PUBLIC_E2E_TEST=
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=https://bot.mydomain.com
typebot-viewer_1   | Got index from inline env: 0, replacing NEXT_PUBLIC_VIEWER_URL
typebot-viewer_1   | env.sh done
typebot-viewer_1   | 
typebot-viewer_1   | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-viewer_1   | 
typebot-viewer_1   | ✔ Generated Prisma Client (4.12.0 | library) to ./node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 973ms
typebot-viewer_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-viewer_1   | ```
typebot-viewer_1   | import { PrismaClient } from '@prisma/client'
typebot-viewer_1   | const prisma = new PrismaClient()
typebot-viewer_1   | ```
typebot-viewer_1   | info  - Loaded env from /app/apps/viewer/.env.production
typebot-viewer_1   | Listening on port 3000 url: http://32a092b14a9b:3000







Again, sorry if i messed up something.

Kind regards,

**Comment by baptisteArno** [comment]
This is due to invalid SMTP configuration. Can you double-check your email SMTP settings?

**Comment by tuxpilot** [comment]
Bloody stupid me!!!
Thank you!

I was configuring another server on the side and this one had the SMTP on port 25, which was why i did not had the idea of questioning this part of the conf for Typebot, which is supposed to use the 465.
I was only looking at what the error message was saying and looked in the doc for the sign up disable function.


So sorry for the mistake.

I had the opportunity to test it a bit,   wonderful job you did there!
Many thanks and all the best!

Best regards,
