### ISSUE TITLE
The bot you're looking for doesn't exist

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#48]
Hi

I have the same problem ...

And I cannot upload images to a flow or as Avatar.

I can choose a local image but nothing happen when I click on upload.

Docker (Ubuntu) same config as mihha

_Originally posted by @Famku in https://github.com/baptisteArno/typebot.io/issues/44#issuecomment-1132238143_

**Comment by Famku** [comment]
I renamed apps/viewer/.env.local.example to apps/viewer/.env.local and add my domain https://typebotview.****.net:8443 as NEXT_PUBLIC_VIEWER_URL 
The container has been rebuild but still the same error

**Comment by baptisteArno** [comment]
Then that must be a bug. I just [pushed a commit that logs useful information when it can't find the typebot](https://github.com/baptisteArno/typebot.io/commit/0f06aae80cd12ad350c80d959992ba010fadd958). It will help us debug your situation. Can you pull the new changes, navigate to the same URL and print the logs here?

**Comment by Famku** [comment]
ok, I pulled and build it again.

Where can I find the logs?

**Comment by baptisteArno** [comment]
You could run `docker-compose logs` after loading the page

**Comment by Famku** [comment]
here we are:

looks like the port number of my domain is missing

[](url)Attaching to typebotio_builder_1, typebotio_viewer_1, typebotio_db_1
db_1       |
db_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1       |
db_1       | 2022-05-20 21:51:56.755 UTC [1] LOG:  starting PostgreSQL 13.7 (Debian 13.7-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by g     cc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1       | 2022-05-20 21:51:56.764 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1       | 2022-05-20 21:51:56.764 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1       | 2022-05-20 21:51:56.766 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1       | 2022-05-20 21:51:56.770 UTC [26] LOG:  database system was shut down at 2022-05-20 21:38:42 UTC
db_1       | 2022-05-20 21:51:56.906 UTC [1] LOG:  database system is ready to accept connections
builder_1  | Prisma schema loaded from prisma/schema.prisma
builder_1  |
builder_1  | ✔ Generated Prisma Client (3.14.0 | library) to ./node_modules/@prisma/client in 760ms
builder_1  | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
builder_1  | ```
builder_1  | import { PrismaClient } from '@prisma/client'
builder_1  | const prisma = new PrismaClient()
builder_1  | ```
builder_1  | Waiting 5s for db to be ready...
builder_1  | Prisma schema loaded from prisma/schema.prisma
builder_1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "db:5432"
builder_1  |
builder_1  | 17 migrations found in prisma/migrations
builder_1  |
builder_1  |
builder_1  | No pending migrations to apply.
builder_1  | info  - Loaded env from /app/.env.production
builder_1  | Listening on port 3000
viewer_1   | Prisma schema loaded from prisma/schema.prisma
viewer_1   |
viewer_1   | ✔ Generated Prisma Client (3.14.0 | library) to ./node_modules/@prisma/client in 898ms
viewer_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
viewer_1   | ```
viewer_1   | import { PrismaClient } from '@prisma/client'
viewer_1   | const prisma = new PrismaClient()
viewer_1   | ```
viewer_1   | info  - Loaded env from /app/.env.production
viewer_1   | Listening on port 3000
viewer_1   | Couldn't customDomain: typebotview.0000.net/my-typebot-0lt4lif
viewer_1   | Couldn't customDomain: typebotview.0000.net/favicon.ico

**Comment by Famku** [comment]
now i received this error after I pulled it again:

```
Step 12/32 : RUN yarn install --frozen-lockfile
 ---> Running in 4c10e8ae401b
yarn install v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@chakra-ui/focus-lock/-/focus-lock-2.0.0.tgz: Request failed \"502 Bad Gateway\"".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install --frozen-lockfile' returned a non-zero code: 1
ERROR: Service 'builder' failed to build : Build failed
```

**Comment by baptisteArno** [comment]
Does it happen consistently? Do you have access to internet?

**Comment by Famku** [comment]
I tried it again and now it works.

I can also now see my bots!

Thank you very much for your help.
