### ISSUE TITLE
Self-Hosted Installation on Docker is failing to send emails

### ISSUE THREAD

**Issue by IzMichael** [baptisteArno/typebot.io#481]
Hiya, I'm self-hosting using the docker-compose script, and I can't sign in or sign up using the magic link email auth provider. I've checked the docker logs, and it's saying that NextAuth is failing to send the email.
```
[next-auth][error][SIGNIN_EMAIL_ERROR]
https://next-auth.js.org/errors#signin_email_error Email(s) could not be sent {
  error: {
    message: 'Email(s) could not be sent',
    stack: 'Error: Email(s) could not be sent\n' +
      '    at Object.sendVerificationRequest (/app/apps/builder/.next/server/chunks/1518.js:330:15)\n' +
      '    at async Promise.all (index 0)\n' +
      '    at async email (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.3.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/lib/email/signin.js:31:3)\n' +
      '    at async Object.signin (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.3.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/routes/signin.js:115:24)\n' +
      '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.3.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/core/index.js:260:26)\n' +
      '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.22.1_next@13.3.4_nodemailer@6.9.1_react-dom@18.2.0_react@18.2.0/node_modules/next-auth/next/index.js:22:19)\n' +
      '    at async handler (/app/apps/builder/.next/server/chunks/1518.js:527:12)',
    name: 'Error'
  },
  providerId: 'email',
  message: 'Email(s) could not be sent'
}
```

My env variables are like this. I've replaced the values for privacy, but they're identically formatted.
```yml
- SMTP_USERNAME="email@example.com"
- SMTP_PASSWORD="somerandompassword"
- SMTP_HOST="smtp.fastmail.com"
- SMTP_PORT=465
- NEXT_PUBLIC_SMTP_FROM="forms@example.com"
- SMTP_SECURE=true
```

I've only just installed and setup all of this today. Any help is appreciated :)

**Comment by baptisteArno** [comment]
Can you try removing the quotes `"`? I'm not sure if that could be causing an issue.

Are you sure your SMTP credentials are valid?

**Comment by IzMichael** [comment]
Nope, removing the quotes didn't fix the issue. My SMTP credentials are valid, I've tested them on another platform

**Comment by IzMichael** [comment]
For now, I've had to setup GitHub signin so that I can actually use the app

**Comment by baptisteArno** [comment]
It is using Nodemailer under the hood. Having this error means your SMTP creds are invalid.

Can you maybe try port 587 and remove SMTP_SECURE env?

**Comment by baptisteArno** [comment]
I'm considering this issue fixed! Feel free to re-open 👌

**Comment by IzMichael** [comment]
Hi! Sorry, it's been a busy week. I've tried 587 without secure, and it appears to be working now, thanks!
