### ISSUE TITLE
Cannot upload any media, in bubble or profile.

### ISSUE THREAD

**Issue by tuxpilot** [baptisteArno/typebot.io#482]
Greetings,

No matter what kind of bubble i do, and no matter if it's a template or a new typebot, it seems i can't upload any media.
No matter if it's a video, a sound or an image, nothing happens, no error message.

This is the docker-compose logs i got after a tried to upload:

typebot-builder_1  | env.sh done
typebot-builder_1  | 
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | 
typebot-builder_1  | ✔ Generated Prisma Client (4.12.0 | library) to ./node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 1.27s
typebot-builder_1  | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-builder_1  | ```
typebot-builder_1  | import { PrismaClient } from '@prisma/client'
typebot-builder_1  | const prisma = new PrismaClient()
typebot-builder_1  | ```
typebot-builder_1  | Waiting 5s for db to be ready...
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"
typebot-builder_1  | 
typebot-builder_1  | 51 migrations found in prisma/migrations
typebot-builder_1  | 
typebot-builder_1  | 
typebot-builder_1  | No pending migrations to apply.
typebot-builder_1  | ┌─────────────────────────────────────────────────────────┐
typebot-builder_1  | │  Update available 4.12.0 -> 4.13.0                      │
typebot-builder_1  | │  Run the following to update                            │
typebot-builder_1  | │    npm i --save-dev prisma@latest                       │
typebot-builder_1  | │    npm i @prisma/client@latest                          │
typebot-builder_1  | └─────────────────────────────────────────────────────────┘
typebot-builder_1  | info  - Loaded env from /app/apps/builder/.env.production
typebot-builder_1  | Listening on port 3000 url: http://d508dbf730c3:3000
typebot-builder_1  | (node:363) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
typebot-builder_1  | 
typebot-builder_1  | Please migrate your code to use AWS SDK for JavaScript (v3).
typebot-builder_1  | For more information, check the migration guide at https://a.co/7PzMCcy
typebot-builder_1  | (Use `node --trace-warnings ...` to show where the warning was created)
typebot-builder_1  | Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
typebot-builder_1  | Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
typebot-builder_1  | Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
typebot-builder_1  | prisma:error 
typebot-builder_1  | Invalid `prisma.verificationToken.delete()` invocation:
typebot-builder_1  | 
typebot-builder_1  | 
typebot-builder_1  | An operation failed because it depends on one or more records that were required but not found. Record to delete does not exist.
typebot-db_1       | 
typebot-db_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
typebot-db_1       | 
typebot-db_1       | 2023-05-02 15:23:14.565 UTC [1] LOG:  starting PostgreSQL 13.10 (Debian 13.10-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
typebot-db_1       | 2023-05-02 15:23:14.565 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
typebot-db_1       | 2023-05-02 15:23:14.565 UTC [1] LOG:  listening on IPv6 address "::", port 5432
typebot-db_1       | 2023-05-02 15:23:14.660 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
typebot-db_1       | 2023-05-02 15:23:14.723 UTC [27] LOG:  database system was interrupted; last known up at 2023-05-02 14:33:13 UTC
typebot-db_1       | 2023-05-02 15:23:15.381 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
typebot-db_1       | 2023-05-02 15:23:15.429 UTC [27] LOG:  redo starts at 0/1747C18
typebot-db_1       | 2023-05-02 15:23:15.429 UTC [27] LOG:  invalid record length at 0/1747D00: wanted 24, got 0
typebot-db_1       | 2023-05-02 15:23:15.429 UTC [27] LOG:  redo done at 0/1747CC8
typebot-db_1       | 2023-05-02 15:23:15.850 UTC [1] LOG:  database system is ready to accept connections
typebot-db_1       | 2023-05-02 15:23:25.423 UTC [35] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:27:34.135 UTC [40] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:27:34.177 UTC [41] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:30:14.658 UTC [45] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:46:54.999 UTC [66] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:46:55.047 UTC [67] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 15:49:10.955 UTC [72] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 16:05:01.195 UTC [98] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 18:42:02.667 UTC [263] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 18:44:26.705 UTC [268] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 18:44:26.757 UTC [269] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 18:45:37.376 UTC [273] LOG:  could not receive data from client: Connection reset by peer
typebot-db_1       | 2023-05-02 22:00:43.214 UTC [31] LOG:  using stale statistics instead of current ones because stats collector is not responding
typebot-db_1       | 2023-05-02 22:00:53.382 UTC [493] LOG:  using stale statistics instead of current ones because stats collector is not responding
typebot-viewer_1   | env.sh loaded
typebot-viewer_1   | Matched inline env:
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=https://bot.domain.com
typebot-viewer_1   | Reading ./apps/viewer/.env.production...
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=
typebot-viewer_1   | NEXT_PUBLIC_E2E_TEST=
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=https://bot.domain.com
typebot-viewer_1   | Got index from inline env: 0, replacing NEXT_PUBLIC_VIEWER_URL
typebot-viewer_1   | env.sh done
typebot-viewer_1   | 
typebot-viewer_1   | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-viewer_1   | 
typebot-viewer_1   | ✔ Generated Prisma Client (4.12.0 | library) to ./node_modules/.pnpm/@prisma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 1.16s
typebot-viewer_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-viewer_1   | ```
typebot-viewer_1   | import { PrismaClient } from '@prisma/client'
typebot-viewer_1   | const prisma = new PrismaClient()
typebot-viewer_1   | ```
typebot-viewer_1   | info  - Loaded env from /app/apps/viewer/.env.production
typebot-viewer_1   | Listening on port 3000 url: http://45821df0ae27:3000
typebot-viewer_1   | (node:231) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
typebot-viewer_1   | 
typebot-viewer_1   | Please migrate your code to use AWS SDK for JavaScript (v3).
typebot-viewer_1   | For more information, check the migration guide at https://a.co/7PzMCcy
typebot-viewer_1   | (Use `node --trace-warnings ...` to show where the warning was created)

Even if i try to upload an image for my avatar, the same thing happens: no error message, but nothing gets uploaded.

This is my environment:
Virtual Machine:

    Debian11
    2GB of RAM
    2 vCPUs

The instance runs behind an Apache2 Reverse-Proxy, installed on another Front server, and the WAF is disabled.

Sorry if i did something wrong, i just don't know where to look.

Best regards,

**Comment by baptisteArno** [comment]
Have you correctly configured an S3 storage? https://docs.typebot.io/self-hosting/configuration/builder#s3-storage-media-uploads

**Comment by tuxpilot** [comment]
Hi,

Sorry but no.
I thought it was optional and because it was self-hosted, i could host my uploaded medias on the server directly.
Is there any way i can host it on my server directly and not on a S3?
Or at least have a way to encrypt my datas before they are sent on the S3?

Many thanks.

**Comment by baptisteArno** [comment]
You can easily add an S3 storage to your docker-compose stack: https://docs.typebot.io/self-hosting/docker#s3-storage

Would that work for you?
