### ISSUE TITLE
Upload file to S3 doesn't work

### ISSUE THREAD

**Issue by makemouse** [baptisteArno/typebot.io#491]
When I try to upload file through viewer, it gives me an error message: An error occured while uploading the file (See attached screenshot and logs from vercel) 

![Capture1](https://user-images.githubusercontent.com/132714533/236715008-b4f63db5-b84e-44b5-83e0-84cae97d1062.PNG)
![capture2](https://user-images.githubusercontent.com/132714533/236715234-7d188aee-59bc-48e1-9fa0-3ec2e0382746.jpg)

**Comment by SamSCx** [comment]
I had the same problem with no error message etc. 
After I specified the following parameters it worked (for Amazon S3):

S3_SSL=true
S3_REGION=xx
