### ISSUE TITLE
Potentially Suspicious Content Detected!

### ISSUE THREAD

**Issue by luizeof** [baptisteArno/typebot.io#492]
Hello @baptisteArno 

Thank you very much for your time providing Typebot, a fantastic tool.

I'm the manager of a community of people who use opensource systems and today I received the first suspicious code alert in typebot.

We have the same report with N8N, another open source system made in nodejs. https://community.n8n.io/t/potentially-suspicious-code-google-marked-site-as-phishing/23630/22

Could you check please? 

Just pass the url with the latest version of a **typebot viewer** installation in this url: https://quttera.com/website-malware-scanner

![Quttera-Detailed-Malware-Scan-Report Overview](https://user-images.githubusercontent.com/257004/236907780-26a2b8bb-39f4-4ad8-839a-4592d59e0442.png)

![Quttera-Detailed-Malware-Scan-Report](https://user-images.githubusercontent.com/257004/236907798-c09629a3-4f4a-4088-b811-c2d7ddbdb65f.png)

**Comment by baptisteArno** [comment]
I'd say that it's a false alarm!

Is this an issue for you currently?

**Comment by luizeof** [comment]
@baptisteArno the domain as a whole is banned giving a message that my website is phishing.

**Comment by cbalbinos** [comment]
Hello @baptisteArno 

I scanned the url of my Typebot and it also detected the problem... I had this problem with the n8n that is in another domain, and the inconvenience caused was great because Google marks the whole domain as fraudulent

**Comment by FlavioGuardia** [comment]
@baptisteArno, even being a false positive this situation causes such a problem that in a few lines it would be difficult to express. As the colleague @cbalbinos e o @luizeof mentioned above, Google flags the root domain as fraudulent and flags the domain and all subdomains, showing a big red screen alerting the user. I've already had the root domain effectively blocked by the issuing authority because of this "false positive" because of a .json from n8n.

For these reasons, I request, as far as possible, adjustments by the Typebot team to correct this situation. Thank you, Flavio Guardia.

**Comment by baptisteArno** [comment]
What did you scan? The builder or the viewer?

**Comment by cbalbinos** [comment]
@baptisteArno viewer

**Comment by baptisteArno** [comment]
Ok, v2.13.1 might fix this issue. Can you let me know?

**Comment by willdotcom** [comment]
Hello @luizeof @baptisteArno has this been resolved?
I've been having this problem for weeks too.

The scann log said this:
![image](https://github.com/baptisteArno/typebot.io/assets/9564011/dff3e3af-7d84-40bc-a763-ba6353e74fa4)

![image](https://github.com/baptisteArno/typebot.io/assets/9564011/7f494b31-bc52-4826-93fb-e3aff8ffec3c)

![image](https://github.com/baptisteArno/typebot.io/assets/9564011/ba1ac895-7d74-4072-b692-95ab2533185f)

Thanks!

**Comment by luizeof** [comment]
Hello @willdotcom  I don't know if @baptisteArno  made any changes about this, but the latest version of typebot viewer passed the tests I did today 2023-07-09.

![image](https://github.com/baptisteArno/typebot.io/assets/257004/27828d19-2d89-4541-ac44-b29184908b1e)

could you rerun your test with the latest version of typebot?

**Comment by baptisteArno** [comment]
Yes 🙌
