### ISSUE TITLE
Issue with Auto-Opening and Session Persistence on Page Redirection

### ISSUE THREAD

**Issue by lpadula** [baptisteArno/typebot.io#503]
Hi! 

I need to create a bot for an e-commerce platform that enhances the search functionality for specific products. However, I'm facing an issue where the chatbot fails to open automatically upon redirection to a new page. Additionally, even if I manually open the chatbot, it starts from scratch instead of retaining the previous session.

I have enabled the "Prefill input" and "Remember session" options, but they don't seem to be functioning as expected.

Please let me know if you need any further information.

**Comment by itzomen** [comment]
Do you have any errors in the console ?

- What exactly do you mean by fail to open?
- Are you passing the queries that will prefill the typebot?
- What are you using to add the typebot to your website?

**Comment by lpadula** [comment]
Hi @itzomen!

**- What exactly do you mean by fail to open?**
I was expecting the chat to open if Typebot finds some variables to fill in.

**- Are you passing the queries that will prefill the typebot?**
Yes, I inserted the bubble code on a WooCommerce site. When a user searches for a product, the chat will add WooCommerce parameters along with Chatbot parameters. For example: ?s=argolla&post_type=product&tk_options=Consultar%20por%20producto&tk_product=argolla

**- What are you using to add the typebot to your website?**
I am using the bubble code provided by Typebot.

**Comment by baptisteArno** [comment]
> What exactly do you mean by fail to open?

That's not how it works. You can automatically open it by using the `open` command (https://docs.typebot.io/embed/html-javascript#open-or-close-the-typebot)

---

It should retain the previous session if you did not close the browser or change tab. Do you confirm it's the case? If so it's most likely a bug

**Comment by baptisteArno** [comment]
Any chance I can access your site to try it out? If you'd like to share it privately: baptiste@typebot.io

**Comment by baptisteArno** [comment]
I can't reproduce the issue. I embedded a bot that has the Remember user session setting on. I answer the first question, then hit refresh, open the bot again and the first question is prefilled with my previous answer

**Comment by lpadula** [comment]
> Any chance I can access your site to try it out? If you'd like to share it privately: [baptiste@typebot.io](mailto:baptiste@typebot.io)

Yes, this is a test site: https://casanatalia.broobe.net/

> I can't reproduce the issue. I embedded a bot that has the Remember user session setting on. I answer the first question, then hit refresh, open the bot again and the first question is prefilled with my previous answer

If the first question is an input field, it's works, but is not working with buttons.

**Comment by baptisteArno** [comment]
Feel free to create another issue for this with greater detail. We need to see your condition block config etc 👍
