### ISSUE TITLE
Published bots give 404 error

### ISSUE THREAD

**Issue by wejamtech** [baptisteArno/typebot.io#510]
Hey guys,

Been trying for a few days to get up and running, but still have one issue I can't solve...

When I create a bot, I can preview it ok in the builder, however even when I publish it, I get a 404 error saying the bot "doesn't exist" when trying to connect to the public address.

I've attached a docker log in case anyone can see anything wrong here? I've removed the URLs.

Thanks,
David
[Docker log.txt](https://github.com/baptisteArno/typebot.io/files/11478928/Docker.log.txt)

**Comment by baptisteArno** [comment]
I can't see any obvious error in the logs.

Do you confirm the URL is valid, and the bot is published?

Any chance you can invite me in your workspace so that I can check what's wrong? baptiste@typebot.io

**Comment by baptisteArno** [comment]
After exchanging with @wejamtech by email. We figured it was because his reverse proxy was not passing the x-forwarded-host header properly.
