### ISSUE TITLE
local dev not able to show websites using Embed Bubbles

### ISSUE THREAD

**Issue by dkkim93** [baptisteArno/typebot.io#511]
Hello! First of all, thank you so much for developing this great software 👍 
I have been enjoying using this software for our application. 

Before deployment, I am developing locally by following the local setup [instruction](https://github.com/baptisteArno/typebot.io#local-setup). 
Unfortunately, when I use the `Embed` bubble to show a website (e.g., www.google.com) based on the localhost (http://localhost:3001/), it says: `www.google.com refused to connect.`
Would it be possible to help me fix this issue? Would this be expected behavior for localhost connections? 
Any help/guidance will be helpful! 
Thank you so much for your time! :-)

**Comment by baptisteArno** [comment]
That is expected. Google can't be embedded. This block is meant for websites that authorizes to be embedded!

**Comment by dkkim93** [comment]
Aha! I appreciate your clarification!
Again, thank you so much for this great software!
