### ISSUE TITLE
Getting error: User `postgres` was denied access on the database `typebot.public`

### ISSUE THREAD

**Issue by shreyassai123** [baptisteArno/typebot.io#521]
Upon configuring and running the repo, and visiting the builder (locahost:3000), once clicked on sign in, the logs show "User `postgres` was denied access on the database `typebot.public`". I'm unable to login using GitHub because of this.

**Comment by baptisteArno** [comment]
What's your configuration? What did you do exactly?

**Comment by AshishBhalsod** [comment]
hello i have same issue
i manually install in my server i create database server but i got same error 
DATABASE_URL=postgresql://postgres:typebot@127.0.0.1:5432/typebot
this is my db in.env
i need to crate database or its generate automatically
or something need to change in other file
