### ISSUE TITLE
[OpenAI] Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by satoshinotdead** [baptisteArno/typebot.io#523]
I see that 500 error when I try to use my API keys within Typebot. I have the API system working on Discourse and another apps but I can't use it on Typebot.

Could be related with my Nginx configuration? There are something to keep in mind to enable that integration that I'm probably missing out?

Thanks :)

**Comment by baptisteArno** [comment]
Maybe your encryption key is not valid for some reason? 🤔

Are you sure you correctly selected an OpenAI account in the OpenAI block config?

**Comment by satoshinotdead** [comment]
> Maybe your encryption key is not valid for some reason? thinking
> 
> Are you sure you correctly selected an OpenAI account in the OpenAI block config?

I'm using good APIs and I'm already using OpenAI APIs from another apps.

Please, can you tell me how can I check my encryption key within Typebot? :)

**Comment by baptisteArno** [comment]
What version of Typebot are you currently running? Can you send your encryption key after swapping multiple characters to baptiste@typebot.io?

**Comment by satoshinotdead** [comment]
> What version of Typebot are you currently running? Can you send your encryption key after swapping multiple characters to [baptiste@typebot.io](mailto:baptiste@typebot.io)?

I'm on the last release (updating for checking purposes)! How can I get that encryption key?

**Comment by baptisteArno** [comment]
In theory you set it up in your configuration: `ENCRYPTION_SECRET`
