### ISSUE TITLE
Error in OpenAi API Return

### ISSUE THREAD

**Issue by caoramos** [baptisteArno/typebot.io#529]
Sometimes, but unfortunately more frequent, OpenAi return with an error saying that the servers are busy, to try again latter.

There should be a great feature a way to handle that error, maybe as a fallback message, or a retry for X times.

**Comment by baptisteArno** [comment]
Indeed that'd be great 🙏

More info on error codes: https://platform.openai.com/docs/guides/error-codes/api-errors

**Comment by caoramos** [comment]
> Indeed that'd be great 🙏
> 
> More info on error codes: https://platform.openai.com/docs/guides/error-codes/api-errors

Unfortunally the ERRO 429 is being more and more frequent. The problem that depending the the bot is made it justs kills all the bot, because it keep waiting and need an output to the user to continue. I am experiecing this in all projects, there is one big with WhatsApp integration using OpenAI Chat API, Whisper and Google TTS, that I need to get all request in REDIS to because of OPENAI Chat API frequent 429 ERRO.

![Screenshot - 2023-05-28T123203 244](https://github.com/baptisteArno/typebot.io/assets/11988813/470063b7-ebcc-41ca-920e-4d327bbe1a4c)
![Screenshot - 2023-05-28T123410 769](https://github.com/baptisteArno/typebot.io/assets/11988813/62177cd2-8a37-47b9-a851-ab8c6b1c5cbc)

**Comment by baptisteArno** [comment]
In practice, how much time do you have to wait before it works again? Maybe a fallback message would be best then. Let me know

**Comment by caoramos** [comment]
In my other apps I am waiting 5 seconds and trying again. If it still fails
I return a fallback message.

It is working fine so far. I have an app that works in WhatsApp with lots
of requisitions, that was a work around before implementing a queue in
Redis.

But for you in Typebot I think one retry in 5s and then a fallback message
would be fine.

Em seg., 29 de mai. de 2023 às 03:01, Baptiste Arnaud <
***@***.***> escreveu:

**Comment by baptisteArno** [comment]
Ok thank you for the info. I'll try to implement it ASAP.
