### ISSUE TITLE
Clickable replies in text

### ISSUE THREAD

**Issue by anbraten** [baptisteArno/typebot.io#530]
It would be pretty cool, to have a text maybe by using the markdown component which has a text with some "links". By clicking on those links the link text would be used a next reply of the user.

I a  currently using OpenAI to generate a comma separated list of suggestions which are shown as clickable buttons. Using the new component / option I would be able to highlight suggestion in a text and the user would simply get more details about that suggestion.

**Comment by baptisteArno** [comment]
This is 100% what the Buttons input does, right? https://docs.typebot.io/editor/blocks/inputs/buttons

**Comment by anbraten** [comment]
Its more an advanced version of it.

Currently I use buttons, but instead I thought it would be cool to have a text with linked parts (which are behaving similar to buttons) which would look like:

![image](https://github.com/baptisteArno/typebot.io/assets/6918444/1710e7dd-d722-4c2c-8bad-cee9edf9a8c3)

and for example by clicking on `arc`, it would send `arc` as text message from the user. This way I could give my buttons some more context.

**Comment by baptisteArno** [comment]
I think this UX would be kind of misleading. If I see that type of underlined text, I'm expecting to be redirected to a new page. Changing this conceived experience is not a good idea IMO 🙏
