### ISSUE TITLE
Config for Azure Openai services

### ISSUE THREAD

**Issue by mm-edtake** [baptisteArno/typebot.io#532]
Would be great to be able to customize openai config if using azure open ai services.
Here is the documentation to use config for openai sdk : https://github.com/Azure/openai-samples/tree/main/Basic_Samples/Completions

Using Azure openai services, we are able to easily manage our own models and rate limits.

**Comment by baptisteArno** [comment]
Indeed it seems we would just need to call a different endpoint: `https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/chat/completions?api-version=2023-05-15`

With the same parameters

**Comment by mm-edtake** [comment]
Yes exactly.
Could be an option to override the openai endpoint

**Comment by baptisteArno** [comment]
It seems also that there are other services that have OpenAI-compatible endpoints. Things like: [FastChat](https://chat.lmsys.org/)

**Comment by g05357005** [comment]
I have updated my docker version to 2.17.0
but not see the baseurl settings in builder.

or should I set baseurl in .env?

**Comment by baptisteArno** [comment]
This is not included in 2.17.0. It will be there in the next release.

**Comment by mm-edtake** [comment]
Hi @baptisteArno 
I can't found out how to make it work, i have a 404 error during the setup of custom provider. Any idea how to resolve this ?
<img width="672" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/99755384/743577f4-1b0f-4906-842f-ce7d9bfdd25f">
<img width="477" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/99755384/3778b8ea-5844-4b4e-910a-679ed24de7ce">
