### ISSUE TITLE
Cross browser date issue

### ISSUE THREAD

**Issue by wejamtech** [baptisteArno/typebot.io#533]
Hey there,

Chrome and Safari both handle dates from the date input block differently and I can't find a method that will capture the intended selection correctly.

If you try and parse a date in Safari, for example using new Date(), it gets days and months mixed up.

The only solution I can think of at the moment is to detect which browser the user is using, and format the dates accordingly.

Is there a better solution?

Thanks,
David

**Comment by baptisteArno** [comment]
Can you be more precise with your reproduction example?

If you set a variable with the value `new Date()` by default it will be executed on the server, so that should not change from a browser to another.

**Comment by wejamtech** [comment]
I've attached a screenshot of the flow and also the results. As you can see, when trying to parse the date as output from the date block, it gets the day/month the wrong way round.

![Flow](https://github.com/baptisteArno/typebot.io/assets/129077825/4220096a-40f6-4fe1-a76f-13cc4ece6871)
![Result 2](https://github.com/baptisteArno/typebot.io/assets/129077825/cde60b37-2ead-4ce2-921d-409f0918625e)
![Result](https://github.com/baptisteArno/typebot.io/assets/129077825/fed90761-9f93-44f8-9df9-ec1609cd8de8)

**Comment by baptisteArno** [comment]
Thank you. The issue here is that `new Date('31/05/2023')` returns `Invalid date`.

I tried to solve your use case: "Detect if date is before another date". With this date format indeed, it is complicated.

I'll ship someting to make it possible ASAP.
