### ISSUE TITLE
Icon grid doesn't look good when searching

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#536]
<img width="530" alt="CleanShot 2023-05-31 at 14 13 32@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/26a65cab-1504-4b46-91b9-43f4e1a4b5ea">

**Comment by Lanhild** [comment]
Hey @baptisteArno 
Might want to make the grid larger in width, or allow it to be in fullscreen just like some blocks pop-over the window
