### ISSUE TITLE
Problems when using 2 chatbots on the same landing

### ISSUE THREAD

**Issue by willdotcom** [baptisteArno/typebot.io#538]
Hello everyone, we are currently having a rather annoying problem, which is that we use several typebots in the same landing to capture different customer information.

The problem is that only the first button manages to open the chatbot, the rest of the buttons never display anything, I have already carried out different tests of all kinds, modifying the code, assigning an identifier for each button and still the problem persists.

In slightly older versions it worked perfectly with this code:

```
<script src="https://unpkg.com/typebot-js@2.2"></script>
<div id="container-service1" style="width: 100%; height: 600px;"></div>
<script>
  Typebot.initContainer("container-service1", {
    url: "https://chatbot.domain.com/service?name=test&type=home&contact=test",
  });
</script>
```

In this code I always changed only the identifier: 'container-service1' for the other buttons and it worked perfectly.

In the new versions this code is totally different, even so I modified it as follows.

```
<script type="module">
  import Typebot from 'https://cdn.jsdelivr.net/npm/@typebot.io/js@0.0.51/dist/web.js';

  Typebot.initStandard({
    typebot: "type-bot-name00",
    apiHost: "https://chatbot.domain.com",
  });

// Select elements by ID and add the component
  const buttonById = document.getElementById('button_service1');
  if (buttonById) {
    const typebotStandardById = document.createElement('typebot-standard');
    typebotStandardById.setAttribute('style', 'width: 100%; height: 550px; text-align: left;');
    buttonById.appendChild(typebotStandardById);
  }

</script>
<typebot-standard id="button_service1" style="width: 100%; height: 550px; text-align: left;"></typebot-standard>
```

In this code above, elements are selected by their ID using getElementById and **<typebot-standard>** components are added to each element using **appendChild**. Then, the elements are selected by their ID using getElementById and the same process of adding the component to each of them is done.

The first button perfectly displays the chatbot, but when I start adding the others by changing the ID for the typebotStandard, the others are no longer displayed.

Has anyone ever tried to add 2 typebots in the same landing and manage to solve this problem in the new versions?
Thanks

**Comment by baptisteArno** [comment]
If you have different bots on the same page you will have to make them distinct with an additional `id` prop:

```html
<script type="module">
  import Typebot from 'https://cdn.jsdelivr.net/npm/@typebot.io/js@0.0/dist/web.js'

  Typebot.initStandard({
    id: 'bot1'
    typebot: 'my-typebot',
  })

  Typebot.initStandard({
    id: 'bot2'
    typebot: 'my-typebot-2',
  })
</script>

<typebot-standard
  id="bot1"
  style="width: 100%; height: 600px; "
></typebot-standard>
...
<typebot-standard
  id="bot2"
  style="width: 100%; height: 600px; "
></typebot-standard>
```

Does that help?

**Comment by willdotcom** [comment]
Thank you! work perfectly!
