### ISSUE TITLE
Implement a markdown parser

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#539]

**Comment by anbraten** [comment]
Sounds cool. Would you also add a component to show a markdown text?

**Comment by baptisteArno** [comment]
This parser would be for variables in a text bubble.

**Comment by liweifeng2022** [comment]
When will the markdown parser support?

**Comment by baptisteArno** [comment]
Soon! After the release of WhatsApp integration

**Comment by liweifeng2022** [comment]
Is it possible to support in early September? I am looking forward to this support item. It looks very good!!!

**Comment by baptisteArno** [comment]
I can't promise anything! I'm doing my best :)
