### ISSUE TITLE
How to disable new users registration?

### ISSUE THREAD

**Issue by kodxana** [baptisteArno/typebot.io#54]
Hi there I have decided to setup own typebot host for personal projects.
I decided to use GitHub auth method question is if there is any way to disable new users account from being created.
Thank you.

**Comment by teq-dev** [comment]
@baptisteArno I also needed this functionality for GitHub auth. I modified my local deployment as follows:

1- add new env variable called GITHUB_ALLOWED_EMAILS
2-modify `apps/builder/pages/api/auth/[...nextauth].ts` to check for GITHUB_ALLOWED_EMAILS and enforce on login (similar to what the Gitlab auth provider function is doing with groups)

Do you want me to send a PR for review?

**Comment by baptisteArno** [comment]
Thank you for the suggestion!

I'll create a PR for this shortly. It should more global and not just applied to Github :)
