### ISSUE TITLE
Api to generate bot

### ISSUE THREAD

**Issue by Jaikant** [baptisteArno/typebot.io#552]
I am building some services using generative AI, it would be awesome if there is an API which could generate a typebot. I could work on it on my spare time if there is some guidance.

**Comment by baptisteArno** [comment]
Yes we need `GET typebot` and `PUT typebot` endpoints here https://docs.typebot.io/api/get-linked-typebots.

I'll work on that fairly soon!

**Comment by Jaikant** [comment]
Thank you!
