### ISSUE TITLE
[Feature Request] Glide Data Grid

### ISSUE THREAD

**Issue by SamSCx** [baptisteArno/typebot.io#555]
Hey,

I've been using Glideapps for a while and saw that their editor is available on Github.
You could possibly add it to the TypeBot backend for the entries and then still execute the specific functions directly in TypeBot and pass them to e.g. webhooks / APIs.

https://github.com/glideapps/glide-data-grid

**Comment by baptisteArno** [comment]
Can you explain what is your exact use case? I'm not sure to understand

**Comment by SamSCx** [comment]
You could insert Glidetable in the backend, then you can execute various functions directly in TypeBot, for which you might need another tool like AirTable & Co.

**Comment by baptisteArno** [comment]
I'm sorry, I really don't see what you mean? Glide data grid is a front end component, it allows you to display a "powerful" table. Why are you talking about the backend of Typebot? 😅
