### ISSUE TITLE
Input select box

### ISSUE THREAD

**Issue by arthurbarret0** [baptisteArno/typebot.io#556]
Add a select box as one of the inputs. Buttons are useful, but when it comes to a large number of options, buttons become confusing. Imagine an input where the user needs to choose one option out of 15, using buttons would create a visual clutter.

**Comment by SamSCx** [comment]
Addition:
Select box with search field from x entries.
![image](https://github.com/baptisteArno/typebot.io/assets/38918229/5e3a5b20-b06a-44a3-8857-9077abbda776)

**Comment by baptisteArno** [comment]
#473
