### ISSUE TITLE
Onboarding message

### ISSUE THREAD

**Issue by realsubinbabu** [baptisteArno/typebot.io#557]
Hi bro, actually, it's not a big issue, but whenever I refresh the page, I keep getting this onboarding message. Even though I have already interacted with it, it still frequently appears. Is there any solution to this?

![qwqwqw](https://github.com/baptisteArno/typebot.io/assets/92963823/f74db767-6978-40a8-ad20-fb11911a0369)

**Comment by Lanhild** [comment]
Hey @realsubinbabu 
This message appears since you don't have any bots in your workspace, thus why the onboarding message is shown.

Upon creating your first bot in that workspace, you won't see this message anymore
