### ISSUE TITLE
Timeout error with OpenAI block

### ISSUE THREAD

**Issue by StariMarco** [baptisteArno/typebot.io#559]
Sometimes, when I use the OpenAI block and I ask questions that require longer answers (i.e. How do I fix a light bulb), I get back a status 504 response.

No log gets created and I only see an error popup warning me that the answer is empty.

<img width="426" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/49818192/9198c134-c2ec-4fdd-af57-22d6ec6f0f73">

And I get this error in Vercel:
<img width="1107" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/49818192/f2f79e81-7203-4c7d-9c3f-b9690ec1ecbb">

P.S. I've hosted Typebot in Vercel and I'm using Railway for the Postgres database.

**Comment by baptisteArno** [comment]
Hey, with the Vercel Hobby plan, you get a 10s execution limit. So if your OpenAI request goes beyond this timeout, it fails.

**Comment by StariMarco** [comment]
Gotcha, didn't realize that. Thank you for the support

Il giorno lun 12 giu 2023 alle 11:01 Baptiste Arnaud <
***@***.***> ha scritto:
