### ISSUE TITLE
Typebot React Integration Error: Can't resolve `@typebot.io/js/dist/web` in

### ISSUE THREAD

**Issue by mannutech** [baptisteArno/typebot.io#561]
When integrating `Typebot.Standard` in my CRA Typescript react app, I get the error as explained in screenshot.

My `package.json` :

```
"@typebot.io/js": "0.0.63",
    "@typebot.io/react": "0.0.63",
"react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-icons": "^3.0.0",
    "react-router-dom": "^6.11.2",
    "react-scripts": "5.0.1",
    "revo-calendar": "^3.2.3",
    "typescript": "^4.6.3",
```

My `tsconfig.json`
```{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "downlevelIteration": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
}
```

Attaching a screenshot: 
![image](https://github.com/baptisteArno/typebot.io/assets/9911848/f229a72b-e228-4550-8442-164694f6d726)

**Comment by baptisteArno** [comment]
That's a known error with CRA (https://github.com/facebook/create-react-app/issues/11865).

This fixes the issue: https://stackoverflow.com/questions/70964723/webpack-5-in-ceate-react-app-cant-resolve-not-fully-specified-routes/75109686#75109686

On a side note, I would not advise anyone to use CRA anymore as it is "dying" and is not suggested by React officially anymore (https://react.dev/learn/start-a-new-react-project#production-grade-react-frameworks)
