### ISSUE TITLE
ctrl + mouse scroll zooms a lot

### ISSUE THREAD

**Issue by NicolasJardin** [baptisteArno/typebot.io#567]
By turning the mouse wheel just once the zoom is drastically increased or decreased.
Is there any way to reduce the amount of zoom per scroll to leave a zoom similar to the + and - buttons?

[2f80416a-9383-4e54-a3c8-4a762b61b05c.webm](https://github.com/baptisteArno/typebot.io/assets/66677460/3fadb251-7d35-4ed3-9433-bd060144fdb6)

**Comment by evoxf1** [comment]
> /attempt #567
> Options

sorry brother, u can take this, i took another, i tried resigning but it wont work
