### ISSUE TITLE
Add Typebot to Cloudron app store

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#568]

**Comment by gramakri** [comment]
I left a note for you in our forum - https://forum.cloudron.io/post/68314 

"Are you open to having the app published on the App Store ? If so, I can create a repo in our gitlab, give you permissions as well and we can proceed to get it published. Note that GitLab is only for the cloudron package and not for your app development (which can continue wherever you want)."

Please take your time to respond, just wanted you to be aware that this note exists :-)

**Comment by baptisteArno** [comment]
Hey @gramakri sounds great, thank you! Sorry, I did not receive notifications from the Cloudron forum!

**Comment by nebulade** [comment]
For reference, we have nearly completed the package Cloudron now. Packaging code is at https://git.cloudron.io/cloudron/typebot-app (as with all Cloudron packages) so I guess we can remove the `cloudron/` folder in the main project.

Just finishing up the single sign-on integration with Cloudron and then we are ready to push it out for testing amongst the Cloudron users.

**Comment by baptisteArno** [comment]
Nice! Yes, once it's in the app store, I'll delete the Cloudron folder and doc 👍

Thanks for taking some time for this!

**Comment by baptisteArno** [comment]
When are you planning to release it on the app store? @nebulade  :)

**Comment by nebulade** [comment]
Thanks for the reminder, I think this just got overlooked, will pick it up today and hopefully get the first version out. Sorry for that.

**Comment by gramakri** [comment]
@nebulade iirc, the OIDC support I think required some fixes in Cloudron. So, we are probably blocked by Cloudron 7.5

**Comment by nebulade** [comment]
OpenID integration now works, so finished up the app tests and published as unstable for the moment to our app libarary. Very very nice app!

The package repo is at https://git.cloudron.io/cloudron/typebot-app

Currently the images are quite large, unfortunately I don't know too much about pnpm/turbo/prisma to figure out how to strip the package for the moment of potential build artifacts which are not required for deployment. Any hints here are welcome, although this issue can be closed.

**Comment by baptisteArno** [comment]
I'm pushing a new way to manage runtime environment variables injection (#718).

I've asked for access to the repository so that I can push the necessary changes for the Cloudron app 🙏

**Comment by gramakri** [comment]
@baptisteArno you should have full access . thanks!

**Comment by baptisteArno** [comment]
I've created a merge request. If you can test it, it would really help! 🙏

It should also optimize the image size and remove a ton of complexity

**Comment by CptPlastic** [comment]
Whoa if you guys need help with this I have no problem helping out. I use cloudron a lot and this app I have running in it.
