### ISSUE TITLE
Condition "is set" has completely stopped working

### ISSUE THREAD

**Issue by eduazy** [baptisteArno/typebot.io#572]
As you can see here, the condition "is set" has stopped working completely and it's jumping to the "else" option. This is happening in all my bots currently.

![Screenshot](https://github.com/baptisteArno/typebot.io/assets/50171834/4b11fa21-4ab7-4d15-9bdc-3a6426571503)

Test bot link: https://typebot.io/tests-ld6zfw1

Any solution? Thanks

**Comment by baptisteArno** [comment]
I'm investigating

**Comment by baptisteArno** [comment]
Sorry for that, it was introduced a few hours ago. The fix should be available in ~10min

**Comment by eduazy** [comment]
Thank you for your quick response!
