### ISSUE TITLE
Api Builder: get results 

### ISSUE THREAD

**Issue by antonymarion** [baptisteArno/typebot.io#583]
Hi Baptiste,

I am trying to use the Api builder, but I am getting this error 400 on the endpoint results

![image](https://github.com/baptisteArno/typebot.io/assets/8767496/b3ab6baa-a9d8-415a-8f88-e1370c693e6b)

Am I doing something wrong ?

**Nevertheless, It works on other endpoints,** for instance:

![image](https://github.com/baptisteArno/typebot.io/assets/8767496/7386a8cc-fd8c-4822-8662-dafc0603774c)

Regards,
Antony

**Comment by baptisteArno** [comment]
Isn't the error self-explanatory? You need to add a required `limit` query param.

(https://docs.typebot.io/api/list-results)

**Comment by antonymarion** [comment]
OK thank you; As a matter of fact, I just used the example endpoint in the curl and I believed it should work :)

=> I will add some limit then !

thks
