### ISSUE TITLE
NEW FUNCTION - SECOND VISIT

### ISSUE THREAD

**Issue by radioextremosul** [baptisteArno/typebot.io#589]
Hello, you can create a SECOND VISIT function within the typebot configuration tab,

1 - The button for users to return to the previous previous question,
2 - Second Visit - similar to LandBot (with the 3 options available)
2.2 - Provide buttons to start or continue (default)
2.3 - Always carry on a conversation
2.4 - Always start a new conversation

Link document: https://help.landbot.io/article/ntjjsal4ze-second-visit

**Comment by radioextremosul** [comment]
@baptisteArno can you analyze this? if there is possibility

**Comment by baptisteArno** [comment]
For now, I prefer not to implement this. I wouldn't know how to correctly provide this in terms of UX/UI.

You can already remember a user and add conditions on your flow based on already available variables. I know it's not the same
