### ISSUE TITLE
Access results without integrations - results export and/or results API?

### ISSUE THREAD

**Issue by jeremydouglass** [baptisteArno/typebot.io#59]
Thank you for typebot!

I am looking at the hosted version of Typebot before testing the self-hosted version, and I'm trying to understand how results data are accessed (as opposed to being browsed on the results tab). Two things that I had expected I might see:

1. an API call that returns Results for a given 'bot.
2. an export button or menu on each Results page

I don't see either of those things. Is the only way to get results data out through using flow integrations (e.g. Google Sheets) or flow webhooks? Or is the expectation that users will extract their results through direct postgresql queries? Just trying to understand that paradigm here -- for people who don't want to integrate with a third party service (or shouldn't / can't due to data control issues) it isn't clear to me how to get the data out that is being put in.

**Comment by baptisteArno** [comment]
You actually have an Export button that should pop when you select results. It allows you to export a CSV file.

An API endpoint for getting results still needs to be implemented. It should be pretty straightforward, I'll do this soon 👍

**Comment by jeremydouglass** [comment]
Ah, apologies, I should have tried selecting items. Thanks -- CSV export works great as described.

An API endpoint for results would be ideal -- thank you for listing this as an enhancement, and let me know if I can provide testing or feedback on the feature.
