### ISSUE TITLE
TypeBot dont open when use Android Mobile at Facebook.

### ISSUE THREAD

**Issue by danteeb** [baptisteArno/typebot.io#591]
I'm identifying TypeBot issues on facebook, no ads with TypeBot are opening on android phones... only iphone phones.
I did several tests... the TypeBot screen is white, the chat does not load.

**Comment by baptisteArno** [comment]
I could not reproduce. Can you share a bot URL that is failing?

**Comment by jjbairros** [comment]
> I could not reproduce. Can you share a bot URL that is failing?

Several people are reporting the same error in the Jeff Ecom community. I tested it myself, and it only works for iOS. Could you please verify this? It is causing a huge loss of traffic!

Thank you!

**Comment by baptisteArno** [comment]
> I tested it myself

Can you provide the bot URL that you tested?

**Comment by jjbairros** [comment]
Can I send it by email? Otherwise, my offer will be exposed!

**Comment by baptisteArno** [comment]
Yes! baptiste@typebot.io

**Comment by jjbairros** [comment]
sent

**Comment by danteeb** [comment]
Hi Baptiste,

This problem occurs when you are using an android cell phone, you search
your facebook for Typebot, some ads will appear that when you click on the
"Learn More" button will take you to TypeBot, and the screen is all white,
TypeBot does not load. .. I saw that this is only happening on android
phones, and when facebook uses the browser itself for the user to access
TypeBot... several of Jeff's students are also reporting this problem... I
spoke to Jeff yesterday and he said who would talk to you about it.

Regards,
Dannte

Em seg., 10 de jul. de 2023 às 14:23, jjbairros ***@***.***>
escreveu:

**Comment by caianholly** [comment]
hi guys. do we have any updates on this?

**Comment by caianholly** [comment]
@baptisteArno Yes, the problem remains. When I try to open my chat link through instagram on android the screen is all white. I sent the link by direct to test and the problem persists.

**Comment by baptisteArno** [comment]
Can you share the link of your bot? By email if you'd like: baptiste@typebot.io

**Comment by rsuhett** [comment]
> Can you share the link of your bot? By email if you'd like: [baptiste@typebot.io](mailto:baptiste@typebot.io)

Hi, I've faced the same issue and sent the email too.

**Comment by danteeb** [comment]
Hi Baptiste, how can I reset Typebot's statistics to check if the amount of people who are clicking on the ad on Facebook are reaching Typebot?

Regards

**Comment by caianholly** [comment]
> [baptiste@typebot.io](mailto:baptiste@typebot.io)

sent

**Comment by baptisteArno** [comment]
Ok, I just pushed a change that could solve the issue (e293cb011174aa170ee136c8a1b476bfc98e797c).

Can you let me know if it's fixed?

**Comment by caianholly** [comment]
> Ok, I just pushed a change that could solve the issue ([e293cb0](https://github.com/baptisteArno/typebot.io/commit/e293cb011174aa170ee136c8a1b476bfc98e797c)).
> 
> Can you let me know if it's fixed?

Hi Arno,

yes, the issue is fixed.

thanks for helpful support

**Comment by baptisteArno** [comment]
Let's gooo 💪
