### ISSUE TITLE
Vercel Deployment Failing

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#602]
Followed the instructions to deploying with Vercel and it keeps erroring :

Build Failed

Command "cd ../.. && pnpm build:builder && pnpm db:migrate" exited with 1

--------------
builder:build: Failed to compile.

builder:build: Type error: Module '"@typebot.io/prisma"' has no exported member 'User'.

builder:build:  ELIFECYCLE  Command failed with exit code 1.
builder:build: ERROR: command finished with error: command (/vercel/path0/apps/builder) pnpm run build exited (1)
command (/vercel/path0/apps/builder) pnpm run build exited (1)
  Tasks:    3 successful, 4 total
 Cached:    0 cached, 4 total
 Time:    58.884s 
Summary:    /vercel/path0/.turbo/runs/2STtNTJyASeP15ES06UokDd8OEE.json
Failed:    builder#build
ERROR  run failed: command  exited (1)
ELIFECYCLE  Command failed with exit code 1.
Error: Command "cd ../.. && pnpm build:builder && pnpm db:migrate" exited with 1

**Comment by jdefranco** [comment]
And this for the viewer :

bot-engine:build: src/components/TypebotViewer.tsx(15,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Log'.
bot-engine:build: src/providers/TypebotProvider.tsx(4,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Log'.
bot-engine:build: src/types.ts(1,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Log'.
bot-engine:build: src/utils/helpers.ts(1,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Log'.
bot-engine:build: ../../prisma/index.ts(5,3): error TS2305: Module '"@prisma/client"' has no exported member 'Plan'.
bot-engine:build: ../../prisma/index.ts(6,3): error TS2305: Module '"@prisma/client"' has no exported member 'WorkspaceRole'.
bot-engine:build: ../../prisma/index.ts(7,3): error TS2305: Module '"@prisma/client"' has no exported member 'GraphNavigation'.
bot-engine:build: ../../prisma/index.ts(8,3): error TS2305: Module '"@prisma/client"' has no exported member 'CollaborationType'.
bot-engine:build: ../../schemas/features/answer.ts(2,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Answer'.
bot-engine:build: ../../schemas/features/answer.ts(28,32): error TS2694: Namespace '"/vercel/path0/node_modules/.pnpm/@prisma+client@4.14.1_prisma@4.14.1/node_modules/.prisma/client/index".Prisma' has no exported member 'AnswerUncheckedUpdateInput'.
bot-engine:build: ../../schemas/features/blocks/baseSchemas.ts(2,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Credentials'.
bot-engine:build: ../../schemas/features/publicTypebot.ts(1,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'PublicTypebot'.
bot-engine:build: ../../schemas/features/result.ts(5,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Result'.
bot-engine:build: ../../schemas/features/result.ts(5,34): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Log'.
bot-engine:build: ../../schemas/features/typebot/theme/schemas.ts(1,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'ThemeTemplate'.
bot-engine:build: ../../schemas/features/typebot/typebot.ts(5,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Typebot'.
bot-engine:build: ../../schemas/features/webhooks.ts(1,10): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Webhook'.

bot-engine:build: ../../schemas/features/workspace.ts(3,3): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'Workspace'.
bot-engine:build: ../../schemas/features/workspace.ts(5,3): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'MemberInWorkspace'.
bot-engine:build: ../../schemas/features/workspace.ts(7,3): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'User'.
bot-engine:build: ../../schemas/features/workspace.ts(8,3): error TS2305: Module '"@typebot.io/prisma"' has no exported member 'WorkspaceInvitation'.
bot-engine:build:  ELIFECYCLE  Command failed with exit code 2.
bot-engine:build: ERROR: command finished with error: command (/vercel/path0/packages/deprecated/bot-engine) pnpm run build exited (1)
@typebot.io/js:build:  ELIFECYCLE  Command failed.
command (/vercel/path0/packages/deprecated/bot-engine) pnpm run build exited (1)
  Tasks:    2 successful, 4 total
 Cached:    0 cached, 4 total
    Time:    14.088s 
    Summary:    /vercel/path0/.turbo/runs/2STvHo0rmqngJ1l8W3kCvC2E4Fa.json
     Failed:    bot-engine#build
 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "cd ../.. && pnpm build:viewer && pnpm db:migrate" exited with 1

**Comment by davidtmiranda** [comment]
Same for me

**Comment by baptisteArno** [comment]
That's super strange. I've just tried, it works fine.

Can someone record their screen while deploying on Vercel to see what you're doing wrong?

**Comment by davidtmiranda** [comment]
of course! here it is https://drive.google.com/drive/folders/1TUIUAlR3Cj55E2Y4V90X_LRu_Uzbql8q

**Comment by baptisteArno** [comment]
How is your `DATABASE_URL` looks like?

**Comment by jdefranco** [comment]
here is a screen capture of they deployment with Environment Variables 
https://www.awesomescreenshot.com/video/19219289?key=62a722c9a06a5bfbf7d9229552f5b0c4

**Comment by baptisteArno** [comment]
Ok that's it, your `DATABASE_URL` must start with `postgresql://` not `postgres://`

**Comment by baptisteArno** [comment]
Try to rebuild without cache? It should work.

**Comment by jdefranco** [comment]
I tried the viewer redeploy with old url postgres:// and the builder redeploy with postgresql:// and they both did same error again
Screen Capture:
https://www.awesomescreenshot.com/video/19221062?key=25bb9d5e5d38658f86c319905791e7c2

**Comment by jdefranco** [comment]
Ok, its working now.. the issue seems to be the database created with Heroku. I created a new database using Vercel, and changed its url to use postgresql:// and it deployed successfully ..

**Comment by davidtmiranda** [comment]
> Ok, its working now.. the issue seems to be the database created with Heroku. I created a new database using Vercel, and changed its url to use postgresql:// and it deployed successfully ..

same, just working fine now, thanks!
