### ISSUE TITLE
docker-compose up -d  command doesn't work, help

### ISSUE THREAD

**Issue by franroa14** [baptisteArno/typebot.io#604]

**Comment by franroa14** [comment]
Using the installation form Docker, I was able to edit, but lastly the command "docker-compose up -d" my editor didn't recognize, my editor is nano, do you know what it could be? 🙌

**Comment by baptisteArno** [comment]
I'm sorry, but that question does not make much sense! What exactly is the issue?

> You don't have to be an expert to launch your own instance of Typebot but you need a basic understanding of the command-line and networking.

If that's not the case, I really suggest you use https://app.typebot.io 🙏
