### ISSUE TITLE
Yaml issue with this line using double quotes.

### ISSUE THREAD

**Issue by Ymirke** [baptisteArno/typebot.io#607]
Hey - quickly set this up for a friend. Got stuck on this error message. I was using double quotes in my yaml config for the secret, then when I removed it - it was okay. 

The error message then is a bit misleading (?) as the secret is supposed to be 24 characters

https://github.com/baptisteArno/typebot.io/blob/de08179f8bbf291d79a7df3c701d3913f6cb73ca/packages/cloudron/start.sh#L38

**Comment by baptisteArno** [comment]
> as the secret is supposed to be 24 characters

Why are you saying this? It should be 32 characters.

What yaml config are you talking about?
