### ISSUE TITLE
Server Error after upgrading to 2.15.1

### ISSUE THREAD

**Issue by JustinBack** [baptisteArno/typebot.io#608]
After upgrading to 2.15.1 we encounter an internal server error

Env: Docker

```json
{"message":"Output validation failed","code":"INTERNAL_SERVER_ERROR"}
```

Request Headers (Some fields are censored but irrelevant):

| Field                       | Value                                                                                                 |
|-----------------------------|-------------------------------------------------------------------------------------------------------|
| :Authority                  | ****                                                                                |
| :Method                     | POST                                                                                                  |
| :Path                       | /api/v1/sendMessage                                                                                   |
| :Scheme                     | https                                                                                                 |
| Accept                      | */*                                                                                                   |
| Accept-Encoding             | gzip, deflate, br                                                                                     |
| Accept-Language             | de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7                                                                   |
| Content-Length              | 119                                                                                                   |
| Content-Type                | application/json                                                                                      |
| Cookie                      | ***** |
| Origin                      | ****                                                                         |
| Referer                     | ****                                              |
| Sec-Ch-Ua                   | "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"                                      |
| Sec-Ch-Ua-Mobile            | ?0                                                                                                    |
| Sec-Ch-Ua-Platform          | "Windows"                                                                                             |
| Sec-Fetch-Dest              | empty                                                                                                 |
| Sec-Fetch-Mode              | cors                                                                                                  |
| Sec-Fetch-Site              | same-origin                                                                                           |
| User-Agent                  | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 |

Request Payload:

```json
{"startParams":{"isPreview":false,"typebot":"****","prefilledVariables":{},"isStreamEnabled":true}}
```

This happens once you access a chat (preview, widget, directly) - Odd is that some chats work and some wont.

**Comment by baptisteArno** [comment]
Can you provide the server logs? `docker-compose logs`

**Comment by JustinBack** [comment]
Oh woops, forgot to paste them, thought I did that 🤦🏻 - Unfortunately after I applied my "fix" yesterday the problem is gone and so are the logs. 


Though here is what I suspect:

- The typebots were all using the old engine

What I noticed is that the bots that crashed had no avatar, not even the default one - I uploaded a custom one (which sometimes didn't work) or used a giphy avatar and after that the bots started working again.


I'll try to reproduce this so I can catch some logs but even after creating a new bot this issue does not appear anymore, so I suspect the migration to the new engine failed.

**Comment by baptisteArno** [comment]
What was your previous version?

**Comment by JustinBack** [comment]
It was a direct upgrade (not path) from 2.13.x

**Comment by baptisteArno** [comment]
Ok, I'm not sure what happened, but let's close that issue for now. Thank you for the report 🙏
