### ISSUE TITLE
Deploy typebot on a path

### ISSUE THREAD

**Issue by dougecomp** [baptisteArno/typebot.io#610]
Hi!

First I would like to thank you for this great tool!

I am trying to deploy **typebot** on a path like "domain.com.br/typebot/builder" and "domain.com.br/typebot/viewer" but the builder redirects do "domain.com.br/pt" and i don't want that. There is way to keep the original url like **domain.com.br/typebot/builder/pt**? Anyone needed to deploy typebot in some similar way?

Thanks in advance for any help!

**Comment by baptisteArno** [comment]
Hey,

I don't think it would be possible, unfortunately.

Deploying Typebot on subdomains is not an option for you? `builder.domain.com.br` and `viewer.domain.com.br`?

**Comment by dougecomp** [comment]
Unfotunately not. 

I only have the domain and with lets encrypt to get SSL certificate.

I recently deployed a application called **DSpace** on version 7.x that we can configure the base url and the namespace to deploy. With this i could deploy the application on an path like **domain.com.br/dspace**. The application is developed with java spring boot for the backend and angular on frontend. This is the links of the docs: https://wiki.lyrasis.org/display/DSDOC7x/7.0-7.1+Frontend+Installation

I leave an feedback on https://feedback.typebot.io/feedback/92742

Anyway, thanks again for the fast reply and attention!

**Comment by dougecomp** [comment]
Searching on my Hostinger panel i found that i can create subdomains! See: https://builder.jorgestochero.com.br/

Typebot working nicely!

@baptisteArno Thanks again for the amazing tool and for your question that made me curious to find out if i could create subdomains on my hosting platform!

**Comment by baptisteArno** [comment]
Glad to hear that my friend 🙌
