### ISSUE TITLE
[Error: Cipher job failed] | OpenAI Integration

### ISSUE THREAD

**Issue by liweifeng2022** [baptisteArno/typebot.io#612]
![image](https://github.com/baptisteArno/typebot.io/assets/110445630/68840922-dba9-45a4-b466-7e90c57d2435)
hi, bro! I would like to ask a question, it seems that the encryption module is wrong, but I have not seen a more detailed log

**Comment by liweifeng2022** [comment]
@Jorgelig

**Comment by baptisteArno** [comment]
Your `ENCRYPTION_SECRET` is most likely invalid?

Did you correctly generate it with `openssl rand -base64 24 | tr -d '\n' ; echo`

**Comment by baptisteArno** [comment]
Also, make sure `ENCRYPTION_SECRET` is same accross builder and viewer!

**Comment by baptisteArno** [comment]
Oh, the `env.local.example` was invalid. This is fixed on 13ac46975d12d8c3aac3a053ea7f612988c9b90f

**Comment by liweifeng2022** [comment]
@baptisteArno Thanks! According to your description, the problem has been solved!
