### ISSUE TITLE
Como posso pegar o cookie?

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#620]
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/47e70a31-40ea-4e41-84e1-9ec0b48f60e9)

I used setar variable to see everything as a string

**Comment by baptisteArno** [comment]
It means the code failed to execute so it returned it as a string to your variable.

Did you enable the "Execute on client" option in the Set variable block config?

**Comment by RuanMD** [comment]
> It means the code failed to execute so it returned it as a string to your variable.
> 
> Did you enable the "Execute on client" option in the Set variable block config?

![image](https://github.com/baptisteArno/typebot.io/assets/44640884/2a6deccb-c09e-42ac-85ec-ccfc079bcf0b)

enable yes, how can I resolve this error?

**Comment by baptisteArno** [comment]
Can you share the code as text? So that we can try

**Comment by RuanMD** [comment]
`// Obtém o valor docookie _fbp
var _fbp = getCookie("_fbp");

// Obtém o valor do cookie _fbc
var _fbc = getCookie("_fbc");

// Faça o que você precisa fazer com os valores dos cookies _fbp e _fbc
console.log("_fbp:", _fbp);
console.log("_fbc:", _fbc);

// Função auxiliar para obter o valor de um cookie
function getCookie(name) {
  var cookies = document.cookie.split("; ");
  for (var i = 0; i < cookies.length; i++) {
    var cookie = cookies[i].split("=");
    if (cookie[0] === name) {
      return cookie[1];
    }
  }
  return "";
}`

**Comment by RuanMD** [comment]
> Can you share the code as text? So that we can try
```
// Obtém o valor docookie _fbp
var _fbp = getCookie("_fbp");

// Obtém o valor do cookie _fbc
var _fbc = getCookie("_fbc");

// Faça o que você precisa fazer com os valores dos cookies _fbp e _fbc
console.log("_fbp:", _fbp);
console.log("_fbc:", _fbc);

// Função auxiliar para obter o valor de um cookie
function getCookie(name) {
  var cookies = document.cookie.split("; ");
  for (var i = 0; i < cookies.length; i++) {
    var cookie = cookies[i].split("=");
    if (cookie[0] === name) {
      return cookie[1];
    }
  }
  return "";
}
```

**Comment by baptisteArno** [comment]
Ok so you are expected to return a value to attach it to your variable.

In your case, you can either add `return _fbp` or `return _fbc` and it will work.
