### ISSUE TITLE
CapRover one click app

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#63]
Would be great to list Typebot in the One click app CapRover repo

**Comment by dantosXD** [comment]
Here is an actual 1-click-app install config. 

captainVersion: 4
services:
  $$cap_appname-db:
    image: postgres:13
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $$cap_db_name
      POSTGRES_PASSWORD: $$cap_db_password
  $$cap_appname-builder:
    image: baptistearno/typebot-builder:$$cap_builder_version
      args:
        - SCOPE=builder
    restart: always
    depends_on:
      - $$cap_appname-db
    ports:
      - '8080:3000'
    caproverExtra:
      containerHttpPort: '3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      DATABASE_URL: postgresql://postgres:typebot@$$srv-captain--cap_appname-db:5432/typebot
      NEXTAUTH_URL: http://$$cap_appname-builder.$$cap_root_domain
      NEXT_PUBLIC_VIEWER_URL: http://$$cap_appname-viewer.$$cap_root_domain
      ENCRYPTION_SECRET: $$cap_gen_random_hex(32)
      ADMIN_EMAIL: $$cap_admin_email
      SMTP_USERNAME: $$cap_SMTP_username
      SMTP_PASSWORD: $$cap_SMTP_password
      SMTP_HOST: $$cap_SMTP_host
      SMTP_PORT: $$cap_SMTP_port
      NEXT_PUBLIC_SMTP_FROM: $$cap_SMTP_emailfrom
  $$cap_appname-viewer:
    image: baptistearno/typebot-viewer:$$cap_viewer_version
    restart: always
    ports:
      - '8081:3000'
    caproverExtra:
      containerHttpPort: '3000'
    # See https://docs.typebot.io/self-hosting/configuration for more configuration options
    environment:
      DATABASE_URL: postgresql://postgres:typebot@$$srv-captain--cap_appname-db:5432/typebot
      NEXT_PUBLIC_VIEWER_URL: http://$$cap_appname-viewer.$$cap_root_domain
      ENCRYPTION_SECRET: $$cap_gen_random_hex(32)
volumes:
caproverOneClickApp:
    variables:
        - id: '$$cap_db_name'
          label: Postgres Database Name
		  defaultValue: 'typebot'
          description: Enter a name of your database 
        - id: '$$cap_db_password'
		  defaultValue: 'typebot'
          label: Postgres Database Password
          description: Enter a password for your database
        - id: '$$cap_viewer_version'
          label: Typbot Viewer Version
          defaultValue: 'main'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/baptistearno/typebot-viewer/tags
        - id: '$$cap_builder_version'
          label: Typbot Viewer Version
          defaultValue: 'main'
          description: Check out their Docker page for the valid tags https://hub.docker.com/r/baptistearno/typebot-builder/tags
        - id: '$$cap_admin_email'
          label: Admin Email
          description: Email for the admin account
        - id: '$$cap_SMTP_username'
          label: SMTP Username
          description: Username
        - id: '$$cap_SMTP_password'
          label: SMTP Password
          description: Password
        - id: '$$cap_SMTP_host'
          label: SMTP Host
          description: SMTP server address (smtp.example.com)
        - id: '$$cap_SMTP_port'
          label: SMTP Port
          description: SMTP Port
        - id: '$$cap_SMTP_emailfrom'
          label: SMTP Email From
          description: The email account you want the replys sent from
    instructions:
        start: |-
            Open-source conversational forms builder. Typebot gives you powerful blocks to create unique chat experiences. Embed them anywhere on your web/mobile apps and start collecting results like magic.
        end: |-
            You can build your typebot by going to http://$$cap_appname-builder.$$cap_root_domain 
			or the viewer at http://$$cap_appname-viewer.$$cap_root_domain
    displayName: Typebot.io
    isOfficial: true
    description: Open-source conversational forms builder.
    documentation: This docker-compose is taken from https://github.com/baptisteArno/typebot.io/blob/main/docker-compose.yml

**Comment by ronaldloyko** [comment]
I have [added](https://github.com/caprover/one-click-apps/pull/760) it.
Until the PR is merged, you can already use it by selecting the `>>> TEMPLATE <<<` one-click-app and inserting [this file content](https://github.com/caprover/one-click-apps/blob/47a2ceb61d510b11bb8b696b7ba0b33742a73e0f/public/v4/apps/typebot.yml).

**Comment by baptisteArno** [comment]
You rock, thank you! 💙
