### ISSUE TITLE
Infinite looping

### ISSUE THREAD

**Issue by g3k1** [baptisteArno/typebot.io#638]
Hello everything is fine?
Could you help me, please?
my typebot is in infinite looping like in the image below, I already changed accounts, I already cleaned cache, I already formatted the PC, but it continues the same way, could you help me?

Thanks

![image](https://github.com/baptisteArno/typebot.io/assets/138717706/1bbfbee9-342b-4cd6-b60d-b7f450ecf431)

**Comment by baptisteArno** [comment]
What happens if you go to https://app.typebot.io/signin ?

**Comment by baptisteArno** [comment]
Can you tell me what's your account email? So that I can check in database if everything is set up correctly? You can send it to baptiste@typebot.io if you'd like to keep it private.

**Comment by g3k1** [comment]
Of course.
My account is ***@***.***
Thanks
________________________________
De: Baptiste Arnaud ***@***.***>
Enviado: quarta-feira, 26 de julho de 2023 02:43
Para: baptisteArno/typebot.io ***@***.***>
Cc: g3k1 ***@***.***>; Author ***@***.***>
Assunto: Re: [baptisteArno/typebot.io] Infinite looping (Issue #638)


Can you tell me what's your account email? So that I can check in database if everything is set up correctly? You can send it to ***@***.******@***.***> if you'd like to keep it private.

**Comment by baptisteArno** [comment]
Can you send it to me via email? It seems Github does not want you to share your email 😁
