### ISSUE TITLE
Google Authentication - To confirm your identity, sign in with the same account you used originally.

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#639]
Getting the message : 

"To confirm your identity, sign in with the same account you used originally."

I've tried logging in via incognito, different browser, clear cache, everything.. still goes directly to this message once you click sign in with google

--- >>> However, on my android phone, it will work.. if I load multiple browser windows I can create new accounts with google authentication in each tab.

**Comment by baptisteArno** [comment]
Any interesting logs on the server?

**Comment by jdefranco** [comment]
Maybe something with the cache?

[GET] /api/trpc/getAppVersionProcedure
Status Code : 200
Cache : MISS
Function : /api/trpc/[trpc]

[GET] /api/auth/signin
Status Code : 302
Cache : MISS
Function : /api/auth/[...nextauth]

[GET] /api/auth/error
Status Code : 302
Cache: MISS
Function: /api/auth/[...nextauth]

[POST] /api/auth/signin/google
Status Code : 200
Cache : MISS
Function: /api/auth/[...nextauth]

[GET] /api/auth/csrf 
Status Code : 304
Cache: HIT
Function : /api/auth/[...nextauth]



Seems like this is a common issue involving linked emails but still very strange that on mobile it works, as reported in a case below : 
https://github.com/LAION-AI/Open-Assistant/issues/2724
https://github.com/nextauthjs/next-auth/discussions/2808

**Comment by baptisteArno** [comment]
It's how Nextauth handles it. I'll close it for now as it's not that important 🙏
