### ISSUE TITLE
Upgrade from v2.1.0 (docker) to v2.1.1 (new docker release)

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#65]
Hi,

I have v2.1.0 installed using old docker way of installation (docker build)

Now that you provided your own docker images, can you explain how to do an upgrade without losing already created bots?

Is it possible just to replace docker-compose.yaml with new version and set environment variables that we set previously in ".env" files? What happens with already created DB image?

**Comment by teq-dev** [comment]
> set environment variables that we set previously in ".env" files?

I had success with doing this.

> What happens with already created DB image?

I was able to copy my old Docker db volume to the new volume name in `/var/lib/docker/volumes` and all my old Typebots were available.

**Comment by teq-dev** [comment]
> > I was able to copy my old Docker db volume to the new volume name in /var/lib/docker/volumes and all my old Typebots were available.
> 
> Oh yes, I should mention that. What are the commands you had to run to do this?

```
docker-compose down
cd /var/lib/docker/volumes
mv typebotio_db_data typebot-docker_db_data
```
