### ISSUE TITLE
Getting Error! Couldn't initiate the chat even though config is correctly set

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#657]
I'm getting an `Error! Couldn't initiate the chat` error even though my configuration is correctly set.

I found the issue #460 and #621 being similar to this one, but the solutions referenced in those don't apply here.

I'm keeping this one for the sake of documentation.

If any relevant logs appear, I'll link them here

**Comment by baptisteArno** [comment]
Can you check the Network tabs when it happens? (https://developer.chrome.com/docs/devtools/network/)

**Comment by Lanhild** [comment]
>Can you check the Network tabs when it happens? (https://developer.chrome.com/docs/devtools/network/)

Sadly, no. Since the error is happening to one of my users and not me, I can't check the console. I'll link here any potential logs that might appear

**Comment by baptisteArno** [comment]
Oh, ok, so the bug is not happening all the time? I'll close this for now, feel free to re-open when you have more info or a reproduction 🙏
