### ISSUE TITLE
docker-compose.yml build step needed?

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#66]
Is this needed with the new Docker images self-hosted option?

https://github.com/baptisteArno/typebot.io/blob/30d36b9a09647e3a259442f7c3342b690f3a0913/docker-compose.yml#L13

**Comment by baptisteArno** [comment]
You can remove the `build` prop, it is ignored when there is an `image` 👍

**Comment by teq-dev** [comment]
Thank you - here's what happens if you don't clone the entire repo and just use the docker-compose.yml without removing the build step:

```
...
8a72a860cc25: Pull complete
d30d1a75aee3: Pull complete
7dd91cedb27f: Pull complete
Digest: sha256:e3354da5b11f8c52eca6ae00725acf5bb0d07c17d33ceea95d706188e14a0dd5
Status: Downloaded newer image for postgres:13
Building typebot-builder
**ERROR: Cannot locate specified Dockerfile: Dockerfile**
```
