### ISSUE TITLE
Emails are not getting triggered in the flow 

### ISSUE THREAD

**Issue by cherrycharan** [baptisteArno/typebot.io#660]
When i invite a user emails are getting triggered , but when in use the email block in the flow emails are not getting triggered . 
how to debug this ? checked docker logs found nothing

**Comment by baptisteArno** [comment]
Is there anything in the result logs? (https://docs.typebot.io/editor/results#logs)

**Comment by cherrycharan** [comment]
`{
  "error": {
    "errno": -111,
    "code": "ESOCKET",
    "syscall": "connect",
    "address": "127.0.0.1",
    "port": 587,
    "command": "CONN"
  },
  "transportConfig": {
    "port": null,
    "auth": {
      "pass": "******"
    }
  },
  "email": {
    "cc": [],
    "bcc": [],
    "to": [
      "myemail@gmail.com"
    ],
    "subject": "Test Email",
    "text": "This is to test "
  }
}`

**Comment by baptisteArno** [comment]
Can you tell us what's your SMTP config?

**Comment by cherrycharan** [comment]
typebot-builder:
environment:
- SMTP_HOST=smtp.zoho.in
      - SMTP_PORT=587
      - SMTP_USERNAME=email@email.in
      - SMTP_PASSWORD=password
      - SMTP_FROM=email@email.in
      - SMTP_REPLY_TO=email@email.in
      - NEXT_PUBLIC_SMTP_FROM='Type Bot' <email@email.in>
      - SMTP_AUTH_DISABLED=false
      - SMTP_SECURE=false

**Comment by baptisteArno** [comment]
The NEXT_PUBLIC_SMTP_FROM variable should have this shape: `'Type Bot' <email@email.in>`

**Comment by cherrycharan** [comment]
@baptisteArno Tried this as well still the same error

**Comment by baptisteArno** [comment]
Are you sure you are using the default from email?

![CleanShot 2023-08-03 at 07 47 17@2x](https://github.com/baptisteArno/typebot.io/assets/16015833/1204d025-e9d0-497b-a9af-0503f7210b56)

If you can be a bit more talkative, i.e. actively trying to debug with me, it would help a lot! We need as much info as possible

**Comment by cherrycharan** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/16544980/eac9e484-9c40-4d66-9011-f711b7fa26d0)

I am using default email only

**Comment by baptisteArno** [comment]
Can I have access to your tool and try it out myself? If you'd like to keep the details private, you can send a message to baptiste@typebot.io

**Comment by cherrycharan** [comment]
Invited you pls check you mail

**Comment by luizeof** [comment]
Hello @baptisteArno  ... is there a possibility to consider including at least 1 email provider through API?

**Comment by baptisteArno** [comment]
Oh right, I'm dumb. You probably forgot to add the STMP credentials to the viewer environment (https://docs.typebot.io/self-hosting/configuration/viewer#emails-notifications)

**Comment by cherrycharan** [comment]
I tried using the SMTP Creds in viewer env , now i am getting a new error as below 

{
  "error": {
    "code": "EMESSAGE",
    "response": "553 Relaying disallowed as undefined@localhost",
    "responseCode": 553,
    "command": "DATA"
  },
