### ISSUE TITLE
Upgrade from v2.15.2 to v2.16.0: getting `Couldn't initiate the chat` error

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#668]
I got similar error yet on caprover. I upgraded like always did until now, and everything on builder side worked. Yet viewer was giving that error. I reverted to previous version i had, works like a charm.

_Originally posted by @uhlhosting in https://github.com/baptisteArno/typebot.io/issues/662#issuecomment-1664287322_

**Comment by baptisteArno** [comment]
Can you provide a link where I can see the error? If you'd like to keep it private: baptiste@typebot.io

**Comment by uhlhosting** [comment]
Sure one place can be on my testing site, eofs.dev . I just made the switch to 2.16.x is same builder works, viewer not.

**Comment by uhlhosting** [comment]
@baptisteArno mail sent with logs too.

**Comment by baptisteArno** [comment]
Thank you for this.

The issue is that the `apiHost` field points to your builder. It should point to your viewer.

I wonder why it works on 2.15.x though? 🤔

**Comment by baptisteArno** [comment]
I'm referring to the bubble embed you have on https://eofs.dev. It doesn't have a valid `apiHost` value, you need to follow the embed instructions in the Share tab of your bot! :)

**Comment by uhlhosting** [comment]
> I'm referring to the bubble embed you have on https://eofs.dev. It doesn't have a valid `apiHost` value, you need to follow the embed instructions in the Share tab of your bot! :)

@baptisteArno You got mail! ;)

**Comment by uhlhosting** [comment]
@baptisteArno any updates on last investigation? Have you managed to identify the root cause? Any ETA for a fix?

**Comment by jmempreendedorismo** [comment]
I solved my problem like this:
https://github.com/baptisteArno/typebot.io/issues/701#issuecomment-1827126998
