### ISSUE TITLE
docker installation not working. using ubuntu 22.04

### ISSUE THREAD

**Issue by kolinfluence** [baptisteArno/typebot.io#669]
2 questions:

1. docker installation not working. using ubuntu 22.04

2. how to use llama.cpp as backend instead of openai api?
https://github.com/ggerganov/llama.cpp

very well done by the way. impressive.

**Comment by baptisteArno** [comment]
Hey man

> docker installation not working. using ubuntu 22.04

What is not working?

> how to use llama.cpp as backend instead of openai api?

No easy way to implement that afaik

**Comment by kolinfluence** [comment]
tried installing on lightsail aws but the ports are not responding. i did enabled the firewall ports but internally seemed the docker instance program inside is not running.

let me try on my laptop again and see.
