### ISSUE TITLE
NEXT_PUBLIC_SMTP_AUTH_DISABLED not working in Docker image

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#67]
First, thank you for simplifying the Docker deployment option!

I added my existing env variable `NEXT_PUBLIC_SMTP_AUTH_DISABLED=true`, but the email login form option is still displayed on the /signin page. I did notice that email login is prevented (when attempted), but previously the login form was hidden.

**Comment by baptisteArno** [comment]
I reproduced the issue.

Waiting for help here https://github.com/vercel/next.js/discussions/17641#discussioncomment-2829534

**Comment by baptisteArno** [comment]
Should be fixed on v2.1.2.

See migration guide: https://github.com/baptisteArno/typebot.io/releases/tag/v2.1.2
