### ISSUE TITLE
OPEN AI - API KEY INVALID KEY LENGTH.

### ISSUE THREAD

**Issue by luck-git** [baptisteArno/typebot.io#672]
I have watched the video in which you specify how to connect the Open AI and set the API key .. But In my case When i Add my account and Put the API key . "It shows invalid key length" .. Could you please guide me through this .

**Comment by luck-git** [comment]
![Screenshot from 2023-08-10 17-17-47](https://github.com/baptisteArno/typebot.io/assets/130035922/069c6476-cd5e-4f1c-aecc-e67741790f8b)
**for refrence i have attached the screenshort**

**Comment by baptisteArno** [comment]
It means your `ENCRYPTION_SECRET` has not the valid length (https://docs.typebot.io/self-hosting/docker#2-add-the-required-configuration)

**Comment by luck-git** [comment]
Thank YOU ... It's done
