### ISSUE TITLE
Jump function does not sequence groups

### ISSUE THREAD

**Issue by radioextremosul** [baptisteArno/typebot.io#675]
When I use the "jump" function, it stops the execution of the current flow, not continuing to the next "Groups" created, is it supposed to be like this, does the "jump" really stop when used? wanted after pulling the "jump" of the sequence to my flow

**Comment by baptisteArno** [comment]
Can you share a typebot that reproduces the bug?

**Comment by radioextremosul** [comment]
Yes, of course, what happens I will try to explain also by text, is that when I select another typebot to integrate it simple for the flow and not giving continuity to the next blocks of the current bot

https://github.com/baptisteArno/typebot.io/assets/135563573/933ef97e-22d3-4b31-bac7-e6a28d8a1f2f
