### ISSUE TITLE
How to make Google (Auth, Sheets, Fonts) working?

### ISSUE THREAD

**Issue by geniusshiun** [baptisteArno/typebot.io#68]
I follow this [doc](https://docs.typebot.io/self-hosting/configuration). 
Apply scopes (userinfo.email, spreadsheets, drive.readonly) in my console.
There are two question：
1. If ask spreadsheets, drive.readonly, we need to apply verification. 
How to deal with "Provide users a link to your public privacy policy" and "Provide users a link to your public terms of service"?
2. I use userinfo.email only, and key in the NEXT_PUBLIC_GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET. But it don't work.
Here is my env
![image](https://user-images.githubusercontent.com/10183057/170652104-e33454e8-0a6f-4692-b57d-2fe5c46c53a6.png)

**Comment by baptisteArno** [comment]
Hey @geniusshiun,

If you have a `NEXT_PUBLIC_GOOGLE_CLIENT_ID` value then it should show the "Continue with Google" button.

What is your docker-compose config? Are you sure `NEXT_PUBLIC_GOOGLE_CLIENT_ID` has a value?

**Comment by baptisteArno** [comment]
Replied on Github, let's discuss there :)

**Comment by baptisteArno** [comment]
There is a new version of the docker config. Please see this migration guide: https://github.com/baptisteArno/typebot.io/releases/tag/v2.1.2

Feel free to re-open if it still occurs.
