### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by itzomen** [baptisteArno/typebot.io#681]
`ReferenceError: window is not defined` error from `@typebot.io/react` when using version >=[0.1.0](https://www.npmjs.com/package/@typebot.io/react/v/0.1.0)

Do you have any idea how to fix this?
![Screenshot from 2023-08-13 04-38-02](https://github.com/baptisteArno/typebot.io/assets/61752841/0db8ae6f-4fea-489f-85f5-55f8396cf34e)

**Comment by baptisteArno** [comment]
Hey, there is this new dedicated package for Next.js environment: https://www.npmjs.com/package/@typebot.io/nextjs

Let me know if it works
