### ISSUE TITLE
email not send

### ISSUE THREAD

**Issue by amirmdehghanpour** [baptisteArno/typebot.io#682]
hi
i install typebot on own server bot emaill not send for singup
`Attaching to root_typebot-builder_1, root_typebot-viewer_1, root_typebot-db_1
typebot-builder_1  | env.sh loaded
typebot-builder_1  | Matched inline env:
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@mail.jfjl.ir>
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=rooyeshjavan.ir:8081
typebot-builder_1  | Reading ./apps/builder/.env.production...
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM=
typebot-builder_1  | NEXT_PUBLIC_GOOGLE_API_KEY=
typebot-builder_1  | NEXT_PUBLIC_GIPHY_API_KEY=
typebot-builder_1  | NEXT_PUBLIC_STRIPE_PUBLIC_KEY=
typebot-builder_1  | NEXT_PUBLIC_SENTRY_DSN=
typebot-builder_1  | NEXT_PUBLIC_VIEWER_INTERNAL_URL=
typebot-builder_1  | NEXT_PUBLIC_E2E_TEST=
typebot-builder_1  | NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=
typebot-builder_1  | NEXT_PUBLIC_UNSPLASH_APP_NAME=
typebot-builder_1  | NEXT_PUBLIC_UNSPLASH_ACCESS_KEY=
typebot-builder_1  | NEXT_PUBLIC_ONBOARDING_TYPEBOT_ID=
typebot-builder_1  | NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@mail.jfjl.ir>
typebot-builder_1  | NEXT_PUBLIC_VIEWER_URL=rooyeshjavan.ir:8081
typebot-builder_1  | Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
typebot-builder_1  | Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
typebot-builder_1  | env.sh done
typebot-builder_1  | 
typebot-builder_1  | Checking if required environment variables are set and valid...
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | 
typebot-builder_1  | ✔ Generated Prisma Client (5.0.0 | library) to ./node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client in 5.42s
typebot-viewer_1   | env.sh loaded
typebot-viewer_1   | Matched inline env:
typebot-viewer_1   | NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@mail.jfjl.ir>
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=rooyeshjavan.ir:8081
typebot-viewer_1   | Reading ./apps/viewer/.env.production...
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=
typebot-viewer_1   | NEXT_PUBLIC_E2E_TEST=
typebot-viewer_1   | NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@mail.jfjl.ir>
typebot-viewer_1   | NEXT_PUBLIC_VIEWER_URL=rooyeshjavan.ir:8081
typebot-viewer_1   | Got index from inline env: 0, replacing NEXT_PUBLIC_SMTP_FROM
typebot-viewer_1   | Got index from inline env: 1, replacing NEXT_PUBLIC_VIEWER_URL
typebot-viewer_1   | env.sh done
typebot-viewer_1   | 
typebot-viewer_1   | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-viewer_1   | 
typebot-viewer_1   | ✔ Generated Prisma Client (5.0.0 | library) to ./node_modules/.pnpm/@prisma+client@5.0.0_prisma@5.0.0/node_modules/@prisma/client in 5.49s
typebot-viewer_1   | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-viewer_1   | ```
typebot-viewer_1   | import { PrismaClient } from '@prisma/client'
typebot-viewer_1   | const prisma = new PrismaClient()
typebot-builder_1  | You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
typebot-builder_1  | ```
typebot-builder_1  | import { PrismaClient } from '@prisma/client'
typebot-builder_1  | const prisma = new PrismaClient()
typebot-builder_1  | ```
typebot-builder_1  | Waiting 5s for db to be ready...
typebot-builder_1  | Prisma schema loaded from packages/prisma/postgresql/schema.prisma
typebot-builder_1  | Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"
typebot-builder_1  | 
typebot-builder_1  | 54 migrations found in prisma/migrations
typebot-builder_1  | 
typebot-builder_1  | 
typebot-builder_1  | No pending migrations to apply.
typebot-builder_1  | ┌─────────────────────────────────────────────────────────┐
typebot-builder_1  | │  Update available 5.0.0 -> 5.1.1                        │
typebot-builder_1  | │  Run the following to update                            │
typebot-builder_1  | │    npm i --save-dev prisma@latest                       │
typebot-builder_1  | │    npm i @prisma/client@latest                          │
typebot-builder_1  | └─────────────────────────────────────────────────────────┘
typebot-builder_1  | - info Loaded env from /app/apps/builder/.env.production
typebot-builder_1  | Listening on port 3000 url: http://579a7a01b9e3:3000
typebot-builder_1  | - info Loaded env from /app/apps/builder/.env.production
typebot-builder_1  | (node:172) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
typebot-builder_1  | 
typebot-builder_1  | Please migrate your code to use AWS SDK for JavaScript (v3).
typebot-builder_1  | For more information, check the migration guide at https://a.co/7PzMCcy
typebot-builder_1  | (Use `node --trace-warnings ...` to show where the warning was created)
typebot-viewer_1   | ```
typebot-viewer_1   | - info Loaded env from /app/apps/viewer/.env.production
typebot-viewer_1   | Listening on port 3000 url: http://7ca8124f66fe:3000
typebot-db_1       | 
typebot-db_1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
typebot-db_1       | 
typebot-db_1       | 2023-08-13 13:30:55.399 UTC [1] LOG:  starting PostgreSQL 13.11 (Debian 13.11-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
typebot-db_1       | 2023-08-13 13:30:55.400 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
typebot-db_1       | 2023-08-13 13:30:55.400 UTC [1] LOG:  listening on IPv6 address "::", port 5432
typebot-db_1       | 2023-08-13 13:30:55.420 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
typebot-db_1       | 2023-08-13 13:30:55.475 UTC [26] LOG:  database system was shut down at 2023-08-13 13:30:30 UTC
typebot-db_1       | 2023-08-13 13:30:55.534 UTC [1] LOG:  database system is ready to accept connections
typebot-db_1       | 2023-08-13 13:31:28.244 UTC [33] LOG:  could not receive data from client: Connection reset by peer`
this log 
and this is my confing
`version: '3.3'
services:
  typebot-db:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot
  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    # See https://docs.typebot.io/self-hosting/configuration/builder for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXTAUTH_URL=xxxxxxxxxxxxxxxxxxxx:8080
      - NEXT_PUBLIC_VIEWER_URL=xxxxxxxxxxxxxxx::8081
      - ENCRYPTION_SECRET=K+Bar660Ofaec7v1jHC25tAn3l2b7c81
      - ADMIN_EMAIL=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - SMTP_USERNAME=xxxxxxxxxxxxxxxxxxxxx
      - SMTP_PASSWORD=xxxxxxxxxxxxxx
      - SMTP_HOST=xxxxxxxxxxxxxx
      - SMTP_PORT=465
      - NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@xxxxxxxxxxxxxx.com>
      - SMTP_SECURE=true
  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '8081:3000'
    # See https://docs.typebot.io/self-hosting/configuration/viewer for more configuration options
    environment:
      - DATABASE_URL=postgresql://postgres:typebot@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=xxxxxxxxxxxxxxxx:8081
      - ENCRYPTION_SECRET=K+Bar660Ofaec7v1jHC25tAn3l2b7c81
      - NEXTAUTH_URL=xxxxxxxxxxxxx:8080
      - SMTP_USERNAME=xxxxxxxxxxxx
      - SMTP_PASSWORD=xxxxxxxxxxxxxx
      - SMTP_HOST=xxxxxxxxxxxxxxxxxx
      - SMTP_PORT=465
      - NEXT_PUBLIC_SMTP_FROM='Typebot Notifications' <notifications@xxxxxxxxxxxxx.com>
      - SMTP_SECURE=true
volumes:
  db_data:
`

**Comment by baptisteArno** [comment]
Can you format the text correctly? We can't read this.... 😅

**Comment by baptisteArno** [comment]
We can't see anything related to SMTP email error here…

Do you get an error on the client side? What does it say?

**Comment by baptisteArno** [comment]
Check the logs on your SMTP service, does it say anything?
