### ISSUE TITLE
Bug:  Button - Dynamic data not working

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#683]
The dynamic data option doesn't seem to be working for me when creating a new bot, in the latest version.

For testing, i've set a variable like this:

<img width="563" alt="image" src="https://github.com/baptisteArno/typebot.io/assets/64059154/4e4cfa4f-bdbc-4eb2-9640-0a30de06cf40">

Note: this works fine if i set "Execute on client" = `false`;

**Comment by baptisteArno** [comment]
I managed to reproduce the bug. Thank you for reporting it!

**Comment by baptisteArno** [comment]
Fixed in ed77f5d1244cc35d71ac5897c6617f93b94f5a58
