### ISSUE TITLE
fonts via bunny CDN / JS via jsdelivr

### ISSUE THREAD

**Issue by github-luckow-org** [baptisteArno/typebot.io#684]
Cloudron user here.

I use the Typebot app from the official Cloudron store. Thanks for the great app and the easy installation (with one click) :)

Currently, I am looking for a solution to not use the fonts via fonts.bunny.net. Is there any way to self-host the fonts in the templates?
Same for the web.js via cdn.jsdelivr.net

For me, it is important to decide if and if so, where to store the files for web applications.

**Comment by github-luckow-org** [comment]
I will collect my findings on this  :)

Same for the invitation banner served from https://typebot.s3.eu-west-3.amazonaws.com/assets/invitation-banner.png

**Comment by baptisteArno** [comment]
Ok I understand. That's a good point! I'll see what we can integrate to the apps directly so that self-hosters are not depending on external resources

**Comment by baptisteArno** [comment]
Will be possible with https://github.com/baptisteArno/typebot.io/issues/1249
