### ISSUE TITLE
Reset variables before restart of the bot

### ISSUE THREAD

**Issue by mihha** [baptisteArno/typebot.io#69]
I have a fairly complex bot, where in some point, I offer to restart the QA process 

Before the restart, I need to clear the variables, so the visitor can type new answers, without the need to delete old answers first

I tried to "Set variables" and select only variables, but that doesn't work because if you don't put anything in the "Value" field, Typebot doesn't take this into account at all

![image](https://user-images.githubusercontent.com/3791124/170669238-c2a4cd37-3b5a-457f-81df-f0890a3e0016.png)

I also tried to "Set variables" and put the one space in the "Value" field. In that case, when the bot is restarted, you get "0" in the question field

![image](https://user-images.githubusercontent.com/3791124/170669802-30a28632-5cc0-4608-83da-d6c8adf49bef.png)

Can you tell me is it possible to reset the variable to be empty?

**Comment by baptisteArno** [comment]
It will be available in the next stable version.

If you need it now, you can however pull the frequently updated docker images with the tag `main`: `baptistearno/typebot-builder:main` and `baptistearno/typebot-viewer:main`
