### ISSUE TITLE
Typebot Sends Questions Generated by OpenAI to Webhook Separated by Commas

### ISSUE THREAD

**Issue by lpadula** [baptisteArno/typebot.io#693]
Typebot is currently sending questions generated by OpenAI to the webhook using commas as separators. This approach complicates the matching process with user answers, especially when those answers also contain commas.

**Example:** 

"AI questions": { "Great! Could you provide more details about the specific software development needs you have?,Understood. In terms of software development, are you looking to build a web application, mobile app, or desktop software?,That’s alright. To help narrow down your needs, could you let me know what problem or objective you are trying to solve through software development?,That’s alright. How about we explore the nature of your business or industry? Understanding your domain can give us insights into potential software development solutions that could benefit your organization. Could you please provide some context about your company or the industry you operate in?" },
"User reponse": { no ,dont know ,dont know,no},

**Comment by baptisteArno** [comment]
Yep, that's not good!

**Comment by baptisteArno** [comment]
I will fix it with #687
