### ISSUE TITLE
Button item is dragged when we try to select the text inside

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#697]

**Comment by baptisteArno** [comment]
We can't select text in draggable items:

https://github.com/baptisteArno/typebot.io/assets/16015833/42cff945-6d98-4fff-8493-3b640d9a7fdf

**Comment by subhajit20** [comment]
@baptisteArno I have reproduced the bug.
Would like to work on this, can you assign this issue to me ?

**Comment by baptisteArno** [comment]
Awesome, thank you so much 🙏

**Comment by subhajit20** [comment]
> Awesome, thank you so much 🙏

One more thing, can you tell me in which file I have check ? Would be so helpful then

**Comment by baptisteArno** [comment]
Do you need help with anything?

**Comment by subhajit20** [comment]
@baptisteArno Hey sorry! Can you specify the exact place where I have to change?
