### ISSUE TITLE
DB reference in docker-compose.yml

### ISSUE THREAD

**Issue by teq-dev** [baptisteArno/typebot.io#70]
This should be `typebot-db`

https://github.com/baptisteArno/typebot.io/blob/30d36b9a09647e3a259442f7c3342b690f3a0913/docker-compose.yml#L19

**Comment by baptisteArno** [comment]
Do you feel like you could create a PR for this? (I would love to count you as a repo contributor in the main page since you are very implicated 🥰)

**Comment by jsonsmth** [comment]
> Do you feel like you could create a PR for this? (I would love to count you as a repo contributor in the main page since you are very implicated 🥰)

Sure. Just sent under my main account.
