### ISSUE TITLE
npm install @typebot.io/nextjs

### ISSUE THREAD

**Issue by macshinaider** [baptisteArno/typebot.io#706]
![image](https://github.com/baptisteArno/typebot.io/assets/15176165/8734f50e-da51-402c-8714-104fa107a981)

I can't download the lib has anyone had this problem?

![image](https://github.com/baptisteArno/typebot.io/assets/15176165/e24b5fb4-f2c3-4066-b2af-42cf968896a0)

**Comment by baptisteArno** [comment]
Maybe in your shell, the @ must be escaped.

Can you try `npm install \@typebot.io/nextjs`?

**Comment by macshinaider** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/15176165/a1eef409-ed76-48a6-a186-3bfc62fdd805)

**Comment by baptisteArno** [comment]
Oh there you go: https://stackoverflow.com/questions/37834613/npm-scoped-packages-and-powershell

replace \ with `

**Comment by macshinaider** [comment]
![image](https://github.com/baptisteArno/typebot.io/assets/15176165/d1bc10b0-b917-4f74-94f0-6b217f64005e)

**Comment by baptisteArno** [comment]
Does your project have `next` installed?
