### ISSUE TITLE
Docker Image baptistearno/typebot-builder and baptistearno/typebot-viewer ARM64

### ISSUE THREAD

**Issue by willph** [baptisteArno/typebot.io#716]
Hi, how are you?

Is there image in docker hub for ARM64 architecture?

presented this error

Using Docker version 20.10.25, build 20.10.25-0ubuntu1~20.04.1

**Architecture:** VPS Ubuntu 20.04 ARM64 

![image](https://github.com/baptisteArno/typebot.io/assets/17226802/ce162e6f-0e27-4b24-bd2c-02e2783826ec)

**Comment by willph** [comment]
Thanks for the answer.

Do you have any predictions if you would ever have this support?

Em seg., 28 de ago. de 2023 10:37, Baptiste Arnaud ***@***.***>
escreveu:

**Comment by willph** [comment]
> hat is strange though. I can build and run the images on my Mac M1. (ARM64 arch)
> 
> Any idea what is different with yours?

I used the docker-compose that I had on this page https://docs.typebot.io/self-hosting/docker, but now it gives a 404 error

Then I saw that he used these images of docker hub https://hub.docker.com/r/baptistearno/typebot-viewer and https://hub.docker.com/r/baptistearno/typebot-builder/ and all two are for ARCH amd64.

![image](https://github.com/baptisteArno/typebot.io/assets/17226802/9f0cd2fa-70f7-41e3-bdd6-280b904d042d)

**Comment by willph** [comment]
Did have any changes in the docs regarding installation via docker?

It's different from when I accessed

and the link https://raw.githubusercontent.com/baptisteArno/typebot.io/latest/.env.example error 404: Not Found

**Comment by willph** [comment]
ARM64 VPS of hetzner

Em seg., 28 de ago. de 2023 11:01, Baptiste Arnaud ***@***.***>
escreveu:

**Comment by willph** [comment]
> So in theory that should work?

I managed to install using of Elestio image. As you can see in the image that appears for both AMD and ARM as well.


![image](https://github.com/baptisteArno/typebot.io/assets/17226802/ce645ee5-1ab8-47cb-8db4-d4ca498869ce)


Unfortunately with the official image you can't, there was that error in the photo that I posted here at the beginning

**Comment by baptisteArno** [comment]
Ok I see, I can enable the build for that arch 👍

**Comment by baptisteArno** [comment]
For reference, I can get inspiration from: https://github.com/plausible/analytics/blob/master/.github/workflows/build-public-images.yml

**Comment by willph** [comment]
> > > Então, em teoria, isso deveria funcionar?
> > 
> > 
> > Consegui instalar usando a imagem do Elestio. Como você pode ver na imagem que aparece tanto para AMD quanto para ARM.
> > ![imagem](https://user-images.githubusercontent.com/17226802/264165480-ce645ee5-1ab8-47cb-8db4-d4ca498869ce.png)
> > Infelizmente com a imagem oficial não dá, deu aquele erro na foto que postei aqui no começo
> 
> Hello @willph, could you please explain to me how to install with the Elest.io image?

I used docker-compose.yml from here https://docs.typebot.io/self-hosting/guides/docker

I changed the images, I used by Elestio

baptistearno/typebot-builder:latest -> docker pull elestio/typebot-builder:latest

baptistearno/typebot-viewer:latest -> docker pull elestio/typebot-viewer:latest

**Comment by willph** [comment]
> For reference, I can get inspiration from: https://github.com/plausible/analytics/blob/master/.github/workflows/build-public-images.yml

Thanks a lot for the help.
I will be waiting anxiously

**Comment by willph** [comment]
[roccianetto](https://github.com/roccianetto) 

You don't even need to use the image of Elestio, just use git to clone the repository and use the docker-compose.build.yml file and to configure it correctly according to the documentation itself and at the end run the command docker-compose up - d

Basically I did it like this

```
ARM64 Install Typebot

git clone https://github.com/baptisteArno/typebot.io

cd typebot.io

git checkout latest

cp docker-compose.yml docker-compose.yml.backup

cp docker-compose.build.yml docker-compose.yml

nano docker-compose.yml

add S3 Storage doc https://docs.typebot.io/self-hosting/guides/docker#s3-storage

cp .env.example .env

nano .env

docker-compose up -d
```

**NOTE:**

Remembering that you need to configure the details of the .env file and docker-compose.yml.
