### ISSUE TITLE
Document release cycle

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#717]
Hey @baptisteArno 

Currently, releases are made on what seems like a random time basis. More information about how you decide to make a new release would be appreciated.

For self-hosters sake of easier maintenance and to facilitate development, a release cycle should be introduced.

Whether it is to make a new release every X weeks, months, etc.

We can take the recent `2.16.0` release as an example. Since that one, a lot of commits have been made, but no new release.

**Comment by baptisteArno** [comment]
Indeed, I mention it here briefly: https://docs.typebot.io/self-hosting/guides/docker#update-typebot

It is now a monthly release. Every 1st.

But I'm ok to ship more of them during the month if I'm fixing critical issues!
