### ISSUE TITLE
Wrong CSS on iFrame embbed template

### ISSUE THREAD

**Issue by danielpantu** [baptisteArno/typebot.io#726]
When you click on the iFrame option for embedding your TypeBot you get the following code:
`<iframe src="https://<EXAMPLE-URL>" style="border: none; width='100%'; height='600px'"></iframe>`

But when I test it on websites it gets the wrong appearance. I think this happens because the CSS on this element should be like this:
`<iframe  src="https://<EXAMPLE-URL>" style="border: none; width: 100%; height: 600px"></iframe>`

Considering there is no other reason I'll be happy to fix that. Otherwise just let me know why it's written this way.

**Comment by baptisteArno** [comment]
That's definitely a typo! Thank you for the report 🙏
