### ISSUE TITLE
Integration with Zemantic AI

### ISSUE THREAD

**Issue by ezynda3** [baptisteArno/typebot.io#741]
Hi,

Would you be willing to accept a block that integrates directly with https://zemantic.ai? It has an API feature that allows you to do question answering with documents using AI. I would be willing to code and submit a PR for this integration.

Cheers!

**Comment by baptisteArno** [comment]
Sure!!

**Comment by ShaheerCH** [comment]
@ezynda3 hello. You see I'm also working on an integration but I'm having issues with initial setup and configuration. Is it possible to arrange a zoom meet and discuss it further.

**Comment by ezynda3** [comment]
@ShaheerCH I'm new to this repo, so I'm afraid I don't know enough to help anyone else.
