### ISSUE TITLE
Failed to send the reply : variable stays empty when it is update with button

### ISSUE THREAD

**Issue by chrisagon** [baptisteArno/typebot.io#748]
Hello,
I have an error after a condition I try to update a variable with 3 buttons and the bot Failed to send the reply : and my variable stays empty :
![erreur_typebot1](https://github.com/baptisteArno/typebot.io/assets/4162318/a2d019f0-c9e9-402c-8324-75e02aba4116)
Here is the export of my typebot :
[typebot-export-bxp-onboarding2-glmstbq.zip](https://github.com/baptisteArno/typebot.io/files/12486904/typebot-export-bxp-onboarding2-glmstbq.zip)
I try to change the name of the variable, to change the condition but I still have the error. I don't understand what's happen with this step or this variable.
If somebody can explain what's happen with my bot...

**Comment by baptisteArno** [comment]
It seems you are introducing an infinite loop with Jump blocks.

Recap role => Aller fin Onboarding => Recap role
