### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by geniusshiun** [baptisteArno/typebot.io#75]
I used docker-compose.yml but viewer is failed with this message："standard_init_linux.go:228: exec user process caused: exec format error".
But if I change viewer image from build. The issue is solved.

**Comment by baptisteArno** [comment]
This error means that the CPU architecture of your VPS is incompatible with the images. Both images only work on `linux/amd64` arch.

For example, you can't run Typebot on a Raspberry Pi.
