### ISSUE TITLE
Error! Couldn't initiate the chat.

### ISSUE THREAD

**Issue by MarcolaCdd** [baptisteArno/typebot.io#753]
PLS I NEED HELP

it seems that after updating the type bot to version 20, it is getting this error, can anyone help me?
![image](https://github.com/baptisteArno/typebot.io/assets/124307074/5a11bc67-e6e6-420b-9b9d-4285ec5550e0)

**Comment by MarcolaCdd** [comment]
I have already reinstalled typebot several times, but it continues like this. I really don't know what to do. It was working fine before!

**Comment by kadinho120** [comment]
same here on viewer.

**Comment by baptisteArno** [comment]
Can you share a URL so that I can check what's wrong?

**Comment by kadinho120** [comment]
> Can you share a URL so that I can check what's wrong?

https://chat.desconto.cloud/smm-seguidores-eckgnkh

**Comment by baptisteArno** [comment]
It's not the same error as OP's:

<img width="530" alt="CleanShot 2023-09-02 at 15 08 48@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/a812622f-3ccd-4363-b692-586ae04502de">

Can you create another issue with your server logs? There should be an error displayed.

**Comment by kadinho120** [comment]
> It's not the same error as OP's:
> 
> <img alt="CleanShot 2023-09-02 at 15 08 48@2x" width="530" src="https://user-images.githubusercontent.com/16015833/265206610-a812622f-3ccd-4363-b692-586ae04502de.png">
> Can you create another issue with your server logs? There should be an error displayed.

That's the error that shows when try to access de url. The error "couldn't initiate the chat" appears in the bot preview, on builder.

Can i give you access to the builder? Just inform the email

**Comment by baptisteArno** [comment]
Can't guess anything without the server logs. Please provide them (`docker-compose logs`).

**Comment by MarcolaCdd** [comment]
LET'S GO: CHAT ERROR DOES NOT START HOW TO SOLVE IT!

First you go to your docker compose file

You will search this for "typebot-viewer:"
(without quotes)

you will see that in this part of the typebot viewer, below it will have some commands like DATABASE_URL and NEXT_PUBLIC_VIEWER_URL! this is where you will paste this code

you will click to enter, it will open a new line and you will put this code

 - NEXT_PUBLIC_VIEWER_URL=http://bot.yourdomain.com (in this case you will use a URL that you use to ENTER your bots panel, where you configure the resources)

now you are going to save the file and you are going to play the command

CD type

docker compose up -d

![image](https://github.com/baptisteArno/typebot.io/assets/124307074/3de8cc04-ad45-44b4-baef-b00766a10058)
