### ISSUE TITLE
Main page is scrollable when popup is visible

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#763]
When a typebot is embedded as a Popup and the popup is visible, the page behind is still scrollable.

To embed a Popup, see: https://docs.typebot.io/embed/html-javascript#popup

**Comment by anikdhabal** [comment]
@baptisteArno Could you please share a picture?

**Comment by rishi-raj-jain** [comment]
@baptisteArno which `apps` https://github.com/baptisteArno/typebot.io/tree/main/apps is this regarding?

**Comment by baptisteArno** [comment]
> @baptisteArno which `apps` https://github.com/baptisteArno/typebot.io/tree/main/apps is this regarding?

Updated issue description

**Comment by rishi-raj-jain** [comment]
Thank you!
