### ISSUE TITLE
File upload block should upload files on a private URL

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#772]
For now every file are uploaded in the public folder of the S3 storage.

It would be nice to upload the files from the bot submissions in a private folder.

**Comment by Lanhild** [comment]
@baptisteArno +1. This is essential for any bots that can be potentially used to collect CVs, etc.

**Comment by baptisteArno** [comment]
Done with https://github.com/baptisteArno/typebot.io/pull/1196
