### ISSUE TITLE
Typebot 2.17.1 build target only for linux/arm64 (broken latest images for linux/amd64)

### ISSUE THREAD

**Issue by luizeof** [baptisteArno/typebot.io#776]
Hello @baptisteArno ;)

Today's release of version 2.17.1 only has images for the linux/arm64 architecture.

This broken `latest`, `main` and `2` tags.

Could you release the builder and viewer images for linux/amd64 as well?

![image](https://github.com/baptisteArno/typebot.io/assets/257004/758ee0b7-e2a2-42a5-a244-c14b98ebe38b)

thank you very much for your time ;)

**Comment by albertogodinho** [comment]
please!!

**Comment by AntonionniGomes** [comment]
deu ruim!!!

**Comment by guilhermejansen** [comment]
Ajuda ai @baptisteArno por favor, seu gostoso!

**Comment by infograps** [comment]
kkkkkkkkkkkkkkkkkkkkkkk

**Comment by infograps** [comment]
por favor

**Comment by infograps** [comment]
please

**Comment by baptisteArno** [comment]
You can pull 2.17.2 🙏
