### ISSUE TITLE
Send chats limit alert emails: All jobs have failed - Send chats limit alert emails #994

### ISSUE THREAD

**Issue by jdefranco** [baptisteArno/typebot.io#788]
There is an error and multiple warnings related to a failed attempt to download an action from the repository. 

The specific error indicates that the service is unavailable (HTTP status code 503). After each failed attempt, there's a recommendation to wait for a certain amount of time before retrying the download. 

Additionally, an email notification from GitHub indicates that the "Send chats limit alert emails" workflow for the repository. 

The email was sent on Sep 5, 2023, at 12:11 AM.

This error has been repeating for weeks everyday to my email from github

**Comment by baptisteArno** [comment]
I suggest you disabled the forked Github workflow (https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow).

They are only relevant for Typebot Cloud 👍
