### ISSUE TITLE
Error! Couldn't initiate the chat.

### ISSUE THREAD

**Issue by mateuskee** [baptisteArno/typebot.io#791]
Hello, I'm getting the following error when trying to view the flow Error! Couldn't initiate the chat.
I configured the NEXTAUTH_URL and NEXT_PUBLIC_VIEWER_URL variables with my url login and url chat domain respectively.

In the console of the page I get the error:
Failed to load resource: net::ERR_CONNECTION_REFUSED
2977.bd721ea4931fc62c.js:1 TypeError: Fetch failed

I am using railway vps, I installed typebot via template.

Also, when accessing the public page, I get the following error:
Internal Server Error.

**Comment by baptisteArno** [comment]
We need the server logs: `docker-compose logs`.

**Comment by mateuskee** [comment]
Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83
typebot-viewer_1   | Error: Invalid environment variables
typebot-viewer_1   |     at T.m (/app/apps/viewer/.next/server/chunks/321.js:12094:575)
typebot-viewer_1   |     at T (/app/apps/viewer/.next/server/chunks/321.js:12094:765)
typebot-viewer_1   |     at P (/app/apps/viewer/.next/server/chunks/321.js:12094:1156)
typebot-viewer_1   |     at /app/apps/viewer/.next/server/chunks/378.js:9261:83

**Comment by mateuskee** [comment]
A thousand apologies, it was an extra letter that didn't have encryption, now it's working.

**Comment by wesleysaraujo** [comment]
On my case, needed insert variable NEXTAUTH_URL on typebot-viewer container. This variable is the URL of Builder.
