### ISSUE TITLE
Bug a flow with jump

### ISSUE THREAD

**Issue by cbalbinos** [baptisteArno/typebot.io#802]
Flow with Jump in Typebot with version 2.17.2 is showing **Error! Couldn't initiate the chat.**

**Comment by paulobeneton** [comment]
This also happens here.

It does not allow viewing the bot.

**Comment by CptPlastic** [comment]
I just tested this and its not happening to me with jump.

https://nsncorp.app.nsnmindlabs.com/my-typebot-uux045v

![Jump](https://github.com/baptisteArno/typebot.io/assets/1010444/fd619b29-485d-4cd0-91b1-5e21490bfe23)

**Comment by baptisteArno** [comment]
It is only happening if you add a jump block? Can you share a minimal reproduction of the bug?

**Comment by baptisteArno** [comment]
It is only happening if you add a jump block? Can you share a minimal reproduction of the bug?

**Comment by cbalbinos** [comment]
Hi @baptisteArno 

The problem also occurred when adding buttons, I uninstalled Typebot and today I installed a new one with 2.17.2 and now it is no longer showing the Error message! Couldn't initiate the chat
