### ISSUE TITLE
Possible bug with search results from a dynamic list

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#803]
Sometimes the links of the search results do not match the the actual block you click. IE they are the wrong selection. Other times the links when clicked do not load. I'm loading the results from a google sheet.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/b272c6ca-d2be-418d-a421-fe8cae54971a)

If I do not have searchable turned on everything works just fine.

![image](https://github.com/baptisteArno/typebot.io/assets/1010444/078fdb03-e38a-40ce-87be-cd4a2a8f0590)

**Comment by baptisteArno** [comment]
Is there anything wrong in the first screenshot?

**Comment by CptPlastic** [comment]
That was the filtered list of you don't have "is searchable" on it never has an issue it's like the links are moved and it's odd because sometimes it works but seems to do it when there are more then one result returned

**Comment by baptisteArno** [comment]
Can you provide a simple reproduction of the bug 🙏

**Comment by CptPlastic** [comment]
Sure, I set up new one just to see if it was something I did.
So I have a list of states in a google sheet. The bug comes in when you search and have more then one result you cant click on them. You also have to search with the exact case if the result is New Mexico and you search new Mexico it wont be clickable. 

![TestGif2](https://github.com/baptisteArno/typebot.io/assets/1010444/cc4a92bf-4764-4643-9cd7-27d2b85e8518)

**Comment by CptPlastic** [comment]
Further testing it looks like its do to how the button loads. Looks like it could be an easy fix if the search reloads on the same screen button works.
![TestGif2](https://github.com/baptisteArno/typebot.io/assets/1010444/10843ae9-a9da-43ed-bccf-cfba2f221da6)

**Comment by baptisteArno** [comment]
Thank you, I managed to reproduce!
