### ISSUE TITLE
The Public S3 URL variable does not work

### ISSUE THREAD

**Issue by rmarquess** [baptisteArno/typebot.io#812]
Hello,

I'm using storage where I need to define the public url which is different from **S3_ENDPOINT** using docker.

When I inform **S3_PUBLIC_CUSTOM_DOMAIN** the URL does not return, only the **S3_ENDPOINT**.

The upload is performed normally but it appears that the variable does not return the customized public domain.

**Comment by rmarquess** [comment]
Okay, I'll share it below!

I have been using Cloudflare's R2, the entire upload process is working correctly. After uploading, it does not return the public domain that was defined in Cloudflare and entered in the variable **S3_PUBLIC_CUSTOM_DOMAIN** to access the file publicly

I'm going to leave the settings below my docker env and a video showing the problem, I don't know if I'm doing something wrong.

![typebot S3 R2 Cloudflare](https://github.com/baptisteArno/typebot.io/assets/23084429/6b3e651a-5828-433c-b035-e170defa380e)


https://github.com/baptisteArno/typebot.io/assets/23084429/550af408-343c-429e-89f9-63cc2b4dc507

**Comment by baptisteArno** [comment]
Hey, sorry for the confusion but the commit introducing the public custom domain URL is still not released! You need to wait the next release, the 1st of next month

**Comment by murillodominguez** [comment]
Hey @rmarquess i'm trying to use Cloudflare R2 for typebot storage but i can't figure out why it's not working. The error it displays to me is the following:

<img width="406" height="145" alt="Image" src="https://github.com/user-attachments/assets/45afecb2-61cf-40b8-8bdb-a31e76e6c04b" />

I'm using the same cors configuration as the documentation advises.

If you managed to successfully update files to your bucket, could you please help me?

**Comment by luispimenta** [comment]
@murillodominguez did you solve this?

**Comment by murillodominguez** [comment]
> [@murillodominguez](https://github.com/murillodominguez) did you solve this?

No, i didn't manage to solve this problem. I was forced to migrate my storage to AWS S3. It seems Typebot has no compatibility with Cloudflare R2 Storage. There are other alternatives such as MinIO and DigitalOcean Spaces that are present in typebot official documentation [https://docs.typebot.io/self-hosting/guides/s3](url)
