### ISSUE TITLE
ERROR STRIPE IN TYPEBOT

### ISSUE THREAD

**Issue by MarcolaCdd** [baptisteArno/typebot.io#816]
I'm having an error when paying via stripe, where when I click on the button to redirect me to payment it says that an error occurred "An error occurred

Failed to send the reply"
![image](https://github.com/baptisteArno/typebot.io/assets/124307074/dfa9ac00-cdae-4b01-b83f-b171dd66399a)

then comes this print
![image](https://github.com/baptisteArno/typebot.io/assets/124307074/bc5868e8-425b-41a0-b7e2-cca1553ab173)

{
  "message": "The operation failed for an operation-specific reason",
  "code": "INTERNAL_SERVER_ERROR"
}

**Comment by baptisteArno** [comment]
Have you correctly configured the block?
