### ISSUE TITLE
Error uploading, SignatureDoesNotMatch

### ISSUE THREAD

**Issue by moraisamilton** [baptisteArno/typebot.io#817]
Hello, I am using this link to make the settings
https://docs.typebot.io/self-hosting/configuration

I configured the policy on the minio for access this way, but I'm getting a "SignatureDoesNotMatch" error

Here is the minio configuration:

 
```javascript
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "PublicRead",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::typebot/public/*"
            ]
        },
        {
            "Sid": "CORSPut",
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::typebot/public/*"
            ]
        }
    ]
}
``` 

Return message follows

XML

```html
<Error>
<script/>
<script/>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<Key>public/typebots/clmii3jri0005qfegxrtfb2nb/hostAvatar</Key>
<BucketName>typebot</BucketName>
<Resource>/typebot/public/typebots/clmii3jri0005qfegxrtfb2nb/hostAvatar</Resource>
<RequestId>1784D921360DDA82</RequestId>
<HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId>
</Error>
``` 

When I send the request below through Postman, changing `image%2Fpng` to `image/png` it works

http://192.168.0.201:9000/typebot/public/typebots/clmii3jri0005qfegxrtfb2nb/hostAvatar?Content-Type=image%2Fpng&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QygEd1uIWG2VUtm0bvys/20230914%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230914T192750Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=0fd3659b4c7f99b7ffe7b8fb26efafe7a16e9c073c08c767f861ace41b89ac61

Can anyone help me?

**Comment by baptisteArno** [comment]
Can you share your docker config and your environment variables?

**Comment by moraisamilton** [comment]
I managed to solve the problem. In fact, I was using the domain with `S3_ENDPOINT='https://minioapi.mydomain.com.br'`, and the correct configuration was the following:

```
S3_ACCESS_KEY=ddsdsdsdsdsds
S3_SECRET_KEY=sdsdsdsdsddsdsds
S3_BUCKET=typebot
S3_PORT=443
S3_ENDPOINT='minioapi.mydomain.com.br'
S3_SSL=true
```

I also adjusted this configuration in the Minio proxy:

```
underscores_in_headers off;
merge_slashes off;
```
