### ISSUE TITLE
Collect WA start keyword if flow starts with input block

### ISSUE THREAD

**Issue by jeffsystem** [baptisteArno/typebot.io#824]
Dear, when the user sends the first message and the flow needs to be started by a certain keyword, the robot only starts when it sends this message twice, as in the image below.

From what I understand, the first message is at the beginning and the second is interpreted by the collector.

Is there already a way to fix this?

![268545103-6fef6597-f834-479d-825b-2be1a3ff42c2](https://github.com/baptisteArno/typebot.io/assets/39931647/25fde5e1-522a-412e-8df9-73c8677df97d)

This is my flow that has a problem.

I'm using it integrated with WhatsApp, but this problem is in the first message that typebot doesn't recognize.

![268545107-e153ce82-8e1a-4d3f-886f-3c5444845d8e](https://github.com/baptisteArno/typebot.io/assets/39931647/48824dd3-482d-4e31-933e-b3aceef56486)

**Comment by baptisteArno** [comment]
Hmmm that's a good point.

WhatsApp trigger and the first question is 2 different things for now. But that would be nice to be able to collect the trigger word

**Comment by DIO85-git** [comment]
Please, solve It!

**Comment by BrunoFrost** [comment]
I have the same problem. Could you fix it?

**Comment by NLSARCOS** [comment]
Please, solve It!

**Comment by baptisteArno** [comment]
You need to wait for the next release on the 1st of October

**Comment by agencia904** [comment]
Hello! Has this been resolved with the latest release?

**Comment by baptisteArno** [comment]
Yes, `2.18.0`.
