### ISSUE TITLE
ERROR "Cannot set properties of null (setting 'innerText')"

### ISSUE THREAD

**Issue by gabzitto** [baptisteArno/typebot.io#825]
Error in React template code:

import { Standard } from "@typebot.io/react";

const TypebotIntegrationReact = ({code}) => {
  console.log('teste')
  return (
    <Standard
    typebot="arthur"
      style={{ width: "undefined", height: "100vh" }}
    />
  );
};
export default TypebotIntegrationReact;

Returns this error infinitely during the chat:

Uncaught runtime errors:
×
ERROR
Cannot set properties of null (setting 'innerText')
TypeError: Cannot set properties of null (setting 'innerText')
    at <anonymous>:19:26
ERROR
Cannot set properties of null (setting 'innerText')
TypeError: Cannot set properties of null (setting 'innerText')
    at <anonymous>:19:26

**Comment by baptisteArno** [comment]
This error is most likely due to some code you added in the Head section (Settings > Metadata). It's out of Typebot scope.
