### ISSUE TITLE
getting TCP client error on newly created integration

### ISSUE THREAD

**Issue by Utkarshkapil** [baptisteArno/typebot.io#831]
TRPCClientError: [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "typebot",
      "groups",
      2,
      "blocks",
      0,
      "options"
    ],
    "message": "Required"
  }
]

**Comment by baptisteArno** [comment]
The error should be self-explanatory, you are trying to parse a typebot that does not have an `options` field which is required.
