### ISSUE TITLE
CAN'T INSTALL ANYMORE

### ISSUE THREAD

**Issue by 7figurefortune** [baptisteArno/typebot.io#832]
hello ive been trying to install a copy of this on my server and am having alot of trouble!. Ive hired some developers as well and something has broken inside your program sir. My dev says its an upstream? or upstram issue. But we can no longer use this app.

**Comment by baptisteArno** [comment]
Tell your developers to create an issue here with more details please 🙏

**Comment by 7figurefortune** [comment]
Hey baptiste! This is the issue/errors im getting when trying to use vercel to install. Can you help a brother out? I followed the step by step instructions added all the proper variables but it keeps stopping me:/

![Screenshot 2023-09-26 5 40 00 PM](https://github.com/baptisteArno/typebot.io/assets/80868208/44842a69-e2f6-4d07-886c-2ee0c0212736)

**Comment by 7figurefortune** [comment]
is this correct..changing the "build and output settings to pnpm db:migrate & pnpm turbo build --filter=builder instead of what they were originally?

**Comment by 7figurefortune** [comment]
![Screenshot 2023-09-26 5 58 27 PM](https://github.com/baptisteArno/typebot.io/assets/80868208/a99e2c27-34be-4338-a147-5bd4501f8247)

**Comment by 7figurefortune** [comment]
Tried many different things:/ cant seem to win sir

**Comment by baptisteArno** [comment]
https://docs.typebot.io/self-hosting/guides/vercel

**Comment by 7figurefortune** [comment]
This is the thread bro...Ive added my images here AND followed those
directions several times. They do not work as of Sept. 26 2023.

**Comment by 7figurefortune** [comment]
![Screenshot 2023-09-28 9 18 34 AM](https://github.com/baptisteArno/typebot.io/assets/80868208/57dcdb01-1822-4763-8f80-6688da7e4cbd)
![Screenshot 2023-09-28 9 18 38 AM](https://github.com/baptisteArno/typebot.io/assets/80868208/d45d3bf7-0644-41a8-80cd-530975e33b0c)

**Comment by 7figurefortune** [comment]
i copied and pasted from the instructions...so i dont know why they would be wrong

**Comment by 7figurefortune** [comment]
![Screenshot 2023-09-28 9 20 36 AM](https://github.com/baptisteArno/typebot.io/assets/80868208/d138f09a-9c48-4dcf-be4a-d5ab68490497)

**Comment by 7figurefortune** [comment]
those are the commands and ill redeploy and send new error, if any

**Comment by baptisteArno** [comment]
Share the env non-sensitive variable values please 🙏 This error message means one of the variable is invalid. Maybe the encryption secret does not have the right length?

**Comment by vinayakg** [comment]
```` server: {
    NODE_ENV: z.enum(['development', 'production', 'test']).optional(),
    DATABASE_URL: z
      .string()
      .url()
      .refine((url) => url.startsWith('postgres') || url.startsWith('mysql')),
    ENCRYPTION_SECRET: z.string().length(32),
    NEXTAUTH_URL: z.string().url(),
````

I checked the rules for env and I get the same error as above on vercel.
Secert is 32 chars and url is a valid url in my case but stil no luck running this on vercel

**Comment by vinayakg** [comment]
I changed DATABASE_URL from postgres to postgresql and it got deployed successfully (learnt about this since git repo built successfully on my local in which .env had postgresql)
