### ISSUE TITLE
Issue in Self hosting manual

### ISSUE THREAD

**Issue by kolapallichinu** [baptisteArno/typebot.io#841]
<img width="1071" alt="Screenshot 2023-09-22 at 5 19 00 PM" src="https://github.com/baptisteArno/typebot.io/assets/139605650/bdff3d73-b587-4a95-9cc1-52f1281cb976">

When I'm trying to self hosting, it was getting this error

**Comment by kolapallichinu** [comment]
This is my .env

ENCRYPTION_SECRET=eZftB+277rBcw0vKauF9W4xCBQkRtSXF

DATABASE_URL=postgres://type_post:dxZmkVdVg3tJr5aeg54MPLv5AsXnl7OI@dpg-ck6n9rfq54js73fh7640-a.ohio-postgres.render.com/typebot_2zvl

NEXTAUTH_URL=http://assistbot.io
NEXT_PUBLIC_VIEWER_URL=http://app.assistbot.io
ADMIN_EMAIL=kolapallikvsnr@gmail.com

GITHUB_CLIENT_ID=2f3b14a6f08fd1ac1336
GITHUB_CLIENT_SECRET=8f178dc7510c85778efdb886391325f6bf890f2c

**Comment by Lambdac0re** [comment]
Do you realize that the whole world can now see your secrets and passwords?

**Comment by michaelvips** [comment]
This is not a issue, you must open this on discussions and ask help for others users.

**Comment by baptisteArno** [comment]
Have you modify any of the code? You just cloned the repository, installed the dependencies and run this command?
