### ISSUE TITLE
The bot you're looking for doesn't exist

### ISSUE THREAD

**Issue by CursoAnalistaVoip** [baptisteArno/typebot.io#843]
![image](https://github.com/baptisteArno/typebot.io/assets/102430464/16569ea2-28ba-4227-8e08-240f5ebe1ba7)

I had an error in the bot:

404
The bot you're looking for doesn't exist

V 2.17.2

{"message":"Not found","code":"NOT_FOUND"}

**Comment by baptisteArno** [comment]
Duplicate #809

You need to provide more info there, please!
