### ISSUE TITLE
Popup loading

### ISSUE THREAD

**Issue by arthurbarret0** [baptisteArno/typebot.io#847]
When I use the script in popup mode, when the user clicks the button to open the popup (Typebot.open()), the screen displays a backdrop for a few seconds until the widget finishes loading. It would be useful to insert a loading indicator in the middle of the screen until the loading is complete, to signal to the user that something is happening in the meantime. Even though it's a short period, the user might think it's an error and leave the page.

**Comment by baptisteArno** [comment]
You can add a backgroundColor to the Popup so that it shows the popup even though the bot isn't loaded yet. Something like:

```jsx
<Popup typebot="..." theme={{backgroundColor: 'white'}}/>
```

Would that suit you?
