### ISSUE TITLE
Another reactivity issue maybe 

### ISSUE THREAD

**Issue by CptPlastic** [baptisteArno/typebot.io#852]
I have a dynamic search done on a set of fields in a google sheet however if I have only one result it will never show up. My testing has been done here.
[Frontend](https://nsncorp.app.nsnmindlabs.com/frontend-txf0iiz)

If you select **Texas** and **Loving County** you will never see the single results show up even though it appears to gather the correct data to display it. 

However, when I did the same thing to **Oklahoma** and **Canadian County** I added two services or two entries in the same sheet and they show up fine. 

Here is the data filters on county and state.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/1208691d-71ac-4eb7-a0b9-2be3661742b4)

![TestGif23](https://github.com/baptisteArno/typebot.io/assets/1010444/aff8cf03-02d9-4349-8935-82e667f58861)

**Comment by baptisteArno** [comment]
Sorry but we definitely need a way to reproduce this on our end. Or maybe you can share the bot URL?

I can't guess of anything wrong here.

**Comment by CptPlastic** [comment]
I did share the link above. It's the blue Frontend link that goes to https://nsncorp.app.nsnmindlabs.com/frontend-txf0iiz 

I also provided examples of my clicks and a screenshot of my data. If dynamic Pick images are used and it only finds one result it will never show that result.

**Comment by CptPlastic** [comment]
I recreated it to make sure it's some kind of issue.

https://nsncorp.app.nsnmindlabs.com/bug-jng074f

[typebot-export-bug-jng074f.zip](https://github.com/baptisteArno/typebot.io/files/12727776/typebot-export-bug-jng074f.zip)

Here is the sheet (type 1 only has one entry and is broken when it displays)
https://docs.google.com/spreadsheets/d/1kKaS8JVLUW6y2uL5EpGrOyLO4Rl5y9jrwbpDoE-xi_g/edit?usp=sharing

Here is the side by side of the broken single result.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/81baad44-9e74-4bfc-92b4-55933a6ebcc8)

If you have more than one in your sheet it renders just fine
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/9bc821e3-f808-4106-a5ca-0a4eaa0e15e3)


Here is three with three entries.
![image](https://github.com/baptisteArno/typebot.io/assets/1010444/8f30de7a-c084-4fb2-8750-bedfac7205a2)

**Comment by baptisteArno** [comment]
Thank you for the reproduction, will try this ASAP
