### ISSUE TITLE
ElevenLabs integration block

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#853]

**Comment by jdefranco** [comment]
I've already integrated with elevenlabs, indirectly using webhook module, I think its a good idea. Also allow voice input from user.

**Comment by jonarjeo** [comment]
@baptisteArno with OpenAI's tts now deployed this is less urgent, right?
in any case, for a successful implementation you can look at the [amazing YakGPT](https://github.com/yakGPT/yakGPT/blob/main/stores/ElevenLabs.ts).
