### ISSUE TITLE
Multi input block

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#854]
- [x] Make sure it works fine with WhatsApp text + file input

**Comment by papalardo** [comment]
My suggestion is implement its like chatgpt 4 input:
![image](https://github.com/baptisteArno/typebot.io/assets/17734894/c49b1d74-a070-4d1e-9e0a-667e2bcec48e)

With this, we can implements perfect whatsapp flow.

**Comment by baptisteArno** [comment]
Time spent: 42.5 hours
