### ISSUE TITLE
Rating block not responsive

### ISSUE THREAD

**Issue by jsonsmth** [baptisteArno/typebot.io#86]
Hi,

Is there a way to make the rating block responsive? Maybe have the numbers wrap so the user doesn't have to scroll right/left?

https://user-images.githubusercontent.com/7754107/173616933-c299a598-5d33-46f8-beee-2b0360c350cf.mp4

**Comment by baptisteArno** [comment]
Yeah, wasn't really sure how to make it responsive, especially when you add labels at the bottom of the buttons.

I'll see what I can do 😀

**Comment by jsonsmth** [comment]
Thanks! Here's how I've seen it done in other platforms:
<img width="434" alt="Screen Shot 2022-06-15 at 10 07 53 AM" src="https://user-images.githubusercontent.com/7754107/173847926-a4d34b06-e480-418b-9255-2bf1949f5d8e.png">

**Comment by baptisteArno** [comment]
Mmmmh I see, that's not bad!

**Comment by jsonsmth** [comment]
I managed to re-work the CSS and move a couple divs around to come up with this (using flex-wrap CSS and omitting the concept of a middle label). The existence of the middle label is a challenge.
![CleanShot%202022-06-17%20at%2011 33 41](https://user-images.githubusercontent.com/7754107/174330787-50d2e020-762e-4a7e-ab5b-eaff5377968f.jpeg)

**Comment by baptisteArno** [comment]
Thank you for your help my friend, I removed the middle label for now and followed your styles.

I will publish a release today 👍
