### ISSUE TITLE
File upload block should have a credentials option

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#861]
@baptisteArno just like the Send Email block, the file upload block should allow for an option to choose credentials:
![image](https://github.com/baptisteArno/typebot.io/assets/73610779/b9e8831c-bc28-4de1-96ca-e6c28f0bb11b)

This would allow for more flexibility when it comes to building bots; being able to upload files/images to different buckets/S3 instances depending on the bot is a very useful and needed feature.

**Comment by baptisteArno** [comment]
After consideration, I've decided to decline this suggestion. My main priority is to create a user-friendly environment where users can easily upload their files **directly onto Typebot**. Introducing S3 configuration options might greatly increase the technical complexity for the average user.

**Comment by Lanhild** [comment]
@baptisteArno I get your point, though your answer is completely ditching away the self-hosted users POV. For anyone self-hosting typebot, having the ability to upload files to a different S3 instance/bucket than the one configured in the environment is a must.

**Comment by baptisteArno** [comment]
If I have this request from other self-hosters I'll reconsider but for now I clearly disagree with this. IMO, Typebot should be linked to a specific typebot bucket. I'm open to real-case scenario if you have any.

Also, needless to say that it would also be a huge pain to implement and maintain / debug 😮‍💨
