### ISSUE TITLE
Add function calling params in OpenAI config

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#863]

**Comment by vforvilela** [comment]
Hey there! I'm in desperate need of this. :D
Right now, I'm cloning the OpenAI block and directly embedding my functions into it to bypass any interface complications.

Is there anything I can do to facilitate the advancement?

**Comment by Vinny-growth** [comment]
"I'm also facing the same issue, urgently needing this."

**Comment by baptisteArno** [comment]
Can you provide a specific use case for it?
