### ISSUE TITLE
Create amazing Discord server

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#866]
Typebot owes its very existence to the incredible community of early adopters who supported us back in 2022.

If you still did not know, Typebot is maintained and improved by only me. This is why having an awesome community is absolutely crucial for Typebot's future.

I'm seriously stoked about how well our current Facebook group is doing. You folks rock! I love seeing your reactions to new announcements, sharing cool stuff, and having lively discussions. But let's be real, Facebook groups have their limitations.

So here's the vision I have for the Typebot community:

- It's the go-to place where you can get help from Typebot experts and ambassadors. They're like superheroes of the Typebot world.
- It's where you can show off your bots, get inspiration from others, and have the chance to be blown away by the amazing things people create.
- You'll be able to hang out and chat with fellow Typebot enthusiasts who totally get your love for all things conversational.
- Did somebody say rewards? Yup, we'll have those too! Get recognized and get goodies for your contributions to the community.
- And hey, I want the freedom to keep you updated on product improvements, do live streams for special occasions, and have a blast together.

That's why we're moving the fun over to Discord. It's the perfect spot for our Typebot community, right in your pocket. So join us, let's make this an unforgettable journey!

**Comment by Lanhild** [comment]
@baptisteArno Much needed indeed. Let's keep in mind that this Discord server could both be used for chatting between users/contributors, but also some sort of forum. The somewhat new "Threads" feature of Discord IMHO is perfect for users to submit their help requests/non-issues

**Comment by CptPlastic** [comment]
Assign this to me. I would love to build this out.

**Comment by baptisteArno** [comment]
Sent email to [jason.johnson@p7n.net](mailto:jason.johnson@p7n.net)

**Comment by baptisteArno** [comment]
The server: https://discord.com/invite/ymK8Q33d5Z
