### ISSUE TITLE
Error Notifications For Typebot

### ISSUE THREAD

**Issue by leobaldoneto** [baptisteArno/typebot.io#867]
Hi guys, how are you? Thank you @baptisteArno for that great project!

Does Typebot have any error notification or something similar? Sometimes, the flow can be interrupted by an external error, like when making a webhook. If the external service is having issues, it would be good if Typebot notified when this error occurs.

**Comment by baptisteArno** [comment]
That's right, that would be nice 👍

**Comment by baptisteArno** [comment]
This in fact can be done with a simple condition block and a Send email block 👍

**Comment by leobaldoneto** [comment]
Hi @baptisteArno . Thanks about the project! 

The feature I'm proposing is something different. My suggestion is about an error handling to notify about errors in flows.

**Comment by leobaldoneto** [comment]
Hi @baptisteArno . Thanks about the project! 

The feature I'm proposing is something different. My suggestion is about an error handling to notify about errors in flows.

**Comment by baptisteArno** [comment]
But Typebot can't really guess what is your definition of error for example when you make an HTTP request.

That's why I suggest that you add your own error handler after each HTTP request block.

You can save the `statusCode` into a variable and have a simple Condition block that checks that value
