### ISSUE TITLE
Missing package while trying to install @typebot.io/js

### ISSUE THREAD

**Issue by copostic** [baptisteArno/typebot.io#871]
Hi there,

I'm trying to install typebot on a Nuxt 3 project and I have an error when I try to install it.
I wanted to use the solution given in issue #585 

- Node version : 18.17.1
- npm version : 9.6.7
- yarn version : 1.22.19
- Nuxt version : 3.7.0

Command used : 
`yarn add @typebot.io/js`

Output / error : 
`$ yarn add @typebot.io/js
yarn add v1.22.19
[1/4] Resolving packages...
error Couldn't find package "@typebot.io/bot-engine@1.0.0" required by "@typebot.io/js" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
`

And when I try to access bot-engine package npm ask me to login so the package must be private but is a direct dependency.

Is there something that I forgot ? 

Thanks !

**Comment by baptisteArno** [comment]
Thank you for reporting this 🙏. It will be fixed on version `0.1.33` of the package.
