### ISSUE TITLE
BUG: Multiple, identical executions of the API block

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#872]
I use an API block in the parent bot to submit the data generated collected from one of 3 child bots.

The issue i have: on every submission, the API block is getting triggered 3 times, instead of 1!

Parent bot:
![image](https://github.com/baptisteArno/typebot.io/assets/64059154/027b219f-26cb-4835-b77c-6035137575e1)

The API block in the image above is getting triggered 3 times, even though data is incoming from just one of the child bots.

There are no API blocks in the child bots.

This is the end block in one of the child bots (same for other 2):
![image](https://github.com/baptisteArno/typebot.io/assets/64059154/1a90b0bb-acf9-4d08-abf4-bc3df901aacb)

Why?
And how to fix this?

**Comment by baptisteArno** [comment]
Indeed, I believe it is fixed by cd97da2d34fcf576100d03fa30608ce26f1784c4. So it will be available on next release 🙏

**Comment by arladmin** [comment]
@baptisteArno 
Thanks for the quick response!

By when is the next release expected?

Could you also confirm if my approach (regarding jumping back from child bot to parent bot) is implemented correctly?

**Comment by baptisteArno** [comment]
1st of every month! so in 2 days 👍

> Could you also confirm if my approach (regarding jumping back from child bot to parent bot) is implemented correctly?

Yep, looks good!

**Comment by arladmin** [comment]
> 1st of every month! so in 2 days 👍
> 
> > Could you also confirm if my approach (regarding jumping back from child bot to parent bot) is implemented correctly?
> 
> Yep, looks good!

Thanks!

**Comment by arladmin** [comment]
Hi @baptisteArno 

The issue doesn't seem to have resolved in the latest release.

I'm still getting 2 identical executions for every submission.

**Comment by baptisteArno** [comment]
Oh I just checked your description and it seems you use a typebot link block in the children to link back to the parent.

You should not do that as it automatically continues in the parent bot when the linked children is over!
