### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by RuanMD** [baptisteArno/typebot.io#874]
![image](https://github.com/baptisteArno/typebot.io/assets/44640884/9252fed0-5c8a-4f03-bff1-85fd5ba62b5d)

 I installed the latest version of typebot, it works normally, but when I use typebot it gives me this error and it stops working, I'm using Oracle's vps

**Comment by baptisteArno** [comment]
What do you mean by "When I use typebot" Can you give more info on how I can reproduce that?

**Comment by 38ca** [comment]
I get same error here.
"When I use typebot", i think: when started, access and try edit a flow on typebot.
The window on typebot.mydomain.com, freeze and get this same error on console "Error: socket hang up".

When up server, we can access normaly, but after some minutes editing, we can get this error.

**Comment by 38ca** [comment]
@RuanMD i think 

I think I found the solution.
It seems like you need to release the postgres port in iptables:

`sudo iptables -I OUTPUT -p tcp -d 0.0.0.0/0 -m tcp --dport 5432 -j ACCEPT`

I've been using it for at least 1 hour and I don't have any problems with my typebot.
