### ISSUE TITLE
Conversation Flow Not Triggered on First Message in WhatsApp

### ISSUE THREAD

**Issue by cristian2617** [baptisteArno/typebot.io#876]
Problem Description:
I am encountering an issue with Typebot on WhatsApp, specifically related to the activation of conversation flows using specific keywords. When setting up two distinct conversation flows that should be triggered by specific keywords, I've observed that the first input block does not recognize the received message on the first attempt.

Steps to Reproduce the Problem:

Set up two different conversation flows, each triggered by a distinct keyword.
Send the first keyword that should activate the first conversation flow.
Observe that the first input block does not recognize the message sent on the first attempt.
Send the same keyword again.
The first conversation flow is activated on the second attempt.
Expected Behavior:
The expected behavior is for the first input block to recognize the message on the first instance the keyword is sent, activating the corresponding conversation flow.

Environment:

Platform: WhatsApp

Additional Information:
This problem occurs only on WhatsApp; on other platforms, keyword activation works as expected.

Expectations:
I hope that this issue can be investigated and resolved so that the conversation flow is triggered correctly on the first attempt, in accordance with the settings.

![image](https://github.com/baptisteArno/typebot.io/assets/143018335/25ea588c-0b1a-4623-ad0e-d90146860cb7)

![image](https://github.com/baptisteArno/typebot.io/assets/143018335/f4ddf195-925f-49bd-9158-d6d0acab64da)

**Comment by baptisteArno** [comment]
What Typebot version are you using? This feature is available on version `2.18.0`

**Comment by baptisteArno** [comment]
Hmmm hard to debug. I just tried this on https://app.typebot.io:

<img width="1021" alt="CleanShot 2023-10-03 at 16 07 15@2x" src="https://github.com/baptisteArno/typebot.io/assets/16015833/6d1ebf57-8803-459d-b669-fb4d4f0f80a0">

It works as intended. 🤔

**Comment by agencia904** [comment]
Het @baptisteArno, the problem in the issue #877 is not via WhatsApp Integration but via API.

**Comment by Jorgeaceiro** [comment]
Hello friend, Has this error via API been fixed yet? I also have problems when starting a flow via API it doesn't recognize the first message
