### ISSUE TITLE
When collecting input via API, it is necessary to send 2 messages to start

### ISSUE THREAD

**Issue by agencia904** [baptisteArno/typebot.io#877]
Hello There!

I was waiting for this issue to be resolved along with the WA issue, however, for API calls it remains the same.

It's exactly the same problem as this issue, but focused on API: https://github.com/baptisteArno/typebot.io/issues/824

Thanks in advance here Baptiste.

**Comment by agencia904** [comment]
Thanks @baptisteArno, it will be in the next release?

**Comment by baptisteArno** [comment]
I will release a new version tomorrow 🙏
