### ISSUE TITLE
Webhooks Not Working In Builder

### ISSUE THREAD

**Issue by kmain4** [baptisteArno/typebot.io#88]
Webhooks are failing in Builder tests but working in viewer:
```
TypeError
Failed to fetch
```

**Comment by baptisteArno** [comment]
I'll need a reproducible case in order for me to see the error.

How can I do it? :)

**Comment by kmain4** [comment]
Someone messed up the VIEWER_URL and that caused the webhooks to fail. :) I've since fixed the VIEWER_URL but it is still incorrect throughout the app? (They left off the last .tld and now all the links are broken in the builder :( )

**Comment by jsonsmth** [comment]
> Someone messed up the VIEWER_URL and that caused the webhooks to fail. :) I've since fixed the VIEWER_URL but it is still incorrect throughout the app? (They left off the last .tld and now all the links are broken in the builder :( )

I had that happen to me. Pretty sure the URL for the Typebots gets stored in Postgres. I had to blow away the Postgres Docker volume and start over. I suppose you could also connect to Postgres and manually edit the Typebot entries to correct the Viewer URL as well.

**Comment by baptisteArno** [comment]
> > Someone messed up the VIEWER_URL and that caused the webhooks to fail. :) I've since fixed the VIEWER_URL but it is still incorrect throughout the app? (They left off the last .tld and now all the links are broken in the builder :( )
> 
> I had that happen to me. Pretty sure the URL for the Typebots gets stored in Postgres. I had to blow away the Postgres Docker volume and start over. I suppose you could also connect to Postgres and manually edit the Typebot entries to correct the Viewer URL as well.

This really isn't supposed to be stored in Postgres... That's a really strange issue.

**Comment by baptisteArno** [comment]
I think I'll implement this https://github.com/sparanoid/env.sh

So that we have real runtime config...
