### ISSUE TITLE
Handle unsupported message format in WhatsApp

### ISSUE THREAD

**Issue by Danieloutliers** [baptisteArno/typebot.io#880]
Hello, typebot is incredible but I have this difficulty when I ask a user a question on WhatsApp, if the user responds with an audio, typebot simply doesn't recognize it and the flow doesn't continue. Is there any solution for this

**Comment by baptisteArno** [comment]
Indeed, audio files should only work if you are expecting a file upload! There is no way to transcribe an audio clip for now

**Comment by Rod-Gomes** [comment]
I believe that it's expected for a bot not to listen to audio, but having a notification informing that audio processing is not possible is crucial, along with the option to customize this notification.

**Comment by baptisteArno** [comment]
#913
