### ISSUE TITLE
Unable to get app working in React v18

### ISSUE THREAD

**Issue by girishonward** [baptisteArno/typebot.io#887]
Getting a version mismatch error. Has anyone else been able to get the bot working in React? We used the instructions here (https://docs.typebot.io/embed/react) but looks like v18 is not yet supported.

**Comment by girishonward** [comment]
Thank you for the response. @anirudhmaddy - can you please share the error message here?

**Comment by anirudhmaddy** [comment]
Here is the error message
<img width="869" alt="Screenshot 2023-10-05 at 9 59 34 PM" src="https://github.com/baptisteArno/typebot.io/assets/4455923/3bfe7228-f6d5-4a59-9506-5c99b111b875">

**Comment by baptisteArno** [comment]
So it seems your app is using React v16. Would it be possible to upgrade to v18?

**Comment by anirudhmaddy** [comment]
@baptisteArno I'm actually using v18.2.6

**Comment by baptisteArno** [comment]
Well this is exactly what it says `While resolving: onramp-ui-static@0.1.8, found react@16.14.0`.

I can help if you provide a reproduction 🙏
