### ISSUE TITLE
Error! Couldn't initiate the chat - Wordpress Short

### ISSUE THREAD

**Issue by 38ca** [baptisteArno/typebot.io#893]
TypeBot error on wordpress plugin?

[typebot typebot="xxxx-xxxx-xxxxx" host="https://bot.mydomain.com" height="100vh"]

I am running an Apache webserver on my VPS and TypeBot through Docker.
I use a reverse proxy to redirect to the ports of TypeBot-builder and TypeBot-viewer on Apache.
But when I put the short on a WordPress on the same server (wordpress same ip) or external (another wp server), I get the error: Error! Couldn't initiate the chat."

Need help.

**Comment by edson7ac** [comment]
I have the same problem, when adding the code to the plugin this error appears:
Error! Couldn't initiate the chat

**Comment by baptisteArno** [comment]
Can you share a website so that we can check the issue?

If you'd like to keep it private, send it to baptiste@typebot.io

**Comment by edson7ac** [comment]
https://endestaque.com.br/

**Comment by 38ca** [comment]
> Can you share a website so that we can check the issue?
> 
> If you'd like to keep it private, send it to [baptiste@typebot.io](mailto:baptiste@typebot.io)

Direct Bot > https://bot.carlosgestor.live/my-typebot-351nr7v

Wordpress with bot > https://carlosgestor.com.br/test-typebot/

Thank you!

**Comment by brunotavares45** [comment]
Olá @edson7ac , você conseguiu resolver o problema? ainda não achei nada a respeito que funcionou.

**Comment by edson7ac** [comment]
@brunotavares45 Não consegui rapaz, nada

**Comment by baptisteArno** [comment]
@edson7ac The host you provided (https://chat.endestaque.com.br) does not resolve to anything.

@38ca For some reason you have a CORS issue 🤔. By default Typebot should allow all domain to query typebot. Maybe you have a reverse proxy that blocks the incoming request because it does not match a specifc hostname? How do you self-host Typebot?

**Comment by edson7ac** [comment]
Typebot.initBubble({
  typebot: "endestaque-com-br-1",
  apiHost: "https://chatbio.link",
  theme: {
    button: { backgroundColor: "#2c2cfc" },
    chatWindow: { backgroundColor: "#0C0C0C" },
  },
});

**Comment by edson7ac** [comment]
I tried with several flows, uninstalled and reinstalled the plugin, updated the typebot installation image

**Comment by edson7ac** [comment]
I got rid of the problem!
I reinstalled typebot again in version 2.18.1, I still don't know what it was, but it's ok now

**Comment by baptisteArno** [comment]
Oh right, I forgot to say that if you are on <=2.18.0, you need to stay on the Wordpress plugin v3.3.0

**Comment by edson7ac** [comment]
Indeed, the problem returned, I downgraded to version 3.3.0 of the plugin and it worked correctly, thank you

**Comment by baptisteArno** [comment]
It should work just fine on 3.4.0 and 2.18.1 though!
