### ISSUE TITLE
ECONNRESET • Typebot going offline

### ISSUE THREAD

**Issue by ofmarconi** [baptisteArno/typebot.io#894]
I made the same comment on Facebook:
https://www.facebook.com/groups/262165102257585/user/100000306833214

I'm using Typebot on an ARM server hosted at Oracle. During operation, I occasionally encounter the ECONNRESET error in the container logs. This error stops Typebot's functionality, although the container continues to run. I'm currently using Portainer to manage my containers, but it doesn't offer a native solution to monitor the logs and restart the container when this specific error is identified.

Sometimes the Viwer crashes, other times just the Builder

It would be very useful if Typebot could have built-in functionality to monitor its own logs and attempt an automatic reconnection or container restart when the ECONNRESET error is detected. This would help ensure continuity of operation without manual intervention.

This functionality would be especially useful in environments where manual monitoring or intervention is not practical or possible in real time.

- - -

Has anyone had problems with ARM + ORACLE?

- - - 

I also opened a ticket in Portainer asking it to restart automatically if the log has the error:
https://github.com/portainer/portainer/issues/10427

**Comment by baptisteArno** [comment]
Can you provide an example of the logs you're seeing exactly?

Maybe your VM does not have enough RAM?

**Comment by ofmarconi** [comment]
Sure:

![Imagem do WhatsApp de 2023-10-07 à(s) 18 50 31_086c5c8a](https://github.com/baptisteArno/typebot.io/assets/6594795/5f6843b6-9f77-4e1c-a351-c15cb3e8abae)

My VM has 12gb of RAM, 2 cores ARM Oracle

**Comment by baptisteArno** [comment]
That's strange. I just released v2.18.1 that fixes a ton of bug. Can you try it out?

**Comment by ofmarconi** [comment]
@baptisteArno 
https://www.loom.com/share/02e63bbd8c4244c58cabfd314dd94b89?sid=400041a8-eb5f-48f8-b636-c43f1718a323

I set it the wrong way on purpose to reach the error, it happened, but this time it took less than 1 minute and it started working again... I don't know if it was a correction or luck.

Thanks
