### ISSUE TITLE
Chatgpt does not respond with more than 1 word

### ISSUE THREAD

**Issue by nilalisson14** [baptisteArno/typebot.io#901]
Hello everything is fine? I have a little problem, I don't know if it's already known but in the o Official version it works but in the version installed on the vps it doesn't. When I use the gpt API to respond to a user's message, it only responds if it has just one word like, hi, if I put it. Hi, okay, it shows the error  {
  "message": "Cannot read properties of undefined (reading 'at')",
  "code": "INTERNAL_SERVER_ERROR"
}
Does anyone have a solution for this?

**Comment by nilalisson14** [comment]
![Screenshot_2023-10-09-09-19-41-822_com whatsapp](https://github.com/baptisteArno/typebot.io/assets/110121014/8c8e3c5e-91e7-472d-ace8-dcf51e2714ea)

**Comment by baptisteArno** [comment]
That's strange. I just released v2.18.1 that fixes a ton of bug. Can you try it out?
