### ISSUE TITLE
Erro de envio de primero Aceso.

### ISSUE THREAD

**Issue by Aritan15** [baptisteArno/typebot.io#914]
Boa noite!

Conseguem me ajudar com erro, conforme captura de tela da tela?
![WhatsApp Image 2023-10-12 at 03 14 25](https://github.com/baptisteArno/typebot.io/assets/147579039/922bed3d-fcdc-4086-88fe-632bd170b9bc)

**Comment by baptisteArno** [comment]
Can you share the server logs? There must be an issue displayed :)

**Comment by Adilmar** [comment]
@baptisteArno how to see the logs?

**Comment by Aritan15** [comment]
Não achei.

**Comment by Adilmar** [comment]
I solved it by configuring the correct SMTP port!

**Comment by Aritan15** [comment]
SMTP está correta 
Porta: 465

Será que precisa fazer algo no servidor da TypeBot?

**Comment by Aritan15** [comment]
??

**Comment by Aritan15** [comment]
Boa tarde!

Está com erro de entrega para confirmação de inscrição.
![image](https://github.com/baptisteArno/typebot.io/assets/147579039/d54d6250-9b8f-4535-af67-46e79327899f)

**Comment by Aritan15** [comment]
Quem pode me ajudar?

**Comment by Aritan15** [comment]
???
