### ISSUE TITLE
Team plan wasn't automatically granted

### ISSUE THREAD

**Issue by fernando-nyx** [baptisteArno/typebot.io#92]
`"Login with the admin email to have access to a Team plan workspace automatically"`

Not working for me

Any help?

**Comment by baptisteArno** [comment]
That's odd! Are you sure you properly set the `ADMIN_EMAIL` environment variable? Without any additional characters? What's the email?

Also, are you sure you didn't create another workspace than your original one?

**Comment by fernando-nyx** [comment]
Yes, all ok

Look:

![image](https://user-images.githubusercontent.com/107439567/174440301-e4c996a3-f2b6-46d1-bbbd-890ab9851d9b.png)


![image](https://user-images.githubusercontent.com/107439567/174440187-30b1272e-ac98-4cf9-92f1-5a72df2fc747.png)


I'm not create another workspace

Any tips on what I can try to do?

**Comment by baptisteArno** [comment]
That's very strange! Can you destroy the app and try again maybe with another email address? Are you sure you don't have the Team plan enabled?

To destroy the apps:
`docker-compose down --volumes --remove-orphans`

**Comment by baptisteArno** [comment]
I'll close this issue, for now, feel free to re-open it if you have more info 👍
