### ISSUE TITLE
Preview in Builder does not work after update (Vercel)

### ISSUE THREAD

**Issue by jmchat** [baptisteArno/typebot.io#929]
After the last update (from 2.16) 2.18 (I use Vercel and Supabase) When I try to preview in the builder I get this error: 
Error! Couldn't initiate the chat.
I my console I see this is caused by a CORS Header issue.
But if I test the embed link (public) it works perfectly fine also in the website where I embed the typebot it still works just inside the Builder where the issue is now.

Any idea how to fix the issue in the builder preview?

Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by baptisteArno** [comment]
You are probably missing now required environment variables in the viewer configuration. Check out the server logs for more details 🙏

**Comment by jaison-x** [comment]
> You are probably missing now required environment variables in the viewer configuration. Check out the server logs for more details 🙏

Hello.. I am having the same problem. I searched in the docs but couldn`t find any variables that helped me. Could you help with this, please?

**Comment by jmchat** [comment]
I also still have the issue and I am not missing any required fields if I compare it with the documentation.

**Comment by jaison-x** [comment]
I have this issue in manual installation. I can install it with docker with no problems.
