### ISSUE TITLE
Invalid `prisma.typebot.create()` invocation: The column `Typebot.whatsAppPhoneNumberId` does not exist in the current database.

### ISSUE THREAD

**Issue by renelourenco** [baptisteArno/typebot.io#931]
Don't know what to do. When I try to start a new typebot this appears...

"Invalid `prisma.typebot.create()` invocation: The column `Typebot.whatsAppPhoneNumberId` does not exist in the current database."

**Comment by michaelvips** [comment]
This shouldn't be in the issues category, this is a error on your instalation, is not a error on code. Try help on Discussions.

**Comment by baptisteArno** [comment]
What's your typebot version?
