### ISSUE TITLE
Webhook failing: blocked by CORS policy

### ISSUE THREAD

**Issue by gamalthb** [baptisteArno/typebot.io#935]
I face the same issue as this:
https://github.com/baptisteArno/typebot.io/issues/109

I'm deploying with docker and accessing it directly through my VPS ip address, where can i set the cors policy for the typebot viewer? it seems the next_public_viewer_url in .env is governing the cors policy as well? i'm filling it with [my vps ip address]:8081

**Comment by gamalthb** [comment]
I have pulled the new image, still no luck. Now i think it's not about CORS, it just throwing an error 500 everytime i hit the test button on webhook block: http://xxxx.xxx.xxx.xx:8081/api/typebots/clnty2crd0001s51pok6zgqsd/blocks/npehcmnmbqrsx03seol1glih/executeWebhook

**Comment by baptisteArno** [comment]
Can you share the server logs please? 🙏

```
docker-compose logs
```

**Comment by gamalthb** [comment]
Sure, there's not much in the typebot-builder
`No pending migrations to apply.
┌─────────────────────────────────────────────────────────┐
│  Update available 5.0.0 -> 5.4.2                        │
│  Run the following to update                            │
│    npm i --save-dev prisma@latest                       │
│    npm i @prisma/client@latest                          │
└─────────────────────────────────────────────────────────┘
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 928ms
- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/builder/public/__ENV.js'.
Waiting for 15s for database to be ready...
Prisma schema loaded from packages/prisma/postgresql/schema.prisma
Datasource "db": PostgreSQL database "typebot", schema "public" at "typebot-db:5432"

57 migrations found in prisma/migrations


No pending migrations to apply.
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 953ms
`

Here's the typebot-viewer logs:
`✓ Ready in 953ms
Archiving 100 / 54 results...
ecm@ECM04:~$ sudo docker logs typebot_typebot-viewer_1
- event [next-runtime-env] read environment variables prefixed with 'NEXT_PUBLIC_' from process.env.
- ready [next-runtime-env] wrote browser runtime environment variables to '/app/apps/viewer/public/__ENV.js'.
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000

 ✓ Ready in 111ms
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1364)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1364)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1364)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1364)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1364)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
TypeError: Cannot read properties of undefined (reading 'groups')
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6819
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:6371
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4956
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5125
    at Array.map (<anonymous>)
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:5003
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4720
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:4279
    at /app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:2844
    at async handler (/app/apps/viewer/.next/server/pages/api/typebots/[typebotId]/blocks/[blockId]/executeWebhook.js:1:1727)
`

**Comment by baptisteArno** [comment]
It is still failing after a page refresh? Can you restart your docker stack?

**Comment by gamalthb** [comment]
So i'm have to use VPN to access my SSH, and funny thing is when i accidently turn off my VPN, the webhook block is working. Sorry but i think it's on my end, i don't know why my VPN causing internal server error, other apps doesn't really get that.

**Comment by dialmedu** [comment]
I have problem too: 

```
Access to fetch at 'https://view.**.com/api/typebots/clsale5gm0007pi1it3x34pp6/blocks/lneoiet7rs8v1ypg6uj5kc83/executeWebhook' 
from origin 'https://build.**.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' 
header is present on the requested resource.
 If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

webhook is N8N implements, in inspect console found the `fetch` with https://view.**.com and https://build.**.com

![image](https://github.com/baptisteArno/typebot.io/assets/8028861/4e155f88-4e15-4ed8-bf30-7dbf11760799)

My docker_compose.yml is this: (** hidden data )

```yml
version: '3.3'

volumes:
  db-data:

services:
  typebot-db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_typeboot
      - POSTGRES_PASSWORD=**
    ports:
      - '5432:5432'
    networks:
      - proxymanager_default

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    restart: always
    depends_on:
      - typebot-db
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
   environment:
      - DATABASE_URL=postgresql://postgres:**@typebot-db:5432/db_typeboot
      - ENCRYPTION_SECRET=**
      - NEXTAUTH_URL=build.**.com
      - NEXT_PUBLIC_VIEWER_URL=view.**.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - ADMIN_EMAIL=admin@**.com
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - DEBUG=true
      - GOOGLE_CLIENT_ID=**.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=**
      - NEXT_PUBLIC_GOOGLE_API_KEY=**

    networks:
      - proxymanager_default

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    restart: always
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:**@typebot-db:5432/db_typeboot
      - ENCRYPTION_SECRET=**
      - NEXTAUTH_URL=build.**.com
      - NEXT_PUBLIC_VIEWER_URL=view.**.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - ADMIN_EMAIL=admin@**.com
      - DEFAULT_WORKSPACE_PLAN=UNLIMITED
      - DEBUG=true
      - GOOGLE_CLIENT_ID=**.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=**
      - NEXT_PUBLIC_GOOGLE_API_KEY=**

    networks:
      - proxymanager_default

networks:
  proxymanager_default:
    external: true
```
