### ISSUE TITLE
Generate build fails locally on viewer

### ISSUE THREAD

**Issue by tecoad** [baptisteArno/typebot.io#941]
I am trying to install local by the first time.
I have sucessfully deployed at Vercel.
I can also generate the build locally for the builder.

However, the viewer fails on bot-engine#build. Which seems to be related to the deprecated/bot-engine package.

Mostly the error is related to the following:
```
bot-engine:build:   The Yarn Plug'n'Play manifest forbids importing "@typebot.io/lib" here because it's not listed as a dependency of this package:
bot-engine:build: 
bot-engine:build:     ../../../../../.pnp.cjs:38:33:
bot-engine:build:       38 │           "packageDependencies": [\
bot-engine:build:          ╵                                  ~~
bot-engine:build: 
bot-engine:build:   You can mark the path "@typebot.io/lib" as external to exclude it from the bundle, which will remove this error.
```

Attached the full log. [log.txt](https://github.com/baptisteArno/typebot.io/files/12922068/log.txt)
I mostly use yarn in local. However i have pnpm installed in v 8.9.0.
Seems that somehow it tries to use the The Yarn Plug'n'Play, which is a yarn feature.

Has anyone experienced that?

**Comment by baptisteArno** [comment]
Hey!

What viewer build command have you entered?

Does it fail on Vercel or locally?

**Comment by tecoad** [comment]
pnpm build or pnpm build, both fails.
Screen recording [here](https://youtu.be/NdqOcgJ8Nm0)

**Comment by tecoad** [comment]
For Anyone running into this issue:

on 'packages/deprecated/bot-engine/package.json'

Moving these two dependencies:

```
    "@typebot.io/lib": "workspace:*",
    "@typebot.io/schemas": "workspace:*"
```

From devDependencies to dependencies, fixes for me.

Not sure if its a matter of my pnpm or typescript version.
Closing the issue for now.
