### ISSUE TITLE
Preview of Selected Values Doesn't Update for Second Item in Multi-Select Loop

### ISSUE THREAD

**Issue by cherrycharan** [baptisteArno/typebot.io#948]
I have a loop flow where users can select multiple options and then go through a series of questions. After completing this flow, there's a check block that repeats the same questions for the second choice they made. To prevent repetition of the questions for the first choice, I'm clearing the stored variable.

The problem I'm encountering is that when users make a selection for the second item, the preview of selected values still displays the choices made for the first item, even though the questions are correctly repeating for the second item. It seems like the selected values in the preview are not updating to reflect the second choice.

**Steps to Reproduce:**

Select multiple options.
Go through the question flow.
Observe that the questions are correctly repeated for the second choice.
However, in the preview of selected values, it displays the choices made for the first item, not the second.

**Expected Behavior:**
The preview of selected values should update to display the choices made for the second item when repeating the questions for that item.

**Actual Behavior:**
The preview of selected values still shows the choices made for the first item, even when repeating the questions for the second item.

**Comment by baptisteArno** [comment]
Can you provide a typebot file for the reproduction? 🙏

**Comment by cherrycharan** [comment]
![Untitled design (9)](https://github.com/baptisteArno/typebot.io/assets/16544980/4f96d3ab-2423-4ae1-b4da-34459cd41755)

Check the options which i have choosed and which is being previewed . 

I have exported the bot and sharing the download link of the json file 
https://www.mediafire.com/file/1le8tm2zmu0ua9t/typebot-export-bot-for-loop-hiktw97.json/file

**Comment by cherrycharan** [comment]
Yes , when i remove space it was working now as exepected. 
When i tried using collect date field , this is previewing old value when selected new value

**Comment by cherrycharan** [comment]
![ezgif com-video-to-gif](https://github.com/baptisteArno/typebot.io/assets/16544980/0b5c22de-70ec-488c-972d-8effa7e2bd6c)
In this check the date field where when i select new date in the loop its still previewing old value
