### ISSUE TITLE
Commas shouldn't be allowed in filenames for the file upload block

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#955]
@baptisteArno the title says everything. 

When a client uploads multiple files using the file upload block, the files URL are returned in a comma-separated list. Though, the caveat is that commas are allowed in filenames and creates issues when trying to split the URL list into single items.

**Comment by poorna-prakash-sr** [comment]
Hey I can work on this?

**Comment by baptisteArno** [comment]
Sure man!

**Comment by baptisteArno** [comment]
Let me know if you have any questions

**Comment by Lanhild** [comment]
@baptisteArno I wouldn't consider this issue completed. The problem is still there;
![image](https://github.com/baptisteArno/typebot.io/assets/73610779/dd256aa4-812a-4dea-8bfe-3ffbddf7d513)

There is a need to have commas and any other special characters encoded in the URLs.

In the state that it is currently, if you try to compute this list of screenshots URLs and separate it by commas, it won't work as the commas inside the URL item itself isn't encoded.

**Comment by Lanhild** [comment]
[typebot-export-file-upload-ur-ls-list-parsing-mfxshqs.json](https://github.com/baptisteArno/typebot.io/files/13478216/typebot-export-file-upload-ur-ls-list-parsing-mfxshqs.json)

@baptisteArno here is a file showing the issue. Follow the bot's instructions and you'll understand what I explain in my last comment.

**Comment by baptisteArno** [comment]
All good, will be fixed on next release! Thanks for the reproduction

**Comment by Lanhild** [comment]
Thanks. What might be a solution is to encode each uploaded files URLs using `encodeURIComponent` before bundling them as a list. Then, it would be much easier to separate the list by `,` (comma) and after that decode each items.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
