### ISSUE TITLE
Unhandled Runtime Error Error: window is not defined

### ISSUE THREAD

**Issue by pengjinning** [baptisteArno/typebot.io#960]
i got this error, when added this code to nextjs, with "@typebot.io/nextjs": "^0.2.7", :

import {Bubble} from '@typebot.io/nextjs';
const App = () => {
  return <Bubble typebot="customer-support-78bk0io" theme={{button: {backgroundColor: '#0042DA'}}} />;
};
export default App;

error:

1 of 1 unhandled error
Next.js is up to date

Unhandled Runtime Error
Error: window is not defined

Call Stack
window
node_modules/@typebot.io/nextjs/dist/web-9288988b.js (1:12166)
ue
node_modules/@typebot.io/nextjs/dist/web-9288988b.js (1:48111)
(rsc)/./node_modules/@typebot.io/nextjs/dist/web-9288988b.js
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-ai-widget/examples/nextjs-app/.next/server/vendor-chunks/@typebot.io.js (60:1)
__webpack_require__
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-ai-widget/examples/nextjs-app/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./node_modules/@typebot.io/nextjs/dist/Bubble-6ccf366e.js (7:74)
(rsc)/./node_modules/@typebot.io/nextjs/dist/Bubble-6ccf366e.js
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-ai-widget/examples/nextjs-app/.next/server/vendor-chunks/@typebot.io.js (20:1)
Function.__webpack_require__
/Users/ningjinpeng/Desktop/git/private/bytedesk-vue3/weiyu-ai-widget/examples/nextjs-app/.next/server/webpack-runtime.js (33:42)

**Comment by baptisteArno** [comment]
Strange!

Can you provide a reproduction? 🙏

**Comment by AntonyJudeShaman** [comment]
i get the same error when i tried to integrate typebot to my website in nextjs

**Comment by AntonyJudeShaman** [comment]
ok it throws error when u use it in your `layout.tsx` file but when i imported it in my `page.tsx` its working fine
