### ISSUE TITLE
About New Plan Rules

### ISSUE THREAD

**Issue by luizeof** [baptisteArno/typebot.io#964]
Hello @baptisteArno how are you ? Thank you very much for your work with Typebot!!!

In release 2.18.3 we have important changes regarding the billing method.

I have 2 questions:

1. With the UNLIMITED plan, will it no longer be possible to add team members? I got it with Pro, but not with Unlimited.

![8778a987-12ad-43b4-b5fe-8011e4b4e975](https://github.com/baptisteArno/typebot.io/assets/257004/16eb5e0b-0ad5-4679-80c2-b0480091b0da)

![c565cc65-688c-47ba-9a85-2e656a7ef682](https://github.com/baptisteArno/typebot.io/assets/257004/085182e0-36ca-4c65-a308-03faea7eb392)

2. Will the `customChatsLimit` field no longer be considered?

Thank you very much for your time ;)

**Comment by Cazzolli** [comment]
After updating to v2.18.3, even when using the UNLIMITED version, this option is preventing the addition of another admin.

**Comment by SuporteLC** [comment]
Here, after installing version 2.18.3, the same thing is happening.

**Comment by baptisteArno** [comment]
Releasing v2.18.4 right now. Should be available in ~15 min.
