### ISSUE TITLE
Integration with Chatwoot

### ISSUE THREAD

**Issue by arthurbarret0** [baptisteArno/typebot.io#965]
Chatwoot has the "Applications" tab for integrating with Dialogflow, Dyte, OpenAI, and more. It would be interesting to add Typebot to the tab and include the functionality to create a bot using a Chatwoot agent bot, but built using the Typebot builder, integrated with Chatwoot's common messages + interactive messages.

When activating Typebot in "Applications," it would request the URL to communicate with TypeBot, API credentials, etc. It would then communicate and function as a native tool.

Currently, Chatwoot bots are manually created without a builder, and Typebot would be an excellent integration to fulfill this functionality.

**Comment by mrkirthi-24** [comment]
Hey @arthurbarret0 I would like to work on this issue

**Comment by baptisteArno** [comment]
I guess this issue should be created in the Chatwoot repo instead of here then :)

**Comment by ramonmatias19** [comment]
I left a comment on discord about this integration:

https://discord.com/channels/647412545203994635/1160047690017685584

**Comment by lazmo88** [comment]
Does typebot offer public API interface for chats? If so, there could be chance to get this implemented, however also Chatwoot would need to be updated to facilitate the integration.

**Comment by arthurbarret0** [comment]
> Does typebot offer public API interface for chats? If so, there could be chance to get this implemented, however also Chatwoot would need to be updated to facilitate the integration.

https://www.chatwoot.com/developers/api/

**Comment by lazmo88** [comment]
> > Does typebot offer public API interface for chats? If so, there could be chance to get this implemented, however also Chatwoot would need to be updated to facilitate the integration.
> 
> https://www.chatwoot.com/developers/api/

I'm familiar with the Chatwoot API, but my question was if Typebot has public API or options to embed it to 3rd party applications?

**Comment by arthurbarret0** [comment]
> > > Does typebot offer public API interface for chats? If so, there could be chance to get this implemented, however also Chatwoot would need to be updated to facilitate the integration.
> > 
> > 
> > https://www.chatwoot.com/developers/api/
> 
> I'm familiar with the Chatwoot API, but my question was if Typebot has public API or options to embed it to 3rd party applications?

Oh, forgive me! Here is the Typebot API documentation: https://docs.typebot.io/api/

**Comment by lazmo88** [comment]
> > > > Does typebot offer public API interface for chats? If so, there could be chance to get this implemented, however also Chatwoot would need to be updated to facilitate the integration.
> > > 
> > > 
> > > https://www.chatwoot.com/developers/api/
> > 
> > I'm familiar with the Chatwoot API, but my question was if Typebot has public API or options to embed it to 3rd party applications?
> 
> Oh, forgive me! Here is the Typebot API documentation: https://docs.typebot.io/api/

Thanks, it seems there is indeed necessary APIs available. Which in theory would allow interacting from Chatwoot > Typebot. However, this will require quite a lot of development efforts from both platforms. Especially as Typebot Chat API is highly experimental.

I wouldn't go through the hassle to integrate the bot builder to Chatwoot UI, as most likely the Chatwoot won't accept such PR anyway.

Easy way out would be to build a Chatwoot specific endpoint for Chat API that would directly be compatible with the Chatwoot bot requests.

Alternative is to build a Chatwoot <> Typebot bridge (there are example bridges for Chatwoot <> service X in github). This middleware would then handle formatting the webhooks and API requests between these two apps.

Considering Typebot already has a integration with Chatwoot (live chat/agent) it could make sense the Chat API could accept requests from Chatwoot directly.

What comes to the installing a bot on Chatwoot UI, it should be a feature that Chatwoot would need to implement in both scenarios above. 

IMHO, bot builder should not be integrated to Chatwoot UI and builder should be accessible from the Typebot app only. This would remove a lot of complexity and maintenance need to facilitate such feature on both platforms as there is already Chat API + Chatwoot Bot interfaces available.
