### ISSUE TITLE
Persistent Multiple Responses Issue on WhatsApp Integration with ChatGPT

### ISSUE THREAD

**Issue by Rod-Gomes** [baptisteArno/typebot.io#972]
I'm encountering several bugs while using the WhatsApp + ChatGPT integration. I was able to resolve most of them directly within the flow, but there's one in particular that's driving me crazy.

In the web version, everything works perfectly, and ChatGPT responds exactly the way I want. However, on WhatsApp, when I ask more than one question, I receive up to 5 consecutive responses, one after the other, even without sending any additional questions.

I conducted some tests but couldn't identify the cause of the bug. So, I'll try to provide as much information as possible:

- I'm using a Facebook test number.
- I'm using an installation within Cloudron, with the default configuration and no modifications.
- I'm implementing some filters before running the AI and after receiving the user's question to identify when the user says "speak to an agent" or "end" in order to execute the corresponding actions.

If you need any additional information, please let me know.

![Captura de tela 2023-10-26 100914](https://github.com/baptisteArno/typebot.io/assets/19373840/4906ba6d-7255-4543-bcf0-38cb721fe079)

![Captura de tela 2023-10-26 101727](https://github.com/baptisteArno/typebot.io/assets/19373840/0ffb50d2-f658-4e13-9724-fd90ec6b44fc)

**Comment by Rod-Gomes** [comment]
Hello,

I was able to reproduce the issue using the "Basic ChatGPT" model, and I have sent it to your email.
When I send something to the bot, it responds five times, which results in a significantly higher token consumption.

I also noticed a pattern; it seems to occur only when the responses from ChatGPT are lengthy or are more likely to occur in these situations. Sometimes it sends only two consecutive responses, and at times, five.
The inconsistency makes me believe that it might be related to the responses generated by ChatGPT.
Additionally, there are many formatting errors, as you can see in the image, but I managed to resolve those by replacing these characters within the flow.

Thank you very much, and if I can assist with anything else, please feel free to reach out.
![Captura de tela 2023-10-27 174018](https://github.com/baptisteArno/typebot.io/assets/19373840/2d8928a7-8bdc-4c69-bae2-4edc1b8b01f1)

**Comment by baptisteArno** [comment]
Indeed WhatsApp parsing need to be improved here 🙏

**Comment by Giusti10** [comment]
Estou sofrendo o mesmo problema com HTTP Request. Loop Infinito quando uso pro Whats como evolution API
