### ISSUE TITLE
Add Gumlet video support

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#978]
https://docs.gumlet.com/docs/embed-videos

**Comment by Ulrfis** [comment]
Thanks Baptiste :)

**Comment by Raju-kadel-27** [comment]
@baptisteArno I want to take this..can you please explain this more about this ??

**Comment by Ulrfis** [comment]
> User should be able to paste a Gumlet URL into a Video bubble configuration and it correctly displays the Gumlet embed player

@Raju-kadel-27 [Gumlet](https://www.gumlet.com/pricing/?tab=video) is like Vimeo (but more affordable); we need to embed videos without the YouTube mess (next videos overlays etc). Ideally it should also work with vertical videos

**Comment by Ulrfis** [comment]
Thank you @baptisteArno !
