### ISSUE TITLE
Endpoints to use for status check

### ISSUE THREAD

**Issue by Lanhild** [baptisteArno/typebot.io#984]
Hi @baptisteArno 

There isn't any documentation about status checks for self-hosted users. Could you give an insight on what endpoints you are using for this status page, for example;

https://status.typebot.io/

It would be very helpful to know which endpoints I should ping on my instance to ensure good status checks

**Comment by baptisteArno** [comment]
This status page is dedicated to Typebot Cloud. The monitors are outside of Typebot infrastructure. It is powered by Betterstack (https://betterstack.com/)

**Comment by Lanhild** [comment]
@baptisteArno 
Thanks for the info, but I was actually asking about the endpoints:

For example, do we have to call https://bot.app/status to get the status of an instance or something similar?

**Comment by baptisteArno** [comment]
Typebot does not have a status endpoint. What Betterstack does is going directly to https://app.typebot.io and check if it is a success response status code
