### ISSUE TITLE
The outcomes are not apparent, but the record does exist within the database.

### ISSUE THREAD

**Issue by vishnusharmax** [baptisteArno/typebot.io#985]
<img width="972" alt="Screenshot 2023-10-28 at 11 25 38 AM" src="https://github.com/baptisteArno/typebot.io/assets/17336334/b4836394-3e6d-4cda-b418-76d8741cde2e">

As you can observe, the outcome is not displayed in the user interface. However, the corresponding record is present in the database. When the key is set to 1 in either "isCompleted" or "hasStarted," the record becomes visible.

![image (4)](https://github.com/baptisteArno/typebot.io/assets/17336334/a9c5a1c4-e0b9-422c-9741-1f908a19b501)

**Comment by baptisteArno** [comment]
If the result is not set as "hasStarted" then it won't appear to the Results table. That is expected. Is that an issue?
