### ISSUE TITLE
Request for feature: Integrate Typebot with Chatwoot natively for WhatsApp usage via Chatwoot

### ISSUE THREAD

**Issue by Rod-Gomes** [baptisteArno/typebot.io#986]
I find myself in a current scenario where I need to abandon the official WhatsApp Business API due to the lack of a panel for customer communication. Since it's not possible to use WhatsApp mobile apps when using the official APIs.

Considering the communication challenges posed by the official API, I believe it would make a significant impact and likely attract a large community to use this application if it could utilize WhatsApp through Chatwoot. Chatwoot already has a mobile app and offers an easy way to communicate with customers. Of course, we shouldn't forget to maintain integration with WhatsApp buttons, if possible.

**Comment by baptisteArno** [comment]
That seems to be clearly impossible technically and it does not fit Typebot's long term vision 🙏

Eventually it will have a live chat option.

**Comment by Rod-Gomes** [comment]
Hello Baptiste,

Many people are doing this today using only APIs and n8n, so it doesn't seem technically impossible. However, it's just a suggestion. I'm currently working on setting up this API integration, but it would be great if Typebot had this natively.

Having an integrated chat would be wonderful, but it seems like something much more complex and time-consuming to develop.

**Comment by baptisteArno** [comment]
Yes I'm starting to reconsider the live chat option. It can be a feature implemented in the future. But not in the near future!
