### ISSUE TITLE
Send a message POST Request API 

### ISSUE THREAD

**Issue by abdkelani** [baptisteArno/typebot.io#988]
I am trying to make a post request API in postman

This is the url: http://localhost:3000/api/v2/sendMessage
I have added the headers
My body look like this: 

```
{
    "startParams": {
        "typebot": "clocon1s*****iaw0t2uql0cc",
        "isPreview": false,
        "startGroupId": "g30ngf6*****l0oblzzq08mw",
        "isStreamEnabled": false,
        "isOnlyRegistering": false
    },
    "clientLogs": [
        {
            "status": "string",
            "description": "string"
        }
    ]
}
```

but as a response I'm only getting a HTML response. 

Is it because Chat API still in (beta)?

**Comment by abdkelani** [comment]
I noticed that the url need to be in api/v2 but at the project there is no v2 folder inside the pages which cause the HTML response that indicate nothing found

**Comment by baptisteArno** [comment]
Are you sure you did not started the viewer on port `3001`? If so the URL should be:

http://localhost:3001/api/v2/sendMessage

**Comment by abdkelani** [comment]
Actually I was only running the builder app and using port 3000 instead of 3001. 
After I run the viewer and builder and using 3001 port it works. 

Thanks you @baptisteArno
