### ISSUE TITLE
Whatsapp integration: Unable to activate different bot with the same WA

### ISSUE THREAD

**Issue by arladmin** [baptisteArno/typebot.io#991]
I started with enabling the Whatsapp integration for Bot A, using Whatsapp No. 1.
Then i disabled the above integration, and enabled it for Bot B, using the same No. 1.

But, every time i initiate a chat on whatsapp, i get the message from Bot A and not Bot B!

**Comment by arladmin** [comment]
Even after disabling whatsapp integration on all bots, the first configured bot is still active!

**Comment by arladmin** [comment]
@baptisteArno 

Even more surprisingly, even deleting the typebot doesn't seem to affect the Whstapp integration.

**Comment by baptisteArno** [comment]
> But, every time i initiate a chat on whatsapp, i get the message from Bot A and not Bot B!

Are you sure the chat session with Bot A was finished?

> Even after disabling whatsapp integration on all bots, the first configured bot is still active!

It is still possible if a session is still opened. Sessions by default expire after 4 hours unless you customize this.

**Comment by arladmin** [comment]
> Are you sure the chat session with Bot A was finished?

I don't think so.

For now, to test, I can manually delete the Session entry from the database. 
But, how do i identify the correct session record?

**Comment by baptisteArno** [comment]
This should have the following id: `wa-${phoneNumberId}-${receivedMessage.from}`

**Comment by arladmin** [comment]
> This should have the following id: `wa-${phoneNumberId}-${receivedMessage.from}`
> 
> Look in the `ChatSession` table

Deleted. Will try now.

Also, earlier, the problem existed even when i tried to initiate the Whatsapp chat from a different mobile number.

**Comment by baptisteArno** [comment]
Then that's most likely a bug. Let me know step by step how I can reproduce 🙏
