### ISSUE TITLE
Retrieval of Variables and Their Values in sendMessage POST Request

### ISSUE THREAD

**Issue by phenriquec** [baptisteArno/typebot.io#992]
Hello,
When using the sendMessage method, is it possible for the typebot to return the variables and their associated values in the post result?

tks

**Comment by baptisteArno** [comment]
You should be able to get all the stored variable values with this API endpoint: https://docs.typebot.io/api/get-result-by-id

`/sendMessage` is a public endpoint and should never show internal values

**Comment by MCSXV** [comment]
> Hello, When using the sendMessage method, is it possible for the typebot to return the variables and their associated values in the post result?
> 
> tks

Henrique, vi uma contribuição que você fez no "whatsWG", sou novo no git e não sabia como entrar em contato com você, então encontrei essa forma para tentar. A questão que tenho é que não consigo receber as mensagens pelo webhook. Faço o teste no postman e a função funciona, porém em produção não retorna nada. Gostaria de um help, se puder me ajudar serei muito grato.

[Baptiste, espero que compreenda o fato de estar usando essa "issue" para resolver a barreira que encontrei. De qualquer forma, ela(issue) está sendo usada para uma causa nobre: um programador travado em uma demanda (hehehe) ]
