### ISSUE TITLE
New option for "Remember user": save the chat state to display it again on second visit.

### ISSUE THREAD

**Issue by baptisteArno** [baptisteArno/typebot.io#993]

**Comment by CptPlastic** [comment]
This would be awesome I have a use case where I want to save a users state so when they come back or open the app again they can pick up right where they left off. My use case is a search tool that I am planning to create a mobile app from this would be super helpful.

**Comment by donaldev** [comment]
+1 for this

Similar use case as @CptPlastic - using the typebot to help users navigate our website but after redirection the bot starts again. Would be great to pass in some ID to the bot so it picks up where it left off.

**Comment by MAS-CreativeLabs** [comment]
Excellent!!! I'm happy to see I'm not the only one waiting for this functionality. I honestly this this issue should be at the top of the feature list. 

+1 for this @CptPlastic @donaldev
