### ISSUE TITLE
APP security

### ISSUE THREAD

**Issue by TheusBoot** [baptisteArno/typebot.io#998]
Immediately after logging in via Email (admin), it is still available for anyone else to enter their email and receive the magic link, meaning the person can have access to 200 free messages.

This panel for adding new members would be interesting, if it were possible, just within the typebot, with a token, checking whether the 'admin' is logged in or not.

I had a lot of problems using it in Brazil, because my application was easily hacked and to get around this, I had to remove the 'SMTP' service, so the email wouldn't be sent to people....

If there was this member control, within typebot, with an email verification token (admin), things would be much smoother.

**Comment by baptisteArno** [comment]
The `DISABLE_SIGNUP`variable is most likely what you're looking for: https://docs.typebot.io/self-hosting/configuration#general
